# Generated by Django 4.1 on 2022-09-06 06:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modeltraining', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('room_no', models.IntegerField(primary_key=True, serialize=False)),
                ('room_type', models.CharField(choices=[('Multibed', 'Multibed Ward'), ('Twin sharing', 'Twin sharing Room'), ('Single', 'Single Room'), ('Single Deluxe', 'Single Deluxe Room'), ('General', 'General ward')], max_length=200)),
                ('status', models.CharField(choices=[('occupied', 'occupied'), ('occupied', 'occupied')], max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('patient_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('patient_name', models.CharField(max_length=200)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('room_type', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=200)),
                ('register_on', models.DateTimeField(auto_now_add=True)),
                ('addr_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='modeltraining.address')),
            ],
        ),
        migrations.CreateModel(
            name='OutPatient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease', models.CharField(max_length=200)),
                ('date_of_treatment', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='modeltraining.profile')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modeltraining.patient')),
            ],
        ),
        migrations.CreateModel(
            name='InPatient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease', models.CharField(max_length=200)),
                ('date_of_admission', models.DateTimeField(auto_now_add=True)),
                ('date_of_discharge', models.DateTimeField()),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='modeltraining.profile')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modeltraining.patient')),
                ('room', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='modeltraining.room')),
            ],
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('bill_no', models.AutoField(primary_key=True, serialize=False)),
                ('doctor_charge', models.IntegerField(blank=True, null=True)),
                ('room_charge', models.IntegerField(blank=True, null=True)),
                ('total_charge', models.IntegerField()),
                ('num_of_days', models.IntegerField(blank=True, null=True)),
                ('generated_on', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modeltraining.patient')),
            ],
        ),
    ]
