# Generated by Django 4.0.5 on 2022-11-14 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('mobile', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('images', models.ImageField(upload_to='')),
                ('likes', models.IntegerField(default=0)),
                ('shares', models.IntegerField(default=0)),
                ('comments', models.IntegerField(default=0)),
                ('is_completed', models.BooleanField(default=False)),
                ('category', models.CharField(choices=[('cars', 'cars'), ('bikes', 'bikes'), ('animals', 'animals'), ('technology', 'technology'), ('movies', 'movies')], max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_text', models.CharField(max_length=200)),
                ('is_valid', models.BooleanField(default=False)),
                ('post_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_query_name='post', to='post.post')),
            ],
        ),
    ]
