# Generated by Django 4.0.5 on 2022-11-15 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='email',
            field=models.EmailField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='mobile',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
