# Generated by Django 4.0.5 on 2022-11-15 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_alter_post_email_alter_post_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='images',
            field=models.CharField(max_length=200),
        ),
    ]
