# Generated by Django 4.0.5 on 2022-11-17 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_comments_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_winner',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='email',
            field=models.EmailField(error_messages={'unique': 'This email has already been registered.'}, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='mobile',
            field=models.CharField(error_messages={'unique': 'This mobile number has already been registered.'}, max_length=10, unique=True),
        ),
    ]
