# Generated by Django 4.0.5 on 2022-11-17 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_post_is_winner_alter_post_email_alter_post_mobile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='is_winner',
        ),
    ]
