# Generated by Django 4.0.5 on 2022-11-17 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0007_post_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_winner',
            field=models.BooleanField(default=False),
        ),
    ]
