# Generated by Django 4.0.5 on 2022-11-23 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0011_fileupload'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileupload',
            name='file_field',
            field=models.FileField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
