# Generated by Django 4.0.5 on 2022-11-24 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0012_fileupload_file_field'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FileUpload',
        ),
    ]
