# Generated by Django 4.0.5 on 2022-11-24 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0013_delete_fileupload'),
    ]

    operations = [
        migrations.CreateModel(
            name='Uploader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
                ('mobile', models.IntegerField(blank=True, max_length=10, null=True)),
                ('age', models.IntegerField()),
            ],
        ),
    ]
