# Generated by Django 4.0.5 on 2022-11-24 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0014_uploader'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploader',
            name='age',
        ),
        migrations.AddField(
            model_name='uploader',
            name='email',
            field=models.CharField(blank=True, default=None, max_length=50),
        ),
    ]
