# Generated by Django 4.0.5 on 2022-11-24 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0015_remove_uploader_age_uploader_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploader',
            name='mobile',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
