# Generated by Django 4.0.5 on 2022-12-05 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0018_post_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='user_id',
        ),
    ]
