# Generated by Django 4.1 on 2022-09-13 09:54

from django.db import migrations, models
import tasks.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ValidatorsTask',
            fields=[
                ('uid', models.IntegerField(primary_key=True, serialize=False)),
                ('uname', models.CharField(max_length=50)),
                ('upass', models.CharField(max_length=50, validators=[tasks.validators.validatePassword])),
            ],
        ),
    ]
