# Generated by Django 4.1 on 2022-09-16 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('rollno', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('sname', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=60)),
                ('phone', models.CharField(max_length=13)),
                ('address', models.TextField(max_length=250)),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('courseid', models.IntegerField(primary_key=True, serialize=False)),
                ('coursename', models.CharField(max_length=100)),
                ('courseduration', models.FloatField()),
            ],
            options={
                'managed': True,
            },
        ),
    ]
