# Generated by Django 4.1.1 on 2022-09-05 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Train',
            fields=[
                ('train_no', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('train_name', models.CharField(max_length=50)),
                ('arrival_time', models.TimeField()),
                ('departure_time', models.TimeField()),
                ('availability_of_seats', models.IntegerField()),
                ('train_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('adhar_no', models.CharField(default='', max_length=50)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('age', models.IntegerField(default=0)),
                ('mobile_no', models.CharField(max_length=13)),
                ('email', models.EmailField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('pincode', models.CharField(max_length=12)),
                ('password', models.CharField(max_length=50)),
                ('security_ques', models.CharField(default='', max_length=50)),
                ('security_ans', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TrainStatus',
            fields=[
                ('train_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='mymodel.train')),
                ('b_seat1', models.IntegerField()),
                ('b_seat2', models.IntegerField()),
                ('w_seat1', models.IntegerField()),
                ('w_seat2', models.IntegerField()),
                ('a_seat1', models.IntegerField()),
                ('a_seat2', models.IntegerField()),
                ('fair2', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('WL', 'Waiting list'), ('CNF', 'Confirm'), ('RAC', 'RAC')], max_length=3)),
                ('no_of_passengers', models.IntegerField()),
                ('train_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mymodel.train')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mymodel.user')),
            ],
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('station_no', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('station_name', models.CharField(max_length=50)),
                ('hault', models.IntegerField()),
                ('arrival_time', models.TimeField()),
                ('train_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mymodel.train')),
            ],
        ),
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('passenger_id', models.IntegerField(primary_key=True, serialize=False)),
                ('pnr_no', models.IntegerField()),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('reservation_status', models.CharField(choices=[('WL', 'Waiting list'), ('CNF', 'Confirm'), ('RAC', 'RAC')], max_length=3)),
                ('seat_no', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=50)),
                ('ticket_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mymodel.ticket')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mymodel.user')),
            ],
        ),
        migrations.CreateModel(
            name='Cancel',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('passenger_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mymodel.passenger')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mymodel.user')),
            ],
        ),
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mymodel.user')),
            ],
        ),
        migrations.CreateModel(
            name='Stopped',
            fields=[
                ('train_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='mymodel.train')),
                ('station_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mymodel.station')),
            ],
        ),
        migrations.CreateModel(
            name='Started',
            fields=[
                ('train_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='mymodel.train')),
                ('station_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mymodel.station')),
            ],
        ),
        migrations.CreateModel(
            name='Reaches',
            fields=[
                ('train_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='mymodel.train')),
                ('timing', models.TimeField()),
                ('station_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mymodel.station')),
            ],
        ),
    ]
