# Generated by Django 4.1.1 on 2022-09-05 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mymodel', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Books',
            new_name='Book',
        ),
        migrations.RenameModel(
            old_name='Reaches',
            new_name='Reach',
        ),
    ]
