spring.application.name=Vehicle-Insurance-Project
server.port=8000
datasource.url=jdbc:mysql://localhost:3306/bhanu
datasource.username=practice
datasource.password=Vbhanu@123
datasource.driver-class-name=com.mysql.cj.jdbc.Driver