# Generated by Django 4.1.3 on 2022-11-24 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('branch_id', models.IntegerField(primary_key=True, serialize=False)),
                ('branch_name', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'Branch',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Marks',
            fields=[
                ('marks_id', models.IntegerField(primary_key=True, serialize=False)),
                ('marks', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Marks',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StudentInfo',
            fields=[
                ('student_id', models.IntegerField(primary_key=True, serialize=False)),
                ('student_name', models.CharField(blank=True, max_length=255, null=True)),
                ('roll_no', models.CharField(blank=True, max_length=255, null=True)),
                ('dob', models.DateField(blank=True, db_column='DOB', null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('gender', models.CharField(blank=True, max_length=255, null=True)),
                ('phone_no', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'Student_Info',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('subject_id', models.IntegerField(primary_key=True, serialize=False)),
                ('subject_name', models.CharField(blank=True, max_length=255, null=True)),
                ('semester', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Subjects',
                'managed': False,
            },
        ),
    ]
