# Generated by Django 4.1.1 on 2022-09-26 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('appointment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.customer'),
        ),
        migrations.AddField(
            model_name='report',
            name='appointment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointment.appointment'),
        ),
        migrations.AddField(
            model_name='lab',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointment.branch'),
        ),
        migrations.AddField(
            model_name='bill',
            name='appointment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointment.appointment'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointment.branch'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='test',
            field=models.ManyToManyField(blank=True, to='appointment.test'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.customer'),
        ),
    ]
