# Generated by Django 4.1.1 on 2022-09-28 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0003_appointment_sample_collector_appointment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='test',
            field=models.ManyToManyField(blank=True, null=True, to='appointment.test'),
        ),
    ]
