# Generated by Django 4.1.1 on 2022-09-28 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_staff_status_user_is_employee_alter_user_is_staff'),
        ('appointment', '0006_remove_appointment_user_alter_appointment_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.customer'),
        ),
    ]
