# Generated by Django 4.1.1 on 2022-09-28 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0010_alter_appointment_appointment_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='test',
        ),
    ]
