# Generated by Django 4.1.1 on 2022-09-29 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0011_remove_appointment_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='slot',
            field=models.CharField(choices=[('10 AM', '10 AM'), ('1PM', '1PM'), ('4 PM', '4 PM')], max_length=100),
        ),
    ]
