# Generated by Django 4.1.1 on 2022-09-29 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0012_alter_appointment_slot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='slot',
            field=models.CharField(choices=[('10 AM', '10 AM'), ('1 PM', '1 PM'), ('4 PM', '4 PM')], max_length=100),
        ),
    ]
