# Generated by Django 4.1 on 2022-09-06 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_profile_id_remove_profile_user_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Skill',
        ),
    ]
