# Generated by Django 4.0.5 on 2022-09-06 07:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0014_alter_topictag_tag_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Solved',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('solution', models.TextField(max_length=500)),
                ('status', models.IntegerField(choices=[(1, 'Accepted'), (2, 'Wrong Answer'), (3, 'Time Limit Exceeded'), (4, 'Input Limit Exceeded'), (5, 'Not Attempted')])),
                ('problem_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.problem')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
