# Generated by Django 4.1 on 2022-09-05 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CRICKET_BOARDS',
            fields=[
                ('board_id', models.TextField(max_length=30, primary_key=True, serialize=False)),
                ('board_name', models.TextField(max_length=30)),
                ('board_chairman', models.TextField(max_length=30, null=True)),
            ],
        ),
    ]
