# Generated by Django 4.1 on 2022-09-13 09:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Master',
            fields=[
                ('master_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('qualification', models.CharField(max_length=20)),
                ('position', models.CharField(max_length=20)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('question_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('question_name', models.TextField(max_length=10000)),
                ('answer', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Set',
            fields=[
                ('set_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('set_name', models.CharField(max_length=20)),
                ('master_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app4.master')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('subject_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('subject_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('reqister_number', models.CharField(blank=True, max_length=20, null=True)),
                ('college_name', models.CharField(blank=True, max_length=50, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SetQuestionNumber',
            fields=[
                ('set_question_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('question_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app4.question')),
                ('set_id', models.ManyToManyField(to='app4.set')),
            ],
        ),
        migrations.AddField(
            model_name='set',
            name='subject_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app4.subject'),
        ),
        migrations.AddField(
            model_name='question',
            name='set_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app4.set'),
        ),
        migrations.AddField(
            model_name='question',
            name='subject_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app4.subject'),
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('option_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('choice_a', models.CharField(max_length=1000)),
                ('choice_b', models.CharField(max_length=1000)),
                ('choice_c', models.CharField(max_length=1000)),
                ('choice_d', models.CharField(max_length=1000)),
                ('question_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app4.question')),
            ],
        ),
        migrations.CreateModel(
            name='ExamAttemptDetail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_answer', models.CharField(max_length=1000, null=True)),
                ('set_question_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app4.setquestionnumber')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app4.student')),
            ],
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_marks', models.IntegerField()),
                ('score', models.IntegerField()),
                ('result', models.BooleanField(default=False)),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app4.student')),
            ],
        ),
    ]
