# Generated by Django 4.1 on 2022-09-05 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app4', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CRICKET_BOARDS',
            new_name='CricketBoard',
        ),
    ]
