# Generated by Django 4.1 on 2022-09-05 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app4', '0002_rename_cricket_boards_cricketboard'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('coach_id', models.TextField(max_length=40, primary_key=True, serialize=False)),
                ('coach_name', models.TextField(max_length=30)),
                ('coach_country', models.TextField(blank=True, max_length=30, null=True)),
                ('coach_experience', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
