# Generated by Django 4.1 on 2022-09-05 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app4', '0003_coach'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coach',
            name='coach_id',
            field=models.CharField(max_length=40, primary_key=True, serialize=False),
        ),
    ]
