# Generated by Django 4.1 on 2022-09-05 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app4', '0004_alter_coach_coach_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coach',
            name='coach_country',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='coach',
            name='coach_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='cricketboard',
            name='board_chairman',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='cricketboard',
            name='board_id',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='cricketboard',
            name='board_name',
            field=models.CharField(max_length=30),
        ),
    ]
