# Generated by Django 4.1 on 2022-09-06 05:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app4', '0005_alter_coach_coach_country_alter_coach_coach_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coach',
            name='coach_country',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='coach',
            name='coach_name',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='cricketboard',
            name='board_chairman',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='cricketboard',
            name='board_id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='cricketboard',
            name='board_name',
            field=models.CharField(max_length=50),
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('tean_id', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('team_name', models.CharField(max_length=50)),
                ('team_rank', models.IntegerField(blank=True, null=True)),
                ('board_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app4.cricketboard')),
            ],
        ),
    ]
