# Generated by Django 4.1 on 2022-09-06 05:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app4', '0006_alter_coach_coach_country_alter_coach_coach_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Captain',
            fields=[
                ('captain_id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('no_of_wins', models.IntegerField(blank=True, null=True)),
                ('no_of_loses', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='team',
            name='coach_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app4.coach'),
        ),
        migrations.AddField(
            model_name='team',
            name='captain_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app4.captain'),
        ),
    ]
