# Generated by Django 4.1 on 2022-09-06 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app4', '0007_captain_team_coach_id_team_captain_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Batsman',
            fields=[
                ('batsman_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('type_of_batsman', models.CharField(max_length=30)),
                ('test_runs', models.IntegerField(blank=True, null=True)),
                ('odi_runs', models.IntegerField(blank=True, null=True)),
                ('t20_runs', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Bowler',
            fields=[
                ('bowler_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('type_of_bowler', models.CharField(max_length=30)),
                ('test_wkts', models.IntegerField(blank=True, null=True)),
                ('odi_wkts', models.IntegerField(blank=True, null=True)),
                ('t20_wkts', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WicketKeeper',
            fields=[
                ('wk_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('no_of_catches', models.IntegerField(blank=True, null=True)),
                ('no_of_stumpings', models.IntegerField(blank=True, null=True)),
                ('no_of_runouts', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
