# Generated by Django 4.1 on 2022-09-06 05:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app4', '0008_batsman_bowler_wicketkeeper'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('player_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('player_name', models.CharField(max_length=30)),
                ('player_age', models.IntegerField()),
                ('matches_played', models.IntegerField(blank=True, null=True)),
                ('player_country', models.CharField(blank=True, max_length=20, null=True)),
                ('batsman_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app4.batsman')),
                ('bowler_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app4.bowler')),
                ('captain_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app4.captain')),
                ('team_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app4.team')),
                ('wk_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app4.wicketkeeper')),
            ],
        ),
    ]
