# Generated by Django 4.1 on 2022-09-07 04:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airlines',
            fields=[
                ('airlines_name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('origin_country', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('airport_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('airport_name', models.CharField(blank=True, max_length=50, null=True)),
                ('airport_owner', models.CharField(blank=True, max_length=50, null=True)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('flight_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('flight_name', models.CharField(blank=True, max_length=50, null=True)),
                ('destination', models.CharField(blank=True, max_length=50, null=True)),
                ('model_number', models.CharField(blank=True, max_length=50, null=True)),
                ('capacity', models.PositiveIntegerField(blank=True, null=True)),
                ('weight', models.PositiveIntegerField(blank=True, null=True)),
                ('airlines_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app4.airlines')),
                ('airport_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app4.airport')),
            ],
        ),
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('passenger_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('passenger_name', models.CharField(blank=True, max_length=50, null=True)),
                ('mobile_number', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(max_length=50)),
                ('passenger_city', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('ticket_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('booking_from', models.CharField(blank=True, max_length=50, null=True)),
                ('booking_to', models.CharField(blank=True, max_length=50, null=True)),
                ('travel_date', models.DateTimeField()),
                ('flight_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app4.flight')),
                ('passenger_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app4.passenger')),
            ],
        ),
        migrations.CreateModel(
            name='Terminal',
            fields=[
                ('terminal_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('terminal_description', models.TextField(blank=True, max_length=200, null=True)),
                ('airport_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app4.airport')),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('staff_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('staff_designation', models.CharField(blank=True, max_length=50, null=True)),
                ('staff_name', models.CharField(blank=True, max_length=50, null=True)),
                ('staff_phone', models.PositiveIntegerField()),
                ('airlines_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app4.airlines')),
                ('airport_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app4.airport')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('departure_time', models.DateTimeField(primary_key=True, serialize=False)),
                ('arrival_time', models.DateTimeField()),
                ('airport_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app4.airport')),
                ('flight_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app4.flight')),
                ('terminal_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app4.terminal')),
            ],
        ),
        migrations.AddField(
            model_name='airlines',
            name='airport_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app4.airport'),
        ),
        migrations.AddField(
            model_name='airlines',
            name='terminal_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app4.terminal'),
        ),
    ]
