# Generated by Django 4.1 on 2022-09-09 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app4', '0002_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Luggage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('luggage_type', models.CharField(blank=True, max_length=50, null=True)),
                ('luggage_weight', models.PositiveIntegerField()),
                ('ticket_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app4.ticket')),
            ],
        ),
        migrations.CreateModel(
            name='StaffShifts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift_from', models.DateTimeField(verbose_name='default=timezone.now')),
                ('shift_to', models.DateTimeField(verbose_name='default=timezone.now')),
                ('flight_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app4.flight')),
                ('staff_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app4.staff')),
            ],
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
