# Generated by Django 4.1 on 2022-09-12 04:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app4', '0003_luggage_staffshifts_delete_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='flight_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app4.flight'),
        ),
    ]
