# Generated by Django 4.1 on 2022-09-29 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app4', '0005_passenger_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='airlines',
            name='airlines_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='airlines',
            name='airlines_img',
            field=models.ImageField(default=None, upload_to=''),
        ),
    ]
