# Generated by Django 4.1 on 2022-09-30 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app4', '0006_airlines_airlines_id_airlines_airlines_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='travel_date',
            field=models.DateField(),
        ),
    ]
