# Generated by Django 2.2.4 on 2022-11-03 09:36

import app4.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app4', '0007_alter_ticket_travel_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='passenger',
            name='is_admin',
            field=models.CharField(default='false', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='passenger',
            name='passenger_image',
            field=models.ImageField(default=None, null=True, upload_to=app4.models.upload_paths),
        ),
        migrations.AddField(
            model_name='ticket',
            name='seat_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='airlines',
            name='airlines_id',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='airlines',
            name='airlines_img',
            field=models.ImageField(default=None, null=True, upload_to=app4.models.upload_path),
        ),
        migrations.AlterField(
            model_name='airlines',
            name='airport_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app4.Airport'),
        ),
        migrations.AlterField(
            model_name='airlines',
            name='origin_country',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='airlines',
            name='terminal_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app4.Terminal'),
        ),
        migrations.AlterField(
            model_name='luggage',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='email',
            field=models.EmailField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='arrival_time',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='departure_time',
            field=models.DateField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='staffshifts',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='staffshifts',
            name='shift_from',
            field=models.DateField(verbose_name='default=timezone.now'),
        ),
        migrations.AlterField(
            model_name='staffshifts',
            name='shift_to',
            field=models.DateField(verbose_name='default=timezone.now'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticket_id',
            field=models.PositiveIntegerField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
