# Generated by Django 4.1 on 2022-09-13 13:07

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import jangoapp4.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='department',
            fields=[
                ('deptid', models.IntegerField(default=1, primary_key=True, serialize=False)),
                ('dept_name', models.CharField(choices=[('ece', 'electronics and communication'), ('eee', 'electrical and electronics'), ('civ', 'civil'), ('mech', 'mechanical')], default='ece', max_length=4)),
            ],
            options={
                'db_table': 'Department',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'loaction',
            },
        ),
        migrations.CreateModel(
            name='PracticeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=60)),
                ('shirt_size', models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large')], max_length=1, null=True)),
                ('languages_known', models.CharField(choices=[('tel', 'telugu'), ('hin', 'hindi'), ('eng', 'english')], default='tel', max_length=5)),
                ('Bool', models.BooleanField(default=False, verbose_name='this is a boolean field')),
                ('character', models.CharField(help_text='enter full name', max_length=100, verbose_name='name')),
                ('Date', models.DateField(default=django.utils.timezone.now)),
                ('deci', models.DecimalField(db_column='decimal value', decimal_places=2, default=1.0, max_digits=5, verbose_name='decimalfield')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('sid', models.IntegerField(db_column='student id', primary_key=True, serialize=False)),
                ('sname', models.CharField(max_length=20)),
                ('Marks', models.IntegerField(validators=[jangoapp4.models.validate_marks])),
                ('semester', models.IntegerField(validators=[django.core.validators.MaxValueValidator(8), django.core.validators.MinValueValidator(1)])),
                ('file', models.FileField(upload_to='', validators=[django.core.validators.FileExtensionValidator(['pdf', 'png'])])),
                ('departments', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='jangoapp4.department')),
            ],
            options={
                'db_table': 'student',
            },
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('pid', models.IntegerField(primary_key=True, serialize=False)),
                ('p_name', models.CharField(max_length=50)),
                ('departments', models.ManyToManyField(to='jangoapp4.department')),
            ],
            options={
                'db_table': 'Professor',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='college',
            fields=[
                ('clg_code', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('clgname', models.CharField(max_length=50)),
                ('places', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='jangoapp4.location')),
            ],
            options={
                'db_table': 'college',
            },
        ),
    ]
