# Generated by Django 4.1 on 2022-09-14 05:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jangoapp4', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='practicemodel',
            name='email',
            field=models.EmailField(max_length=100, null=True, verbose_name='email id'),
        ),
        migrations.AddField(
            model_name='practicemodel',
            name='file',
            field=models.FileField(null=True, upload_to='', validators=[django.core.validators.FileExtensionValidator(['pdf'])]),
        ),
        migrations.AddField(
            model_name='practicemodel',
            name='image',
            field=models.ImageField(null=True, upload_to='', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg'])]),
        ),
    ]
