# Generated by Django 4.1 on 2022-10-28 03:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_alter_employee_table'),
        ('vehicle', '0001_initial'),
        ('order', '0002_order_delivery_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='employee.employee')),
                ('order_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='order.order')),
                ('vehicle_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='vehicle.vehicle')),
            ],
        ),
    ]
