# Generated by Django 4.1 on 2022-10-28 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_deliveryt'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryt',
            name='finsihed',
            field=models.BooleanField(default=False),
        ),
    ]
