# Generated by Django 4.1 on 2022-10-28 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_deliveryt_finsihed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryt',
            name='finsihed',
            field=models.BooleanField(default=True),
        ),
    ]
