# Generated by Django 5.2.4 on 2025-07-17 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0003_remove_order_order_status'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='order',
            table='Orders',
        ),
    ]
