# Generated by Django 4.1 on 2022-10-20 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('vehicle_no', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('model', models.CharField(max_length=20)),
                ('owner_name', models.CharField(max_length=50)),
                ('permit_range', models.CharField(max_length=50)),
                ('fuel_efficiency', models.FloatField()),
                ('load_capacity', models.FloatField()),
            ],
        ),
    ]
