# Generated by Django 4.2.23 on 2025-07-15 04:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('Class_id', models.IntegerField(primary_key=True, serialize=False)),
                ('Section', models.CharField(max_length=3)),
            ],
            options={
                'db_table': 'classes',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Age', models.IntegerField()),
                ('Section', models.CharField(max_length=3)),
                ('joining_date', models.DateField(auto_now_add=True)),
                ('attendance', models.IntegerField()),
                ('Class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.classes')),
            ],
            options={
                'db_table': 'student',
            },
        ),
        migrations.CreateModel(
<<<<<<< HEAD
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FatherName', models.CharField(max_length=100)),
                ('MotherName', models.CharField(max_length=100)),
                ('FatherAge', models.IntegerField()),
                ('MotherAge', models.IntegerField()),
                ('address', models.CharField(max_length=100)),
                ('Student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='school.student')),
            ],
            options={
                'db_table': 'student_profile',
=======
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('level', models.CharField(choices=[('p', 'primary'), ('h', 'high school'), ('l', 'low school')], max_length=2)),
                ('joining_date', models.DateField(auto_now_add=True)),
                ('experience', models.IntegerField()),
            ],
            options={
                'db_table': 'teacher',
>>>>>>> e964a07e243f273514c12db57b669607a88267cd
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.classes')),
                ('Teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.teacher')),
            ],
            options={
                'db_table': 'subject',
            },
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FatherName', models.CharField(max_length=100)),
                ('MotherName', models.CharField(max_length=100)),
                ('FatherAge', models.IntegerField()),
                ('MotherAge', models.IntegerField()),
                ('address', models.CharField(max_length=100)),
                ('Student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='school.student')),
            ],
            options={
                'db_table': 'student_profile',
            },
        ),
        migrations.CreateModel(
            name='Results',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.IntegerField()),
                ('percentage', models.FloatField()),
                ('Class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.classes')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.subject')),
            ],
            options={
                'db_table': 'results',
            },
        ),
        migrations.AddField(
            model_name='classes',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.teacher'),
        ),
        migrations.AlterUniqueTogether(
            name='classes',
            unique_together={('Section', 'Class_id')},
        ),
    ]
