# Generated by Django 5.2.4 on 2025-07-14 06:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FatherName', models.CharField(max_length=100)),
                ('MotherName', models.CharField(max_length=100)),
                ('FatherAge', models.IntegerField()),
                ('MotherAge', models.IntegerField()),
                ('address', models.CharField(max_length=100)),
                ('Student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='school.student')),
            ],
            options={
                'db_table': 'student_profile',
            },
        ),
    ]
