# Generated by Django 4.1.6 on 2023-02-13 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('booking', '0002_initial'),
        ('show', '0001_initial'),
        ('cinema', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShowSeat',
            fields=[
                ('show_seat_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('status', models.IntegerField(blank=True, default=1, null=True)),
                ('price', models.IntegerField(blank=True, default=1, null=True)),
                ('booking', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='booking.booking')),
                ('cinema_seat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cinema.cinema_seat')),
                ('show', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='show.show')),
            ],
        ),
    ]
