# Generated by Django 4.1 on 2022-08-18 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medplus_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='employees1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('phone_number', models.IntegerField()),
                ('email_id', models.EmailField(max_length=50)),
                ('role', models.CharField(max_length=100)),
                ('salary', models.IntegerField()),
            ],
        ),
    ]
