# Generated by Django 4.1 on 2022-08-18 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medplus_app', '0002_employees1'),
    ]

    operations = [
        migrations.DeleteModel(
            name='employees',
        ),
    ]
