# Generated by Django 4.0.5 on 2022-08-24 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medplus_app', '0003_delete_employees'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='employees1',
            table='employees1',
        ),
    ]
