# Generated by Django 4.0.5 on 2022-08-24 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medplus_app', '0004_alter_employees1_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='employees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('phone_number', models.IntegerField()),
                ('email_id', models.EmailField(max_length=50)),
                ('role', models.CharField(max_length=100)),
                ('salary', models.IntegerField()),
            ],
        ),
    ]
