# -*- coding: utf-8 -*-
"""Assignment_1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YhP5uS-YigpA1f2MKCnppXK065Wo3B8d

Assignment - 1

Task-1

Student Averages with Tuple Unpacking

Problem Statement: First, write a helper function get_student_info() that simply returns a hardcoded list of student data. Each element in the list should be a tuple structured as (student_id, student_name, (score1, score2, score3)). The scores themselves are in an inner tuple.

Second, write a script that calls this function to get the data. Then, iterate through the list using a for loop. Inside the loop, you must use tuple unpacking to directly assign the ID, name, and the tuple of scores to distinct variables. Calculate the average score for each student and print their name and average score.

Requirements:

The get_student_info() function should be defined and used.
The for loop must use tuple unpacking to handle the nested structure, e.g., for student_id, name, (s1, s2, s3) in students:.
The output should be a clean printout for each student.
"""

def get_student_info():
  student_data=[]
  student_data.append((1,"Uday",(20,30,40)))
  student_data.append((2,"Bhanu",(20,35,45)))
  student_data.append((3,"Rohan",(25,35,40)))
  student_data.append((4,"Shaikh",(25,30,40)))
  student_data.append((5,"kanishka",(30,35,45)))
  student_data.append((6,"leon",(30,30,40)))
  student_data.append((7,"rohith",(20,40,40)))
  return student_data

required_data=get_student_info()
for data_tuple in required_data:
  ID,name,scores=data_tuple
  print(f'{name} has an average score of {(sum(scores)/len(scores)):.2f}')

"""Task -2"""

def group_by_key(tuple_list):
  res={}
  for key,val in tuple_list:
    if key in res:
      res[key].append(val)
    else:
      res[key]=[val]
  return res

print(group_by_key([(1,2),(1,3),(2,4),(3,6),(4,8),(3,10),(2,9)]))

"""Task -3"""

a={'1':2,'1':4}

a['1']

def merge_and_sum(dict_1,dict_2):
  res={}
  for key,value in dict_1.items():
    res[key]=value
  for key,value in dict_2.items():
    if key in res:
      res[key]+=value
    else:
      res[key]=value
  return res

print(merge_and_sum({'1':2,'2':3,'3':6},{'4':6,'5':7,'3':2,'1':5}))

"""Task -4"""

def invert_dictionary(d_1):
  new_dict={}
  for key,value in d_1.items():
    new_dict.setdefault(value,[]).append(key)
    # if value in new_dict:
    #   new_dict[value].append(key)
    # else:
    #   new_dict[value]=[key]
  return new_dict

invert_dictionary( {'a': 1, 'b': 2, 'c': 1, 'd': 3})

"""Task -5"""

def create_or_update_item(items_dict, key, value=None):
  if key!=None:
    if value!=None:
      items_dict[key]=value
    else:
      del items_dict[key]

new_dict={}
create_or_update_item(new_dict,1,22)
print(new_dict)

create_or_update_item(new_dict,2,22)
print(new_dict)

create_or_update_item(new_dict,1,42)
print(new_dict)

create_or_update_item(new_dict,None,22)
print(new_dict)

create_or_update_item(new_dict,3,22)
print(new_dict)

create_or_update_item(new_dict,3,None)
print(new_dict)

"""Task -6"""

def  find_common_elements(list1, list2):
  return [ele for ele in list1 if ele in list2]

find_common_elements([1,2,3,4,5,0],[4,3,7,8,5])

"""Task -7"""

def flatten_list(nested_list):
  ans=[ele for new_list in nested_list for ele in new_list]
  return ans

print(flatten_list([[12,3,4],[6,7,8]]))

"""Task -8"""

def  process_scores(scores):
  if len(scores)>2:
    first,*middle,last=scores
    middle_avg=sum(middle)/len(middle)
  else:
    first,last=scores
    middle_avg=0
  return (first,last,middle_avg)

print(process_scores([98, 85, 88, 92, 78]))

"""Task -9"""

def  is_palindrome_slicing(data):
  return data==data[::-1]

print(is_palindrome_slicing("abcdcba"))
print(is_palindrome_slicing([1,2,3,3,2,1]))
print(is_palindrome_slicing("abcdefg"))
print(is_palindrome_slicing([1,2,3,4,5,6]))

"""Task -10"""

a='123.56'.split('.')[0]
print(a)

def change_amount(amount_val):
  amount_val_str="{:.2f}".format(amount_val)
  changed_amount='.'+amount_val_str[-2]+amount_val_str[-1]
  count=0
  for ele in amount_val_str.split('.')[0][::-1]:
    if (count)%3==0 and count!=0:
      changed_amount=','+changed_amount
      changed_amount=ele+changed_amount

    else:
      changed_amount=ele+changed_amount
    count+=1
  return changed_amount

def format_currency(amount, currency_symbol='$'):
  seperated_amount=change_amount(round(amount,2))
  print(f'{currency_symbol}{seperated_amount}')

format_currency(1,'$')

"""Task -11"""

def process_names(names):
  print(list(filter(lambda name:len(name)>3,map(str.capitalize,names))))

process_names(["kanishka",'father','kan','uday'])

"""Task 12"""

mapper={10:'A',11:'B',12:'C',13:'D',14:'E',15:'F'}

# def convert_to_custom_base(decimal_num, base,ans):
#   if decimal_num<=0:
#     return ans

#   rem=decimal_num%base
#   decimal_num=decimal_num//base
#   if rem>=10:
#     ans=mapper[rem]+ans
#   else:
#     ans=str(rem)+ans
#   return convert_to_custom_base(decimal_num,base,ans)

def convert_to_custom_base(decimal_num, base):
  if decimal_num==0:
    return '0'
  ans=''
  while decimal_num>0:

    rem=decimal_num%base
    decimal_num=decimal_num//base
    if rem>=10:
      ans=mapper[rem]+ans
    else:
      ans=str(rem)+ans
  return ans

convert_to_custom_base(42,8)

