# Generated by Django 4.1.1 on 2022-09-06 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('branch_id', models.IntegerField(primary_key=True, serialize=False)),
                ('branch_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Exam_branch',
            fields=[
                ('hall_ticket_number', models.IntegerField(primary_key=True, serialize=False)),
                ('due_subjects', models.IntegerField()),
                ('total_subjects', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Fee_report',
            fields=[
                ('fee_id', models.IntegerField(primary_key=True, serialize=False)),
                ('total_fee', models.IntegerField()),
                ('fee_due', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Hod',
            fields=[
                ('hod_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='hod')),
                ('hod_name', models.CharField(max_length=30)),
                ('Professor_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('professor_id', models.IntegerField(primary_key=True, serialize=False)),
                ('professor_name', models.CharField(max_length=30)),
                ('branch_id', models.IntegerField()),
                ('salary', models.IntegerField()),
                ('professor_password', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.IntegerField(primary_key=True, serialize=False)),
                ('student_name', models.CharField(max_length=30)),
                ('Student_mobile', models.CharField(max_length=30)),
                ('Student_email', models.CharField(max_length=30)),
                ('student_password', models.CharField(max_length=30)),
                ('branch_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.branch')),
                ('fee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.fee_report')),
                ('hall_ticket_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.exam_branch')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.IntegerField(primary_key=True, serialize=False)),
                ('course_name', models.CharField(max_length=30)),
                ('employee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.professor')),
            ],
        ),
        migrations.AddField(
            model_name='branch',
            name='hod_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.hod'),
        ),
    ]
