# Generated by Django 4.1 on 2022-09-06 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Beds",
            fields=[
                ("bed_no", models.IntegerField(primary_key=True, serialize=False)),
                ("bed_type", models.CharField(max_length=50)),
                ("charge", models.IntegerField()),
                ("is_occupied", models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name="Department",
            fields=[
                ("dept_id", models.IntegerField(primary_key=True, serialize=False)),
                ("dept_name", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Labs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("lab_id", models.IntegerField()),
                ("lab_type", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Patient",
            fields=[
                ("patient_id", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("age", models.IntegerField()),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female"), ("T", "Transgender")],
                        max_length=1,
                    ),
                ),
                ("contact_num", models.CharField(max_length=20)),
                ("address", models.CharField(max_length=150)),
                ("in_date_time", models.DateTimeField()),
                ("out_date_time", models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Role",
            fields=[
                ("role_id", models.IntegerField(primary_key=True, serialize=False)),
                ("role_name", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Staff",
            fields=[
                ("emp_id", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=50)),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female"), ("T", "Transgender")],
                        max_length=1,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Ward",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ward_id", models.IntegerField()),
                ("ward_name", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Treatment_details",
            fields=[
                ("sl_no", models.IntegerField(primary_key=True, serialize=False)),
                ("disease", models.CharField(max_length=50)),
                (
                    "bed_no",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="hospital_app.beds",
                    ),
                ),
                (
                    "patient_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="hospital_app.patient",
                    ),
                ),
                (
                    "treated_doc",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="hospital_app.staff",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Staff_Role_Dept",
            fields=[
                ("sl_no", models.IntegerField(primary_key=True, serialize=False)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "dept_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="hospital_app.department",
                    ),
                ),
                (
                    "emp_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="hospital_app.staff",
                    ),
                ),
                (
                    "role_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="hospital_app.role",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Diagnosis",
            fields=[
                (
                    "diagnosis_id",
                    models.IntegerField(primary_key=True, serialize=False),
                ),
                ("amount", models.IntegerField()),
                (
                    "doctor_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="hospital_app.staff",
                    ),
                ),
                (
                    "lab_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="hospital_app.labs",
                    ),
                ),
                (
                    "patient_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="hospital_app.patient",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Bill",
            fields=[
                ("bill_no", models.IntegerField(primary_key=True, serialize=False)),
                ("no_of_days", models.IntegerField()),
                ("consultation_charge", models.IntegerField()),
                ("total_amount", models.IntegerField()),
                (
                    "bed_charge",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="hospital_app.beds",
                    ),
                ),
                (
                    "lab_charge",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="hospital_app.diagnosis",
                    ),
                ),
                (
                    "patient_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="hospital_app.patient",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="beds",
            name="ward_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="hospital_app.ward"
            ),
        ),
    ]
