# Generated by Django 4.1 on 2022-09-29 07:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CoDriver',
            fields=[
                ('co_driver_id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='ContainsItem',
            fields=[
                ('contains_id', models.IntegerField(primary_key=True, serialize=False)),
                ('price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('customer_name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=13)),
                ('email', models.EmailField(max_length=60)),
                ('address', models.CharField(max_length=250)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('driver_id', models.IntegerField(primary_key=True, serialize=False)),
                ('license_no', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='GraniteStore',
            fields=[
                ('store_id', models.IntegerField(primary_key=True, serialize=False)),
                ('store_name', models.CharField(max_length=50)),
                ('established_year', models.IntegerField()),
                ('store_description', models.CharField(max_length=250)),
                ('contact', models.IntegerField()),
                ('website', models.CharField(max_length=150)),
                ('address', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('item_id', models.IntegerField(primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=50)),
                ('item_pattern', models.CharField(max_length=30)),
                ('item_description', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.IntegerField(primary_key=True, serialize=False)),
                ('order_time', models.DateTimeField()),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='granite_mart.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('role_id', models.IntegerField(primary_key=True, serialize=False)),
                ('role_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('vehicle_no', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('model', models.CharField(max_length=20)),
                ('owner_name', models.CharField(max_length=50)),
                ('permit_range', models.CharField(max_length=50)),
                ('fuel_efficiency', models.FloatField()),
                ('load_capacity', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('shipment_id', models.IntegerField(primary_key=True, serialize=False)),
                ('delivery_address', models.CharField(max_length=250)),
                ('co_driver_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='granite_mart.codriver')),
                ('driver_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='granite_mart.driver')),
                ('order_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='granite_mart.order')),
                ('vehicle_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='granite_mart.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('payment_id', models.IntegerField(primary_key=True, serialize=False)),
                ('amount', models.FloatField()),
                ('payment_method', models.CharField(max_length=80)),
                ('payment_datetime', models.DateTimeField()),
                ('order_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='granite_mart.order')),
            ],
        ),
        migrations.CreateModel(
            name='OrderedItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contains_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='granite_mart.containsitem')),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='granite_mart.order')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_id', models.IntegerField(primary_key=True, serialize=False)),
                ('employee_name', models.CharField(max_length=50)),
                ('doj', models.DateField()),
                ('phone', models.IntegerField()),
                ('email', models.EmailField(max_length=60)),
                ('address', models.CharField(max_length=250)),
                ('salary', models.FloatField()),
                ('role_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='granite_mart.role')),
            ],
        ),
        migrations.AddField(
            model_name='driver',
            name='employee_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='granite_mart.employee'),
        ),
        migrations.AddField(
            model_name='containsitem',
            name='item_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='granite_mart.item'),
        ),
        migrations.AddField(
            model_name='containsitem',
            name='store_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='granite_mart.granitestore'),
        ),
        migrations.AddField(
            model_name='codriver',
            name='employee_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='granite_mart.employee'),
        ),
    ]
