# Generated by Django 4.1 on 2022-09-13 07:01

import app3.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Biodata1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=250)),
            ],
            options={
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='MyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('odd_field', models.IntegerField(validators=[app3.models.validate_odd])),
            ],
        ),
        migrations.CreateModel(
            name='Hobbies1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hobby', models.CharField(max_length=250)),
                ('biodata', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app3.biodata1')),
            ],
            options={
                'managed': True,
            },
        ),
    ]
