# Generated by Django 4.1 on 2022-09-13 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app3', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hobbies1',
            options={'managed': False},
        ),
    ]
