# Generated by Django 4.1 on 2022-09-14 08:42

import app3.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app3', '0002_alter_hobbies1_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mymodel',
            name='odd_field',
            field=models.IntegerField(null=True, validators=[app3.models.validate_odd]),
        ),
    ]
