# Generated by Django 4.1 on 2022-09-14 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app3', '0003_alter_mymodel_odd_field'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyModel',
        ),
    ]
