# Generated by Django 4.1 on 2022-09-14 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app3', '0004_delete_mymodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('odd_field', models.IntegerField()),
            ],
        ),
    ]
