# Generated by Django 4.1 on 2022-09-06 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('Admin_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('Admin_first_name', models.CharField(max_length=50)),
                ('Admin_last_name', models.CharField(max_length=50)),
                ('Admin_email_id', models.CharField(max_length=50)),
                ('Admin_contact_number', models.IntegerField()),
                ('Admin_password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('Customer_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('Customer_first_name', models.CharField(max_length=50)),
                ('Customer_last_name', models.CharField(max_length=50)),
                ('Customer_Email_id', models.CharField(max_length=50)),
                ('Customer_contact_number', models.IntegerField()),
                ('Customer_password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Hall',
            fields=[
                ('Hall_number', models.IntegerField(primary_key=True, serialize=False)),
                ('Capacity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('Movie_name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('Amount_paid', models.IntegerField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('Ticket_price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('res_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('number_of_tickets', models.IntegerField()),
                ('res_date', models.DateField(max_length=50)),
                ('show_time', models.TimeField(max_length=50)),
                ('Customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ticket_booking.customer')),
                ('Hall_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ticket_booking.hall')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('trans_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('trans_date', models.DateField()),
                ('trans_type', models.CharField(max_length=50)),
                ('Total_amount', models.IntegerField()),
                ('Admin_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ticket_booking.admin')),
                ('res_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ticket_booking.reservation')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('Ticket_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('res_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ticket_booking.reservation')),
                ('trans_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ticket_booking.transaction')),
            ],
        ),
        migrations.CreateModel(
            name='Seating_arrangement',
            fields=[
                ('seat_number', models.IntegerField(primary_key=True, serialize=False)),
                ('series', models.CharField(max_length=50)),
                ('ticket_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ticket_booking.ticket')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('Report_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('report_date', models.DateField(max_length=50)),
                ('no_of_tickets_sold', models.IntegerField()),
                ('income', models.IntegerField()),
                ('Hall_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ticket_booking.hall')),
            ],
        ),
        migrations.AddField(
            model_name='hall',
            name='Movie_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ticket_booking.movie'),
        ),
    ]
