# Generated by Django 4.1.1 on 2022-09-12 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Admin', '0019_alter_subject_details_sub_subject_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='student_details',
            fields=[
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('stud_username', models.CharField(max_length=35, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=15)),
                ('gender', models.CharField(max_length=6)),
                ('father_name', models.CharField(max_length=35)),
                ('roll_no', models.IntegerField()),
                ('class_name', models.ForeignKey(max_length=35, on_delete=django.db.models.deletion.CASCADE, to='Admin.class_details')),
            ],
        ),
    ]
