# Generated by Django 4.1.1 on 2022-09-12 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_details',
            name='date_of_birth',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='student_details',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student_details',
            name='user_type',
            field=models.CharField(default='', max_length=15),
        ),
    ]
