# Generated by Django 4.1.1 on 2022-09-13 06:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Faculty', '0001_initial'),
        ('Student', '0002_student_details_date_of_birth_student_details_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='feedback_by_student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=12)),
                ('year', models.IntegerField(max_length=4)),
                ('Q1', models.IntegerField(max_length=1)),
                ('Q2', models.IntegerField(max_length=1)),
                ('Q3', models.IntegerField(max_length=1)),
                ('Q4', models.IntegerField(max_length=1)),
                ('Q5', models.IntegerField(max_length=1)),
                ('Q6', models.IntegerField(max_length=1)),
                ('Q7', models.IntegerField(max_length=1)),
                ('Q8', models.IntegerField(max_length=1)),
                ('remarks', models.TextField(max_length=200)),
                ('GPA', models.DecimalField(decimal_places=2, max_digits=3)),
                ('stud_username', models.ForeignKey(max_length=35, on_delete=django.db.models.deletion.CASCADE, to='Student.student_details')),
                ('to_faculty', models.ForeignKey(max_length=35, on_delete=django.db.models.deletion.CASCADE, to='Faculty.faculty_details')),
            ],
        ),
    ]
