# Generated by Django 4.1.1 on 2022-09-13 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0003_feedback_by_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback_by_student',
            name='Q1',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='feedback_by_student',
            name='Q2',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='feedback_by_student',
            name='Q3',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='feedback_by_student',
            name='Q4',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='feedback_by_student',
            name='Q5',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='feedback_by_student',
            name='Q6',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='feedback_by_student',
            name='Q7',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='feedback_by_student',
            name='Q8',
            field=models.IntegerField(),
        ),
    ]
