# Generated by Django 4.1.1 on 2022-09-13 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Faculty', '0001_initial'),
        ('Student', '0004_alter_feedback_by_student_q1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='feedback_by_faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=12)),
                ('year', models.IntegerField(max_length=4)),
                ('Q1', models.IntegerField()),
                ('Q2', models.IntegerField()),
                ('Q3', models.IntegerField()),
                ('Q4', models.IntegerField()),
                ('Q5', models.IntegerField()),
                ('remarks', models.TextField(max_length=200)),
                ('GPA', models.DecimalField(decimal_places=2, max_digits=3)),
                ('facul_username', models.ForeignKey(max_length=35, on_delete=django.db.models.deletion.CASCADE, to='Faculty.faculty_details')),
                ('to_student', models.ForeignKey(max_length=35, on_delete=django.db.models.deletion.CASCADE, to='Student.student_details')),
            ],
        ),
    ]
