# Generated by Django 4.1.1 on 2022-09-13 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0005_feedback_by_faculty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback_by_student',
            name='year',
            field=models.IntegerField(),
        ),
    ]
