# Generated by Django 4.1.1 on 2022-09-30 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0006_alter_feedback_by_student_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback_by_student',
            name='stud_username',
        ),
        migrations.RemoveField(
            model_name='feedback_by_student',
            name='to_faculty',
        ),
        migrations.RemoveField(
            model_name='student_details',
            name='class_name',
        ),
        migrations.DeleteModel(
            name='feedback_by_faculty',
        ),
        migrations.DeleteModel(
            name='feedback_by_student',
        ),
        migrations.DeleteModel(
            name='student_details',
        ),
    ]
