# Generated by Django 4.1 on 2022-10-10 06:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0037_datewisehall_delete_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='datewisehall',
            name='Movie_id',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='home.movie'),
        ),
    ]
