# Generated by Django 4.1 on 2022-10-13 12:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0039_remove_datewisehall_movie_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='Movie_poster',
            field=models.CharField(default='https://cdn.bollywoodmdb.com/fit-in/movies/largethumb/2021/jug-jugg-jeeyo/jug-jugg-jeeyo-poster-5.jpg', max_length=1000),
        ),
        migrations.AlterField(
            model_name='booking',
            name='Date',
            field=models.DateField(default=datetime.date(2022, 10, 13)),
        ),
        migrations.AlterField(
            model_name='datewisehall',
            name='Date',
            field=models.DateField(default=datetime.date(2022, 10, 13)),
        ),
        migrations.AlterField(
            model_name='hall',
            name='Date',
            field=models.DateField(default=datetime.date(2022, 10, 13)),
        ),
        migrations.AlterField(
            model_name='movie',
            name='Movie_Release_date',
            field=models.DateField(default=datetime.date(2022, 10, 13)),
        ),
        migrations.AlterField(
            model_name='users',
            name='User_DOB',
            field=models.DateField(default=datetime.date(2022, 10, 13)),
        ),
    ]
