# Generated by Django 4.1 on 2022-10-14 10:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0040_movie_movie_poster_alter_booking_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='Date',
            field=models.DateField(default=datetime.date(2022, 10, 14)),
        ),
        migrations.AlterField(
            model_name='datewisehall',
            name='Date',
            field=models.DateField(default=datetime.date(2022, 10, 14)),
        ),
        migrations.AlterField(
            model_name='hall',
            name='Date',
            field=models.DateField(default=datetime.date(2022, 10, 14)),
        ),
        migrations.AlterField(
            model_name='hall',
            name='Hall_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='movie',
            name='Movie_Release_date',
            field=models.DateField(default=datetime.date(2022, 10, 14)),
        ),
        migrations.AlterField(
            model_name='users',
            name='User_DOB',
            field=models.DateField(default=datetime.date(2022, 10, 14)),
        ),
        migrations.AlterUniqueTogether(
            name='datewisehall',
            unique_together={('Date', 'Hall_id')},
        ),
    ]
