# Generated by Django 4.1 on 2022-10-25 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0048_remove_hall_movie_id_remove_hall_endtime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='PROMOCODE',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='home.promocode'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='Payment_Status',
            field=models.CharField(choices=[('Paid', 'Paid'), ('Not Paid', 'Not Paid')], default='Not Paid', max_length=45),
        ),
    ]
