# Generated by Django 4.1 on 2022-09-09 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rentalapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="email",
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AddField(
            model_name="owner",
            name="email",
            field=models.CharField(default=0, max_length=50),
        ),
    ]
