# Generated by Django 4.1 on 2022-09-13 04:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("rentalapp", "0002_customer_email_owner_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bill",
            name="rental_id",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="rentalapp.rent_trip"
            ),
        ),
        migrations.AlterField(
            model_name="vehicle_status",
            name="vehicle_no",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="rentalapp.vehicle"
            ),
        ),
    ]
