# Generated by Django 4.1 on 2022-09-13 05:41

from django.db import migrations, models
import rentalapp.models


class Migration(migrations.Migration):

    dependencies = [
        ("rentalapp", "0003_alter_bill_rental_id_alter_vehicle_status_vehicle_no"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="email",
            field=models.CharField(
                max_length=50, validators=[rentalapp.models.mail_validator]
            ),
        ),
        migrations.AlterField(
            model_name="owner",
            name="email",
            field=models.CharField(
                max_length=50, validators=[rentalapp.models.mail_validator]
            ),
        ),
    ]
