# Generated by Django 4.1 on 2022-09-13 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rentalapp", "0004_alter_customer_email_alter_owner_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vehicle",
            name="image",
            field=models.CharField(max_length=255),
        ),
    ]
