# Generated by Django 2.2.12 on 2022-11-28 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student_Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('address', models.CharField(max_length=25)),
                ('d_o_b', models.DateField()),
                ('branch', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Marks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.FloatField()),
                ('semester', models.IntegerField()),
                ('stu_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Stu_Assign.Student_Info')),
                ('sub_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Stu_Assign.Subjects')),
            ],
        ),
    ]
