# Generated by Django 2.2.12 on 2022-12-05 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stu_Assign', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_info',
            name='image',
            field=models.ImageField(default=None, upload_to='images'),
        ),
    ]
