# Generated by Django 4.1.1 on 2022-09-19 07:23

import app.views
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customerId', models.IntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
                ('contactNumber', models.PositiveBigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employeeId', models.IntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('department', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=50)),
                ('contactNumber', models.CharField(max_length=15, validators=[app.views.validate_length])),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('paymentId', models.IntegerField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=50)),
                ('paymentDate', models.DateField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Prices',
            fields=[
                ('daysRange', models.IntegerField(primary_key=True, serialize=False)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('reservationId', models.IntegerField(primary_key=True, serialize=False)),
                ('reservationDate', models.DateField()),
                ('dateIn', models.DateField()),
                ('dateOut', models.DateField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.customer')),
                ('daysRangeStay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.prices')),
            ],
        ),
        migrations.CreateModel(
            name='RoomClass',
            fields=[
                ('classId', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('transactionId', models.IntegerField(primary_key=True, serialize=False)),
                ('transactionName', models.CharField(max_length=50)),
                ('transactionDate', models.DateField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.customer')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.employee')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.payment')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.reservation')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('roomId', models.IntegerField(primary_key=True, serialize=False)),
                ('price', models.IntegerField()),
                ('description', models.TextField()),
                ('classRoom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.roomclass')),
            ],
        ),
        migrations.AddField(
            model_name='reservation',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.room'),
        ),
        migrations.AddField(
            model_name='prices',
            name='classRoom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.roomclass'),
        ),
    ]
