# Generated by Django 4.1.1 on 2022-09-19 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('water', 'water'), ('electricity', 'electricity'), ('maintenance', 'maintenance'), ('others', 'others')], default='electricity', max_length=20)),
                ('date', models.DateField(auto_now=True)),
                ('description', models.CharField(max_length=50)),
                ('billNumber', models.IntegerField()),
                ('isPaid', models.BooleanField(default=False)),
                ('totalBill', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('mobileNo', models.PositiveBigIntegerField()),
                ('email', models.EmailField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Flat',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('type', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('blockId', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.block')),
            ],
        ),
        migrations.CreateModel(
            name='FlatOwmer',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('mobileNo', models.PositiveBigIntegerField()),
                ('email', models.EmailField(max_length=50)),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='FlatServicedByEmployees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employeeId', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.employees')),
                ('flatId', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.flat')),
            ],
        ),
        migrations.CreateModel(
            name='Reciept',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('date', models.DateField(auto_now_add=True)),
                ('paymentType', models.CharField(choices=[('UPI', 'UPI'), ('Cash', 'Cash'), ('Card', 'Card')], default='Cash', max_length=5)),
                ('billId', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.bill')),
            ],
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Visitors',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('reason', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('flatId', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.flat')),
            ],
        ),
        migrations.RemoveField(
            model_name='payment',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='prices',
            name='classRoom',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='daysRangeStay',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='room',
        ),
        migrations.RemoveField(
            model_name='room',
            name='classRoom',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='payment',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='reservation',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
        migrations.DeleteModel(
            name='Prices',
        ),
        migrations.DeleteModel(
            name='Reservation',
        ),
        migrations.DeleteModel(
            name='Room',
        ),
        migrations.DeleteModel(
            name='RoomClass',
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
        migrations.AddField(
            model_name='flat',
            name='ownerId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.flatowmer'),
        ),
        migrations.AddField(
            model_name='employees',
            name='roleId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.roles'),
        ),
        migrations.AddField(
            model_name='bill',
            name='ownerId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.flatowmer'),
        ),
    ]
