# Generated by Django 4.1.1 on 2022-09-19 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_bill_block_employees_flat_flatowmer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlatOwner',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('mobileNo', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=50)),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='employees',
            name='mobileNo',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='bill',
            name='ownerId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.flatowner'),
        ),
        migrations.AlterField(
            model_name='flat',
            name='ownerId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.flatowner'),
        ),
        migrations.DeleteModel(
            name='FlatOwmer',
        ),
    ]
