# Generated by Django 4.1 on 2022-09-05 12:44

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('model_training', '0002_deliverypartner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('cart_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryPartners',
            fields=[
                ('DeliveryPartner_id', models.CharField(default=0, max_length=10, primary_key=True, serialize=False)),
                ('DeliveryPartner_Name', models.CharField(default='', max_length=50)),
                ('DeliveryPartner_Phone', models.CharField(default='', max_length=11)),
                ('DeliveryPartner_Address', models.CharField(default='', max_length=255)),
                ('DeliveryPartner_status', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('order_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('Date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('Item_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('Item_Name', models.CharField(max_length=50)),
                ('Details', models.CharField(max_length=255)),
                ('Category', models.CharField(max_length=50)),
                ('Item_status', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('Order_status', models.CharField(max_length=50)),
                ('Cart_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='model_training.cart')),
                ('DeliveryPartner_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='model_training.deliverypartners')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('Payment_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('Billing_address', models.CharField(max_length=250)),
                ('Payment_method', models.CharField(choices=[('CASH', 'CASH'), ('CARD', 'CARD')], max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='DeliveryPartner',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='id',
        ),
        migrations.AddField(
            model_name='customer',
            name='Address',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='customer',
            name='Name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='customer',
            name='Phone',
            field=models.CharField(default='', max_length=11),
        ),
        migrations.AddField(
            model_name='customer',
            name='customer_id',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='payment',
            name='customer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='model_training.customer'),
        ),
        migrations.AddField(
            model_name='payment',
            name='order_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='model_training.order'),
        ),
        migrations.AddField(
            model_name='order',
            name='customer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='model_training.customer'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='Payment_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='model_training.payment'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='customer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='model_training.customer'),
        ),
        migrations.AddField(
            model_name='cart',
            name='item_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='model_training.menu'),
        ),
    ]
