spring.application.name=applicationspringboot
server.port=8086
spring.security.user.name= second
spring.security.user.password = 123
#to change password and username of default
#server.port=0 it starts server on random port u find it in console
#server.servlet.context-path=/helloworld
#debug=true
