# Generated by Django 4.1.2 on 2022-10-12 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='emp_pic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
