# Generated by Django 4.1.2 on 2022-10-12 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_alter_employee_emp_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
