# Generated by Django 4.1.1 on 2022-09-24 10:12

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('cust_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('contact', models.CharField(max_length=13)),
                ('email', models.CharField(max_length=50, unique=True, validators=[django.core.validators.EmailValidator()])),
                ('address', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name_plural': 'customer',
            },
        ),
        migrations.CreateModel(
            name='Distributor',
            fields=[
                ('dist_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('dist_name', models.CharField(max_length=50)),
                ('contact', models.CharField(max_length=13)),
                ('email', models.CharField(max_length=50, unique=True, validators=[django.core.validators.EmailValidator()])),
                ('address', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name_plural': 'distributor',
            },
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('doc_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('specialization', models.CharField(max_length=250)),
                ('contact', models.CharField(max_length=13)),
                ('email', models.CharField(max_length=50, unique=True, validators=[django.core.validators.EmailValidator()])),
                ('address', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name_plural': 'doctor',
            },
        ),
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('drug_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('drug_name', models.CharField(max_length=50)),
                ('mrp', models.DecimalField(decimal_places=5, max_digits=5)),
                ('discount', models.DecimalField(decimal_places=5, max_digits=5)),
                ('stock', models.IntegerField()),
                ('mfg_date', models.DateField()),
            ],
            options={
                'verbose_name_plural': 'drug',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('emp_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('doj', models.DateField()),
                ('designation', models.CharField(max_length=50)),
                ('job_type', models.CharField(max_length=50)),
                ('salary', models.IntegerField()),
                ('contact', models.CharField(max_length=13)),
                ('email', models.CharField(max_length=50, unique=True, validators=[django.core.validators.EmailValidator()])),
                ('address', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name_plural': 'employee',
            },
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('company_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=50)),
                ('contact', models.CharField(max_length=13)),
                ('email', models.CharField(max_length=50, unique=True, validators=[django.core.validators.EmailValidator()])),
                ('address', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name_plural': 'manufacturer',
            },
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('purchase_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('purchase_date', models.DateField()),
                ('drug_name', models.CharField(max_length=100)),
                ('drug_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pharmacy_Database.drug')),
            ],
            options={
                'verbose_name_plural': 'purchase',
            },
        ),
        migrations.CreateModel(
            name='Supply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_date', models.DateField()),
                ('drug_name', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=10, max_digits=10)),
                ('company_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Pharmacy_Database.manufacturer')),
                ('dist_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Pharmacy_Database.distributor')),
                ('drug_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pharmacy_Database.drug')),
                ('purchase_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pharmacy_Database.purchase')),
            ],
            options={
                'verbose_name_plural': 'supply',
            },
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('sale_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('sale_date', models.DateField()),
                ('quantity', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=10, max_digits=10)),
                ('cust_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pharmacy_Database.customer')),
                ('drug_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pharmacy_Database.drug')),
                ('emp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pharmacy_Database.employee')),
            ],
            options={
                'verbose_name_plural': 'sales',
            },
        ),
        migrations.CreateModel(
            name='Prescribe',
            fields=[
                ('prescription_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('cust_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pharmacy_Database.customer')),
                ('doc_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pharmacy_Database.doctor')),
                ('drug_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pharmacy_Database.drug')),
            ],
            options={
                'verbose_name_plural': 'prescribe',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('order_date', models.DateField()),
                ('payment_mode', models.CharField(max_length=10)),
                ('cust_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pharmacy_Database.customer')),
                ('drug_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pharmacy_Database.drug')),
                ('prescription_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pharmacy_Database.prescribe')),
            ],
            options={
                'verbose_name_plural': 'order',
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('bill_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('billing_date', models.DateField()),
                ('payment_mode', models.CharField(max_length=10)),
                ('quantity', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=10, max_digits=10)),
                ('cust_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pharmacy_Database.customer')),
                ('drug_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pharmacy_Database.drug')),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pharmacy_Database.order')),
            ],
            options={
                'verbose_name_plural': 'invoice',
            },
        ),
        migrations.AddField(
            model_name='drug',
            name='company_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Pharmacy_Database.manufacturer'),
        ),
        migrations.AddField(
            model_name='drug',
            name='dist_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Pharmacy_Database.distributor'),
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=10, max_digits=10)),
                ('cust_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pharmacy_Database.customer')),
                ('drug_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pharmacy_Database.drug')),
            ],
            options={
                'verbose_name_plural': 'cart',
            },
        ),
    ]
