# Generated by Django 4.1.1 on 2022-09-30 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pharmacy_Database', '0002_alter_employee_doj'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='doj',
            field=models.CharField(max_length=500),
        ),
    ]
