# Generated by Django 4.1.1 on 2022-09-30 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pharmacy_Database', '0003_alter_employee_doj'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drug',
            name='mfg_date',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='employee',
            name='doj',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='billing_date',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='purchase_date',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='sales',
            name='sale_date',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='supply',
            name='purchase_date',
            field=models.CharField(max_length=50),
        ),
    ]
