# Generated by Django 3.2.6 on 2022-10-10 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pharmacy_Database', '0004_alter_drug_mfg_date_alter_employee_doj_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='drug',
            name='exp_date',
            field=models.CharField(default='', max_length=50),
        ),
    ]
