# Generated by Django 3.2.6 on 2022-10-10 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pharmacy_Database', '0005_drug_exp_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drug',
            name='exp_date',
            field=models.CharField(max_length=50),
        ),
    ]
