# Generated by Django 3.2.6 on 2022-10-10 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pharmacy_Database', '0006_alter_drug_exp_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drug',
            name='exp_date',
        ),
    ]
