# Generated by Django 3.2.6 on 2022-10-10 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pharmacy_Database', '0007_remove_drug_exp_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drug',
            name='company_id',
        ),
        migrations.RemoveField(
            model_name='drug',
            name='dist_id',
        ),
        migrations.AddField(
            model_name='drug',
            name='company_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='drug',
            name='dist_name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
