# Generated by Django 3.2.6 on 2022-10-10 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pharmacy_Database', '0008_auto_20221010_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drug',
            name='company_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='drug',
            name='dist_name',
            field=models.CharField(max_length=50),
        ),
    ]
