# Generated by Django 3.2.6 on 2022-10-10 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pharmacy_Database', '0009_auto_20221010_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drug',
            name='mfg_date',
            field=models.CharField(max_length=100),
        ),
    ]
