# Generated by Django 3.2.6 on 2022-10-10 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pharmacy_Database', '0010_alter_drug_mfg_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drug',
            name='discount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='drug',
            name='mrp',
            field=models.IntegerField(),
        ),
    ]
