# Generated by Django 4.0.5 on 2022-09-06 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='password',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='students',
            name='password',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
