# Generated by Django 4.0.5 on 2022-09-07 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0004_rename_admin_admin_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='mail_id',
            field=models.EmailField(default='cms@gmail.com', max_length=254),
        ),
    ]
