# Generated by Django 4.1.1 on 2022-09-12 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_time', models.TimeField()),
                ('out_time', models.TimeField()),
                ('DATE', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept_name', models.CharField(max_length=25)),
                ('attendence_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='medplus.attendence')),
            ],
        ),
        migrations.CreateModel(
            name='insurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insurance_name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=25, unique=True)),
                ('email', models.EmailField(max_length=25)),
                ('password', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='personal_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=25)),
                ('dob', models.DateField()),
                ('contact_no', models.IntegerField()),
                ('dept_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medplus.department')),
                ('insurance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medplus.insurance')),
                ('login_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='medplus.login')),
            ],
        ),
        migrations.CreateModel(
            name='salary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Team_lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lead_name', models.CharField(max_length=25)),
                ('leave_request', models.IntegerField()),
                ('profile_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='medplus.personal_details')),
            ],
        ),
        migrations.CreateModel(
            name='role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(max_length=25)),
                ('salary_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='medplus.salary')),
            ],
        ),
        migrations.CreateModel(
            name='leave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_type', models.CharField(max_length=25)),
                ('attendence_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='medplus.attendence')),
            ],
        ),
        migrations.AddField(
            model_name='department',
            name='role_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medplus.role'),
        ),
    ]
