# Generated by Django 4.1.1 on 2022-09-13 04:24

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('medplus', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='login',
            managers=[
                ('shashi', django.db.models.manager.Manager()),
            ],
        ),
    ]
