# Generated by Django 4.1.1 on 2022-09-13 05:01

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('medplus', '0002_alter_login_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='department',
            managers=[
                ('req_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
