# Generated by Django 4.1.1 on 2022-09-13 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medplus', '0003_alter_department_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='department',
            managers=[
            ],
        ),
    ]
