# Generated by Django 4.1.1 on 2022-09-13 05:28

from django.db import migrations, models
import medplus.models


class Migration(migrations.Migration):

    dependencies = [
        ('medplus', '0004_alter_department_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salary',
            name='salary',
            field=models.IntegerField(validators=[medplus.models.validate_even]),
        ),
    ]
