# Generated by Django 4.1.1 on 2022-09-13 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medplus', '0005_alter_salary_salary'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='login',
            new_name='log',
        ),
    ]
