# Generated by Django 4.1.1 on 2022-09-13 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medplus', '0006_rename_login_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='user_name',
            field=models.CharField(max_length=25),
        ),
    ]
