# Generated by Django 4.1.1 on 2022-09-13 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medplus', '0007_alter_log_user_name'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='log',
            managers=[
            ],
        ),
    ]
