# Generated by Django 4.0.5 on 2022-09-06 07:36

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_problem'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopicTag',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tag_id', models.UUIDField(default=uuid.uuid4)),
                ('problem_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.problem')),
            ],
        ),
    ]
