# Generated by Django 4.0.5 on 2022-09-06 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_topictag'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('tag_id', models.AutoField(primary_key=True, serialize=False)),
                ('tag_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='topictag',
            name='tag_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='home.tag'),
        ),
    ]
