# Generated by Django 4.0.5 on 2022-09-06 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_tag_alter_topictag_tag_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topictag',
            name='tag_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.tag'),
        ),
    ]
