# Generated by Django 4.0.5 on 2022-09-12 06:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0018_alter_problem_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discussion',
            name='downvotes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='discussion',
            name='upvotes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='problem',
            name='dislikes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='ProblemVotes',
            fields=[
                ('votes_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('vote', models.CharField(choices=[('L', 'like'), ('D', 'dislike')], max_length=1)),
                ('problem_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.problem')),
                ('voter_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
