# Generated by Django 4.1.1 on 2022-09-25 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_account'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Account',
        ),
    ]
