# Generated by Django 4.1.1 on 2022-09-26 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_delete_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='difficulty_level',
            field=models.IntegerField(choices=[(0, 'easy'), (1, 'medium'), (2, 'hard')], default='E'),
        ),
    ]
