# Generated by Django 4.1 on 2022-09-28 10:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0027_alter_problem_difficulty_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discussion',
            name='user_id',
        ),
        migrations.AddField(
            model_name='discussion',
            name='username',
            field=models.ForeignKey(db_column='username', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, to_field='username'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='difficulty_level',
            field=models.IntegerField(choices=[(0, 'easy'), (1, 'medium'), (2, 'hard')], default=0),
        ),
    ]
