# Generated by Django 4.1 on 2022-09-28 15:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0031_alter_profile_facebook_alter_profile_github_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='inbuilt_code',
            field=models.TextField(default='', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='problem',
            name='outputs',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='discussion',
            name='problem_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='home.problem'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='discussion',
            name='username',
            field=models.ForeignKey(db_column='username', default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username'),
            preserve_default=False,
        ),
    ]
