# Generated by Django 4.0.5 on 2022-09-29 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0033_alter_comment_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='outputs',
            field=models.TextField(max_length=500),
        ),
    ]
