# Generated by Django 4.0.5 on 2022-09-29 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0034_alter_problem_outputs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='inbuilt_code',
        ),
        migrations.AddField(
            model_name='problem',
            name='json_test_cases',
            field=models.JSONField(default=''),
            preserve_default=False,
        ),
    ]
