# Generated by Django 4.0.5 on 2022-10-06 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0036_solved_result_alter_solved_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='accuracy',
            field=models.FloatField(default=0),
        ),
    ]
