# Generated by Django 4.0.5 on 2022-10-06 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0037_problem_accuracy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='description',
            field=models.TextField(max_length=1000, unique=True),
        ),
    ]
