# Generated by Django 4.0.5 on 2022-10-06 12:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0039_profile_streak'),
    ]

    operations = [
        migrations.AddField(
            model_name='solved',
            name='solved_date_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
