# Generated by Django 4.1 on 2022-10-11 09:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0040_solved_solved_date_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('blog_id', models.AutoField(primary_key=True, serialize=False)),
                ('created_date_time', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=50)),
                ('discussion', models.TextField(max_length=2000)),
                ('tag', models.IntegerField(choices=[(1, 'web development'), (2, 'game development'), (3, 'devops'), (4, 'Artificial intelligence'), (5, 'block chain'), (6, 'mobile development'), (7, 'data structures')])),
                ('likes', models.IntegerField(default=0)),
                ('user_id', models.ForeignKey(db_column='username', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
        ),
    ]
