# Generated by Django 4.1 on 2022-10-11 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0041_blog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='tag',
            field=models.CharField(choices=[('web development', 'web development'), ('game development', 'game development'), ('devops', 'devops'), ('Artificial intelligence', 'Artificial intelligence'), ('block chain', 'block chain'), ('mobile development', 'mobile development'), ('data structures', 'data structures')], max_length=30),
        ),
    ]
