# Generated by Django 4.0.5 on 2022-10-14 10:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0043_blogcomment_blogcommentreply_blogcommentlike'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='created_date_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
