# Generated by Django 4.0.5 on 2022-10-27 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0045_problemtag_problem_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='description',
            field=models.TextField(max_length=3000, unique=True),
        ),
        migrations.AlterField(
            model_name='problem',
            name='outputs',
            field=models.TextField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='problem',
            name='tags',
            field=models.ManyToManyField(related_name='problems', to='home.problemtag'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='test_cases',
            field=models.TextField(max_length=1000),
        ),
    ]
