# Generated by Django 4.0.5 on 2022-10-31 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0046_alter_problem_description_alter_problem_outputs_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='problem',
            index=models.Index(fields=['problem_id'], name='home_proble_problem_710e4d_idx'),
        ),
    ]
