# Generated by Django 4.0.5 on 2022-10-31 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0047_problem_home_proble_problem_710e4d_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='json_test_cases',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
