# Generated by Django 4.0.5 on 2022-10-31 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0048_alter_problem_json_test_cases'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, related_name='problems', to='home.problemtag'),
        ),
    ]
