# Generated by Django 4.1 on 2022-09-12 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_alter_cart_options_alter_snacks_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selected_seats',
            name='Seating_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.seating'),
        ),
    ]
