# Generated by Django 4.1 on 2022-09-28 08:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_alter_booking_date_alter_hall_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hall',
            name='cols',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='hall',
            name='rows',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='booking',
            name='Date',
            field=models.DateField(default=datetime.date(2022, 9, 28)),
        ),
        migrations.AlterField(
            model_name='hall',
            name='Date',
            field=models.DateField(default=datetime.date(2022, 9, 28)),
        ),
        migrations.AlterField(
            model_name='movie',
            name='Movie_Release_date',
            field=models.DateField(default=datetime.date(2022, 9, 28)),
        ),
        migrations.AlterField(
            model_name='user',
            name='User_DOB',
            field=models.DateField(default=datetime.date(2022, 9, 28)),
        ),
    ]
