# Generated by Django 4.1 on 2022-10-06 06:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0032_payment_payment_status_payment_payment_mode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='Date',
            field=models.DateField(default=datetime.date(2022, 10, 6)),
        ),
        migrations.AlterField(
            model_name='hall',
            name='Date',
            field=models.DateField(default=datetime.date(2022, 10, 6)),
        ),
        migrations.AlterField(
            model_name='movie',
            name='Movie_Release_date',
            field=models.DateField(default=datetime.date(2022, 10, 6)),
        ),
        migrations.AlterField(
            model_name='users',
            name='User_DOB',
            field=models.DateField(default=datetime.date(2022, 10, 6)),
        ),
        migrations.AlterField(
            model_name='users',
            name='User_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
