# Generated by Django 4.1 on 2022-10-06 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0034_users_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='Payment_id',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='payment',
            name='Payment_mode',
            field=models.CharField(default='Card', max_length=45),
        ),
    ]
