# Generated by Django 4.1 on 2022-10-20 09:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0043_remove_payment_payment_id_alter_booking_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='Booking_status',
            field=models.CharField(choices=[('Booked', 'Booked'), ('Cancelled', 'Cancelled')], default='Booked', max_length=25),
        ),
        migrations.AlterField(
            model_name='booking',
            name='Date',
            field=models.DateField(default=datetime.date(2022, 10, 20)),
        ),
        migrations.AlterField(
            model_name='datewisehall',
            name='Date',
            field=models.DateField(default=datetime.date(2022, 10, 20)),
        ),
        migrations.AlterField(
            model_name='hall',
            name='Date',
            field=models.DateField(default=datetime.date(2022, 10, 20)),
        ),
        migrations.AlterField(
            model_name='movie',
            name='Movie_Release_date',
            field=models.DateField(default=datetime.date(2022, 10, 20)),
        ),
        migrations.AlterField(
            model_name='payment',
            name='Payment_mode',
            field=models.CharField(default='Online', max_length=45),
        ),
        migrations.AlterField(
            model_name='users',
            name='User_DOB',
            field=models.DateField(default=datetime.date(2022, 10, 20)),
        ),
    ]
