# Generated by Django 4.1 on 2022-10-25 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0045_booking_payment_status_booking_payment_mode_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hall',
            name='T_No_Of_Seats',
        ),
    ]
