# Generated by Django 4.1 on 2022-10-25 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0047_datewisehall_movie_id_datewisehall_endtime_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hall',
            name='Movie_id',
        ),
        migrations.RemoveField(
            model_name='hall',
            name='endTime',
        ),
        migrations.RemoveField(
            model_name='hall',
            name='startTime',
        ),
        migrations.AlterUniqueTogether(
            name='datewisehall',
            unique_together={('Date', 'Hall_id', 'startTime', 'endTime')},
        ),
    ]
