export const SplitBy = {
    "htmlElementType": "FORM",
    "id": "splitByInfo",
    "label": "",
    "name": null,
    "value": null,
    "className": null,
    "readOnly": false,
    "disabled": false,
    "autofocus": false,
    "required": false,
    "style": null,
    "attributes": null,
    "message": null,
    "htmlActions": null,
    "elementSize": null,
    "defaultValue": null,
    "helperText": null,
    "labelClassName": null,
    "htmlGroups": [
        {
            "htmlElementType": "ELEMENTGROUP",
            "id": "splitByGrp",
            "label": "Split By",
            "name": null,
            "value": null,
            "className": null,
            "readOnly": false,
            "disabled": false,
            "autofocus": false,
            "required": false,
            "style": null,
            "attributes": null,
            "message": null,
            "htmlActions": null,
            "elementSize": null,
            "defaultValue": null,
            "helperText": null,
            "groups": null,
            "groupElements": [
                {
                    "htmlElementType": "RADIO",
                    "id": "sliptBy",
                    "label": "",
                    "name": null,
                    "value": null,
                    "className": null,
                    "readOnly": false,
                    "disabled": false,
                    "autofocus": true,
                    "required": true,
                    "style": null,
                    "attributes": null,
                    "message": null,
                    "htmlActions": null,
                    "elementSize": null,
                    "defaultValue": null,
                    "helperText": null,
                    "labelClassName": null,
                    "values": [
                        {
                            "htmlElementType": "OPTION",
                            "id": "store",
                            "label": "Store",
                            "name": null,
                            "value": "store",
                            "className": null,
                            "readOnly": false,
                            "disabled": false,
                            "autofocus": false,
                            "required": false,
                            "style": null,
                            "attributes": null,
                            "message": null,
                            "htmlActions": null,
                            "elementSize": null,
                            "defaultValue": null,
                            "helperText": null,
                            "labelClassName": null,
                            "displayValue": "store",
                            "selected": true,
                            "hidden": false
                        },
                        {
                            "htmlElementType": "OPTION",
                            "id": "product",
                            "label": "Product",
                            "name": null,
                            "value": "product",
                            "className": null,
                            "readOnly": false,
                            "disabled": false,
                            "autofocus": false,
                            "required": false,
                            "style": null,
                            "attributes": null,
                            "message": null,
                            "htmlActions": null,
                            "elementSize": null,
                            "defaultValue": null,
                            "helperText": null,
                            "labelClassName": null,
                            "displayValue": "product",
                            "selected": false,
                            "hidden": false
                        }
                    ],
                    "hidden": false
                }
            ],
            "cloneable": false,
            "groupFirst": false,
            "hidden": false
        }
    ]
};
