# Generated by Django 4.1.6 on 2023-02-13 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0006_remove_orderdetail_user_remove_orderitem_movie_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Show',
            fields=[
                ('show_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('dateOfShow', models.DateField()),
                ('startTime', models.TimeField()),
                ('endTime', models.TimeField()),
                ('movie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.movie')),
            ],
        ),
    ]
