# Generated by Django 4.1.1 on 2022-09-28 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FacilityDetail',
            fields=[
                ('facility_id', models.AutoField(primary_key=True, serialize=False)),
                ('facility_name', models.CharField(max_length=255)),
                ('facility_location', models.CharField(max_length=255)),
                ('facility_phone', models.CharField(max_length=255, unique=True)),
                ('facility_email', models.CharField(max_length=255)),
                ('facility_password', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('slot_id', models.AutoField(primary_key=True, serialize=False)),
                ('slot_time', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('sport_id', models.AutoField(primary_key=True, serialize=False)),
                ('sport_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SportsInFacility',
            fields=[
                ('facility_sport_id', models.AutoField(primary_key=True, serialize=False)),
                ('cost_per_slot', models.IntegerField()),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facilities.facilitydetail')),
                ('sport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facilities.sport')),
            ],
            options={
                'unique_together': {('facility', 'sport')},
            },
        ),
        migrations.AddField(
            model_name='sport',
            name='facility',
            field=models.ManyToManyField(through='facilities.SportsInFacility', to='facilities.facilitydetail'),
        ),
        migrations.CreateModel(
            name='SlotsInSportFacility',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('facility_sport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facilities.sportsinfacility')),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facilities.slot')),
            ],
        ),
        migrations.AddField(
            model_name='slot',
            name='sport_facility',
            field=models.ManyToManyField(through='facilities.SlotsInSportFacility', to='facilities.sportsinfacility'),
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('equip_id', models.AutoField(primary_key=True, serialize=False)),
                ('equip_name', models.CharField(max_length=255)),
                ('rent_per_slot', models.IntegerField()),
                ('sport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facilities.sport')),
            ],
        ),
    ]
