# Generated by Django 4.1.1 on 2022-09-30 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingData',
            fields=[
                ('booking_id', models.AutoField(primary_key=True, serialize=False)),
                ('date_time', models.CharField(max_length=255)),
                ('reviews', models.TextField(blank=True, null=True)),
                ('ratings', models.IntegerField(blank=True, null=True)),
                ('facility_sport_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='facilities.sportsinfacility')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=255)),
                ('user_phone', models.CharField(max_length=255, unique=True)),
                ('user_email', models.CharField(max_length=255)),
                ('user_password', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SlotsBookedForBookingId',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='facilities.bookingdata')),
                ('slot_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='facilities.slot')),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('invoice_id', models.AutoField(primary_key=True, serialize=False)),
                ('total_cost', models.IntegerField()),
                ('invoice_pdf', models.TextField()),
                ('booking_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='facilities.bookingdata')),
            ],
        ),
        migrations.CreateModel(
            name='EquipmentsRentedForBookingId',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='facilities.bookingdata')),
                ('equip', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='facilities.equipment')),
            ],
        ),
        migrations.AddField(
            model_name='bookingdata',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='facilities.user'),
        ),
    ]
