# Generated by Django 4.1.1 on 2022-10-03 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0002_bookingdata_user_slotsbookedforbookingid_invoice_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookingdata',
            old_name='user',
            new_name='user_id',
        ),
    ]
