# Generated by Django 4.1.1 on 2022-10-03 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0003_rename_user_bookingdata_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookingdata',
            old_name='date_time',
            new_name='date',
        ),
    ]
