# Generated by Django 4.1.1 on 2022-10-03 07:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0004_rename_date_time_bookingdata_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingdata',
            name='ratings',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
