# Generated by Django 4.1.1 on 2022-10-03 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0005_alter_bookingdata_ratings'),
    ]

    operations = [
        migrations.RenameField(
            model_name='slotsinsportfacility',
            old_name='slot',
            new_name='slot_id',
        ),
    ]
