# Generated by Django 4.1.1 on 2022-10-03 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0006_rename_slot_slotsinsportfacility_slot_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='slotsinsportfacility',
            old_name='facility_sport',
            new_name='facility_sport_id',
        ),
    ]
