# Generated by Django 4.1.1 on 2022-10-06 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0009_alter_equipment_equip_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='invoice_pdf',
            field=models.TextField(blank=True, null=True),
        ),
    ]
