# Generated by Django 4.1.1 on 2022-10-11 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0012_bookingdata_equipments_booked_bookingdata_slots'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipmentsrentedforbookingid',
            name='booking_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facilities.bookingdata'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='booking_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facilities.bookingdata'),
        ),
        migrations.AlterField(
            model_name='slotsbookedforbookingid',
            name='booking_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facilities.bookingdata'),
        ),
    ]
