# Generated by Django 4.1.1 on 2022-10-13 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0013_alter_equipmentsrentedforbookingid_booking_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingdata',
            name='facility_sport_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='facilities.sportsinfacility'),
        ),
    ]
