# Generated by Django 4.1.1 on 2022-10-14 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0014_alter_bookingdata_facility_sport_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slot',
            name='sport_facility',
        ),
        migrations.AddField(
            model_name='sportsinfacility',
            name='slot',
            field=models.ManyToManyField(through='facilities.SlotsInSportFacility', to='facilities.slot'),
        ),
    ]
