# Generated by Django 4.1.6 on 2023-02-09 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_movie_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='brand',
            new_name='productionHouse',
        ),
    ]
