# Generated by Django 4.1.6 on 2023-02-09 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_rename_brand_movie_productionhouse'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='countInStock',
            new_name='number_of_screens',
        ),
    ]
