# Generated by Django 4.1.6 on 2023-02-13 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_rename_countinstock_movie_number_of_screens'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetail',
            name='user',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='movie',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='order_detail',
        ),
        migrations.RemoveField(
            model_name='review',
            name='movie',
        ),
        migrations.RemoveField(
            model_name='review',
            name='user',
        ),
        migrations.DeleteModel(
            name='CinemaHallAddress',
        ),
        migrations.DeleteModel(
            name='OrderDetail',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
