# Generated by Django 4.1 on 2022-09-09 12:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_user_user_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='User_DOB',
            field=models.DateField(default=datetime.date(2022, 9, 9)),
        ),
    ]
