spring.application.name=Users
#spring.security.user.name = karthik
#spring.security.user.password = 12345

spring.datasource.url=jdbc:mysql://localhost:3306/orga
spring.datasource.username=devuser
spring.datasource.password=211Fa@4223
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
twilio.account.sid=AC15b24fb4619ffe1923821674db318b36
twilio.auth.token=8bccaf6a3133488663d0d39475b887c5
twilio.phone.number=+17754427265