spring.application.name=IMS
spring.datasource.url=jdbc:mysql://localhost:3306/ims
spring.datasource.username=root
spring.datasource.password=Medplus@321
spring.security.user.name=saketh
spring.security.user.password=saketh
