# Generated by Django 4.1.1 on 2022-09-28 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fpapp', '0002_alter_user_first_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='teacher_id',
        ),
        migrations.AddField(
            model_name='subject',
            name='teacher_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fpapp.teacher'),
        ),
    ]
