# Generated by Django 3.0.5 on 2022-10-03 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fpapp', '0002_evaluation_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='question_number',
        ),
        migrations.RemoveField(
            model_name='question',
            name='marks',
        ),
    ]
