# Generated by Django 3.0.5 on 2022-10-03 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fpapp', '0003_auto_20221003_1258'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_number',
            field=models.PositiveIntegerField(default=0, unique=True),
        ),
    ]
