# Generated by Django 3.0.5 on 2022-10-04 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fpapp', '0004_question_question_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='teacher_id',
        ),
    ]
