# Generated by Django 3.0.5 on 2022-10-04 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fpapp', '0005_remove_course_teacher_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(default=0, max_length=50),
        ),
    ]
