# Generated by Django 3.0.5 on 2022-10-04 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fpapp', '0006_user_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('Student', 'Student'), ('Teacher', 'Teacher')], default=0, max_length=50),
        ),
    ]
