# Generated by Django 3.0.5 on 2022-10-04 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fpapp', '0007_auto_20221004_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('Student', 'Student'), ('Teacher', 'Teacher'), ('Admin', 'Admin')], default='Admin', max_length=50),
        ),
    ]
