# Generated by Django 3.0.5 on 2022-10-04 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fpapp', '0008_auto_20221004_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(default='Admin', max_length=50),
        ),
    ]
