# Generated by Django 3.0.5 on 2022-10-04 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fpapp', '0009_auto_20221004_1311'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='question_number',
        ),
    ]
