# Generated by Django 3.0.5 on 2022-10-08 07:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fpapp', '0010_remove_question_question_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='teacher_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fpapp.Teacher'),
        ),
    ]
