# Generated by Django 3.0.5 on 2022-10-10 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fpapp', '0011_course_teacher_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='marks',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
