# Generated by Django 3.0.5 on 2022-10-10 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fpapp', '0012_question_marks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='marks',
        ),
    ]
