# Generated by Django 3.0.5 on 2022-10-11 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fpapp', '0013_remove_question_marks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answer',
            field=models.CharField(choices=[('option1', 'option1'), ('option2', 'option2'), ('option3', 'option3'), ('option4', 'option4')], max_length=200),
        ),
    ]
