# Generated by Django 3.0.5 on 2022-10-17 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fpapp', '0014_auto_20221011_2339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='college_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='reqister_number',
            field=models.CharField(default=400, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='position',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='qualification',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='user',
            name='mobile_no',
            field=models.CharField(default='', max_length=10),
        ),
    ]
