# Generated by Django 4.0.6 on 2022-08-23 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_users'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='User',
        ),
    ]
