# Generated by Django 4.0.6 on 2022-09-12 10:15

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('tagline', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Timeline',
            fields=[
                ('full_date', models.DateField(db_column='full_date', max_length=10)),
                ('timeline_uid', models.BigIntegerField(db_column='timeline_uid', primary_key=True, serialize=False, unique=True)),
                ('year', models.IntegerField(db_column='year')),
                ('month', models.IntegerField(db_column='month')),
                ('month_name', models.CharField(db_column='month_name', max_length=10)),
                ('date', models.IntegerField(db_column='date')),
                ('day_name', models.CharField(db_column='day_name', max_length=10)),
                ('days_in_month', models.IntegerField(db_column='days_in_month')),
                ('day_of_year', models.IntegerField(db_column='day_of_year')),
                ('week_of_year', models.IntegerField(db_column='week_of_year')),
                ('quarter_of_year', models.IntegerField(db_column='quarter_of_year')),
                ('month_of_year', models.IntegerField(db_column='month_of_year')),
                ('quarter_id', models.CharField(db_column='quarter_id', max_length=10)),
                ('month_quarter_id', models.CharField(db_column='month_quarter_id', max_length=10)),
            ],
            options={
                'db_table': 'timeline',
                'managed': True,
                'index_together': {('year', 'month', 'date')},
            },
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=255)),
                ('body_text', models.TextField()),
                ('pub_date', models.DateField()),
                ('mod_date', models.DateField(default=django.utils.timezone.now)),
                ('number_of_comments', models.IntegerField(default=0)),
                ('number_of_ping_backs', models.IntegerField(default=0)),
                ('rating', models.IntegerField(default=5)),
                ('authors', models.ManyToManyField(to='masters.author')),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masters.blog')),
            ],
        ),
    ]
