# Generated by Django 4.0.6 on 2022-09-12 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeline',
            name='month_quarter_id',
            field=models.CharField(db_column='month_quarter_id', max_length=200),
        ),
    ]
