# Generated by Django 4.0.6 on 2022-09-12 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0002_alter_timeline_month_quarter_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Timeline',
        ),
    ]
