# Generated by Django 4.0.6 on 2022-09-12 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0003_delete_timeline'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entry',
            options={'managed': True},
        ),
        migrations.AlterModelTable(
            name='entry',
            table='timeline_entry',
        ),
    ]
