# Generated by Django 4.1 on 2022-10-06 06:42

from django.db import migrations, models
import django.db.models.deletion
import rentalapp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                ("customer_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=50)),
                ("dl_no", models.CharField(max_length=50, unique=True)),
                ("contact_no", models.CharField(max_length=50, unique=True)),
                (
                    "email",
                    models.CharField(
                        max_length=50,
                        unique=True,
                        validators=[rentalapp.models.mail_validator],
                    ),
                ),
                ("address", models.CharField(max_length=200)),
                ("password", models.CharField(default=0, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="CustomerToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("customer_token_id", models.IntegerField()),
                ("token", models.CharField(max_length=255)),
                ("expired_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Owner",
            fields=[
                ("owner_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=50)),
                ("contact_no", models.CharField(max_length=50, unique=True)),
                (
                    "email",
                    models.CharField(
                        max_length=50,
                        unique=True,
                        validators=[rentalapp.models.mail_validator],
                    ),
                ),
                ("address", models.CharField(max_length=200)),
                ("password", models.CharField(default=0, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="OwnerToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("owner_token_id", models.IntegerField()),
                ("token", models.CharField(max_length=255)),
                ("expired_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Vehicle",
            fields=[
                (
                    "vehicle_no",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                ("type", models.CharField(max_length=50)),
                ("brand", models.CharField(max_length=50)),
                ("model", models.CharField(max_length=50)),
                ("image", models.TextField()),
                ("price_day", models.FloatField()),
                (
                    "owner_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="rentalapp.owner",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Vehicle_status",
            fields=[
                ("sl_no", models.AutoField(primary_key=True, serialize=False)),
                ("is_available", models.BooleanField()),
                (
                    "vehicle_no",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="rentalapp.vehicle",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Rent_Trip",
            fields=[
                ("rent_id", models.AutoField(primary_key=True, serialize=False)),
                ("booking_date", models.DateTimeField(auto_now=True)),
                ("pickup_date", models.DateField()),
                ("return_date", models.DateField(null=True)),
                ("odo_start_reading", models.IntegerField(null=True)),
                ("odo_end_reading", models.IntegerField(null=True)),
                ("customer_review", models.CharField(max_length=500, null=True)),
                ("owner_review", models.CharField(max_length=500, null=True)),
                (
                    "customer_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="rentalapp.customer",
                    ),
                ),
                (
                    "owner_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="rentalapp.owner",
                    ),
                ),
                (
                    "vehicle_no",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="rentalapp.vehicle",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Bill",
            fields=[
                ("bill_no", models.AutoField(primary_key=True, serialize=False)),
                ("rental_days", models.IntegerField()),
                ("km_ran", models.IntegerField()),
                ("amount", models.IntegerField()),
                (
                    "rental_id",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="rentalapp.rent_trip",
                    ),
                ),
            ],
        ),
    ]
