# Generated by Django 4.1 on 2022-09-30 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rentalapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rent_trip",
            name="customer_review",
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="rent_trip",
            name="odo_end_reading",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="rent_trip",
            name="odo_start_reading",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="rent_trip",
            name="owner_review",
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="rent_trip",
            name="return_date_time",
            field=models.DateTimeField(null=True),
        ),
    ]
