# Generated by Django 4.1 on 2022-10-11 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rentalapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bill",
            name="km_ran",
            field=models.IntegerField(null=True),
        ),
    ]
