# Generated by Django 4.1 on 2022-09-30 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rentalapp", "0002_alter_rent_trip_customer_review_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="rent_trip",
            old_name="owner_d",
            new_name="owner_id",
        ),
    ]
