# Generated by Django 4.1 on 2022-10-17 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rentalapp", "0002_alter_bill_km_ran"),
    ]

    operations = [
        migrations.AddField(
            model_name="rent_trip",
            name="order_status",
            field=models.BooleanField(default=True),
        ),
    ]
