# Generated by Django 4.1 on 2022-10-18 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rentalapp", "0003_rent_trip_order_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="vehicle",
            name="is_available",
            field=models.BooleanField(default=True),
        ),
        migrations.DeleteModel(
            name="Vehicle_status",
        ),
    ]
