# Generated by Django 4.1 on 2022-10-27 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rentalapp", "0004_vehicle_is_available_delete_vehicle_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="vehicle",
            name="bill_generated",
            field=models.BooleanField(default=False),
        ),
    ]
