# Generated by Django 4.1 on 2022-09-26 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rentalapp", "0005_alter_vehicle_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bill",
            name="bill_no",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="customer",
            name="customer_id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="owner",
            name="owner_id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="rent_trip",
            name="rent_id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="image",
            field=models.ImageField(upload_to="static/images"),
        ),
        migrations.AlterField(
            model_name="vehicle_status",
            name="sl_no",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
