# Generated by Django 4.1 on 2022-10-27 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rentalapp", "0005_vehicle_bill_generated"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="vehicle",
            name="bill_generated",
        ),
        migrations.AddField(
            model_name="rent_trip",
            name="bill_generated",
            field=models.BooleanField(default=False),
        ),
    ]
