# Generated by Django 4.1 on 2022-09-27 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rentalapp", "0006_alter_bill_bill_no_alter_customer_customer_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="password",
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AddField(
            model_name="owner",
            name="password",
            field=models.CharField(default=0, max_length=50),
        ),
    ]
