# Generated by Django 4.1 on 2022-10-28 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rentalapp", "0006_remove_vehicle_bill_generated_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Rent_Trip",
            new_name="RentTrip",
        ),
    ]
