# Generated by Django 4.1 on 2022-09-27 08:57

from django.db import migrations, models
import rentalapp.models


class Migration(migrations.Migration):

    dependencies = [
        ("rentalapp", "0007_customer_password_owner_password"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="contact_no",
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name="customer",
            name="email",
            field=models.CharField(
                max_length=50, unique=True, validators=[rentalapp.models.mail_validator]
            ),
        ),
        migrations.AlterField(
            model_name="owner",
            name="contact_no",
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name="owner",
            name="email",
            field=models.CharField(
                max_length=50, unique=True, validators=[rentalapp.models.mail_validator]
            ),
        ),
    ]
