# Generated by Django 4.1 on 2022-09-27 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rentalapp", "0008_alter_customer_contact_no_alter_customer_email_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="dl_no",
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
