# Generated by Django 4.1 on 2022-08-23 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersadmin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='sub_code',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
