# Generated by Django 4.1 on 2022-08-24 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersadmin', '0002_alter_subject_sub_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculties',
            name='gender',
            field=models.CharField(choices=[('male', 'male'), ('female', 'female')], default='male', max_length=50),
        ),
        migrations.AlterField(
            model_name='courses',
            name='course_code',
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
