# Generated by Django 4.1 on 2022-08-26 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersadmin', '0003_faculties_gender_alter_courses_course_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='std_id',
            field=models.CharField(default='m001', max_length=40, unique=True),
        ),
    ]
