# Generated by Django 4.1 on 2022-08-26 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usersadmin', '0004_students_std_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='students',
            old_name='std_id',
            new_name='admission_id',
        ),
    ]
