# Generated by Django 4.1 on 2022-08-26 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersadmin', '0005_rename_std_id_students_admission_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='course_id',
            field=models.IntegerField(default=1, max_length=3, unique=True),
            preserve_default=False,
        ),
    ]
