# Generated by Django 4.1 on 2022-08-29 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usersadmin', '0006_courses_course_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courses',
            name='course_id',
        ),
    ]
