# Generated by Django 4.1 on 2022-08-29 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersadmin', '0007_remove_courses_course_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='adminusers2',
        ),
        migrations.AddField(
            model_name='adminusers',
            name='role',
            field=models.CharField(choices=[('admin', 'admin'), ('student', 'student'), ('teacher', 'teacher')], default='admin', max_length=10),
        ),
    ]
