# Generated by Django 4.1 on 2022-08-30 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersadmin', '0009_alter_adminusers_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminusers',
            name='role',
            field=models.CharField(default='admin', max_length=10),
        ),
    ]
