# Generated by Django 4.0.5 on 2022-08-29 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_templates', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variables',
            name='phone_number',
            field=models.IntegerField(),
        ),
    ]
