export const COMPANY_LOGIN_REQUEST = 'COMPANY_LOGIN_REQUEST'
export const COMPANY_LOGIN_SUCCESS = 'COMPANY_LOGIN_SUCCESS'
export const COMPANY_LOGIN_FAIL = 'COMPANY_LOGIN_FAIL'

export const COMPANY_LOGOUT = 'COMPANY_LOGOUT'

export const COMPANY_REGISTER_REQUEST = 'COMPANY_REGISTER_REQUEST'
export const COMPANY_REGISTER_SUCCESS = 'COMPANY_REGISTER_SUCCESS'
export const COMPANY_REGISTER_FAIL = 'COMPANY_REGISTER_FAIL'

export const COMPANY_DETAILS_REQUEST = 'COMPANY_DETAILS_REQUEST'
export const COMPANY_DETAILS_SUCCESS = 'COMPANY_DETAILS_SUCCESS'
export const COMPANY_DETAILS_FAIL = 'COMPANY_DETAILS_FAIL'
export const COMPANY_DETAILS_RESET = 'COMPANY_DETAILS_RESET'


export const COMPANY_UPDATE_PROFILE_REQUEST = 'COMPANY_UPDATE_PROFILE_REQUEST'
export const COMPANY_UPDATE_PROFILE_SUCCESS = 'COMPANY_UPDATE_PROFILE_SUCCESS'
export const COMPANY_UPDATE_PROFILE_FAIL = 'COMPANY_UPDATE_PROFILE_FAIL'
export const COMPANY_UPDATE_PROFILE_RESET = 'COMPANY_UPDATE_PROFILE_RESET'


export const APPLIED_CANDIDATE_DETAIL_PROFILE_REQUEST = 'APPLIED_CANDIDATE_DETAIL_PROFILE_REQUEST'
export const APPLIED_CANDIDATE_DETAIL_PROFILE_SUCCESS = 'APPLIED_CANDIDATE_DETAIL_PROFILE_SUCCESS'
export const APPLIED_CANDIDATE_DETAIL_PROFILE_FAIL = 'APPLIED_CANDIDATE_DETAIL_PROFILE_FAIL'


export const GET_COMPANY_DETAIL_PROFILE_REQUEST = 'GET_COMPANY_DETAIL_PROFILE_REQUEST'
export const GET_COMPANY_DETAIL_PROFILE_SUCCESS = 'GET_COMPANY_DETAIL_PROFILE_SUCCESS'
export const GET_COMPANY_DETAIL_PROFILE_FAIL = 'GET_COMPANY_DETAIL_PROFILE_FAIL'
export const GET_COMPANY_DETAIL_PROFILE_RESET = 'GET_COMPANY_DETAIL_PROFILE_RESET'


export const UPDATE_COMPANY_DETAIL_PROFILE_REQUEST = 'UPDATE_COMPANY_DETAIL_PROFILE_REQUEST'
export const UPDATE_COMPANY_DETAIL_PROFILE_SUCCESS = 'UPDATE_COMPANY_DETAIL_PROFILE_SUCCESS'
export const UPDATE_COMPANY_DETAIL_PROFILE_FAIL = 'UPDATE_COMPANY_DETAIL_PROFILE_FAIL'
export const UPDATE_COMPANY_DETAIL_PROFILE_RESET = 'UPDATE_COMPANY_DETAIL_PROFILE_RESET'


export const GET_COMPANIES_LIST_REQUEST = 'GET_COMPANIES_LIST_REQUEST'
export const GET_COMPANIES_LIST_SUCCESS = 'GET_COMPANIES_LIST_SUCCESS'
export const GET_COMPANIES_LIST_FAIL = 'GET_COMPANIES_LIST_FAIL'


export const GET_COMPANIES_LIST_BY_FILTER_REQUEST = 'GET_COMPANIES_LIST_BY_FILTER_REQUEST'
export const GET_COMPANIES_LIST_BY_FILTER_SUCCESS = 'GET_COMPANIES_LIST_BY_FILTER_SUCCESS'
export const GET_COMPANIES_LIST_BY_FILTER_FAIL = 'GET_COMPANIES_LIST_BY_FILTER_FAIL'


export const GET_COMPANIES_LIST_BY_FILTER_BY_LOCATION_REQUEST = 'GET_COMPANIES_LIST_BY_FILTER_BY_LOCATION_REQUEST'
export const GET_COMPANIES_LIST_BY_FILTER_BY_LOCATION_SUCCESS = 'GET_COMPANIES_LIST_BY_FILTER_BY_LOCATION_SUCCESS'
export const GET_COMPANIES_LIST_BY_FILTER_BY_LOCATION_FAIL = 'GET_COMPANIES_LIST_BY_FILTER_BY_LOCATION_FAIL'