export const COMPANY_JOB_POST_LIST_REQUEST = 'COMPANY_JOB_POST_LIST_REQUEST'
export const COMPANY_JOB_POST_LIST_SUCCESS = 'COMPANY_JOB_POST_LIST_SUCCESS'
export const COMPANY_JOB_POST_LIST_FAIL = 'COMPANY_JOB_POST_LIST_FAIL'

export const COMPANY_JOB_POST_DETAILS_REQUEST = 'COMPANY_JOB_POST_DETAILS_REQUEST'
export const COMPANY_JOB_POST_DETAILS_SUCCESS = 'COMPANY_JOB_POST_DETAILS_SUCCESS'
export const COMPANY_JOB_POST_DETAILS_FAIL = 'COMPANY_JOB_POST_DETAILS_FAIL'

export const APPLIED_CANDIDATE_DETAILS_REQUEST = 'APPLIED_CANDIDATE_DETAILS_REQUEST'
export const APPLIED_CANDIDATE_DETAILS_SUCCESS = 'APPLIED_CANDIDATE_DETAILS_SUCCESS'
export const APPLIED_CANDIDATE_DETAILS_FAIL = 'APPLIED_CANDIDATE_DETAILS_FAIL'

export const COMPANY_JOB_POST_DELETE_REQUEST = 'COMPANY_JOB_POST_DELETE_REQUEST'
export const COMPANY_JOB_POST_DELETE_SUCCESS = 'COMPANY_JOB_POST_DELETE_SUCCESS'
export const COMPANY_JOB_POST_DELETE_FAIL = 'COMPANY_JOB_POST_DELETE_FAIL'