export const ADD_EDUCATION_REQUEST = 'ADD_EDUCATION_REQUEST';
export const ADD_EDUCATION_SUCCESS = 'ADD_EDUCATION_SUCCESS';
export const ADD_EDUCATION_FAIL = 'ADD_EDUCATION_FAIL';
export const ADD_EDUCATION_RESET = 'ADD_EDUCATION_RESET';


export const GET_EDUCATION_REQUEST = 'GET_EDUCATION_REQUEST';
export const GET_EDUCATION_SUCCESS = 'GET_EDUCATION_SUCCESS';
export const GET_EDUCATION_FAIL = 'GET_EDUCATION_FAIL';


export const UPDATE_EDUCATION_REQUEST = 'UPDATE_EDUCATION_REQUEST';
export const UPDATE_EDUCATION_SUCCESS = 'UPDATE_EDUCATION_SUCCESS';
export const UPDATE_EDUCATION_FAIL = 'UPDATE_EDUCATION_FAIL';
export const UPDATE_EDUCATION_RESET = 'UPDATE_EDUCATION_RESET';


export const DELETE_EDUCATION_REQUEST = 'DELETE_EDUCATION_REQUEST';
export const DELETE_EDUCATION_SUCCESS = 'DELETE_EDUCATION_SUCCESS';
export const DELETE_EDUCATION_FAIL = 'DELETE_EDUCATION_FAIL';