export const ADD_EXPERIENCE_REQUEST = 'ADD_EXPERIENCE_REQUEST';
export const ADD_EXPERIENCE_SUCCESS = 'ADD_EXPERIENCE_SUCCESS';
export const ADD_EXPERIENCE_FAIL = 'ADD_EXPERIENCE_FAIL';
export const ADD_EXPERIENCE_RESET = 'ADD_EXPERIENCE_RESET';


export const GET_EXPERIENCE_REQUEST = 'GET_EXPERIENCE_REQUEST';
export const GET_EXPERIENCE_SUCCESS = 'GET_EXPERIENCE_SUCCESS';
export const GET_EXPERIENCE_FAIL = 'GET_EXPERIENCE_FAIL';


export const UPDATE_EXPERIENCE_REQUEST = 'UPDATE_EXPERIENCE_REQUEST';
export const UPDATE_EXPERIENCE_SUCCESS = 'UPDATE_EXPERIENCE_SUCCESS';
export const UPDATE_EXPERIENCE_FAIL = 'UPDATE_EXPERIENCE_FAIL';
export const UPDATE_EXPERIENCE_RESET = 'UPDATE_EXPERIENCE_RESET';


export const DELETE_EXPERIENCE_REQUEST = 'DELETE_EXPERIENCE_REQUEST';
export const DELETE_EXPERIENCE_SUCCESS = 'DELETE_EXPERIENCE_SUCCESS';
export const DELETE_EXPERIENCE_FAIL = 'DELETE_EXPERIENCE_FAIL';