export const JOB_CART_ADD_ITEM = 'JOB_CART_ADD_ITEM'

export const JOB_CART_ADD_ITEM_REQUEST = 'JOB_CART_ADD_ITEM_REQUEST'
export const JOB_CART_ADD_ITEM_SUCCESS = 'JOB_CART_ADD_ITEM_SUCCESS'
export const JOB_CART_ADD_ITEM_FAIL = 'JOB_CART_ADD_ITEM_FAIL'
export const JOB_CART_ADD_ITEM_RESET = 'JOB_CART_ADD_ITEM_RESET'

export const GET_CART_ITEMS_REQUEST = 'GET_CART_ITEMS_REQUEST'
export const GET_CART_ITEMS_SUCCESS = 'GET_CART_ITEMS_SUCCESS'
export const GET_CART_ITEMS_FAIL = 'GET_CART_ITEMS_FAIL'
export const GET_CART_ITEMS_RESET = 'GET_CART_ITEMS_RESET'

export const DELETE_CART_ITEM_REQUEST = 'DELETE_CART_ITEM_REQUEST'
export const DELETE_CART_ITEM_SUCCESS = 'DELETE_CART_ITEM_SUCCESS'
export const DELETE_CART_ITEM_FAIL = 'DELETE_CART_ITEM_FAIL'