export const JOB_POST_LIST_REQUEST = 'JOB_POST_LIST_REQUEST'
export const JOB_POST_LIST_SUCCESS = 'JOB_POST_LIST_SUCCESS'
export const JOB_POST_LIST_FAIL = 'JOB_POST_LIST_FAIL'

export const JOB_POST_DETAILS_REQUEST = 'JOB_POST_DETAILS_REQUEST'
export const JOB_POST_DETAILS_SUCCESS = 'JOB_POST_DETAILS_SUCCESS'
export const JOB_POST_DETAILS_FAIL = 'JOB_POST_DETAILS_FAIL'


export const JOB_POST_ADD_REQUEST = 'JOB_POST_ADD_REQUEST'
export const JOB_POST_ADD_SUCCESS = 'JOB_POST_ADD_SUCCESS'
export const JOB_POST_ADD_FAIL = 'JOB_POST_ADD_FAIL'
export const JOB_POST_ADD_RESET = 'JOB_POST_ADD_RESET'


export const JOB_POST_EDIT_REQUEST = 'JOB_POST_EDIT_REQUEST'
export const JOB_POST_EDIT_SUCCESS = 'JOB_POST_EDIT_SUCCESS'
export const JOB_POST_EDIT_FAIL = 'JOB_POST_EDIT_FAIL'
export const JOB_POST_EDIT_RESET = 'JOB_POST_EDIT_RESET'

