export const ADD_SKILL_REQUEST = 'ADD_SKILL_REQUEST';
export const ADD_SKILL_SUCCESS = 'ADD_SKILL_SUCCESS';
export const ADD_SKILL_FAIL = 'ADD_SKILL_FAIL';
export const ADD_SKILL_RESET = 'ADD_SKILL_RESET';


export const GET_SKILL_REQUEST = 'GET_SKILL_REQUEST';
export const GET_SKILL_SUCCESS = 'GET_SKILL_SUCCESS';
export const GET_SKILL_FAIL = 'GET_SKILL_FAIL';

export const DELETE_SKILL_REQUEST = 'DELETE_SKILL_REQUEST';
export const DELETE_SKILL_SUCCESS = 'DELETE_SKILL_SUCCESS';
export const DELETE_SKILL_FAIL = 'DELETE_SKILL_FAIL';

export const GET_ALL_SKILLS_REQUEST = 'GET_ALL_SKILLS_REQUEST';
export const GET_ALL_SKILLS_SUCCESS = 'GET_ALL_SKILLS_SUCCESS';
export const GET_ALL_SKILLS_FAIL = 'GET_ALL_SKILLS_FAIL';

