# Generated by Django 5.2.4 on 2025-07-28 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Issue', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='status',
            field=models.CharField(choices=[('I', 'ISSUE'), ('R', 'RETURNED')], max_length=1),
        ),
    ]
