# Generated by Django 5.2.4 on 2025-07-28 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Issue', '0002_alter_issue_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='returnDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='issue',
            name='status',
            field=models.CharField(choices=[('I', 'ISSUE'), ('R', 'RETURNED')], default='R', max_length=1),
        ),
    ]
