# Generated by Django 5.2.4 on 2025-07-29 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Issue', '0003_alter_issue_returndate_alter_issue_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='status',
            field=models.CharField(choices=[('I', 'ISSUE'), ('R', 'RETURNED')], default='I', max_length=1),
        ),
    ]
