export const WISHLIST_ADD_ITEM = 'WISHLIST_ADD_ITEM'
export const WISHLIST_REMOVE_ITEM = 'WISHLIST_REMOVE_ITEM'
export const WISHLIST_SAVE_BOOKING_ADDRESS = 'WISHLIST_SAVE_BOOKING_ADDRESS'

export const WISHLIST_SAVE_PAYMENT_METHOD = 'WISHLIST_SAVE_PAYMENT_METHOD'

export const WISHLIST_CLEAR_ITEMS = 'WISHLIST_CLEAR_ITEMS'