# Generated by Django 4.1.6 on 2023-02-14 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_address_user_alter_education_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobapplications',
            name='company',
        ),
    ]
