# Generated by Django 4.1.6 on 2023-03-16 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_address_user_alter_education_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplications',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='candidate_resume/'),
        ),
    ]
