# Generated by Django 4.1 on 2022-09-13 08:54

from django.db import migrations, models
import ormTask.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lecturer',
            fields=[
                ('lecturer_name', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'Teaching Staff',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('dept_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('dept_name', models.CharField(default='computer Science', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('subj_code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('subj_name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'subject',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('semester', models.IntegerField(default=1, validators=[ormTask.models.validate_even])),
                ('joined_on', models.DateTimeField(auto_now_add=True, db_column='admission_date', null=True)),
                ('subjects_enrolled', models.ManyToManyField(blank=True, to='ormTask.subject')),
            ],
            options={
                'verbose_name': 'class',
                'verbose_name_plural': 'class-es',
                'db_table': 'class',
                'ordering': ['semester'],
            },
        ),
    ]
