# Generated by Django 4.1 on 2022-09-13 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ormTask', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='ormTask.department'),
        ),
        migrations.AlterModelTable(
            name='department',
            table='branch',
        ),
    ]
