# Generated by Django 5.2.3 on 2025-07-07 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_employee'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='employee',
            table='Employee_Demo',
        ),
    ]
