# Generated by Django 5.2.3 on 2025-07-07 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_employee_table'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Employee',
            new_name='Employee_Demo',
        ),
    ]
