# Generated by Django 5.2.3 on 2025-07-07 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_rename_employee_employee_demo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Employee_Demo',
            new_name='RGUKT',
        ),
        migrations.AlterModelTable(
            name='rgukt',
            table='RGUKT',
        ),
    ]
