# Generated by Django 5.2.3 on 2025-07-07 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_rename_employee_demo_rgukt_alter_rgukt_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Example',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_id', models.CharField(max_length=20)),
                ('emp_name', models.CharField(max_length=30)),
                ('designation', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'Example',
            },
        ),
        migrations.DeleteModel(
            name='RGUKT',
        ),
    ]
