# Generated by Django 5.2.3 on 2025-07-07 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_example_delete_rgukt'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='example',
            options={'managed': False},
        ),
    ]
