# Generated by Django 5.2.3 on 2025-07-07 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_alter_example_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Example',
        ),
    ]
