# Generated by Django 5.2.3 on 2025-07-07 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_example'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Example',
        ),
    ]
