# Generated by Django 5.2.3 on 2025-07-07 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_example'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('age', models.IntegerField(max_length=5)),
                ('salary', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'Employee',
            },
        ),
    ]
