# Generated by Django 4.1.1 on 2022-10-06 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0008_rename_transaction_id_logs_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactiontable',
            name='transaction_amount',
            field=models.CharField(max_length=50),
        ),
    ]
