# Generated by Django 4.1.1 on 2022-10-06 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0010_transactiontable_receiver_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logs',
            name='transaction_time',
        ),
        migrations.AddField(
            model_name='transactiontable',
            name='transaction_time',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
