# Generated by Django 4.1.1 on 2022-10-12 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0020_customerimagetable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditcard',
            name='card_amount',
            field=models.BigIntegerField(),
        ),

        migrations.AlterField(
            model_name='creditcard',
            name='expire_date',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='customerimagetable',
            name='cover_image',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='customerimagetable',
            name='profile_image',
            field=models.CharField(max_length=1000),
        ),
    ]
