# Generated by Django 4.1.1 on 2022-10-13 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0022_remove_creditcard_card_numb_creditcard_card_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerRequests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=200)),
                ('customer_email', models.CharField(max_length=200)),
                ('request_type', models.CharField(max_length=200)),
                ('request_status', models.BooleanField(default=False)),
            ],
        ),
    ]
