# Generated by Django 4.1.1 on 2022-10-13 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0024_alter_customerrequests_request_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerrequests',
            name='request_status',
            field=models.BooleanField(default=False),
        ),
    ]
