# Generated by Django 4.1.1 on 2022-10-14 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0025_alter_customerrequests_request_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debitcard',
            name='cvv',
            field=models.CharField(max_length=200),
        ),
    ]
