# Generated by Django 4.1.1 on 2022-09-13 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pharmacy', '0002_alter_customer_email_alter_distributor_email_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cart',
            table='cart',
        ),
        migrations.AlterModelTable(
            name='customer',
            table='customer',
        ),
        migrations.AlterModelTable(
            name='distributor',
            table='distributor',
        ),
        migrations.AlterModelTable(
            name='doctor',
            table='doctor',
        ),
        migrations.AlterModelTable(
            name='drug',
            table='drug',
        ),
        migrations.AlterModelTable(
            name='employee',
            table='employee',
        ),
        migrations.AlterModelTable(
            name='invoice',
            table='invoice',
        ),
        migrations.AlterModelTable(
            name='manufacturer',
            table='manufacturer',
        ),
        migrations.AlterModelTable(
            name='order',
            table='order',
        ),
        migrations.AlterModelTable(
            name='prescribe',
            table='prescribe',
        ),
        migrations.AlterModelTable(
            name='purchase',
            table='purchase',
        ),
        migrations.AlterModelTable(
            name='sales',
            table='sales',
        ),
        migrations.AlterModelTable(
            name='supply',
            table='supply',
        ),
    ]
