# Generated by Django 4.1.1 on 2022-09-13 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pharmacy', '0003_alter_cart_table_alter_customer_table_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='sales',
            table='sale',
        ),
        migrations.AlterModelTable(
            name='supply',
            table='supplies',
        ),
    ]
