# Generated by Django 4.1.1 on 2022-09-13 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pharmacy', '0004_alter_sales_table_alter_supply_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='sales',
            table='sales',
        ),
        migrations.AlterModelTable(
            name='supply',
            table='supply',
        ),
    ]
