# Generated by Django 4.1.1 on 2022-09-13 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pharmacy', '0005_alter_sales_table_alter_supply_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'verbose_name_plural': 'cart'},
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name_plural': 'customer'},
        ),
        migrations.AlterModelOptions(
            name='distributor',
            options={'verbose_name_plural': 'distributor'},
        ),
        migrations.AlterModelOptions(
            name='doctor',
            options={'verbose_name_plural': 'doctor'},
        ),
        migrations.AlterModelOptions(
            name='drug',
            options={'verbose_name_plural': 'drug'},
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'verbose_name_plural': 'employee'},
        ),
        migrations.AlterModelOptions(
            name='invoice',
            options={'verbose_name_plural': 'invoice'},
        ),
        migrations.AlterModelOptions(
            name='manufacturer',
            options={'verbose_name_plural': 'manufacturer'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name_plural': 'order'},
        ),
        migrations.AlterModelOptions(
            name='prescribe',
            options={'verbose_name_plural': 'prescribe'},
        ),
        migrations.AlterModelOptions(
            name='purchase',
            options={'verbose_name_plural': 'purchase'},
        ),
        migrations.AlterModelOptions(
            name='sales',
            options={'verbose_name_plural': 'sales'},
        ),
        migrations.AlterModelOptions(
            name='supply',
            options={'verbose_name_plural': 'supply'},
        ),
        migrations.AlterModelTable(
            name='cart',
            table=None,
        ),
        migrations.AlterModelTable(
            name='customer',
            table=None,
        ),
        migrations.AlterModelTable(
            name='distributor',
            table=None,
        ),
        migrations.AlterModelTable(
            name='doctor',
            table=None,
        ),
        migrations.AlterModelTable(
            name='drug',
            table=None,
        ),
        migrations.AlterModelTable(
            name='employee',
            table=None,
        ),
        migrations.AlterModelTable(
            name='invoice',
            table=None,
        ),
        migrations.AlterModelTable(
            name='manufacturer',
            table=None,
        ),
        migrations.AlterModelTable(
            name='order',
            table=None,
        ),
        migrations.AlterModelTable(
            name='prescribe',
            table=None,
        ),
        migrations.AlterModelTable(
            name='purchase',
            table=None,
        ),
        migrations.AlterModelTable(
            name='sales',
            table=None,
        ),
        migrations.AlterModelTable(
            name='supply',
            table=None,
        ),
    ]
