# Generated by Django 4.1 on 2022-09-12 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_alter_payment_booking_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hall',
            name='Theatre_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='home.theatre'),
        ),
        migrations.AlterField(
            model_name='user',
            name='User_id',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
        ),
    ]
