# Generated by Django 4.1 on 2022-09-22 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_remove_cart_snacks_user_password_alter_booking_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='Snacks',
            field=models.ManyToManyField(to='home.snacks'),
        ),
        migrations.AddField(
            model_name='cart',
            name='User_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.user'),
        ),
        migrations.AlterField(
            model_name='user',
            name='User_email',
            field=models.CharField(default='', max_length=45),
        ),
        migrations.AlterField(
            model_name='user',
            name='User_name',
            field=models.CharField(default='', max_length=45),
        ),
        migrations.AlterField(
            model_name='user',
            name='User_phone',
            field=models.CharField(default='', max_length=45),
        ),
    ]
