# Generated by Django 4.1 on 2022-09-26 11:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_alter_booking_date_alter_movie_movie_release_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hall',
            name='Date',
            field=models.DateField(default=datetime.date(2022, 9, 26)),
        ),
        migrations.AddField(
            model_name='hall',
            name='startTime',
            field=models.TimeField(auto_now=True),
        ),
    ]
