# Generated by Django 4.1 on 2022-10-10 05:29

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0036_alter_booking_date_alter_hall_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatewiseHall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(default=datetime.date(2022, 10, 10))),
                ('T_No_Of_Seats', models.IntegerField(default=100)),
                ('Hall_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.hall')),
            ],
        ),
        migrations.DeleteModel(
            name='Date',
        ),
    ]
