# Generated by Django 5.2.4 on 2025-07-23 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModelUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=150)),
                ('Age', models.IntegerField()),
                ('Email', models.CharField(max_length=150)),
                ('PhoneNumber', models.CharField(max_length=13)),
                ('Branch', models.CharField(max_length=3)),
                ('Languages', models.CharField(max_length=10)),
                ('State', models.CharField(max_length=50)),
                ('City', models.CharField(max_length=50)),
            ],
        ),
    ]
