# Generated by Django 4.1.3 on 2022-12-02 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_student_marks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='branch',
        ),
        migrations.DeleteModel(
            name='Marks',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.DeleteModel(
            name='Subjects',
        ),
    ]
