# Generated by Django 4.1 on 2022-09-13 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Batsman',
            fields=[
                ('bat_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('bat_name', models.CharField(max_length=30)),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Matches',
            fields=[
                ('match_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('match_hosted', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Bowler',
            fields=[
                ('bow_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('bow_name', models.CharField(max_length=30)),
                ('matches_played', models.ManyToManyField(to='app5.matches')),
            ],
            options={
                'managed': True,
            },
        ),
    ]
