# Generated by Django 4.1 on 2022-09-13 09:26

import app5.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app5', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bowler',
            name='bow_name',
            field=models.CharField(max_length=30, validators=[app5.models.validate_name]),
        ),
    ]
