# Generated by Django 4.1 on 2022-09-14 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='department',
            fields=[
                ('deptid', models.AutoField(primary_key=True, serialize=False)),
                ('deptname', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='employee',
            fields=[
                ('empid', models.AutoField(primary_key=True, serialize=False)),
                ('empname', models.CharField(max_length=25)),
                ('empage', models.IntegerField()),
                ('department', models.CharField(max_length=25)),
            ],
        ),
    ]
