# Generated by Django 4.2.23 on 2025-07-11 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('dept_id', models.AutoField(primary_key=True, serialize=False)),
                ('dept_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('teacher_id', models.AutoField(primary_key=True, serialize=False)),
                ('teacher_first_name', models.CharField(max_length=60)),
                ('teacher_last_name', models.CharField(max_length=20)),
                ('teacher_email', models.EmailField(max_length=254)),
                ('dept_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sample.department')),
            ],
        ),
    ]
