# Generated by Django 4.2.23 on 2025-07-11 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.AutoField(primary_key=True, serialize=False)),
                ('student_first_name', models.CharField(max_length=60)),
                ('student_last_name', models.CharField(max_length=20)),
                ('student_email', models.EmailField(max_length=254)),
                ('student_dob', models.DateField()),
                ('enrollment_year', models.DateField()),
                ('dept_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sample.department')),
            ],
        ),
    ]
