# Generated by Django 4.1.4 on 2023-01-18 11:17

from django.db import migrations, models
import project.models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_course_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(null=True, upload_to=project.models.upload_to),
        ),
    ]
