# Generated by Django 4.1.4 on 2023-02-20 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0010_courserating'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courserating',
            options={'verbose_name_plural': '9.Course Rating'},
        ),
        migrations.AlterField(
            model_name='instructor',
            name='designation',
            field=models.CharField(max_length=50),
        ),
    ]
