# Generated by Django 4.1 on 2022-08-30 09:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('emp_name', models.CharField(max_length=120)),
                ('emp_role', models.TextField(blank=True, null=True)),
                ('emp_salary', models.DecimalField(decimal_places=2, max_digits=1000)),
                ('emp_mail', models.TextField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
        ),
    ]
