# Generated by Django 4.1 on 2022-09-13 09:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('emp_name', models.CharField(max_length=120)),
                ('emp_role', models.TextField(blank=True, null=True)),
                ('emp_email', models.EmailField(max_length=254)),
                ('emp_salary', models.IntegerField(null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
        ),
    ]
