# Generated by Django 4.1.6 on 2023-02-13 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cinema',
            fields=[
                ('cinemaId', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('totalCinemaHalls', models.IntegerField(blank=True, default=1, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cinema_Hall',
            fields=[
                ('cinema_hall_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('totalSeats', models.IntegerField(blank=True, default=0, null=True)),
                ('cinema', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cinema.cinema')),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('state', models.CharField(blank=True, max_length=200, null=True)),
                ('zipCode', models.CharField(blank=True, max_length=200, null=True)),
                ('city_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Cinema_Seat',
            fields=[
                ('cinema_seat_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('seat_number', models.IntegerField(blank=True, default=0, null=True)),
                ('type', models.CharField(blank=True, max_length=200, null=True)),
                ('cinemahall', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cinema.cinema_hall')),
            ],
        ),
        migrations.AddField(
            model_name='cinema',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cinema.city'),
        ),
    ]
