# Generated by Django 4.1.1 on 2022-09-16 09:38

from django.db import migrations, models
import django.db.models.deletion
import employee.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('comp_id', models.IntegerField(primary_key=True, serialize=False)),
                ('comp_desc', models.CharField(max_length=200)),
                ('is_assigned', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('device_id', models.IntegerField(primary_key=True, serialize=False)),
                ('device_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('emp_id', models.IntegerField(primary_key=True, serialize=False)),
                ('emp_name', models.CharField(max_length=30)),
                ('emp_mobile', models.CharField(max_length=30, null=True, validators=[employee.models.mobilenumberValidator])),
                ('emp_email', models.CharField(max_length=30, null=True)),
                ('emp_role', models.CharField(max_length=30, null=True)),
                ('emp_pic', models.ImageField(null=True, upload_to='')),
                ('emp_password', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('facility_id', models.IntegerField(primary_key=True, serialize=False)),
                ('facility_location', models.CharField(max_length=30)),
                ('facility_dept', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_role', models.CharField(max_length=30)),
                ('emp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Issued_to',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comp_status', models.CharField(max_length=30)),
                ('comp_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='employee.complaint')),
                ('emp_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='employee.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Employee_Devices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_name', models.CharField(max_length=30, null=True)),
                ('emp_name', models.CharField(max_length=30, null=True)),
                ('quantity', models.IntegerField(null=True)),
                ('device_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.device')),
                ('emp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.employee')),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='facility_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.facility'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='device_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.device'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='emp_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.employee'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='facility_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='employee.facility'),
        ),
    ]
