# Generated by Django 4.1.1 on 2022-09-21 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='comp_desc',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
