# Generated by Django 4.1.1 on 2022-09-26 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_alter_complaint_comp_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='comp_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
