package com.medplus.marketing.constants;

public class MarketingConstants {
	
	public static final String MODULE_NAME = "marketing";
	
	public static final String MIC_PHARMACY_VIEW_ROLE = "ROLE_MRK_CAMPAIGN_VIEW_MULTIITEM_PHARMACY";
	public static final String MIC_PATHLABS_VIEW_ROLE = "ROLE_MRK_CAMPAIGN_VIEW_MULTIITEM_LAB_DOCTOR";
	public static final String MIC_LENS_VIEW_ROLE = "ROLE_MRK_CAMPAIGN_VIEW_MULTIITEM_LENS";
	
	public static final String MIC_PHARMACY_CREATE_ROLE = "ROLE_MRK_CAMPAIGN_CREATION_MULTIITEM_PHARMACY";
	public static final String MIC_PATHLABS_CREATE_ROLE = "ROLE_MRK_CAMPAIGN_CREATION_MULTIITEM_LAB_DOCTOR";
	public static final String MIC_LENS_CREATE_ROLE = "ROLE_MRK_CAMPAIGN_CREATION_MULTIITEM_LENS";
	
	public static final String MIC_PHARMACY_EDIT_ROLE = "ROLE_MRK_CAMPAIGN_EDIT_MULTIITEM_PHARMACY";
	public static final String MIC_PATHLABS_EDIT_ROLE = "ROLE_MRK_CAMPAIGN_EDIT_MULTIITEM_LAB_DOCTOR";
	public static final String MIC_LENS_EDIT_ROLE = "ROLE_MRK_CAMPAIGN_EDIT_MULTIITEM_LENS";
	
	public static final String MIC_PHARMACY_APPROVE_ROLE = "ROLE_MRK_CAMPAIGN_APPROVE_MULTIITEM_PHARMACY";
	public static final String MIC_PATHLABS_APPROVE_ROLE = "ROLE_MRK_CAMPAIGN_APPROVE_MULTIITEM_LAB_DOCTOR";
	public static final String MIC_LENS_APPROVE_ROLE = "ROLE_MRK_CAMPAIGN_APPROVE_MULTIITEM_LENS";
	
	public static final String MIC_PHARMACY_CLOSE_ROLE = "ROLE_MRK_CAMPAIGN_CLOSE_MULTIITEM_PHARMACY";
	public static final String MIC_PATHLABS_CLOSE_ROLE = "ROLE_MRK_CAMPAIGN_CLOSE_MULTIITEM_LAB_DOCTOR";
	public static final String MIC_LENS_CLOSE_ROLE = "ROLE_MRK_CAMPAIGN_CLOSE_MULTIITEM_LENS";
	
	
	public static final String MIC_APPROVE_RIGHTS = "hasAnyRole('ROLE_MRK_CAMPAIGN_APPROVE_MULTIITEM_LENS', 'ROLE_MRK_CAMPAIGN_APPROVE_MULTIITEM_PHARMACY', 'ROLE_MRK_CAMPAIGN_APPROVE_MULTIITEM_LAB_DOCTOR')";
	public static final String MIC_VIEW_RIGHTS = "hasAnyRole('ROLE_MRK_CAMPAIGN_VIEW_MULTIITEM_LENS', 'ROLE_MRK_CAMPAIGN_VIEW_MULTIITEM_PHARMACY', 'ROLE_MRK_CAMPAIGN_VIEW_MULTIITEM_LAB_DOCTOR')";
	public static final String MIC_EDIT_RIGHTS = "hasAnyRole('ROLE_MRK_CAMPAIGN_EDIT_MULTIITEM_LENS', 'ROLE_MRK_CAMPAIGN_EDIT_MULTIITEM_PHARMACY', 'ROLE_MRK_CAMPAIGN_EDIT_MULTIITEM_LAB_DOCTOR')";
	public static final String MIC_CREATE_RIGHTS = "hasAnyRole('ROLE_MRK_CAMPAIGN_CREATION_MULTIITEM_LENS', 'ROLE_MRK_CAMPAIGN_CREATION_MULTIITEM_PHARMACY', 'ROLE_MRK_CAMPAIGN_CREATION_MULTIITEM_LAB_DOCTOR')";
	public static final String MIC_CLOSE_RIGHTS = "hasAnyRole('ROLE_MRK_CAMPAIGN_CLOSE_MULTIITEM_PHARMACY','ROLE_MRK_CAMPAIGN_CLOSE_MULTIITEM_LENS', 'ROLE_MRK_CAMPAIGN_CLOSE_MULTIITEM_LAB_DOCTOR')";
	
	
	/***
	 * Campaign rights
	 */
	
	public static final String CAMPAIGN_PHARMACY_LIST_ROLE = "ROLE_MRK_CAMPAIGN_LIST_PHARMACY";
	public static final String CAMPAIGN_PATHLABS_LIST_ROLE = "ROLE_MRK_CAMPAIGN_LIST_LABS_DOCTOR";
	public static final String CAMPAIGN_LENS_LIST_ROLE = "ROLE_MRK_CAMPAIGN_LIST_LENS";
	
	public static final String CAMPAIGN_PHARMACY_CREATE_ROLE = "ROLE_MRK_CAMPAIGN_CREATION_PHARMACY";
	public static final String CAMPAIGN_PATHLABS_CREATE_ROLE = "ROLE_MRK_CAMPAIGN_CREATION_LABS_DOCTOR";
	public static final String CAMPAIGN_LENS_CREATE_ROLE = "ROLE_MRK_CAMPAIGN_CREATION_LENS";
	
	public static final String CAMPAIGN_PHARMACY_EDIT_ROLE = "ROLE_MRK_CAMPAIGN_EDIT_PHARMACY";
	public static final String CAMPAIGN_PATHLABS_EDIT_ROLE = "ROLE_MRK_CAMPAIGN_EDIT_LABS_DOCTOR";
	public static final String CAMPAIGN_LENS_EDIT_ROLE = "ROLE_MRK_CAMPAIGN_EDIT_LENS";
	
	public static final String CAMPAIGN_PHARMACY_APPROVE_ROLE = "ROLE_MRK_CAMPAIGN_APPROVE_PHARMACY";
	public static final String CAMPAIGN_PATHLABS_APPROVE_ROLE = "ROLE_MRK_CAMPAIGN_APPROVE_LABS_DOCTOR";
	public static final String CAMPAIGN_LENS_APPROVE_ROLE = "ROLE_MRK_CAMPAIGN_APPROVE_LENS";
	
	/*
	 * For editing to date of an approved campaign
	 */
	public static final String CAMPAIGN_PHARMACY_CLOSE_ROLE = "ROLE_MRK_CAMPAIGN_CLOSE_PHARMACY";
	public static final String CAMPAIGN_PATHLABS_CLOSE_ROLE = "ROLE_MRK_CAMPAIGN_CLOSE_LABS_DOCTOR";
	public static final String CAMPAIGN_LENS_CLOSE_ROLE = "ROLE_MRK_CAMPAIGN_CLOSE_LENS";
	
	public static final String CAMPAIGN_APPROVE_RIGHTS = "hasAnyRole('ROLE_MRK_CAMPAIGN_APPROVE_LENS', 'ROLE_MRK_CAMPAIGN_APPROVE_PHARMACY', 'ROLE_MRK_CAMPAIGN_APPROVE_LABS_DOCTOR')";
	public static final String CAMPAIGN_LIST_RIGHTS = "hasAnyRole('ROLE_MRK_CAMPAIGN_LIST_LENS', 'ROLE_MRK_CAMPAIGN_LIST_PHARMACY', 'ROLE_MRK_CAMPAIGN_LIST_LABS_DOCTOR')";
	public static final String CAMPAIGN_EDIT_RIGHTS = "hasAnyRole('ROLE_MRK_CAMPAIGN_EDIT_LENS', 'ROLE_MRK_CAMPAIGN_EDIT_PHARMACY', 'ROLE_MRK_CAMPAIGN_EDIT_LABS_DOCTOR')";
	public static final String CAMPAIGN_CREATE_RIGHTS = "hasAnyRole('ROLE_MRK_CAMPAIGN_CREATION_LENS', 'ROLE_MRK_CAMPAIGN_CREATION_PHARMACY', 'ROLE_MRK_CAMPAIGN_CREATION_LABS_DOCTOR')";
	public static final String CAMPAIGN_CLOSE_RIGHTS = "hasAnyRole('ROLE_MRK_CAMPAIGN_CLOSE_LENS', 'ROLE_MRK_CAMPAIGN_CLOSE_PHARMACY', 'ROLE_MRK_CAMPAIGN_CLOSE_LABS_DOCTOR')";

	/***
	 * Regular Promotion rights
	 */
	
	public static final String RP_CREATE_ROLE = "ROLE_MRK_REGULAR_PROMOTION_CREATION";
	public static final String RP_EDIT_ROLE = "ROLE_MRK_REGULAR_PROMOTION_EDIT";
	public static final String RP_APPROVE_ROLE = "ROLE_MRK_REGULAR_PROMOTION_APPROVE";
	public static final String RP_CLOSE_ROLE = "ROLE_MRK_REGULAR_PROMOTION_CLOSE";
	public static final String RP_VIEW_ROLE = "ROLE_MRK_REGULAR_PROMOTION_LIST";
	
	public static final String RP_CREATE_RIGHTS = "hasAnyRole('ROLE_MRK_REGULAR_PROMOTION_CREATION')";
	public static final String RP_EDIT_RIGHTS = "hasAnyRole('ROLE_MRK_REGULAR_PROMOTION_EDIT')";
	public static final String RP_APPROVE_RIGHTS = "hasAnyRole('ROLE_MRK_REGULAR_PROMOTION_APPROVE')";
	public static final String RP_CLOSE_RIGHTS = "hasAnyRole('ROLE_MRK_REGULAR_PROMOTION_CLOSE')";
	public static final String RP_VIEW_RIGHTS = "hasAnyRole('ROLE_MRK_REGULAR_PROMOTION_LIST')";
	
	/***
	 * Complimentary Promotion rights
	 */
	
	public static final String COMPLIMENTARY_CREATE_ROLE = "ROLE_MRK_COMPLIMENTARY_CREATION";
	public static final String COMPLIMENTARY_EDIT_ROLE = "ROLE_MRK_COMPLIMENTARY_EDIT";
	public static final String COMPLIMENTARY_APPROVE_ROLE = "ROLE_MRK_COMPLIMENTARY_APPROVE";
	public static final String COMPLIMENTARY_CLOSE_ROLE = "ROLE_MRK_COMPLIMENTARY_CLOSE";
	public static final String COMPLIMENTARY_VIEW_ROLE = "ROLE_MRK_COMPLIMENTARY_LIST";
	
	public static final String COMPLIMENTARY_CREATE_RIGHTS = "hasAnyRole('ROLE_MRK_COMPLIMENTARY_CREATION')";
	public static final String COMPLIMENTARY_EDIT_RIGHTS = "hasAnyRole('ROLE_MRK_COMPLIMENTARY_EDIT')";
	public static final String COMPLIMENTARY_APPROVE_RIGHTS = "hasAnyRole('ROLE_MRK_COMPLIMENTARY_APPROVE')";
	public static final String COMPLIMENTARY_CLOSE_RIGHTS = "hasAnyRole('ROLE_MRK_COMPLIMENTARY_CLOSE')";
	public static final String COMPLIMENTARY_VIEW_RIGHTS = "hasAnyRole('ROLE_MRK_COMPLIMENTARY_LIST')";
	
	/**
	 * Popup Template rights
	 */

	public static final String LAB_TEMPLATE_CREATE_ROLE = "ROLE_MRK_ADD_TEMPLATES_LABS";
	public static final String LAB_TEMPLATE_EDIT_ROLE = "ROLE_MRK_EDIT_TEMPLATES_LABS";
	public static final String LAB_TEMPLATE_VIEW_ROLE = "ROLE_MRK_LIST_VIEW_TEMPLATES_LABS";
	public static final String LAB_TEMPLATE_CLOSE_ROLE = "ROLE_MRK_CLOSE_TEMPLATES_LABS";
	public static final String LAB_TEMPLATE_APPROVE_ROLE = "ROLE_MRK_APPROVE_TEMPLATES_LABS";

	public static final String PHARMA_TEMPLATE_CREATE_ROLE = "ROLE_MRK_ADD_TEMPLATES";
	public static final String PHARMA_TEMPLATE_VIEW_ROLE = "ROLE_MRK_LIST_TEMPLATES";
	public static final String PHARMA_TEMPLATE_APPROVE_ROLE = "ROLE_MRK_APPROVE_TEMPLATES";

	public static final String TEMPLATE_CREATE_RIGHTS = "hasAnyRole('ROLE_MRK_ADD_TEMPLATES_LABS', 'ROLE_MRK_ADD_TEMPLATES')";
	public static final String TEMPLATE_EDIT_RIGHTS = "hasAnyRole('ROLE_MRK_EDIT_TEMPLATES_LABS', 'ROLE_MRK_LIST_TEMPLATES')";
	public static final String TEMPLATE_VIEW_RIGHTS = "hasAnyRole('ROLE_MRK_LIST_VIEW_TEMPLATES_LABS', 'ROLE_MRK_LIST_TEMPLATES')";
	public static final String TEMPLATE_APPROVE_RIGHTS = "hasAnyRole('ROLE_MRK_APPROVE_TEMPLATES_LABS', 'ROLE_MRK_APPROVE_TEMPLATES')";

	/**
	 * Popup Config rights
	 */

	public static final String LAB_CONFIG_CREATE_ROLE = "ROLE_MRK_ADD_POPUP_CONFIG_LABS";
	public static final String LAB_CONFIG_EDIT_ROLE = "ROLE_MRK_EDIT_POPUP_CONFIG_LABS";
	public static final String LAB_CONFIG_VIEW_ROLE = "ROLE_MRK_LIST_VIEW_POPUP_CONFIG_LABS";
	public static final String LAB_CONFIG_CLOSE_ROLE = "ROLE_MRK_CLOSE_POPUP_CONFIG_LABS";
	public static final String LAB_CONFIG_APPROVE_ROLE = "ROLE_MRK_APPROVE_POPUP_CONFIG_LABS";

	public static final String PHARMA_CONFIG_CREATE_ROLE = "ROLE_MRK_ADD_POPUP_CONFIGURATION";
	public static final String PHARMA_CONFIG_VIEW_ROLE = "ROLE_MRK_LIST_POPUP_CONFIGURATION";
	public static final String PHARMA_CONFIG_APPROVE_ROLE = "ROLE_MRK_APPROVE_POPUP_CONFIGURATION";

	public static final String CONFIG_CREATE_RIGHTS = "hasAnyRole('ROLE_MRK_ADD_POPUP_CONFIG_LABS', 'ROLE_MRK_ADD_POPUP_CONFIGURATION')";
	public static final String CONFIG_EDIT_RIGHTS = "hasAnyRole('ROLE_MRK_EDIT_POPUP_CONFIG_LABS', 'ROLE_MRK_LIST_POPUP_CONFIGURATION')";
	public static final String CONFIG_VIEW_RIGHTS = "hasAnyRole('ROLE_MRK_LIST_VIEW_POPUP_CONFIG_LABS', 'ROLE_MRK_LIST_POPUP_CONFIGURATION')";
	public static final String CONFIG_APPROVE_RIGHTS = "hasAnyRole('ROLE_MRK_APPROVE_POPUP_CONFIG_LABS', 'ROLE_MRK_APPROVE_POPUP_CONFIGURATION')";
	
	private MarketingConstants() {}	
}
