export const MIC_CREATE_LENS ="ROLE_MRK_CAMPAIGN_CREATION_MULTIITEM_LENS";
export const MIC_CREATE_PHARMACY ="ROLE_MRK_CAMPAIGN_CREATION_MULTIITEM_PHARMACY";
export const MIC_CREATE_LAB_DOCTOR = "ROLE_MRK_CAMPAIGN_CREATION_MULTIITEM_LAB_DOCTOR";

const MIC_EDIT_LENS ="ROLE_MRK_CAMPAIGN_EDIT_MULTIITEM_LENS";
const MIC_EDIT_PHARMACY ="ROLE_MRK_CAMPAIGN_EDIT_MULTIITEM_PHARMACY";
const MIC_EDIT_LAB_DOCTOR = "ROLE_MRK_CAMPAIGN_EDIT_MULTIITEM_LAB_DOCTOR";

const MIC_APPROVE_LENS ="ROLE_MRK_CAMPAIGN_APPROVE_MULTIITEM_LENS";
const MIC_APPROVE_PHARMACY ="ROLE_MRK_CAMPAIGN_APPROVE_MULTIITEM_PHARMACY";
const MIC_APPROVE_LAB_DOCTOR = "ROLE_MRK_CAMPAIGN_APPROVE_MULTIITEM_LAB_DOCTOR";

const MIC_CLOSE_LENS ="ROLE_MRK_CAMPAIGN_CLOSE_MULTIITEM_LENS";
const MIC_CLOSE_PHARMACY ="ROLE_MRK_CAMPAIGN_CLOSE_MULTIITEM_PHARMACY";
const MIC_CLOSE_LAB_DOCTOR = "ROLE_MRK_CAMPAIGN_CLOSE_MULTIITEM_LAB_DOCTOR";


const MIC_VIEW_LENS ="ROLE_MRK_CAMPAIGN_VIEW_MULTIITEM_LENS";
const MIC_VIEW_PHARMACY ="ROLE_MRK_CAMPAIGN_VIEW_MULTIITEM_PHARMACY";
const MIC_VIEW_LAB_DOCTOR = "ROLE_MRK_CAMPAIGN_VIEW_MULTIITEM_LAB_DOCTOR";

export const MIC_ROLES = {
    pharmacyCreator: [MIC_CREATE_PHARMACY],
    pharmacyEditor: [MIC_EDIT_PHARMACY],
    pharmacyApprover : [MIC_APPROVE_PHARMACY],
    pharmacyCloser : [MIC_CLOSE_PHARMACY],

    lensCreator: [MIC_CREATE_LENS, MIC_EDIT_LENS],
    lensEditor: [MIC_EDIT_LENS],
    lensApprover: [MIC_APPROVE_LENS],
    lensCloser : [MIC_CLOSE_LENS],

    labsCreator: [MIC_CREATE_LAB_DOCTOR,MIC_EDIT_LAB_DOCTOR],
    labsEditor: [MIC_EDIT_LAB_DOCTOR],
    labsApprover: [MIC_APPROVE_LAB_DOCTOR],
    labsCloser : [MIC_CLOSE_LAB_DOCTOR],
    
    listRoles: [MIC_VIEW_LENS, MIC_VIEW_PHARMACY, MIC_VIEW_LAB_DOCTOR],
    createRoles: [MIC_CREATE_LENS, MIC_CREATE_LAB_DOCTOR, MIC_CREATE_PHARMACY],
    cloneRoles: [MIC_CREATE_PHARMACY, MIC_CREATE_LENS, MIC_CREATE_LAB_DOCTOR],
    editRoles: [ MIC_EDIT_LENS, MIC_EDIT_PHARMACY, MIC_EDIT_LAB_DOCTOR],
    editIconRoles: [MIC_EDIT_LENS, MIC_EDIT_PHARMACY, MIC_EDIT_LAB_DOCTOR, 
                  MIC_APPROVE_LENS, MIC_APPROVE_PHARMACY, MIC_APPROVE_LAB_DOCTOR],
    closeRoles: [ MIC_CLOSE_LENS, MIC_CLOSE_PHARMACY, MIC_CLOSE_LAB_DOCTOR],
    approveRoles: [MIC_APPROVE_LENS, MIC_APPROVE_PHARMACY, MIC_APPROVE_LAB_DOCTOR],

    allRoles : [MIC_CREATE_PHARMACY, MIC_EDIT_PHARMACY, MIC_APPROVE_PHARMACY, MIC_CLOSE_PHARMACY, MIC_VIEW_PHARMACY,
                MIC_CREATE_LENS, MIC_EDIT_LENS, MIC_APPROVE_LENS, MIC_CLOSE_LENS, MIC_VIEW_LENS,
                MIC_CREATE_LAB_DOCTOR, MIC_EDIT_LAB_DOCTOR, MIC_APPROVE_LAB_DOCTOR, MIC_CLOSE_LAB_DOCTOR, MIC_VIEW_LAB_DOCTOR]
}   

export const RP_CREATE = "ROLE_MRK_REGULAR_PROMOTION_CREATION";
export const RP_EDIT = "ROLE_MRK_REGULAR_PROMOTION_EDIT";
export const RP_APPROVE = "ROLE_MRK_REGULAR_PROMOTION_APPROVE";
export const RP_CLOSE = "ROLE_MRK_REGULAR_PROMOTION_CLOSE";
export const RP_VIEW = "ROLE_MRK_REGULAR_PROMOTION_LIST";

export const RP_ROLES = {
    pharmacyCreator: [RP_CREATE],
    pharmacyEditor: [RP_EDIT],
    pharmacyApprover : [RP_APPROVE],
    pharmacyCloser : [RP_CLOSE],

    listRoles: [RP_VIEW],
    createRoles: [RP_CREATE],
    cloneRoles: [RP_CREATE],
    editRoles: [RP_EDIT],
    editIconRoles: [RP_EDIT, RP_APPROVE],
    closeRoles: [RP_CLOSE],
    approveRoles: [RP_APPROVE],
    allRoles: [RP_CREATE, RP_EDIT, RP_APPROVE, RP_CLOSE, RP_VIEW]
}   

export const CAMPAIGN_CREATE_LENS ="ROLE_MRK_CAMPAIGN_CREATION_LENS";
export const CAMPAIGN_CREATE_PHARMACY ="ROLE_MRK_CAMPAIGN_CREATION_PHARMACY";
export const CAMPAIGN_CREATE_LAB_DOCTOR = "ROLE_MRK_CAMPAIGN_CREATION_LABS_DOCTOR";

const CAMPAIGN_EDIT_LENS ="ROLE_MRK_CAMPAIGN_EDIT_LENS";
const CAMPAIGN_EDIT_PHARMACY ="ROLE_MRK_CAMPAIGN_EDIT_PHARMACY";
const CAMPAIGN_EDIT_LAB_DOCTOR = "ROLE_MRK_CAMPAIGN_EDIT_LABS_DOCTOR";

const CAMPAIGN_APPROVE_LENS ="ROLE_MRK_CAMPAIGN_APPROVE_LENS";
const CAMPAIGN_APPROVE_PHARMACY ="ROLE_MRK_CAMPAIGN_APPROVE_PHARMACY";
const CAMPAIGN_APPROVE_LAB_DOCTOR = "ROLE_MRK_CAMPAIGN_APPROVE_LABS_DOCTOR";

const CAMPAIGN_CLOSE_LENS ="ROLE_MRK_CAMPAIGN_CLOSE_LENS";
const CAMPAIGN_CLOSE_PHARMACY ="ROLE_MRK_CAMPAIGN_CLOSE_PHARMACY";
const CAMPAIGN_CLOSE_LAB_DOCTOR = "ROLE_MRK_CAMPAIGN_CLOSE_LABS_DOCTOR";


const CAMPAIGN_VIEW_LENS ="ROLE_MRK_CAMPAIGN_LIST_LENS";
const CAMPAIGN_VIEW_PHARMACY ="ROLE_MRK_CAMPAIGN_LIST_PHARMACY";
const CAMPAIGN_VIEW_LAB_DOCTOR = "ROLE_MRK_CAMPAIGN_LIST_LABS_DOCTOR";


export const CAMPAIGN = {
    pharmacyCreator: [CAMPAIGN_CREATE_PHARMACY],
    pharmacyEditor: [CAMPAIGN_EDIT_PHARMACY],
    pharmacyApprover : [CAMPAIGN_APPROVE_PHARMACY],
    pharmacyCloser : [CAMPAIGN_CLOSE_PHARMACY],
    
    lensCreator: [CAMPAIGN_CREATE_LENS],
    lensEditor: [CAMPAIGN_EDIT_LENS],
    lensApprover: [CAMPAIGN_APPROVE_LENS],
    lensCloser: [CAMPAIGN_CLOSE_LENS],

    labsCreator: [CAMPAIGN_CREATE_LAB_DOCTOR],
    labsEditor: [CAMPAIGN_EDIT_LAB_DOCTOR],
    labsApprover: [CAMPAIGN_APPROVE_LAB_DOCTOR],
    labsCloser: [CAMPAIGN_CLOSE_LAB_DOCTOR],

    listRoles: [CAMPAIGN_VIEW_LENS, CAMPAIGN_VIEW_PHARMACY, CAMPAIGN_VIEW_LAB_DOCTOR],
    createRoles: [CAMPAIGN_CREATE_LENS, CAMPAIGN_CREATE_LAB_DOCTOR, CAMPAIGN_CREATE_PHARMACY],
    cloneRoles: [CAMPAIGN_CREATE_PHARMACY, CAMPAIGN_CREATE_LENS, CAMPAIGN_CREATE_LAB_DOCTOR],
    editRoles: [ CAMPAIGN_EDIT_LENS, CAMPAIGN_EDIT_PHARMACY, CAMPAIGN_EDIT_LAB_DOCTOR],
    editIconRoles: [CAMPAIGN_EDIT_LENS, CAMPAIGN_EDIT_PHARMACY, CAMPAIGN_EDIT_LAB_DOCTOR, 
                  CAMPAIGN_APPROVE_LENS, CAMPAIGN_APPROVE_PHARMACY, CAMPAIGN_APPROVE_LAB_DOCTOR],
    closeRoles: [ CAMPAIGN_CLOSE_LENS, CAMPAIGN_CLOSE_PHARMACY, CAMPAIGN_CLOSE_LAB_DOCTOR],
    approveRoles: [CAMPAIGN_APPROVE_LENS, CAMPAIGN_APPROVE_PHARMACY, CAMPAIGN_APPROVE_LAB_DOCTOR],
    allRoles : [CAMPAIGN_CREATE_PHARMACY, CAMPAIGN_EDIT_PHARMACY, CAMPAIGN_APPROVE_PHARMACY, CAMPAIGN_CLOSE_PHARMACY, CAMPAIGN_VIEW_PHARMACY,
        CAMPAIGN_CREATE_LENS, CAMPAIGN_EDIT_LENS, CAMPAIGN_APPROVE_LENS, CAMPAIGN_CLOSE_LENS, CAMPAIGN_VIEW_LENS,
        CAMPAIGN_CREATE_LAB_DOCTOR, CAMPAIGN_EDIT_LAB_DOCTOR, CAMPAIGN_APPROVE_LAB_DOCTOR, CAMPAIGN_CLOSE_LAB_DOCTOR, CAMPAIGN_VIEW_LAB_DOCTOR]

}  

export const COMPLIMENTARY_CREATE = "ROLE_MRK_COMPLIMENTARY_CREATION";
export const COMPLIMENTARY_EDIT = "ROLE_MRK_COMPLIMENTARY_EDIT";
export const COMPLIMENTARY_APPROVE = "ROLE_MRK_COMPLIMENTARY_APPROVE";
export const COMPLIMENTARY_CLOSE = "ROLE_MRK_COMPLIMENTARY_CLOSE";
export const COMPLIMENTARY_VIEW = "ROLE_MRK_COMPLIMENTARY_LIST";

export const COMPLIMENTARY_ROLES = {
    pharmacyCreator: [COMPLIMENTARY_CREATE],
    pharmacyEditor: [COMPLIMENTARY_EDIT],
    pharmacyApprover : [COMPLIMENTARY_APPROVE],
    pharmacyCloser : [COMPLIMENTARY_CLOSE],

    listRoles: [COMPLIMENTARY_VIEW],
    createRoles: [COMPLIMENTARY_CREATE],
    cloneRoles: [COMPLIMENTARY_CREATE],
    editRoles: [COMPLIMENTARY_EDIT],
    editIconRoles: [COMPLIMENTARY_EDIT, COMPLIMENTARY_APPROVE],
    closeRoles: [COMPLIMENTARY_CLOSE],
    approveRoles: [COMPLIMENTARY_APPROVE],
    allRoles: [COMPLIMENTARY_CREATE, COMPLIMENTARY_EDIT, COMPLIMENTARY_APPROVE, COMPLIMENTARY_CLOSE, COMPLIMENTARY_VIEW]
}   

export const ROLE_MRK_ADD_TEMPLATES_LABS = "ROLE_MRK_ADD_TEMPLATES_LABS";
export const ROLE_MRK_EDIT_TEMPLATES_LABS = "ROLE_MRK_EDIT_TEMPLATES_LABS";
export const ROLE_MRK_LIST_VIEW_TEMPLATES_LABS = "ROLE_MRK_LIST_VIEW_TEMPLATES_LABS";
export const ROLE_MRK_APPROVE_TEMPLATES_LABS = "ROLE_MRK_APPROVE_TEMPLATES_LABS";
export const ROLE_MRK_CLOSE_TEMPLATES_LABS = "ROLE_MRK_CLOSE_TEMPLATES_LABS";

export const ROLE_MRK_ADD_POPUP_CONFIG_LABS = "ROLE_MRK_ADD_POPUP_CONFIG_LABS";
export const ROLE_MRK_EDIT_POPUP_CONFIG_LABS = "ROLE_MRK_EDIT_POPUP_CONFIG_LABS";
export const ROLE_MRK_LIST_VIEW_POPUP_CONFIG_LABS = "ROLE_MRK_LIST_VIEW_POPUP_CONFIG_LABS";
export const ROLE_MRK_APPROVE_POPUP_CONFIG_LABS = "ROLE_MRK_APPROVE_POPUP_CONFIG_LABS";
export const ROLE_MRK_CLOSE_POPUP_CONFIG_LABS = "ROLE_MRK_CLOSE_POPUP_CONFIG_LABS";

export const ROLE_MRK_ADD_TEMPLATES_PHARMA = "ROLE_MRK_ADD_TEMPLATES";
export const ROLE_MRK_LIST_TEMPLATES_PHARMA = "ROLE_MRK_LIST_TEMPLATES";
export const ROLE_MRK_APPROVE_TEMPLATES_PHARMA = "ROLE_MRK_APPROVE_TEMPLATES";

export const ROLE_MRK_ADD_POPUP_CONFIGURATION_PHARMA = "ROLE_MRK_ADD_POPUP_CONFIGURATION";
export const ROLE_MRK_LIST_POPUP_CONFIGURATION_PHARMA = "ROLE_MRK_LIST_POPUP_CONFIGURATION";
export const ROLE_MRK_APPROVE_POPUP_CONFIGURATION_PHARMA = "ROLE_MRK_APPROVE_POPUP_CONFIGURATION";

const POPUP_ROLES = {
    createLabTemplate: [ROLE_MRK_ADD_TEMPLATES_LABS],
	createPharmaTemplate: [ROLE_MRK_ADD_TEMPLATES_PHARMA],
    editLabTemplate: [ROLE_MRK_EDIT_TEMPLATES_LABS],
    viewLabTemplates: [ROLE_MRK_LIST_VIEW_TEMPLATES_LABS],
	viewPharmaTemplates: [ROLE_MRK_LIST_TEMPLATES_PHARMA],
    approveLabTemplates: [ROLE_MRK_APPROVE_TEMPLATES_LABS],
    approvePharmaTemplates: [ROLE_MRK_APPROVE_TEMPLATES_PHARMA],

    createLabConfiguration: [ROLE_MRK_ADD_POPUP_CONFIG_LABS],
    createPharmaConfiguration: [ROLE_MRK_ADD_POPUP_CONFIGURATION_PHARMA],
    editLabConfigurations: [ROLE_MRK_EDIT_POPUP_CONFIG_LABS],
    viewLabConfigurations: [ROLE_MRK_LIST_VIEW_POPUP_CONFIG_LABS],
    viewPharmaConfigurations: [ROLE_MRK_LIST_POPUP_CONFIGURATION_PHARMA],
    approveLabConfigurations: [ROLE_MRK_APPROVE_POPUP_CONFIG_LABS, ROLE_MRK_EDIT_POPUP_CONFIG_LABS],
    approvePharmaConfigurations: [ROLE_MRK_APPROVE_POPUP_CONFIGURATION_PHARMA],

    pharmaTemplateRoles: [ROLE_MRK_ADD_TEMPLATES_PHARMA, ROLE_MRK_LIST_TEMPLATES_PHARMA, ROLE_MRK_APPROVE_TEMPLATES_PHARMA],
    pharmaConfigRoles: [ROLE_MRK_ADD_POPUP_CONFIGURATION_PHARMA, ROLE_MRK_LIST_POPUP_CONFIGURATION_PHARMA, ROLE_MRK_APPROVE_POPUP_CONFIGURATION_PHARMA],
    labTemplateRoles: [ROLE_MRK_ADD_TEMPLATES_LABS, ROLE_MRK_EDIT_TEMPLATES_LABS, ROLE_MRK_LIST_VIEW_TEMPLATES_LABS, ROLE_MRK_CLOSE_TEMPLATES_LABS, ROLE_MRK_APPROVE_TEMPLATES_LABS],
    labConfigRoles: [ROLE_MRK_ADD_POPUP_CONFIG_LABS, ROLE_MRK_EDIT_POPUP_CONFIG_LABS, ROLE_MRK_LIST_VIEW_POPUP_CONFIG_LABS, ROLE_MRK_APPROVE_POPUP_CONFIG_LABS, ROLE_MRK_CLOSE_POPUP_CONFIG_LABS],
}

POPUP_ROLES['createTemplate'] = [...POPUP_ROLES.createPharmaTemplate, ...POPUP_ROLES.createLabTemplate];
POPUP_ROLES['editTemplate'] = [...POPUP_ROLES.createPharmaTemplate, ...POPUP_ROLES.editLabTemplate];
POPUP_ROLES['viewTemplates'] = [...POPUP_ROLES.viewPharmaTemplates, ...POPUP_ROLES.viewLabTemplates];
POPUP_ROLES['approveTemplates'] = [...POPUP_ROLES.approvePharmaTemplates, ...POPUP_ROLES.approveLabTemplates];

POPUP_ROLES['createConfiguration'] = [...POPUP_ROLES.createPharmaConfiguration, ...POPUP_ROLES.createLabConfiguration];
POPUP_ROLES['editConfigurations'] = [...POPUP_ROLES.createPharmaConfiguration, ...POPUP_ROLES.editLabConfigurations];
POPUP_ROLES['viewConfigurations'] = [...POPUP_ROLES.viewPharmaConfigurations, ...POPUP_ROLES.viewLabConfigurations];
POPUP_ROLES['approveConfigurations'] = [...POPUP_ROLES.approvePharmaConfigurations, ...POPUP_ROLES.approveLabTemplates];

POPUP_ROLES['templateRoles'] = [...POPUP_ROLES.pharmaTemplateRoles, ...POPUP_ROLES.labTemplateRoles];
POPUP_ROLES['configRoles'] = [...POPUP_ROLES.pharmaConfigRoles, ...POPUP_ROLES.labConfigRoles];

POPUP_ROLES.allRoles = [...POPUP_ROLES.pharmaTemplateRoles, ...POPUP_ROLES.pharmaConfigRoles, ...POPUP_ROLES.labTemplateRoles, ...POPUP_ROLES.labConfigRoles];

export { POPUP_ROLES }