# Generated by Django 4.1 on 2022-10-10 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GraniteStore',
            fields=[
                ('store_id', models.IntegerField(primary_key=True, serialize=False)),
                ('store_name', models.CharField(max_length=50)),
                ('established_year', models.IntegerField()),
                ('store_description', models.CharField(max_length=250)),
                ('contact', models.IntegerField()),
                ('website', models.CharField(max_length=150)),
                ('address', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('item_id', models.IntegerField(primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=50)),
                ('item_pattern', models.CharField(max_length=30)),
                ('item_description', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'granite_mart_item',
            },
        ),
        migrations.CreateModel(
            name='ContainsItem',
            fields=[
                ('contains_id', models.IntegerField(primary_key=True, serialize=False)),
                ('price', models.FloatField()),
                ('item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='item.item')),
                ('store_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='item.granitestore')),
            ],
            options={
                'db_table': 'granite_mart_containsitem',
            },
        ),
    ]
