create database book_store;

use  book_store;



CREATE TABLE customers (
    customer_id INT NOT NULL AUTO_INCREMENT primary key ,
    name VARCHAR(50),
    email VARCHAR(50) UNIQUE
);




CREATE TABLE orders (
    order_id INT AUTO_INCREMENT PRIMARY KEY,
    customer_id INT,
    order_date DATE,
    FOREIGN KEY (customer_id) REFERENCES customers (customer_id)
);

CREATE TABLE books (
    book_id INT AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(50) UNIQUE NOT NULL,
    price FLOAT NOT NULL
);

CREATE TABLE order_items (
    order_id INT,
    book_id INT,
    quantity INT,
    PRIMARY KEY (order_id , book_id),
    FOREIGN KEY (order_id)
        REFERENCES orders (order_id),
    FOREIGN KEY (book_id)
        REFERENCES books (book_id)
);

CREATE TABLE authors (
    author_id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(50) NOT NULL
);

CREATE TABLE book_authors (
    book_id INT,
    author_id INT,
    FOREIGN KEY (book_id)
        REFERENCES books (book_id),
    FOREIGN KEY (author_id)
        REFERENCES authors (author_id)
);

insert into customers (name,email) values 
 ("Prasduuu","Prasda123@gmail.com"),
 ("Prasad","Prasda13@gmail.com"),
 ("vamsi","vamsi.mailindia@gmail.com"),
 ("swapna","swapna123@gmail.com"),
 ("karthik","karthis34523@gmail.com"),
 ("vijay","vijayaaaa@gmail.com"),
 ("gowtham","gowwtham@gmail.com"),
 ("rakesh","rakesh123@gmail.com"),
 ("nelima","nelima369@gmail.com"),
 ("anjali","anjalivanga25@gmail.com"),
 ("bhargavi","bharagaviVelivela123@gmail.com");


insert into orders (customer_id,order_date) values (1,"2024-01-01");
insert into orders (customer_id,order_date) values (3,"2025-02-01");
insert into orders (customer_id,order_date) values (4,"2025-01-01");
insert into orders (customer_id,order_date) values (5,"2025-01-30");
insert into orders (customer_id,order_date) values (6,"2026-01-01");
insert into orders (customer_id,order_date) values (11,"2025-12-01");
insert into orders (customer_id,order_date) values (10,"2022-12-26");
insert into orders (customer_id,order_date) values (6,"2025-06-01");
insert into orders (customer_id,order_date) values (7,"2028-08-09");
insert into orders (customer_id,order_date) values (9,"2001-06-01");
insert into orders (customer_id,order_date) values (2,"2025-07-08");

insert into orders (customer_id,order_date) values (8,"2025-07-08");
insert into orders (customer_id,order_date) values (7,"2025-07-08");
insert into orders (customer_id,order_date) values (2,"2029-07-08");
insert into orders (customer_id,order_date) values (2,"2025-06-09");
insert into orders (customer_id,order_date) values (2,"2000-05-07");

insert into orders (customer_id,order_date) values (5,"2025-01-30");
insert into orders (customer_id,order_date) values (5,"2025-05-30");
insert into orders (customer_id,order_date) values (5,"2025-01-31");
insert into orders (customer_id,order_date) values (5,"2025-09-02");


insert into books (title,price) values
 ("wings of fire",295.63),
 ("To Kill a Mockingbird", 399.50),
 ("1984", 250.00),
 ("The Great Gatsby", 315.75),
 ("The Alchemist", 275.90),
 ("Pride and Prejudice", 289.99),
 ("The Catcher in the Rye", 310.45),
 ("Sapiens", 499.00),
 ("The Hobbit", 369.25),
 ("Harry Potter and the Philosopher's Stone", 450.10),
 ("The Fault in Our Stars", 330.80);


insert into order_items (order_id,book_id,quantity) values 

 (1, 2, 120),
 (2, 3, 75),
 (3, 4, 60),
 (5, 5, 30),
 (4, 5, 10),
 (6, 5, 6),
 (7, 8, 180),
 (8, 9, 220),
 (9, 10, 140),
 (10, 1, 130),
 (11,11,11),
 (12,10,34),
 (13,1,78),
 (14,8,1),
 (15, 1, 30),
 (16,4,9),
 (17, 5, 4),
 (18, 6, 13),
 (19, 7, 10),
 (20,3,333);


INSERT INTO authors (name) VALUES 
 ("APJ ABDUL KALAM"),
 ("Harper Lee"),
 ("George Orwell"),
 ("F. Scott Fitzgerald"),
 ("Paulo Coelho"),
 ("Jane Austen"),
 ("J.D. Salinger"),
 ("Yuval Noah Harari"),
 ("J.R.R. Tolkien"),
 ("J.K. Rowling"),
 ("John Green");


INSERT INTO book_authors (book_id, author_id) VALUES (1,1),(11,11),(2, 2),(3, 3),(4, 4),(5, 5),(6, 6),
(7, 7),(8, 8),(9, 9),(10, 10);

-- list all orders placed by a karthik, including product names and quantities.------

(karthikl_orders=Order_items.objects.select_related('book_id','order_id__customer').filter(order_id__customer_id__name='Karthik').values('book_id__title','quantity','order_id__customer_id__name'))


SELECT 
    customers.name, combined_table.quantity
FROM
    customers
        JOIN
    (SELECT 
        orders.customer_id, order_items.quantity
    FROM
        orders
    JOIN order_items ON orders.order_id = order_items.order_id) AS combined_table ON customers.customer_id = combined_table.customer_id
WHERE
    customers.name = 'vijay';
    
-- Get the total revenue (price × quantity) generated by each product category.
Total=Order_items.objects.aggregate(total_revenue=Sum(ExpressionWrapper(F('book_id__price') * F('quantity'),output_field=FloatField())))

SELECT 
    books.book_id, books.price * sum_table.sum AS total
FROM
    (SELECT 
        book_id, SUM(quantity) AS sum
    FROM
        order_items
    GROUP BY book_id) AS sum_table
        JOIN
    books ON sum_table.book_id = books.book_id
 
 
		-- Show users who have not placed any orders
   -- Customers.objects.exclude(id__in=Orders.objects.values('customer_id'))

SELECT 
    customers.customer_id, customers.name
FROM
    customers
        LEFT JOIN
    orders ON orders.customer_id = customers.customer_id
WHERE
    order_id IS NULL

-- List the top 5 best-selling products by total quantity sold.

-- -->top_5=Order_items.objects.select_related('book_id').values('book_id','book_id__title').annotate(quantity_sum=Sum('quantity')).order_by('-quantity_sum')[:5]



SELECT 
    books.book_id, title, quantity
FROM
    books
        JOIN
    order_items ON books.book_id = order_items.book_id
ORDER BY quantity DESC
LIMIT 5

-- Retrieve the names and emails of users who placed an order in the last 7 days.
--  a=Orders.objects.select_related('customer_id').annotate(diff=ExpressionWrapper(F('order_date')-date.today(),output_field=IntegerField())).filter(diff__lte=7)Web_World_orders


SELECT 
    customers.name, customers.email, orders.order_date
FROM
    customers
        JOIN
    orders ON orders.customer_id = customers.customer_id
WHERE
    (DATEDIFF(CURDATE(), orders.order_date) <= 7
        AND DATEDIFF(CURDATE(), orders.order_date) >= 0)

-- For each user, list their most recent order date.
-- a=Orders.objects.select_related('customer_id').annotate(latest=Max('order_date'))
	
select customers.customer_id,customers.name,orders.order_date
 from customers
        JOIN
    orders ON orders.customer_id = customers.customer_id
where
orders.order_date=(select max(orders.order_date) from orders where
 orders.customer_id=customers.customer_id);
 -- -------------------------------------------------------------------------------------------------------
 -- creating indexes
 
 direcly modifying the models.py and the using migration.
 
 create index customers_index on customers(email);
 
 show index from customers;
 
 CREATE INDEX idx_order_date ON orders (order_date);
 show index from orders;
 
 -- ----------using INSERT ------------------
 
 a=Customers.objects.create(name="Nandu",email="Nandu234@gmail.com")
 a.save 
								(or)
Customers.objects.create(name="Nandu",email="Nandu234@gmail.com")
 
 insert into customers (name,email) values ("bhaskar","Bhaskar123@gmail.com");
 insert into orders (customer_id,order_date) values (12,"2019-12-25");
 insert into books( title,price) values ("my words",222.22);
 insert into order_items (book_id,quantity) values (12,12);
 insert into authors (name) values ("Prasad sankula");
 insert into book_authors (book_id,author_id) values (12,12);
 
 -- -------------------SELECT, WHERE, ORDER BY, LIMIT---------------------------------------------------------
select price from books where price<1000;( Books.objects.filter(price__lt=200))
select * from books;  ( Books.objects.all()))
select name from customers order by name desc; (Customers.objects.values('name').order_by('-name'))
select name from customers order by name asc;(Customers.objects.values('name').order_by('name'))
select name,email from customers order by email asc; (Customers.objects.values('name','email').order_by('email'))
select book_id ,title,price from books order by price;(Books.objects.values('id','title','price').order_by('price'))
select book_id ,title,price from books order by price desc  limit 1;(Books.objects.values('id','title','price').order_by('-price')[:1])
select title from books where title like "19%";(Books.objects.values('title').filter(title__istartswith='19'))

select book_id,title from books where title like "%" order by book_id desc limit 5 ; ( Books.objects.values('id','title').filter(title__icontains='').order_by('-id')[:5])

-- ------------ UPDATE -----------------------------------------------------------
update customers set email = 'Prasda13345@gmail.com' where email = 'Prasda13@gmail.com'; 
(a=Customers.objects.get(email='maya303@gmail.com') a.save())

-- -------------DELETE --------------------------------------------------------------

delete from book_authors where author_id=2; (Book_authors.objects.get(id=2).delete() )

-- ------------------JOINs (INNER, LEFT, RIGHT, FULL) -----------------------------------
-- ------------------INNER JOIN: Get orders with customer details------------
select C.customer_id,C.name,O.order_id,O.order_date 
from customers as C join orders as O on 
C.customer_id=O.customer_id;
    ( Orders.objects.select_related('customer_id').values('customer_id_id__name','order_date') )
-- ----------- LEFT JOIN: Get all customers and their orders (if any)-----------------
select O.order_id,O.order_date ,C.customer_id,C.name
from orders as O left join customers  as C on 
C.customer_id=O.customer_id;
			( Orders.objects.prefetch_related('customer_id').values('customer_id_id__name','order_date') )

-- ------------------ RIGHT JOIN ------------------------------------------------
select B.book_id,B.title ,O.quantity 
from order_items as O right join books as B
 on B.book_id=O.book_id;
   (Django ORM does not support RIGHT JOIN natively)
-- FULL JOIN (simulated in MySQL using UNION of LEFT and RIGHT JOINs)---------------------
select C.customer_id,C.name,O.order_id,OI.quantity from
customers as C left join orders as O on C.customer_id=O.customer_id 
left join order_items as OI on O.order_id=OI.order_id
union 
select C.customer_id,C.name,O.order_id,OI.quantity from
customers as C right join orders as O on C.customer_id=O.customer_id 
right join order_items as OI on O.order_id=OI.order_id;
				

-- -- COUNT: Total number of products in each category-------------
-- -------- Count --------
select C.customer_id,C.name,Count(O.order_id) from customers as C join orders as O on O.customer_id =C.customer_id
group by C.customer_id;
( Orders.objects.select_related('customer_id').values('customer_id_id__name').annotate(count=Count('id')) )

-- SUM ---
select B.title,SUM(O.quantity) from books as B join order_items as O on B.book_id=O.book_id
group by B.title; 
(Order_items.objects.select_related('book_id').values('book_id_id__title').annotate(count=Sum('quantity')) )

-- MAX ---
select B.title,max(O.quantity) from books as B join order_items as O on B.book_id=O.book_id
group by B.title; 
 (Order_items.objects.select_related('book_id').values('book_id_id__title').annotate(max_quantity=Sum('quantity')))
-- min--
 select B.title,min(O.quantity) from books as B join order_items as O on B.book_id=O.book_id
group by B.title; 
 (Order_items.objects.select_related('book_id').values('book_id_id__title').annotate(min_quantity=Min('quantity')))
-- avg------------
 select B.title,avg(O.quantity) from books as B join order_items as O on B.book_id=O.book_id
group by B.title; 
(Order_items.objects.select_related('book_id').values('book_id__title').annotate(avg=Avg('quantity')) )


-- --------- HAVING: ---------------------------
select B.title,sum(quantity) as total from books as B right join order_items as O on B.book_id=O.book_id
group by B.title having total<100; 
 (  Order_items.objects.select_related('book_id').values('book_id__title').annotate(sum=Sum('quantity')).filter(sum__lte=200) )
  -- Subquery in WHERE clause--------------------------------
     -- ---second maximum quantity----
  select max(quantity) from order_items where quantity <(select max(quantity) from order_items);
	
 select C.customer_id,C.name,O.order_id,O.order_date from customers as C join orders as O 
 on C.customer_id=O.customer_id
 where O.order_date=(select max(orders.order_date) from orders);
	( cant by ORM using sqllite3 )
 
 -- Nested query in FROM clause: Find customers who placed orders with total amount greater than the average order amount
 
 select C.customer_id,C.name ,O.order_id,B.title,B.price*OI.quantity from  customers as C join orders as O on O.customer_id=C.customer_id
 join order_items as OI on OI.order_id=O.order_id 
 join books as B on OI.book_id=B.book_id
 where B.price*OI.quantity >(select AVG(B.price*OI.quantity) from books as B 
 join order_items as OI on B.book_id=OI.book_id);
 
 -- -- Subquery in SELECT clause: Get each product's name and its total quantity ordered
SELECT B.title ,(select sum(OI.quantity ) from order_items as OI where OI.book_id=B.book_id) 
from books as B;
-- -------------EXPLAIN--------------------------------------
 EXPLAIN select B.title,sum(quantity) as total from books as B right join order_items as O on B.book_id=O.book_id
group by B.title having total<100; 


set autocommit=0;	
start transaction;
 
  insert into customers (name,email) values ("nandu","B.nandu23@gmail.com");
   insert into customers (name,email) values ("swamy","swamyyy3@gmail.com");
    insert into customers (name,email) values ("sravani","sravs3@gmail.com");
   -- insert into customers (name,email) values ("bhaskar","Bhaskar123@gmail.com"); -- ----
     insert into customers (name,email) values ("soumya","B.soumya123@gmail.com");
 rollback;
 
 start transaction;
 
  insert into customers (name,email) values ("nandu","B.nanu23@gmail.com");
   insert into customers (name,email) values ("swamy","swamyy3@gmail.com");
    insert into customers (name,email) values ("sravani","sras3@gmail.com");
   -- insert into customers (name,email) values ("bhaskar","Bhaskar123@gmail.com"); -- ----
     insert into customers (name,email) values ("soumya","B.soumy123@gmail.com");
 commit;
 start transaction;
 
  insert into customers (name,email) values ("nandu","B.nnu23@gmail.com");
   insert into customers (name,email) values ("swamy","swayy3@gmail.com");
    insert into customers (name,email) values ("sravani","sra3@gmail.com");
    insert into customers (name,email) values ("bhaskar","Bhaskar123@gmail.com"); -- ----
     insert into customers (name,email) values ("soumya","B.sumy123@gmail.com");
 rollback;
 set autocommit=1;	
 
 
 
 -- ------------using Q -----
  a=Books.objects.filter(Q(price__lte=250 ) & Q(price__gte=100))
  a=Books.objects.filter(Q(price__lte=250 ) & Q(price__gte=100)).aggregate(sum=Sum('price'))

 
 
 
 
 