# Generated by Django 4.1 on 2022-10-12 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='Time_of_appointment',
            field=models.CharField(max_length=20),
        ),
    ]
