# Generated by Django 4.1 on 2022-10-19 05:04

from django.db import migrations, models
import salon.models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='branch_id',
            field=models.IntegerField(default=salon.models.from_100, primary_key=True, serialize=False),
        ),
    ]
