# Generated by Django 4.1 on 2022-10-11 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='Appointment_Status',
            field=models.CharField(default='booked', max_length=20),
        ),
    ]
