# Generated by Django 4.1 on 2022-09-29 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='Client_Email_id',
        ),
        migrations.RemoveField(
            model_name='client',
            name='Client_first_name',
        ),
        migrations.RemoveField(
            model_name='client',
            name='Client_last_name',
        ),
        migrations.RemoveField(
            model_name='client',
            name='Password',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='emp_email_id',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='emp_name',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='password',
        ),
    ]
