# Generated by Django 4.1 on 2022-10-12 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0002_alter_appointment_time_of_appointment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='Time_of_appointment',
            field=models.CharField(choices=[('9.00pm-10.00pm', '9.00pm-10.00pm'), ('10.00pm-11.00pm', '10.00pm-11.00pm'), ('11.00pm-12.00pm', '11.00pm-12.00pm'), ('12.00pm-1.0pam', '12.00pm-1.0pam'), ('1.00pm-2.00pm', '1.00pm-2.00pm'), ('2.00pm-3.00pm', '2.00pm-3.00pm'), ('3.00pm-4.00pm', '3.00pm-4.00pm'), ('4.00pm-5.00pm', '4.00pm-5.00pm')], max_length=20),
        ),
    ]
