# Generated by Django 4.1 on 2022-10-19 05:13

from django.db import migrations, models
import salon.models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0002_alter_branch_branch_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='emp_id',
            field=models.IntegerField(default=salon.models.from_2500, primary_key=True, serialize=False),
        ),
    ]
