# Generated by Django 4.1 on 2022-09-29 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0003_alter_transaction_trans_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='Client_id',
            new_name='user_id',
        ),
    ]
