# Generated by Django 4.1 on 2022-10-14 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0003_alter_appointment_time_of_appointment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='Time_of_appointment',
            field=models.CharField(choices=[('9.00am-10.00am', '9.00am-10.00am'), ('10.00am-11.00am', '10.00am-11.00am'), ('11.00am-12.00pm', '11.00am-12.00pm'), ('12.00pm-1.0pm', '12.00pm-1.0pm'), ('1.00pm-2.00pm', '1.00pm-2.00pm'), ('2.00pm-3.00pm', '2.00pm-3.00pm'), ('3.00pm-4.00pm', '3.00pm-4.00pm'), ('4.00pm-5.00pm', '4.00pm-5.00pm')], max_length=20),
        ),
    ]
