# Generated by Django 4.1 on 2022-10-19 05:51
#pylint:disable=C0301
#pylint:disable=C0114
#pylint:disable=C0103

from django.db import migrations, models
import salon.models


class Migration(migrations.Migration):
    """MIGRATIOPNS CLASS"""
    dependencies = [
        ('salon', '0003_alter_employee_emp_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicesprovided',
            name='service_id',
            field=models.IntegerField(default=salon.models.from_200, primary_key=True, serialize=False),
        ),
    ]
