# Generated by Django 4.1 on 2022-11-11 10:04

from django.db import migrations, models
import salon.models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0004_alter_servicesprovided_service_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='review_id',
            field=models.IntegerField(default=salon.models.from_700, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='trans_id',
            field=models.IntegerField(default=salon.models.from_15200, primary_key=True, serialize=False),
        ),
    ]
