# Generated by Django 4.1 on 2022-10-18 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0004_alter_appointment_time_of_appointment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='appointment_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
