# Generated by Django 4.1 on 2022-10-18 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0005_alter_appointment_appointment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='appointment_date',
            field=models.DateField(),
        ),
    ]
