# Generated by Django 4.1 on 2022-09-29 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0005_alter_appointment_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='emp_id',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salon.employee'),
        ),
    ]
