# Generated by Django 4.1 on 2022-09-29 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0006_remove_appointment_emp_id_alter_appointment_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='user_id',
            new_name='emp_id',
        ),
        migrations.AddField(
            model_name='appointment',
            name='Client_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='salon.client'),
        ),
    ]
