# Generated by Django 4.1 on 2022-10-18 12:50

from django.db import migrations, models
import salon.models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0007_alter_appointment_appointment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='Appointment_id',
            field=models.IntegerField(default=salon.models.from_900, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='branch',
            name='branch_id',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='employee',
            name='emp_id',
            field=models.CharField(default=salon.models.from_2500, max_length=10, primary_key=True, serialize=False),
        ),
    ]
