get http://127.0.0.1:8000/1/
Content-Type: application/json

###
get  http://127.0.0.1:8000/saneeth/
Content-Type: 

###
get http://127.0.0.1:8000/age/22/
Content-Type: application/json

###
get http://127.0.0.1:8000/data/get_data/
Content-Type: application/json

###

get http://127.0.0.1:8000/data/get_data_desc/
Content-Type: application/

###

get http://127.0.0.1:8000/data/Q_data/
Content-Type: application/json

###
get http://127.0.0.1:8000/data/field_lookups/
Content-Type: application/json

###
put http:127.0.0.1:8000/data/update_single_row/
Content-Type: application/json

{
    "id":1,
    "age":20
}
