# Generated by Django 4.1 on 2022-09-08 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('cust_id', models.AutoField(primary_key=True, serialize=False)),
                ('uname', models.CharField(max_length=20)),
                ('f_name', models.CharField(max_length=25)),
                ('l_name', models.CharField(max_length=25)),
                ('contact', models.IntegerField(default=0)),
                ('address', models.CharField(max_length=100)),
                ('pin', models.IntegerField(default=0)),
                ('mail', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('emp_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=25)),
                ('contact', models.IntegerField()),
                ('dept', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Order_list',
            fields=[
                ('ord1_id', models.IntegerField(blank=True, primary_key=True, serialize=False)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecom_app.customer')),
            ],
        ),
        migrations.CreateModel(
            name='pickup',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('ofc_name', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=100)),
                ('pincode', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Product_list',
            fields=[
                ('pro_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=25)),
                ('price', models.IntegerField()),
                ('stock', models.IntegerField()),
                ('product_type', models.CharField(max_length=25)),
                ('image', models.ImageField(default=None, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Total_delivered_items',
            fields=[
                ('delivery_id', models.AutoField(primary_key=True, serialize=False)),
                ('emp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecom_app.employees')),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecom_app.order_list')),
            ],
        ),
        migrations.CreateModel(
            name='return_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cust_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecom_app.customer')),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecom_app.order_list')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecom_app.product_list')),
            ],
        ),
        migrations.CreateModel(
            name='Emp_salary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecom_app.total_delivered_items')),
            ],
        ),
        migrations.CreateModel(
            name='delivery_person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecom_app.employees')),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecom_app.order_list')),
            ],
        ),
        migrations.CreateModel(
            name='Cust_delivered_items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cust_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecom_app.customer')),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecom_app.order_list')),
            ],
        ),
        migrations.CreateModel(
            name='cust_cart_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecom_app.order_list')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecom_app.product_list')),
            ],
        ),
    ]
