# Generated by Django 4.1 on 2022-10-03 06:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('emp_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=25)),
                ('contact', models.IntegerField()),
                ('dept', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Order_list',
            fields=[
                ('ord1_id', models.AutoField(primary_key=True, serialize=False)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='pickup',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('brand_name', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=100)),
                ('pincode', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Product_Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('image', models.ImageField(default=None, upload_to='image')),
            ],
        ),
        migrations.CreateModel(
            name='Products_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('price', models.IntegerField()),
                ('stock', models.IntegerField()),
                ('image', models.ImageField(blank=True, upload_to='image')),
                ('product_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecom_app.product_type')),
            ],
        ),
        migrations.CreateModel(
            name='Total_delivered_items',
            fields=[
                ('delivery_id', models.AutoField(primary_key=True, serialize=False)),
                ('emp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecom_app.employees')),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecom_app.order_list')),
            ],
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=20)),
                ('mail', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=10)),
                ('pickup_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecom_app.pickup')),
            ],
        ),
        migrations.CreateModel(
            name='return_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cust_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecom_app.order_list')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecom_app.products_details')),
            ],
        ),
        migrations.CreateModel(
            name='Emp_salary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecom_app.total_delivered_items')),
            ],
        ),
        migrations.CreateModel(
            name='delivery_person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecom_app.employees')),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecom_app.order_list')),
            ],
        ),
        migrations.CreateModel(
            name='customer_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact', models.IntegerField(default=0)),
                ('address', models.CharField(max_length=100)),
                ('pin', models.IntegerField(default=0)),
                ('cust_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cust_delivered_items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cust_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecom_app.order_list')),
            ],
        ),
        migrations.CreateModel(
            name='cust_cart_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecom_app.order_list')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecom_app.products_details')),
            ],
        ),
        migrations.CreateModel(
            name='cart_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecom_app.products_details')),
            ],
        ),
    ]
