# Generated by Django 4.1 on 2022-09-27 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_list',
            name='image',
            field=models.ImageField(blank=True, upload_to='image'),
        ),
        migrations.AlterField(
            model_name='products_details',
            name='image',
            field=models.ImageField(blank=True, upload_to='image'),
        ),
    ]
