# Generated by Django 4.1 on 2022-09-28 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_app', '0002_alter_product_list_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_type',
            name='image',
            field=models.ImageField(default=None, upload_to='image'),
        ),
    ]
