# Generated by Django 4.1 on 2022-09-09 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_app', '0002_customer_image_alter_product_list_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_list',
            name='ord1_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
