# Generated by Django 4.1 on 2022-09-29 05:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_app', '0003_product_type_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='cart_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecom_app.customer')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecom_app.products_details')),
            ],
        ),
        migrations.DeleteModel(
            name='Product_list',
        ),
    ]
