# Generated by Django 4.1 on 2022-09-09 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_app', '0003_alter_order_list_ord1_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pickup',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
