# Generated by Django 4.1 on 2022-09-09 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_app', '0004_alter_pickup_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pickup',
            old_name='ofc_name',
            new_name='brand_name',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='image',
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=20)),
                ('mail', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=10)),
                ('pickup_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecom_app.pickup')),
            ],
        ),
    ]
