# Generated by Django 4.1 on 2022-09-23 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_app', '0005_rename_ofc_name_pickup_brand_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='address',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='pin',
        ),
        migrations.CreateModel(
            name='customer_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact', models.IntegerField(default=0)),
                ('address', models.CharField(max_length=100)),
                ('pin', models.IntegerField(default=0)),
                ('cust_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecom_app.customer')),
            ],
        ),
    ]
