# Generated by Django 4.1.1 on 2022-09-05 10:49

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='admin_login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(default=datetime.datetime.today)),
                ('modify_at', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='courses',
            fields=[
                ('course_code', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('course_name', models.CharField(max_length=50)),
                ('total_sem', models.IntegerField(max_length=2)),
                ('created_at', models.DateTimeField()),
                ('modify_at', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='faculties',
            fields=[
                ('fac_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=40)),
                ('last_name', models.CharField(max_length=50)),
                ('faculties_dob', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('qualifications', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('male', 'male'), ('female', 'female')], max_length=50)),
                ('experience', models.IntegerField()),
                ('created_at', models.DateTimeField(default=datetime.datetime.today)),
                ('modify_at', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='students',
            fields=[
                ('admission_id', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=40)),
                ('last_name', models.CharField(max_length=50)),
                ('roll_number', models.IntegerField()),
                ('student_dob', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('semester', models.CharField(choices=[('1', '1st'), ('2', '2nd'), ('3', '3rd'), ('4', '4th'), ('5', '5th'), ('6', '6th')], max_length=10)),
                ('email', models.CharField(max_length=50, unique=True)),
                ('phone', models.CharField(max_length=50, unique=True)),
                ('gender', models.CharField(choices=[('male', 'male'), ('female', 'female')], max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(choices=[('Andhra Pradesh', 'Andhra Pradesh'), ('Arunachal Pradesh ', 'Arunachal Pradesh '), ('Assam', 'Assam'), ('Bihar', 'Bihar'), ('Chhattisgarh', 'Chhattisgarh'), ('Goa', 'Goa'), ('Gujarat', 'Gujarat'), ('Haryana', 'Haryana'), ('Himachal Pradesh', 'Himachal Pradesh'), ('Jammu and Kashmir ', 'Jammu and Kashmir '), ('Jharkhand', 'Jharkhand'), ('Karnataka', 'Karnataka'), ('Kerala', 'Kerala'), ('Madhya Pradesh', 'Madhya Pradesh'), ('Maharashtra', 'Maharashtra'), ('Manipur', 'Manipur'), ('Meghalaya', 'Meghalaya'), ('Mizoram', 'Mizoram'), ('Nagaland', 'Nagaland'), ('Odisha', 'Odisha'), ('Punjab', 'Punjab'), ('Rajasthan', 'Rajasthan'), ('Sikkim', 'Sikkim'), ('Tamil Nadu', 'Tamil Nadu'), ('Telangana', 'Telangana'), ('Tripura', 'Tripura'), ('Uttar Pradesh', 'Uttar Pradesh'), ('Uttarakhand', 'Uttarakhand'), ('West Bengal', 'West Bengal'), ('Andaman and Nicobar Islands', 'Andaman and Nicobar Islands'), ('Chandigarh', 'Chandigarh'), ('Dadra and Nagar Haveli', 'Dadra and Nagar Haveli'), ('Daman and Diu', 'Daman and Diu'), ('Lakshadweep', 'Lakshadweep'), ('National Capital Territory of Delhi', 'National Capital Territory of Delhi'), ('Puducherry', 'Puducherry')], max_length=255)),
                ('father_name', models.CharField(max_length=50)),
                ('father_occupation', models.CharField(max_length=50)),
                ('mother_name', models.CharField(max_length=50)),
                ('mother_occupation', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField()),
                ('modify_at', models.DateTimeField(null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models_task.courses')),
            ],
        ),
        migrations.CreateModel(
            name='faculties_documents',
            fields=[
                ('fac_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='models_task.faculties')),
                ('adhar_num', models.IntegerField(null=True, unique=True)),
                ('pan_number', models.IntegerField(null=True, unique=True)),
                ('birth_certificate', models.CharField(max_length=255, null=True)),
                ('created_at', models.DateTimeField()),
                ('modify_at', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='faculties_login',
            fields=[
                ('fac_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='models_task.faculties')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(default=datetime.datetime.today)),
                ('modify_at', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='student_login',
            fields=[
                ('std_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='models_task.students')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(default=datetime.datetime.today)),
                ('modify_at', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='students_documents',
            fields=[
                ('std_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='models_task.students')),
                ('adhar_num', models.IntegerField(null=True, unique=True)),
                ('birth_certificate', models.CharField(max_length=255, null=True)),
                ('created_at', models.DateTimeField()),
                ('modify_at', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='subject',
            fields=[
                ('sub_code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('sub_name', models.CharField(max_length=30)),
                ('semester', models.CharField(choices=[('1', '1st'), ('2', '2nd'), ('3', '3rd'), ('4', '4th'), ('5', '5th'), ('6', '6th')], max_length=2)),
                ('theory_marks', models.IntegerField(max_length=3)),
                ('practical_marks', models.IntegerField(max_length=3, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models_task.courses')),
            ],
        ),
        migrations.CreateModel(
            name='enter_marks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theory_marks', models.IntegerField()),
                ('practical_marks', models.IntegerField(null=True)),
                ('created_at', models.DateTimeField(default=datetime.datetime.today)),
                ('modify_at', models.DateTimeField(null=True)),
                ('std_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models_task.students')),
                ('sub_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models_task.subject')),
            ],
        ),
        migrations.CreateModel(
            name='assign_subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=datetime.datetime.today)),
                ('modify_at', models.DateTimeField(null=True)),
                ('fac_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models_task.faculties')),
                ('sub_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models_task.subject')),
            ],
        ),
    ]
