# Generated by Django 4.1.1 on 2022-09-05 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models_task', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='semester',
            field=models.CharField(choices=[('1', '1st'), ('2', '2nd'), ('3', '3rd'), ('4', '4th'), ('5', '5th'), ('6', '6th'), ('7', '7th'), ('8', '8th')], max_length=10),
        ),
        migrations.AlterField(
            model_name='subject',
            name='semester',
            field=models.CharField(choices=[('1', '1st'), ('2', '2nd'), ('3', '3rd'), ('4', '4th'), ('5', '5th'), ('6', '6th'), ('7', '7th'), ('8', '8th')], max_length=2),
        ),
    ]
