(function(d){var h=window.AmazonUIPageJS||window.P,l=h._namespace||h.attributeErrors,c=l?l("DetailPageMobileIconFarmAssets@common","DetailPageMobileIconFarm"):h;c.guardFatal?c.guardFatal(d)(c,window):c.execute(function(){d(c,window)})})(function(d,h,l){d.when("A","ready").register("get-icon-farm-page-state",function(c){return{parseJSON:function(e,b){b="iconfarm-state-"+b;var f='script[data-a-state\x3d"{"key":"'+b+'"}"]',a;try{a=c.$("#"+e).find(f).html()}catch(m){console.log(m.message)}a?e=c.$.parseJSON(a):
(c.state.parse(),e=c.state(b));return e}}});d.declare("icon-farm-mod-constants",{selector:{BUYBOX_ACCORDION:"#buybox .a-accordion",BUYBOX_ACCORDION_ACTIVE:"#buybox .a-accordion-active",iconfarm:"#iconfarmv2_feature_div .offersConsistencyEnabled"}});d.declare("iconfarm-metrics-constants",{ICON_FARM_FEATURE_DIV:"iconFarm_feature_div",ICON_FARM_PAGE_STATE_HOLDER_DIV:"iconfarm-pagestate-holder",METRIC_TYPE:{GLANCE_VIEW:"GLANCE_VIEW",ICON_CLICK:"ICON_CLICK",SECONDARY_PAGE_OPEN:"SECONDARY_PAGE_OPEN",SECONDARY_PAGE_CLOSE:"SECONDARY_PAGE_CLOSE",
FULL_RETURN_POLICY:"FULL_RETURN_POLICY",PAGE_DATA_MISSING:"PAGE_DATA_MISSING",ABSENT:"ABSENT"},REF_MARKER_PREFIX:{ICON_FARM_WIDGET:"iconfarm_wid",AMAZON_DELIVERED:"iconfarm_ad",RETURNS_POLICY:"iconfarm_rp",PAY_ON_DELIVERY:"iconfarm_pod",WARRANTY:"iconfarm_wr",EASY_CARE:"iconfarm_ec",AMAZON_PROTECT:"iconfarm_ap",NO_CONTACT_DELIVERY:"iconfarm_ncd",GENERIC_RETURN_POLICY:"iconfarm_grp",MULTIPLE_SPECIFIC_RETURN_POLICY:"iconfarm_msrp",SINGLE_SPECIFIC_RETURN_POLICY:"iconfarm_ssrp",PAYMENTS_AND_SECURITY:"iconfarm_ps",
PAY_ON_DELIVERY_ACTIVE:"iconfarm_pod_active",PAY_ON_DELIVERY_INACTIVE:"iconfarm_pod_inactive",WARRANTY_EU:"iconfarm_wr_eu",AMAZON_MANAGED_DELIVERY:"iconfarm_amd",AMAZON_DELIVERED_MENA:"iconfarm_ad_mena",SAFE_PAYMENTS:"iconfarm_sp",STATIC_RETURNS_POLICY:"iconfarm_srp",GENERIC_RETURNS_POLICY:"iconfarm_grp",SUPPORT_POLICY:"iconfarm_supp",WARRANTY360:"iconfarm_wr360"},REF_MARKER_SUFFIX:{GLANCE_VIEW:"_gv",ICON_CLICK:"_clk",SECONDARY_PAGE_OPEN:"_sp_op",SECONDARY_PAGE_CLOSE:"_sp_cl",FULL_RETURN_POLICY:"_frp",
ABSENT:"_noavail"},NEXUS_CONFIG:{NEXUS_PRODUCER_ID:"a2i-dpx",NEXUS_SCHEMA_ID:"a2i.dpx.WidgetImpressions.3"},LOGGER_CONFIG:{NEXUS_LOGGER:"nexus"}});d.when("A","iconfarm-return-policy-metric-logger","iconfarm-pay-on-delivery-metric-logger","iconfarm-default-metric-logger").register("iconfarm-icon-metric-factory",function(c,e,b,f){return{getIconMetric:function(a){switch(a){case "RETURNS_POLICY":return e;case "PAY_ON_DELIVERY":return b;default:return f}}}});d.when("A","iconfarm-metrics-constants","get-icon-farm-page-state",
"iconfarm-icon-metric-factory","ready").register("iconfarm-metricLogger",function(c,e,b,f){return{log:function(a,m,k,g){if(a&&m&&null!==k&&e.REF_MARKER_PREFIX[a]&&e.REF_MARKER_SUFFIX[m]){var d=b.parseJSON(e.ICON_FARM_PAGE_STATE_HOLDER_DIV+"-"+k,k);d?f.getIconMetric(a).log(a,m,k,c.$.extend(!0,{asin:d.asin,merchantId:d.merchantId,remoteAddress:d.remoteAddress,isInternal:d.isInternal,isRobot:d.isRobot,buyingOptionIndex:k},g)):console.warn("iconfarm state may not be available")}}}});d.when("A","ready").register("iconfarm-postmetric",
function(){return{postCountMetric:function(c){if("undefined"!==typeof c){var e=h.ue;if(e){var b=e.count(c)||0;e.count(c,b+1)}}},postTimeMetric:function(c,e){if("undefined"!==typeof c&&"undefined"!==typeof e){var b=h.ue;b&&b.count(c,e)}}}});d.when("A","ready").register("iconfarm-metric-cache",function(c){var e=[],b=function(a){if(!f(a))return!1;var b=!1;c.each(e,function(c,e){c.asin===a.asin&&c.merchantId===a.merchantId&&c.ref===a.ref&&c.loggerType===a.loggerType&&c.buyingOptionIndex===a.buyingOptionIndex&&
(b=!0)});return b},f=function(a){return a&&a.asin&&a.merchantId&&a.ref&&a.loggerType&&null!==a.buyingOptionIndex};return{isPresent:b,add:function(a){return f(a)?b(a)?!1:(e.push(a),!0):!1},reset:function(){e=[]}}});"use strict";d.when("A","iconfarm-metric-cache","iconfarm-metrics-constants","ready").register("iconfarm-Nexus-Service",function(c,e,b){return{log:function(f){if(e.add(f)){var a={};a.producerId=b.NEXUS_CONFIG.NEXUS_PRODUCER_ID;a.schemaId=b.NEXUS_CONFIG.NEXUS_SCHEMA_ID;a.refMarker=f.ref;
a.pageAsin=f.asin;a.pageType=c.capabilities?c.capabilities.mobile?c.capabilities.isAmazonApp?"DetailWebView":"DetailAW":"Detail":"";a.subPageType="IconFarm";a.server=h?h.ue_sn:"";a.merchantId=f.merchantId;a.remoteAddress=f.remoteAddress;a.isInternal=f.isInternal?1:0;a.isRobot=f.isRobot?1:0;a.buyingOptionIndex=f.buyingOptionIndex;if(f=h.ue)try{f.event&&f.event(a,b.NEXUS_CONFIG.NEXUS_PRODUCER_ID,b.NEXUS_CONFIG.NEXUS_SCHEMA_ID)}catch(d){f.count("NexusLoggerFailure",1)}}}}});d.when("A","iconfarm-Nexus-Service",
"iconfarm-metrics-constants","iconfarm-postmetric","ready").register("iconfarm-default-metric-logger",function(c,e,b,f){return{log:function(a,d,k,g){k=JSON.parse(JSON.stringify(g));e.log(c.$.extend(!0,k,{ref:b.REF_MARKER_PREFIX[a]+b.REF_MARKER_SUFFIX[d],loggerType:b.LOGGER_CONFIG.NEXUS_LOGGER}));f.postCountMetric(b.REF_MARKER_PREFIX[a]+b.REF_MARKER_SUFFIX[d])}}});d.when("A","iconfarm-Nexus-Service","iconfarm-metrics-constants","iconfarm-postmetric","get-icon-farm-page-state","ready").register("iconfarm-return-policy-metric-logger",
function(c,e,b,f,a){return{log:function(d,k,g,h){a:{if((g=a.parseJSON(b.ICON_FARM_PAGE_STATE_HOLDER_DIV+"-"+g,g))&&g.RETURNS_POLICY&&g.RETURNS_POLICY.secondaryViewData&&g.RETURNS_POLICY.secondaryViewData.glLevelReturnPolicies)switch(g.RETURNS_POLICY.secondaryViewData.glLevelReturnPolicies.length){case 0:g="GENERIC_RETURN_POLICY";break a;case 1:g="SINGLE_SPECIFIC_RETURN_POLICY";break a;default:g="MULTIPLE_SPECIFIC_RETURN_POLICY";break a}g=void 0}d=g||d;h=JSON.parse(JSON.stringify(h));e.log(c.$.extend(!0,
h,{ref:b.REF_MARKER_PREFIX[d]+b.REF_MARKER_SUFFIX[k],loggerType:b.LOGGER_CONFIG.NEXUS_LOGGER}));f.postCountMetric(b.REF_MARKER_PREFIX[d]+b.REF_MARKER_SUFFIX[k])}}});d.when("A","iconfarm-Nexus-Service","iconfarm-metrics-constants","iconfarm-postmetric","get-icon-farm-page-state","ready").register("iconfarm-pay-on-delivery-metric-logger",function(c,d,b,f,a){return{log:function(h,k,g,l){g=(g=a.parseJSON(b.ICON_FARM_PAGE_STATE_HOLDER_DIV+"-"+g,g))&&g.PAY_ON_DELIVERY&&g.PAY_ON_DELIVERY.isEligible?g.PAY_ON_DELIVERY.isEligible?
"PAY_ON_DELIVERY_ACTIVE":"PAY_ON_DELIVERY_INACTIVE":void 0;h=g||h;l=JSON.parse(JSON.stringify(l));d.log(c.$.extend(!0,l,{ref:b.REF_MARKER_PREFIX[h]+b.REF_MARKER_SUFFIX[k],loggerType:b.LOGGER_CONFIG.NEXUS_LOGGER}));f.postCountMetric(b.REF_MARKER_PREFIX[h]+b.REF_MARKER_SUFFIX[k])}}})});
/* ******** */
(function(e){var k=window.AmazonUIPageJS||window.P,g=k._namespace||k.attributeErrors,a=g?g("DetailPageMobileIconFarmAssets@desktop","DetailPageMobileIconFarm"):k;a.guardFatal?a.guardFatal(e)(a,window):a.execute(function(){e(a,window)})})(function(e,k,g){e.when("A","a-popover","icon-farm-constants","iconfarm-metricLogger","iconfarm-metrics-constants","icon-farm-web-mod-util","ready").register("icon-farm-desktop-popover",function(a,l,b,c,d,f){var h=function(b){var h=b.data("name");a.off("a:popover:beforeShow:"+
h);a.on("a:popover:beforeShow:"+h,function(a){a=f.getCurrentBuyingOptionIndex();c.log(h,d.METRIC_TYPE.ICON_CLICK,a);c.log(h,d.METRIC_TYPE.SECONDARY_PAGE_OPEN,a)});a.off("a:popover:beforeHide:"+h);a.on("a:popover:beforeHide:"+h,function(a){a=f.getCurrentBuyingOptionIndex();c.log(h,d.METRIC_TYPE.SECONDARY_PAGE_CLOSE,a)})};return{init:function(){for(var c=a.$(b.ICON_FARM_CONTAINER_CLASS),f=0;f<c.length;f++){var d=a.$(c[f]),e=d.data(b.TYPE_PARAM);if(e&&e===b.TYPE_PARAM_VALUE_CUSTOM_POP_OVER){var e=d,
g=a.$("#"+e.data(b.POPOVER_CONTENT_PARAM)),g={activate:b.POPOVER_ACTIVATION,position:b.POPOVER_POSITION,width:b.POPOVER_WIDTH,inlineContent:g.html(),name:e.data("name")};l.create(e,g);h(d)}}}}});e.when("A","get-icon-farm-page-state","icon-farm-constants","iconfarm-metricLogger","iconfarm-metrics-constants","icon-farm-web-mod-util","ready").register("icon-farm-desktop-returns-policy",function(a,e,b,c,d,f){a.declarative("returns-policy-url","click",function(a){a=f.getCurrentBuyingOptionIndex();c.log("RETURNS_POLICY",
d.METRIC_TYPE.FULL_RETURN_POLICY,a);a=e.parseJSON(b.ICON_FARM_PAGE_STATE_HOLDER_DIV+"-"+a,a);k.open(a.RETURNS_POLICY.genericReturnPolicyURL,"_blank")});a.off("a:popover:beforeShow:return-policy-secondary-view");a.on("a:popover:beforeShow:return-policy-secondary-view",function(a){a=f.getCurrentBuyingOptionIndex();c.log("RETURNS_POLICY",d.METRIC_TYPE.ICON_CLICK,a);c.log("RETURNS_POLICY",d.METRIC_TYPE.SECONDARY_PAGE_OPEN,a)});a.off("a:popover:beforeHide:return-policy-secondary-view");a.on("a:popover:beforeHide:return-policy-secondary-view",
function(a){a=f.getCurrentBuyingOptionIndex();c.log("RETURNS_POLICY",d.METRIC_TYPE.SECONDARY_PAGE_CLOSE,a)});return{init:function(){}}});e.when("A","IconFarmPageStateParserService","icon-farm-desktop-popover","icon-farm-desktop-returns-policy","iconfarm-metricLogger","icon-farm-constants","iconfarm-metrics-constants","iconfarm-metric-cache","icon-farm-web-mod-util","icon-farm-change-buying-option","atf","ready").execute(function(a,l,b,c,d,f,h,g,k,q){function m(){g.reset();a.loadImageManually(a.$(".icon-box"));
b.init();c.init();q.init();for(var f=0;f<n;f++)r(f)}var n=k.getBuyingOptionCounts(),r=function(f){var b="#icon-farm-widget-"+f,c=a.$(b);c&&c.length?d.log("ICON_FARM_WIDGET",h.METRIC_TYPE.GLANCE_VIEW,f):d.log("ICON_FARM_WIDGET",h.METRIC_TYPE.ABSENT,f);(b=a.$(b+" .icon-container"))&&b.length&&b.each(function(){d.log(a.$(this).data("name"),h.METRIC_TYPE.GLANCE_VIEW,f)})};m();a.on("a:pageUpdate",function(){var b;a:{try{if(a.$("#"+f.ICON_FARM_V2_FEATURE_DIV).find("script").length){b=f.ICON_FARM_V2_FEATURE_DIV;
break a}if(a.$("#"+f.ICON_FARM_V2_PRIMARY_FEATURE_DIV).find("script").length){b=f.ICON_FARM_V2_PRIMARY_FEATURE_DIV;break a}d.log("ICON_FARM_WIDGET",h.PAGE_DATA_MISSING,0)}catch(c){e.log(c,"ERROR","DetailPageMobileIconFarm")}b=void 0}if(b){for(var g=0;g<n;g++)if(l.isNewState(b,f.ICON_FARM_STATE+"-"+g)){var p=l.processState(b,f.ICON_FARM_STATE+"-"+g);if(a.objectIsEmpty(p))return}m()}})});e.declare("icon-farm-constants",{ICON_FARM_FEATURE_DIV:"iconFarm_feature_div",ICON_FARM_V2_FEATURE_DIV:"iconfarmv2_feature_div",
ICON_FARM_V2_PRIMARY_FEATURE_DIV:"iconFarmV2InsidePrimary_feature_div",ICON_FARM_PAGE_STATE_HOLDER_DIV:"iconfarm-pagestate-holder",ICON_FARM_CONTAINER_CLASS:".icon-container",ICON_FARM_SECONDARY_VIEW_HOLDER_ID:"#icon-farm-secondary-view-holder",ICON_FARM_STATE:"iconfarm-state",POPOVER_ACTIVATION:"onclick",POPOVER_POSITION:"triggerBottom",POPOVER_WIDTH:"533",POPOVER_CONTENT_PARAM:"iconContent",TYPE_PARAM:"type",TYPE_PARAM_VALUE:"bottom-sheet",TYPE_PARAM_VALUE_CUSTOM_POP_OVER:"custom-pop-over"});(function(){e.when("A",
"atf","ready").register("IconFarmPageStateParserService",function(a){function e(b,c){c='script[data-a-state\x3d"'+JSON.stringify({key:c})+'"]';return a.$("#"+b).find(c)}return{processState:function(b,c){var d;try{var f=e(b,c),h=f[0];d=f.html();var g=a.parseJSON(d);a.state(c,g);a.$.data(h,"state_processed",!0);return g}catch(k){console.log(k)}return a.state(c)},isNewState:function(b,c){try{return!a.$.data(e(b,c)[0],"state_processed")}catch(d){console.warn("Unable to determine state status",d)}return!1}}})})();
"use strict";e.when("A","icon-farm-mod-constants").register("icon-farm-web-mod-util",function(a,e){return{getBuyingOptionCounts:function(){if(!a.$(e.selector.iconfarm).length)return 1;var b=a.$(e.selector.BUYBOX_ACCORDION);if(0===b.length)return 1;b=b[0];if(a.$(e.selector.iconfarm).length){for(var b=b.children,c=0,d=0;d<b.length;d++)var f=a.$(b[d]).attr("data-buying-option-index"),c=Math.max(c,f);b=c}else b=0;return b+1},getCurrentBuyingOptionIndex:function(){var b=0;if(!a.$(e.selector.iconfarm).length)return 0;
var c=a.$(e.selector.BUYBOX_ACCORDION_ACTIVE);c.length&&(b=c.index());return b}}});e.when("A","icon-farm-mod-constants","icon-farm-web-mod-util","ready").register("icon-farm-change-buying-option",function(a,e,b){var c=b.getCurrentBuyingOptionIndex(),d=function(b){var d=a.$(e.selector.iconfarm);if(d.length){var k=d[0].children;k.length&&(d=k[c],b!==g&&b.selectedRow!==g&&b.selectedRow.$row!==g&&a.$(b.selectedRow.$row)!==g&&(b=a.$(b.selectedRow.$row).index(),b!==c&&(k=k[b],d.style.display="none",k.style.display=
"block",c=b)))}};return{init:function(){a.on("a:pageUpdate",d);a.on("PageRefresh:ATF",d);a.on("a:accordion:buybox-accordion:select",d)}}})});
/* ******** */
(function(c){var b=window.AmazonUIPageJS||window.P,d=b._namespace||b.attributeErrors,a=d?d("DetailPageBylineInfoAssets@core","DetailPageBylineInfo"):b;a.guardFatal?a.guardFatal(c)(a,window):a.execute(function(){c(a,window)})})(function(c,b,d){});
/* ******** */
(function(q){var c=window.AmazonUIPageJS||window.P,w=c._namespace||c.attributeErrors,u=w?w("SocialShareWidgetAUI","AmazonUI"):c;u.guardFatal?u.guardFatal(q)(u,window):u.execute(function(){q(u,window)})})(function(q,c,w){var u="function"===typeof Symbol&&"symbol"===typeof Symbol.iterator?function(c){return typeof c}:function(c){return c&&"function"===typeof Symbol&&c.constructor===Symbol&&c!==Symbol.prototype?"symbol":typeof c};q.register("SocialShareWidget",function(){return function(c){function a(d){if(f[d])return f[d].exports;
var b=f[d]={i:d,l:!1,exports:{}};return c[d].call(b.exports,b,b.exports,a),b.l=!0,b.exports}var f={};return a.m=c,a.c=f,a.d=function(d,b,g){a.o(d,b)||Object.defineProperty(d,b,{enumerable:!0,get:g})},a.r=function(a){"undefined"!=typeof Symbol&&Symbol.toStringTag&&Object.defineProperty(a,Symbol.toStringTag,{value:"Module"});Object.defineProperty(a,"__esModule",{value:!0})},a.t=function(d,b){if((1&b&&(d=a(d)),8&b)||4&b&&"object"==("undefined"===typeof d?"undefined":u(d))&&d&&d.__esModule)return d;var g=
Object.create(null);if(a.r(g),Object.defineProperty(g,"default",{enumerable:!0,value:d}),2&b&&"string"!=typeof d)for(var e in d)a.d(g,e,function(a){return d[a]}.bind(null,e));return g},a.n=function(d){var b=d&&d.__esModule?function(){return d.default}:function(){return d};return a.d(b,"a",b),b},a.o=function(a,b){return Object.prototype.hasOwnProperty.call(a,b)},a.p="",a(a.s=6)}([function(h,a,f){Object.defineProperty(a,"__esModule",{value:!0});a.isCSALoaded=a.isNativeAppShareAvailable=a.isNativeWebShareAvailable=
a.isMobileWeb=a.isMobileApp=a.isDesktop=a.isIOS=a.isAndroid=a.isIE=a.isAUILoaded=a.isUeAvailable=a.isClipboardAvailable=a.isTwisterAsin=a.context=a.Device=void 0;var d,b=f(4);!function(a){a.Android="apan";a.IOS="apin";a.MWeb="mwn";a.Other="ud"}(d=a.Device||(a.Device={}));a.context=function(){var e=d.Other;return(0,a.isMobileApp)()&&(0,a.isAndroid)()?e=d.Android:(0,a.isMobileApp)()&&(0,a.isIOS)()?e=d.IOS:(0,a.isMobileWeb)()&&(e=d.MWeb),{device:e,page:(0,a.isUeAvailable)()?c.ue_pty:"unknown",subPage:(0,
a.isUeAvailable)()?c.ue_spty||c.ue_pti:"unknown"}};a.isTwisterAsin=function(){return!!c.isTwisterPage||!!c.twisterController||g};a.isClipboardAvailable=function(){return!!navigator.clipboard&&(0,b.isFunction)(navigator.clipboard.writeText)};a.isUeAvailable=function(){return!!c.ue};a.isAUILoaded=function(){var a;return(0,b.isString)(null===(a=null===c||void 0===c?void 0:c.P)||void 0===a?void 0:a.AUI_BUILD_DATE)};a.isIE=function(){return(0,b.testUserAgent)(/MSIE|Trident/i)};a.isAndroid=function(){return(0,
b.testUserAgent)(/android.([1-9]|[L-Z])/i)&&!(0,b.testUserAgent)(/trident|Edge/i)};a.isIOS=function(){return(0,b.testUserAgent)(/OS [1-9][0-9]*(_[0-9]*)+ like Mac OS X/i)&&!(0,b.testUserAgent)(/trident|Edge/i)};a.isDesktop=function(){return!((0,a.isAndroid)()||(0,a.isIOS)()||(0,a.isMobileApp)()||(0,a.isMobileWeb)())};a.isMobileApp=function(){return/(Windowshop|Amazon|Amazon\.com)\//.test((0,b.getCookie)("amzn-app-id"))};a.isMobileWeb=function(){return 450>=c.screen.availWidth&&((0,b.testUserAgent)(/mobile|mini/i)||
(0,a.isAndroid)()||(0,a.isIOS)())};a.isNativeWebShareAvailable=function(){return c.navigator&&(0,b.isFunction)(c.navigator.share)};a.isNativeAppShareAvailable=function(a){return a&&(0,b.isFunction)(a.share)};a.isCSALoaded=function(){return(0,b.isFunction)(c.csa)};var g=!1;(0,a.isAUILoaded)()&&c.P.when("mobile-inline-twister-critical").execute(function(){g=!0});a.default={context:a.context,isTwisterAsin:a.isTwisterAsin,isClipboardAvailable:a.isClipboardAvailable,isUeAvailable:a.isUeAvailable,isAUILoaded:a.isAUILoaded,
isIE:a.isIE,isAndroid:a.isAndroid,isDesktop:a.isDesktop,isIOS:a.isIOS,isMobileApp:a.isMobileApp,isMobileWeb:a.isMobileWeb,isNativeWebShareAvailable:a.isNativeWebShareAvailable,isNativeAppShareAvailable:a.isNativeAppShareAvailable,isCSALoaded:a.isCSALoaded}},function(c,a,f){Object.defineProperty(a,"__esModule",{value:!0});a.CHANNEL_TO_REF_MAP=a.defaultShareDataAttributes=a.SHARE_TYPE_TO_CHANNEL=a.EMPTY_STRING=a.DEFAULT_CSA_REF_ID=a.CSA_DEFAULT_VALUE=a.CSA_HIT_TYPE=void 0;(function(a){a.CLICK_SUCCESS=
"click_success";a.CLICK_ERROR="click_error";a.CLICK_CANCEL="click_cancel";a.SHARE="share"})(a.CSA_HIT_TYPE||(a.CSA_HIT_TYPE={}));a.CSA_DEFAULT_VALUE={string:"unknown",number:0,boolean:2};a.DEFAULT_CSA_REF_ID="u_";a.EMPTY_STRING="";a.SHARE_TYPE_TO_CHANNEL={"com.google.android.gm.ComposeActivityGmail":"Email","com.android.email.activity.MessageCompose":"Email","com.google.android.gm.ComposeActivityGmailExternal":"Email","com.twitter.android.composer.TextFirstComposerActivity":"Twitter","com.twitter.android.composer.ComposerActivity":"Twitter",
"com.twitter.app.dm.DMActivity":"Twitter","com.android.mms.ui.ConversationComposer":"SMS","com.android.mms.ui.ComposeMessageActivity":"SMS","com.whatsapp.contact.picker.ContactPicker":"WhatsApp","com.weico.international.activity.compose.SeaComposeActivity":"Weibo","com.google.android.apps.messaging.ui.conversationlist.ShareIntentActivity":"SMS","com.facebook.composer.shareintent.ImplicitShareIntentHandlerDefaultAlias":"Facebook","com.facebook.composer.shareintent.ImplicitShareIntentHandler":"Facebook",
"com.facebook.messenger.activity.ShareLauncherActivity":"FacebookMessenger","com.whatsapp.ContactPicker":"WhatsApp","com.sina.weibo.EditActivity":"Weibo","com.sina.weibo.composerinde.ComposerDispatchActivity":"Weibo","com.pinterest.activity.create.PinItActivity":"Pinterest","jp.naver.line.android.activity.selectchat.SelectChatActivity":"Line","com.linecorp.line.share.common.view.FullPickerLaunchActivity":"Line","com.google.android.apps.docs.drive.clipboard.SendTextToClipboardActivity":"Copy","com.instagram.direct.share.handler.DirectShareHandlerActivity":"Instagram",
"com.snap.mushroom.MainActivity":"Snapchat"};a.defaultShareDataAttributes={isInternal:a.CSA_DEFAULT_VALUE.boolean,isRobot:a.CSA_DEFAULT_VALUE.boolean,userAgent:a.CSA_DEFAULT_VALUE.number,platform:a.CSA_DEFAULT_VALUE.string,ingress:a.CSA_DEFAULT_VALUE.string,asin:a.CSA_DEFAULT_VALUE.string,requestId:a.CSA_DEFAULT_VALUE.string,customerId:a.CSA_DEFAULT_VALUE.string,marketplaceId:a.CSA_DEFAULT_VALUE.string};(function(a){a.Weibo="si";a.Twitter="tw";a.SMS="sm";a.Email="em";a.Facebook="fb";a.Copy="cp";a.TencentWeibo=
"tc";a.AirDrop="ar";a.WhatsApp="wa";a.Line="li";a.Pinterest="pi";a.FacebookMessenger="fm";a.Gmail="em";a.WeChat="we";a.WeChatMoment="wm"})(a.CHANNEL_TO_REF_MAP||(a.CHANNEL_TO_REF_MAP={}))},function(h,a,f){Object.defineProperty(a,"__esModule",{value:!0});var d=f(3);h=function(){function a(g,e){this.REF_PARAM_NAME="ref_";a.isValid(g)||(g=a.getDefault());this.url=new URL(g);this._refMarker=new d.default(e)}return a.prototype.getUpdatedUrl=function(a){var e=new URL(this.raw);return e.searchParams.set(this.REF_PARAM_NAME,
a),e.toString()},Object.defineProperty(a.prototype,"raw",{get:function(){return this.url.toString()},enumerable:!1,configurable:!0}),Object.defineProperty(a.prototype,"refMarker",{get:function(){return this._refMarker},enumerable:!1,configurable:!0}),a.isValid=function(a){try{new URL(a)}catch(e){return!1}return!0},a.getDefault=function(){var a,e,d=null===(a=null===c||void 0===c?void 0:c.location)||void 0===a?void 0:a.href;if(!d)return(null===(e=null===c||void 0===c?void 0:c.ue)||void 0===e?0:e.sn)?
"https://"+c.ue.sn:"https://amazon.com";a=new URL(d);e=a.searchParams.has("psc")?"?psc\x3d1":"";return c.ue_pti?c.location.origin+"/dp/"+c.ue_pti+e:(a.search=e,a.href)},a.prototype.getReturnForChannel=function(a){a=this._refMarker.getReturnForChannel(a);return this.getUpdatedUrl(a)},a.prototype.getClickForChannel=function(a){a=this._refMarker.getClickForChannel(a);return this.getUpdatedUrl(a)},Object.defineProperty(a.prototype,"return",{get:function(){return this.getUpdatedUrl(this._refMarker.return)},
enumerable:!1,configurable:!0}),Object.defineProperty(a.prototype,"click",{get:function(){return this.getUpdatedUrl(this._refMarker.click)},enumerable:!1,configurable:!0}),a}();a.default=h},function(h,a,f){Object.defineProperty(a,"__esModule",{value:!0});var d,b=f(0);!function(a){a.RETURN="r";a.CLICK="cl"}(d||(d={}));h=function(){function a(a){if(void 0===a&&(a="ur"),this.PREFIX="cm_sw",this.id="",this.refId="",this.cxt={device:b.Device.Other,page:"",subPage:""},2>a.length)throw new TypeError("refId must be 2 or more characters long");
this.refId=a;this.cxt=(0,b.context)();this.generateUniqueId()}return Object.defineProperty(a.prototype,"return",{get:function(){return this.get(d.RETURN)},enumerable:!1,configurable:!0}),Object.defineProperty(a.prototype,"click",{get:function(){return this.get(d.CLICK)},enumerable:!1,configurable:!0}),a.prototype.getReturnForChannel=function(a){return this.PREFIX+"_"+d.RETURN+"_"+a+"_"+this.cxt.device+"_"+this.refId+"_"+this.id},a.prototype.getClickForChannel=function(a){return this.PREFIX+"_"+d.CLICK+
"_"+a+"_"+this.cxt.device+"_"+this.refId+"_"+this.id},a.prototype.generateUniqueId=function(){var a,d=null===(a=null===c||void 0===c?void 0:c.ue)||void 0===a?void 0:a.rid;return d||(d=(""+Math.random().toString(36).slice(2)+Math.random().toString(36).slice(2)).substring(0,13)),this.id=d},a.prototype.get=function(a){return this.PREFIX+"_"+a+"_"+this.cxt.device+"_"+this.refId+"_"+this.id},a}();a.default=h},function(h,a,f){Object.defineProperty(a,"__esModule",{value:!0});a.getDPXObject=a.getCookie=a.testUserAgent=
a.truncate=a.isString=a.isEmpty=a.isNumber=a.isFunction=void 0;a.isFunction=function(a){return"function"==typeof a};a.isNumber=function(a){return!isNaN(a)&&"number"==typeof a};a.isEmpty=function(a){return!a||!a.length};a.isString=function(a){return"string"==typeof a};a.truncate=function(a,b){void 0===a&&(a="");var d=Array(3).fill(".");return a.length>b?a.substring(0,b-3)+d.join(""):a};a.testUserAgent=function(a){if(!c&&!c.navigator)return!1;try{return a.test(c.navigator.userAgent)}catch(b){return!1}};
a.getCookie=function(a){var d;if(c.ue)return null===(d=c.ue.cookie)||void 0===d?void 0:d.get(a);a+="\x3d";d=document.cookie.split(";");for(var g=0;g<d.length;g++){for(var e=d[g];" "==e.charAt(0);)e=e.substring(1);if(0==e.indexOf(a))return e.substring(a.length,e.length)}return""};a.getDPXObject=function(){var a,b;return null===(b=null===(a=c.DetailPage)||void 0===a?void 0:a.StateController)||void 0===b?void 0:b.state};a.default={isFunction:a.isFunction,isNumber:a.isNumber,isEmpty:a.isEmpty,isString:a.isString,
truncate:a.truncate,testUserAgent:a.testUserAgent,getCookie:a.getCookie,getDPXObject:a.getDPXObject}},function(h,a,f){Object.defineProperty(a,"__esModule",{value:!0});var d=f(0),b=f(9);h=function(){function a(){}return a.logCounter=function(a,b){(0,d.isUeAvailable)()&&(a=this.BASE_METRIC_NAME+"."+a+(b?"."+b:""),c.ue.count(a,(c.ue.count(a)||0)+1))},a.logFatal=function(a){(0,d.isAUILoaded)()&&c.P.log(a,"FATAL",this.BASE_METRIC_NAME)},a.logRefMarker=function(a){this.logFatal(a)},a.logCSAEvent=function(a,
c){(0,d.isCSALoaded)()&&(new b.default).withCSAClickEventData(c).withShareHitType(a).logEvent()},a.startTimer=function(a){c.uet&&(0,d.isUeAvailable)()&&(c.uet("bb",this.BASE_METRIC_NAME,{wb:1}),c.uet("bb",this.BASE_METRIC_NAME+"."+a,{wb:1}))},a.stopTimer=function(a){c.uet&&(0,d.isUeAvailable)()&&(c.uet("be",this.BASE_METRIC_NAME,{wb:1}),c.uet("be",this.BASE_METRIC_NAME+"."+a,{wb:1}));c.uex&&(0,d.isUeAvailable)()&&(c.uex("ld",this.BASE_METRIC_NAME,{wb:1}),c.uex("ld",this.BASE_METRIC_NAME+"."+a,{wb:1}))},
a.BASE_METRIC_NAME="SocialShareFramework",a.getMetricName=function(a){var d;return(a=a('[data-action\x3d"ssf-share-icon"]').data())?(a=(null===(d=a.ssfShareIcon)||void 0===d?void 0:d.shareDataAttributes)||{},d=a.ingress,a=a.platform,(void 0===d?"unknown":d)+"."+(void 0===a?"unknown":a)):""},a}();a.default=h},function(c,a,f){Object.defineProperty(a,"__esModule",{value:!0});a.SocialShareCore=void 0;c=f(7);var d=f(2),b=f(8),g=f(5),e=f(10),x=f(3),k=f(0);f=f(1);a.SocialShareCore={Channels:c.default,Url:d.default,
Translations:b.default,Metrics:g.default,ShareSheet:e.default,RefMarker:x.default,Detection:k.default,Constants:f};a.default=a.SocialShareCore},function(c,a,f){Object.defineProperty(a,"__esModule",{value:!0});a.default=function(a,b){var c={email:{label:"Email",name:"email",ref:"em",shareBaseUrl:"mailto:",image:"https://m.media-amazon.com/images/G/01/share-icons/email-circular.svg",imageSquared:"https://m.media-amazon.com/images/G/01/share-icons/email-squared.svg",canOpenInPopup:!1,getSharingUrl:function(b){var c=
"?subject\x3d"+encodeURIComponent(a.emailSubject||a.title),e="\x26body\x3d"+encodeURIComponent(a.title);b=encodeURIComponent(b||a.shareUrl.getReturnForChannel(this.ref));return""+this.shareBaseUrl+c+e+" "+b}},pi:{label:"Pinterest",name:"pinterest",ref:"pi",shareBaseUrl:"https://www.pinterest.com/pin/create/button/",image:"https://m.media-amazon.com/images/G/01/share-icons/pinterest-circular.svg",imageSquared:"https://m.media-amazon.com/images/G/01/share-icons/pinterest-squared.svg",canOpenInPopup:!0,
getSharingUrl:function(b){b="?url\x3d"+encodeURIComponent(b||a.shareUrl.getReturnForChannel(this.ref));var c="\x26description\x3d"+encodeURIComponent(a.title),e="\x26media\x3d"+encodeURIComponent(a.image);return""+this.shareBaseUrl+b+c+e+"\x26method\x3dbutton"}},li:{label:"Line",name:"line",ref:"li",shareBaseUrl:"https://social-plugins.line.me/lineit/share",image:"https://m.media-amazon.com/images/G/01/share-icons/line-circular.svg",imageSquared:"https://m.media-amazon.com/images/G/01/share-icons/line-squared.svg",
canOpenInPopup:!0,getSharingUrl:function(b){return encodeURIComponent(a.title)+" "+encodeURIComponent(a.text)+" "+(""+encodeURIComponent(b||a.shareUrl.getReturnForChannel(this.ref)))}},fb:{label:"Facebook",name:"facebook",ref:"fa",shareBaseUrl:"https://www.facebook.com/dialog/share",image:"https://m.media-amazon.com/images/G/01/share-icons/facebook-circular.svg",imageSquared:"https://m.media-amazon.com/images/G/01/share-icons/facebook-squared.svg",canOpenInPopup:!0,getSharingUrl:function(b){b=["?_encoding\x3dUTF8\x26app_id\x3d465632727431967\x26display\x3dpopup",
"href\x3d"+encodeURIComponent(b||a.shareUrl.getReturnForChannel(this.ref)),"redirect_uri\x3d"+encodeURIComponent(a.shareUrl.getReturnForChannel(this.ref).replace("_r_","_s_")),"hashtag\x3d"+encodeURIComponent("#"+(a.hashtags[0]||"Amazon"))].join("\x26");return""+this.shareBaseUrl+b}},tw:{label:"Twitter",name:"twitter",ref:"tw",shareBaseUrl:"https://twitter.com/intent/tweet",image:"https://m.media-amazon.com/images/G/01/share-icons/twitter-circular.svg",imageSquared:"https://m.media-amazon.com/images/G/01/share-icons/twitter-squared.svg",
canOpenInPopup:!0,getSharingUrl:function(b){var c="?text\x3d"+encodeURIComponent(a.title);b="\x26url\x3d"+encodeURIComponent(b||a.shareUrl.getReturnForChannel(this.ref));var e="\x26hashtags\x3d"+a.hashtags.join(","),d="\x26via\x3d"+encodeURIComponent("Amazon");return""+this.shareBaseUrl+c+b+e+d}},wa:{label:"WhatsApp",name:"whatsapp",ref:"wa",shareBaseUrl:"https://api.whatsapp.com/send?text\x3d",image:"https://m.media-amazon.com/images/G/01/share-icons/whatsapp-circular.svg",imageSquared:"https://m.media-amazon.com/images/G/01/share-icons/whatsapp-squared.svg",
canOpenInPopup:!0,getSharingUrl:function(b){b="\n              "+encodeURIComponent(a.title)+"\n              "+encodeURIComponent(a.text)+"\n              "+encodeURIComponent(b||a.shareUrl.getReturnForChannel(this.ref));return""+this.shareBaseUrl+b}},sms:{label:"SMS",name:"sms",ref:"sms",shareBaseUrl:"sms:",image:"https://m.media-amazon.com/images/G/01/share-icons/sms-circular.svg",imageSquared:"https://m.media-amazon.com/images/G/01/share-icons/sms-squared.svg",canOpenInPopup:!1,getSharingUrl:function(b){b=
"\n              "+encodeURIComponent(a.title)+"\n              "+encodeURIComponent(b||a.shareUrl.getReturnForChannel(this.ref));return""+this.shareBaseUrl+b}},copy:{label:"Copy",name:"copy",ref:"cp",shareBaseUrl:"",image:"https://m.media-amazon.com/images/G/01/share-icons/link-circular.svg",imageSquared:"https://m.media-amazon.com/images/G/01/share-icons/link-squared.svg",canOpenInPopup:!1,getSharingUrl:function(){return""}}};if(null==b?0:b.length){var e={};return b.forEach(function(a){c[a]&&(e[a]=
c[a])}),e}return c}},function(c,a,f){Object.defineProperty(a,"__esModule",{value:!0});a.default={}},function(h,a,f){Object.defineProperty(a,"__esModule",{value:!0});var d=f(0),b=f(1);h=function(){function a(){var e=this;this.generateTimestampCollection=function(){var a=(new Date).getTimezoneOffset();a=e.getDateTimeByOffset(a);var b=e.getDateTimeByOffset(0);return{hitDay:a.split("T")[0],hitDatetime:a,hitDatetimeUtc:b}};this.getMarketplaceId=function(a){return"string"==typeof a?a:c.ue&&c.ue.mid?c.ue.mid:
b.CSA_DEFAULT_VALUE.string};var d=this.generateTimestampCollection();this.csaMetricsData={schemaId:a.CSA_SCHEMA_ID,userAgentId:b.CSA_DEFAULT_VALUE.number,hitDay:d.hitDay,hitDatetime:d.hitDatetime,hitDatetimeUtc:d.hitDatetimeUtc,pageType:c.ue_pty?c.ue_pty:b.CSA_DEFAULT_VALUE.string,subPageType:c.ue_spty?c.ue_spty:b.CSA_DEFAULT_VALUE.string,sessionId:c.ue&&c.ue.sid?c.ue.sid:b.CSA_DEFAULT_VALUE.string}}return a.prototype.withCSAClickEventData=function(a){var c=a.shareDataAttributes;return this.csaMetricsData.customerId=
c.customerId?c.customerId:b.CSA_DEFAULT_VALUE.string,this.csaMetricsData.httpRequestId=c.requestId?c.requestId:b.CSA_DEFAULT_VALUE.string,this.csaMetricsData.asin=c.asin?c.asin:b.CSA_DEFAULT_VALUE.string,this.csaMetricsData.ingress=c.ingress?c.ingress:b.CSA_DEFAULT_VALUE.string,this.csaMetricsData.platform=c.platform?c.platform:b.CSA_DEFAULT_VALUE.string,this.csaMetricsData.isInternal=this.getCSANumberMapping(c.isInternal),this.csaMetricsData.isRobot=this.getCSANumberMapping(c.isRobot),this.csaMetricsData.channel=
a.channel?a.channel:b.CSA_DEFAULT_VALUE.string,this.csaMetricsData.refMarker=a.refMarker?a.refMarker:b.CSA_DEFAULT_VALUE.string,this.csaMetricsData.referrerUrl=a.refererURL?a.refererURL:b.CSA_DEFAULT_VALUE.string,this.csaMetricsData.marketplaceId=this.getMarketplaceId(c.marketplaceId),this},a.prototype.withShareHitType=function(a){return this.csaMetricsData.shareHitType=a||b.CSA_DEFAULT_VALUE.string,this},a.prototype.getCSANumberMapping=function(a){return isNaN(Number(a))?2:Number(a)},a.prototype.getDateTimeByOffset=
function(b){var c=new Date;0!==b&&(b*=a.MINUTES_TO_MILISECONDS,c=c.getTime()-b,c=new Date(c));return c.toISOString().split("Z")[0].split(".")[0]},a.prototype.logEvent=function(){(0,d.isCSALoaded)()&&c.csa(a.CSAPluginId,{producerId:a.CSA_PRODUCER_ID})(a.CSA_LOG_EVENT,this.csaMetricsData)},a.MINUTES_TO_MILISECONDS=6E4,a.CSAPluginId="Events",a.CSA_PRODUCER_ID="social-share",a.CSA_LOG_EVENT="log",a.CSA_SCHEMA_ID="SocialShareCSACustomEvent.CSAShareMetrics.5",a}();a.default=h},function(h,a,f){var d=this&&
this.__assign||function(){return(d=Object.assign||function(a){for(var b,c=1,d=arguments.length;c<d;c++)for(var e in b=arguments[c])Object.prototype.hasOwnProperty.call(b,e)&&(a[e]=b[e]);return a}).apply(this,arguments)};Object.defineProperty(a,"__esModule",{value:!0});var b=f(5),g=f(0),e=f(2),x=f(4),k=f(1);h=function(){function a(a){var b=this;this.sheetOptions={title:k.EMPTY_STRING,text:k.EMPTY_STRING,shareUrl:new e.default("http://amazon.com/","ur"),lang:"en",shareDataAttributes:k.defaultShareDataAttributes,
refererURL:""};(0,g.isAUILoaded)()&&c.P.when("mash").execute(function(a){return b.mash=a});this.sheetOptions=d(d({},this.sheetOptions),a);this.shareUrl=a.shareUrl}return a.prototype.launchNativeWeb=function(){var a,d={channel:k.EMPTY_STRING,refMarker:this.shareUrl.refMarker.click,refererURL:this.sheetOptions.refererURL,shareDataAttributes:this.sheetOptions.shareDataAttributes};try{null===(a=null===c||void 0===c?void 0:c.navigator)||void 0===a||a.share({url:this.shareUrl.return,title:this.sheetOptions.title,
text:this.sheetOptions.text}).then(function(){b.default.logCSAEvent(k.CSA_HIT_TYPE.CLICK_SUCCESS,d);b.default.logCSAEvent(k.CSA_HIT_TYPE.SHARE,d)}).catch(function(){b.default.logCSAEvent(k.CSA_HIT_TYPE.CLICK_SUCCESS,d);b.default.logCSAEvent(k.CSA_HIT_TYPE.CLICK_CANCEL,d)})}catch(H){b.default.logCSAEvent(k.CSA_HIT_TYPE.CLICK_ERROR,d)}},a.prototype.launchNativeApp=function(){var a,c=this,e={channel:k.EMPTY_STRING,refMarker:this.shareUrl.refMarker.click,refererURL:this.sheetOptions.refererURL,shareDataAttributes:this.sheetOptions.shareDataAttributes},
f={messagePlain:this.getShareMessage,messagePlain160:this.getShare160Message,messagePlain140:this.getShare140Message,messageHTML:this.getShareMessage,url:this.shareUrl.return,subject:this.sheetOptions.text};null===(a=this.mash)||void 0===a||a.share(d(d({},f),{successCallback:function(){b.default.logCSAEvent(k.CSA_HIT_TYPE.CLICK_SUCCESS,e)},failCallback:function(){b.default.logCSAEvent(k.CSA_HIT_TYPE.CLICK_ERROR,e)},shareServiceSelectedCallback:function(a){if(a){a=c.getChannelForSharingType(a);var d=
c.getRefIdForChannel(a);d=c.shareUrl.refMarker.getClickForChannel(d);e.refMarker=d;e.channel=a;b.default.logCSAEvent(k.CSA_HIT_TYPE.SHARE,e)}else b.default.logCSAEvent(a?k.CSA_HIT_TYPE.SHARE:k.CSA_HIT_TYPE.CLICK_CANCEL,e)}}))},a.prototype.launch=function(a){(0,g.isNativeAppShareAvailable)(this.mash)?this.launchNativeApp():(0,g.isNativeWebShareAvailable)()?this.launchNativeWeb():(0,x.isFunction)(a)?a():b.default.logCounter("Log something that says sharing isn't available")},Object.defineProperty(a.prototype,
"getShare160Message",{get:function(){var a=this.shareUrl.return,b=a.length+2;return(0,x.truncate)(this.sheetOptions.title,160-b)+"\n    "+a},enumerable:!1,configurable:!0}),Object.defineProperty(a.prototype,"getShare140Message",{get:function(){var a=this.shareUrl.return,b=a.length+2;return(0,x.truncate)(this.sheetOptions.title,140-b)+"\n    "+a},enumerable:!1,configurable:!0}),a.prototype.getChannelForSharingType=function(a){var b=a;return(0,g.isAndroid)()&&(b=k.SHARE_TYPE_TO_CHANNEL[a]?k.SHARE_TYPE_TO_CHANNEL[a]:
k.CSA_DEFAULT_VALUE.string),b},a.prototype.getRefIdForChannel=function(a){return k.CHANNEL_TO_REF_MAP[a]?k.CHANNEL_TO_REF_MAP[a]:k.DEFAULT_CSA_REF_ID},Object.defineProperty(a.prototype,"getShareMessage",{get:function(){return this.shareUrl.return+"\n    "+this.sheetOptions.title},enumerable:!1,configurable:!0}),a}();a.default=h}])});"use strict";q.register("SocialShareWidgetConfig",function(){var h=Object.freeze({MODAL:"modal",POPOVER:"popover"}),a=Object.freeze({IOS:"ios",ANDROID:"android",VARIABLE:"variable"});
return{WIDGET_TYPE:h,WIDGET_ICON:a,excludedChannels:["sms","wa"],lineMarketplaces:["A1VC38T7YXB528"],defaultShareData:{url:"",title:"Amazon.com",text:"Check this out!",image:"",hashtags:["Amazon"],type:h.POPOVER,lang:"en",refId:"ts",channels:[],refererURL:"",t:{}},defaultWidgetData:{icon:a.VARIABLE,background:!0,width:24},shareDataAttributes:{isInternal:2,isRobot:2,userAgent:c.navigator.userAgent,platform:"DESKTOP",ingress:c.ue_pty,asin:c.ue_pti,requestId:c.ue_id,customerId:c.opts&&c.opts.customerId,
marketplaceId:c.ue_mid},iconMap:{ios:"https://m.media-amazon.com/images/G/01/share-icons/share-std.svg",android:"https://m.media-amazon.com/images/G/01/share-icons/share-android.svg"}}});"use strict";q.when("A","SocialShareWidget","SocialShareWidgetTemplating","SocialShareWidgetTiny","SocialShareWidgetConfig").register("SocialShareWidgetAUI",function(h,a,f,d,b){var g=a.SocialShareCore,e=g.Metrics,x=0,k=e.getMetricName(h.$);e.startTimer(k);e.logCounter("DPX.Desktop.ImageBlockRender");try{(function(){var a=
h.$,v=g.Detection,u=g.Translations,H=g.Channels,C=g.ShareSheet,A=g.Url,B=g.Constants,p=a(".ssf-share-trigger"),l=b.defaultShareData,z=h.extend({},b.defaultWidgetData,p.data("share")),M=function(){var a=b.iconMap;return v.isDesktop()?a.ios:z.icon===b.WIDGET_ICON.VARIABLE?v.isIOS()?a.ios:a.android:a[z.icon]},N=function(a){a.find('[class*\x3d"ssf-multi-"]').length||a.find(".ssf-share-trigger").addClass("ssf-multi-"+Math.random().toString(36).slice(2));p=a.find('[class*\x3d"ssf-multi-"]')},t=void 0,r=
void 0,m=void 0,n=void 0,D=void 0;q.when("a-sheet").execute(function(a){return t=a});q.when("a-popover").execute(function(a){return r=a});q.when("a-modal").execute(function(a){return m=a});var y=function(a){var c=a.shareData,d=c.type===b.WIDGET_TYPE.POPOVER&&r,e=c.type===b.WIDGET_TYPE.MODAL&&m;a=f.build({channels:a.channels,shareData:c,t:a.t});t?(d=a.getBottom(),p.hasClass("a-declarative")||(n=t.create({name:"ssf-share-bottom-sheet",inlineContent:d,closeType:"icon"})),t.showSheet(n)):d?(d=a.getPopover(),
p.hasClass("a-declarative")||(D=r.create(p,{name:"ssf-share-popover",position:"triggerBottom",inlineContent:d,activate:"onclick",closeButton:!1,width:160,padding:"none",popoverLabel:"Share Popup",closeButtonLabel:"Close Share Popup"}).show())):e&&(d=a.getModal(),p.hasClass("a-declarative")||m.create(p,{inlineContent:d,width:600}).show())},F=function(){D&&r.get(p).hide();n&&t.hideSheet(n)},O=function(){var a=l.shareDataAttributes.asin,b=c.DetailPage;if(!b)return!1;b=b.StateController&&b.StateController.getState().current_asin;
l.shareDataAttributes.asin="string"==typeof b?b:a;return a!==b},I=function(a){a.addClass("ssf-noclick");a.find(".a-spinner").removeClass("a-hidden");a.find("i").hide()},J=function(a){a.removeClass("ssf-noclick");a.find(".a-spinner").addClass("a-hidden");a.find("i").show()};a(document).delegate(".ssf-channel:not(.copy)","click",function(b){b.preventDefault();b.stopPropagation();e.logCounter("DPX.Desktop.ChannelClick");e.logCounter(k,"ChannelClick");var f=a(this),g=f.attr("href");b=f.data("name");var p=
f.data("ref"),m=f.data("key"),n=l,r=n.refererURL,z=n.shareDataAttributes,t=n.socialLinks;t=t===w?{}:t;n=n.shareUrl.refMarker.getClickForChannel(p);e.logCSAEvent(B.CSA_HIT_TYPE.SHARE,{channel:b,refMarker:n,refererURL:r,shareDataAttributes:z});b={csrfToken:l.csrfToken,gcmToken:l.gcmToken,url:l.shareUrl.getReturnForChannel(p),originalUrl:t.shareframework,refMarkerId:x++};I(f);d.fetch({data:b,callback:function(a){J(f);a&&(g=l.builtChannels[m].getSharingUrl(a),e.logCounter("Desktop.Tiny.Success"));if("em"===
p)c.open(g,"_self");else if(v.isDesktop()){a=screen.width;var b=screen.height,d="pi"===p?900:600,k=Math.min(d,.7*a);d=Math.min(d,.7*b);c.open(g,"_blank","toolbar\x3d0,status\x3d0,width\x3d"+k+",height\x3d"+d+",top\x3d"+(b/2-d/2)+",left\x3d"+(a/2-k/2))}else c.open(g,"_blank");F();h.trigger("ssf:event:share",l)}})});h.declarative("ssf-share-icon","click",function(d){e.logCounter("DPX.Desktop.SheetClick");e.logCounter(k,"SheetClick");N(d.$currentTarget);l=h.extend(l,d.data);l.shareDataAttributes=h.extend(b.shareDataAttributes,
d.data.shareDataAttributes);var f=h.extend(u[l.lang],l.t),g=H(l,l.channels);l.builtChannels=g;l.url=l.url.startsWith("/")?""+c.location.origin+l.url:l.url;l.shareUrl=new A(l.url,l.refId);O()&&(l.shareUrl=new A(l.url,l.refId),l.shareUrl.url.searchParams.set("psc",1));v.isDesktop()?(l.image=l.image||a("#imgTagWrapperId img").attr("src"),y({shareData:l,t:f,channels:g}),e.logCounter("DPX.Desktop.SheetOpen"),e.logCounter(k,"SheetOpen")):(p.addClass("ssf-noclick"),h.delay(function(){p.removeClass("ssf-noclick")},
1E3),(new C(l)).launch(function(){y({shareData:l,t:f,channels:g});e.logCounter("DPX.Desktop.SheetOpen");e.logCounter(k,"SheetOpen")}));e.logCSAEvent(B.CSA_HIT_TYPE.CLICK_SUCCESS,{channel:B.EMPTY_STRING,refMarker:l.shareUrl.refMarker.click,refererURL:l.refererURL,shareDataAttributes:l.shareDataAttributes});h.trigger("ssf:event:sheetOpen",l)});a(document).delegate(".ssf-copy,.ssf-channel.copy","click",function(b){e.logCounter("DPX.Desktop.ChannelClick");e.logCounter(k,"SheetClick");b.preventDefault();
var c=a(this),f=l,g=f.shareUrl;b=f.shareDataAttributes;var p=f.t;f=f.socialLinks;var m=f===w?{}:f;f=g.refMarker.getClickForChannel("cp");m=m.shareframework;var n=g.getReturnForChannel("cp");g={csrfToken:l.csrfToken,gcmToken:l.gcmToken,url:n,originalUrl:m||n,refMarkerId:x++};var t={channel:"copy",refMarker:f,shareDataAttributes:b};I(c);d.fetch({data:g,callback:function(b){J(c);navigator.clipboard.writeText(b||n).then(function(){e.logCSAEvent(B.CSA_HIT_TYPE.SHARE,t);e.logCounter("DPX.Desktop.CopySuccess");
e.logCounter(k,"CopySuccess");v.isDesktop()?function(){var a=c.find(".copy-label");a.text(p.taf_copy_url_changeover);h.delay(function(){F();a.text(p.taf_copy_name)},1E3)}():(a(".ssf-feedback").show(),F())},function(){e.logCSAEvent(B.CSA_HIT_TYPE.CLICK_ERROR,t);e.logCounter("DPX.Desktop.CopyFailure");e.logCounter(k,"CopyFailure")})}});h.trigger("ssf:event:share",l)});var G=z.width,P=a('[data-action\x3d"ssf-share-icon"]'),K=a("[id$\x3d'mageBlock_feature_div']"),Q=a("#ppd #leftCol"),E=1.4*G;!a(".ssf-background").length&&
z.background&&(E=a('\x3cdiv class\x3d"ssf-background"\x3e\x3c/div\x3e').css({width:E,height:E}),p.wrap(E));"sticky"!==Q.css("position")&&K.css("position","relative");K.prepend(P);z.icon&&p.css({height:G,width:G,backgroundImage:"url("+M()+")"});v.isIE()&&a(".ssf-share-trigger,.ssf-background").remove();h.on("a:popover:afterUpdatePosition:ssf-share-popover",function(a){a=a.popover.$popover;var b=a.position().left-48;a.find(".a-arrow-border").css({right:24,left:""});a.css({left:b})})})()}catch(L){e.logCounter("DPX.Desktop.Error"),
e.logCounter(k,"Error"),e.logFatal("Error loading Share Framework AUI: "+L.toString())}finally{e.logCounter("DPX.Desktop.Render"),e.logCounter(k,"Render"),h.trigger("ssf:event:load"),e.stopTimer(k)}});"use strict";var C=function(){return function(c,a){if(Array.isArray(c))return c;if(Symbol.iterator in Object(c)){var f=[],d=!0,b=!1,g=w;try{for(var e=c[Symbol.iterator](),h;!(d=(h=e.next()).done)&&(f.push(h.value),!a||f.length!==a);d=!0);}catch(k){b=!0,g=k}finally{try{if(!d&&e["return"])e["return"]()}finally{if(b)throw g;
}}return f}throw new TypeError("Invalid attempt to destructure non-iterable instance");}}();q.when("A","SocialShareWidgetConfig","SocialShareWidget").register("SocialShareWidgetTemplating",function(c,a,f){f=f.SocialShareCore;var d=c.$,b=f.Detection.isClipboardAvailable,g=f.Detection.isDesktop,e=a.excludedChannels;b()||e.push("copy");return{build:function(c){var f=c.channels,h=c.shareData,v=c.t,q=h.shareUrl;c=h.socialLinks;var u=c===w?{}:c;c=h.shareDataAttributes;u.email=h.mailToUri;var x='\x3cspan class\x3d"a-button ssf-copy"\x3e\n        \x3cspan class\x3d"a-button-inner"\x3e\n          \x3cinput class\x3d"a-button-input" type\x3d"submit"\x3e\n          \x3cspan class\x3d"a-button-text" aria-hidden\x3d"true"\x3e\n            \x3cdiv class\x3d"copy-label"\x3e'+
v.taf_copy_tooltip+"\x3c/div\x3e\n          \x3c/span\x3e\n        \x3c/span\x3e\n      \x3c/span\x3e";!g()&&b()&&1>d(".ssf-feedback").length&&d(document.body).append('\x3cdiv class\x3d"a-changeover ssf-feedback" style\x3d"display:none"\x3e\n          \x3cdiv class\x3d"a-changeover-inner"\x3e\n            \x3ci class\x3d"a-icon a-icon-checkmark-inverse"\x3e\x3c/i\x3e\n            \x3cstrong class\x3d"a-size-medium"\x3e'+v.taf_copy_url_changeover+"\x3c/strong\x3e\n          \x3c/div\x3e\n        \x3c/div\x3e");
var A=function(a){return{title:v["taf_"+a.name+"_tooltip"]||a.label,label:v["taf_"+a.name+"_name"]||a.label}};a.lineMarketplaces.includes(c.marketplaceId)||u.li?e.push("pi"):e.push("li");return{getModal:function(){var a="",c=!0,d=!1,g=w;try{for(var h=Object.entries(f)[Symbol.iterator](),k;!(c=(k=h.next()).done);c=!0){var t=C(k.value,2),r=t[0],m=t[1];if(!e.includes(r)&&"copy"!==r){var n=A(m),D=u[m.name]||m.getSharingUrl();a+='\x3cdiv class\x3d"ssf-channel-h"\x3e\n              \x3ca class\x3d"ssf-channel a-color-base" href\x3d"'+
D+'" title\x3d"'+n.title+'" data-ref\x3d"'+m.ref+'" data-name\x3d"'+m.name+'"\x3e\n                \x3ci role\x3d"img" aria-label\x3d"'+n.label+'" style\x3d"background-image: url('+m.image+')"\x3e\x3c/i\x3e\n              \x3c/a\x3e\n              \x3cspan\x3e'+n.label+"\x3c/span\x3e\n            \x3c/div\x3e"}}}catch(y){d=!0,g=y}finally{try{!c&&h.return&&h.return()}finally{if(d)throw g;}}c=b()?'\x3cdiv class\x3d"ssf-copy-section a-box a-padding-base a-spacing-top-large"\x3e\n              \x3cdiv class\x3d"link-section"\x3e'+
q.return+'\x3c/div\x3e\n              \x3cdiv class\x3d"copy-button"\x3e'+x+"\x3c/div\x3e\n          \x3c/div\x3e":"";return'\x3ch3 class\x3d"a-spacing-large"\x3e'+v.taf_share_bottom_sheet_title+"\x3c/h3\x3e"+('\x3cdiv class\x3d"ssf-h-icons"\x3e'+a+"\x3c/div\x3e")+c},getPopover:function(){var a="",b=!0,c=!1,d=w;try{for(var g=Object.entries(f)[Symbol.iterator](),h;!(b=(h=g.next()).done);b=!0){var k=C(h.value,2),r=k[0],m=k[1];if(!e.includes(r)){var n=A(m),q=u[m.name]||m.getSharingUrl();a+='\x3cdiv class\x3d"ssf-channel-v"\x3e\n              \x3ca class\x3d"ssf-channel '+
r+' a-color-base" href\x3d"'+q+'" title\x3d"'+n.title+'" data-ref\x3d"'+m.ref+'" data-name\x3d"'+m.name+'" data-key\x3d"'+r+'"\x3e\n                \x3cspan class\x3d"a-spinner a-spinner-small a-align-center a-hidden"\x3e\x3c/span\x3e\n                \x3ci role\x3d"img" aria-label\x3d"'+n.label+'" style\x3d"background-image: url('+m.image+')"\x3e\x3c/i\x3e\n                \x3cspan class\x3d"'+r+'-label"\x3e'+n.label+"\x3c/span\x3e\n              \x3c/a\x3e\n            \x3c/div\x3e"}}}catch(y){c=
!0,d=y}finally{try{!b&&g.return&&g.return()}finally{if(c)throw d;}}return""+a},getBottom:function(){var a="",b=!0,c=!1,d=w;try{for(var g=Object.entries(f)[Symbol.iterator](),h;!(b=(h=g.next()).done);b=!0){var k=C(h.value,2),r=k[0],m=k[1];if(!e.includes(r)){var n=A(m),q=u[m.name]||m.getSharingUrl();a+='\x3cdiv class\x3d"ssf-channel-b a-padding-base"\x3e\n              \x3ca class\x3d"ssf-channel '+r+' a-color-base" href\x3d"'+q+'" title\x3d"'+n.title+'" data-ref\x3d"'+m.ref+'" data-name\x3d"'+m.name+
'"\x3e\n                \x3ci role\x3d"img" aria-label\x3d"'+n.label+'" style\x3d"background-image: url('+m.image+')"\x3e\x3c/i\x3e\n                \x3cspan class\x3d"a-size-base-plus"\x3e'+n.label+"\x3c/span\x3e\n              \x3c/a\x3e\n            \x3c/div\x3e"}}}catch(y){c=!0,d=y}finally{try{!b&&g.return&&g.return()}finally{if(c)throw d;}}return'\x3cdiv class\x3d"a-padding-base ssf-header"\x3e\n          \x3ch4\x3e'+v.taf_share_bottom_sheet_title+'\x3c/h4\x3e\n        \x3c/div\x3e\x3cdiv class\x3d"ssf-scroll"\x3e'+
a+"\x3c/div\x3e"}}}}});"use strict";q.when("jQuery","SocialShareWidget").register("SocialShareWidgetTiny",function(c,a){var f=a.SocialShareCore.Metrics;return{fetch:function(a){var b=a.data,d=a.callback;b.csrfToken&&b.gcmToken&&b.url?c.ajax("/conversations/sharetinyurl",{type:"POST",contentType:"application/json;charset\x3dUTF-8",data:JSON.stringify(b),success:function(a){f.logCounter("Desktop.Tiny.Response");d(a.data&&a.data.url)},error:function(){f.logCounter("Desktop.Tiny.Error");d()}}):(f.logCounter("Tiny.Unavailable"),
d())}}})});
/* ******** */
