# Generated by Django 4.1.1 on 2022-09-09 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabs_models', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin_users',
            name='m_id',
            field=models.CharField(default=10, max_length=10),
        ),
    ]
