# Generated by Django 4.1.1 on 2022-09-09 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabs_models', '0002_admin_users_m_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin_users',
            name='m_id',
            field=models.CharField(max_length=10),
        ),
    ]
