# Generated by Django 4.1.1 on 2022-10-06 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0015_alter_transactiontable_transaction_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactiontable',
            name='transaction_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
