spring.application.name=Roles-backend
spring.datasource.url=jdbc:mysql://localhost:3306/role_management
spring.datasource.username=root
spring.datasource.password=Akash@123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

twilio.accountSid=AC2a9522000738a561a18fcb7dbe670feb
twilio.authToken=1c4a5730b5253220f3341cb536d970d2
twilio.phoneNumber=+19314290452
