# Generated by Django 4.1 on 2022-09-12 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('account_type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerTable',
            fields=[
                ('customer_id', models.IntegerField(primary_key=True, serialize=False)),
                ('customer_name', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=100)),
                ('customer_email', models.CharField(max_length=50)),
                ('customer_password', models.IntegerField()),
                ('customer_address', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='EmployesTable',
            fields=[
                ('employee_id', models.IntegerField(primary_key=True, serialize=False)),
                ('employee_name', models.CharField(max_length=50)),
                ('emp_email', models.CharField(max_length=50)),
                ('emp_password', models.IntegerField()),
                ('employee_address', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='LoanDetails',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('loan_amount', models.CharField(max_length=100)),
                ('date_of_approval', models.DateField()),
                ('loan_type', models.CharField(max_length=100)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modelsapp.customertable')),
            ],
        ),
        migrations.CreateModel(
            name='DebitCard',
            fields=[
                ('debit_id', models.IntegerField(primary_key=True, serialize=False)),
                ('card_number', models.IntegerField()),
                ('expire_date', models.DateField()),
                ('cvv', models.IntegerField()),
                ('account_number', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='modelsapp.accounttable')),
            ],
        ),
        migrations.CreateModel(
            name='CreditCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credit_id', models.IntegerField()),
                ('card_number', models.IntegerField()),
                ('expire_date', models.DateField()),
                ('cvv', models.IntegerField()),
                ('card_amount', models.IntegerField()),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='modelsapp.customertable')),
            ],
        ),
        migrations.CreateModel(
            name='BeneficiaryDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('benf_id', models.IntegerField()),
                ('benf_name', models.CharField(max_length=100)),
                ('benf_number', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modelsapp.customertable')),
            ],
        ),
        migrations.AddField(
            model_name='accounttable',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modelsapp.customertable'),
        ),
    ]
