# Generated by Django 4.1 on 2022-09-12 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modelsapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionTable',
            fields=[
                ('transaction_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('transaction_amount', models.IntegerField()),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='modelsapp.customertable')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='modelsapp.customertable')),
            ],
        ),
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('log_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date_of_transaction', models.DateField(auto_now=True)),
                ('transaction_time', models.TimeField(auto_now=True)),
                ('transaction_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='modelsapp.transactiontable')),
            ],
        ),
    ]
