# Generated by Django 4.1.1 on 2022-09-15 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelsapp', '0002_transactiontable_logs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditcard',
            name='expire_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
