# Generated by Django 4.0.5 on 2022-09-26 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='client_contract_details',
            fields=[
                ('contract_id', models.AutoField(primary_key=True, serialize=False)),
                ('project_deadline', models.DateTimeField()),
                ('project_status', models.CharField(choices=[('P', 'Pending'), ('C', 'Completed')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='client_details',
            fields=[
                ('client_id', models.AutoField(primary_key=True, serialize=False)),
                ('client_name', models.CharField(max_length=100)),
                ('client_country', models.CharField(max_length=20)),
                ('phone_number', models.CharField(max_length=12)),
                ('description', models.TextField(default='', max_length=100)),
                ('email_id', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='client_jobs',
            fields=[
                ('job_id', models.AutoField(primary_key=True, serialize=False)),
                ('project_title', models.CharField(max_length=100)),
                ('total_pay', models.IntegerField()),
                ('experience_level', models.CharField(choices=[('E', 'Expert'), ('I', 'Intermediate'), ('F', 'Fresher')], max_length=1)),
                ('skills_requried', models.CharField(max_length=100)),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='freelance_app.client_details')),
            ],
        ),
        migrations.CreateModel(
            name='freelancer_details',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email_id', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=12)),
                ('password', models.CharField(max_length=25)),
                ('country', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='freelancer_proposals',
            fields=[
                ('proprosal_id', models.AutoField(primary_key=True, serialize=False)),
                ('skills', models.TextField(max_length=100)),
                ('cover_letter', models.TextField(max_length=100)),
                ('requried_pay', models.IntegerField()),
                ('freelancer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='freelance_app.freelancer_details')),
                ('job_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='freelance_app.client_jobs')),
            ],
        ),
        migrations.CreateModel(
            name='freelancer_payment_details',
            fields=[
                ('payment_id', models.AutoField(primary_key=True, serialize=False)),
                ('Tax', models.IntegerField()),
                ('earned', models.IntegerField()),
                ('contract_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='freelance_app.client_contract_details')),
                ('freelancer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='freelance_app.freelancer_details')),
            ],
        ),
        migrations.CreateModel(
            name='freelancer_feedback_form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.CharField(choices=[('E', 'Excellent'), ('G', 'Good'), ('B', 'BAD')], max_length=1)),
                ('feedback', models.TextField(max_length=100)),
                ('contract_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='freelance_app.client_contract_details')),
            ],
        ),
        migrations.CreateModel(
            name='client_feedback_form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.CharField(choices=[('E', 'Excellent'), ('G', 'Good'), ('B', 'BAD')], max_length=1)),
                ('feedback', models.TextField(max_length=100)),
                ('contract_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='freelance_app.client_contract_details')),
            ],
        ),
        migrations.CreateModel(
            name='client_fee_record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('handling_fee', models.IntegerField()),
                ('tax', models.IntegerField()),
                ('total_payment', models.IntegerField()),
                ('contract_id', models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='freelance_app.client_contract_details')),
            ],
        ),
        migrations.AddField(
            model_name='client_contract_details',
            name='client_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='freelance_app.client_details'),
        ),
        migrations.AddField(
            model_name='client_contract_details',
            name='emp_proposal_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='freelance_app.freelancer_proposals'),
        ),
    ]
