# Generated by Django 4.0.5 on 2022-09-26 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelance_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client_jobs',
            name='description',
            field=models.TextField(default='', max_length=100),
        ),
    ]
