# Generated by Django 4.0.5 on 2022-09-09 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('freelance_app', '0002_client_fee_record_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client_contract_details',
            name='emp_proposal_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='freelance_app.freelancer_proposals'),
        ),
        migrations.AlterField(
            model_name='client_fee_record',
            name='contract_id',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='freelance_app.client_contract_details'),
        ),
        migrations.AlterField(
            model_name='client_feedback_form',
            name='contract_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='freelance_app.client_contract_details'),
        ),
        migrations.AlterField(
            model_name='freelancer_feedback_form',
            name='contract_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='freelance_app.client_contract_details'),
        ),
    ]
