# Generated by Django 4.0.5 on 2022-09-27 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('freelance_app', '0002_client_jobs_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client_details',
            name='description',
        ),
    ]
