# Generated by Django 4.0.5 on 2022-09-09 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('freelance_app', '0003_alter_client_contract_details_emp_proposal_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freelancer_proposals',
            name='freelancer_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='freelance_app.freelancer_details'),
        ),
    ]
