# Generated by Django 4.0.5 on 2022-09-09 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('freelance_app', '0004_alter_freelancer_proposals_freelancer_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freelancer_proposals',
            name='freelancer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='freelance_app.freelancer_details'),
        ),
    ]
