# Generated by Django 4.0.5 on 2022-09-29 09:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelance_app', '0004_alter_client_jobs_experience_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client_contract_details',
            name='project_deadline',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 29, 9, 12, 46, 864521)),
        ),
        migrations.AlterField(
            model_name='client_contract_details',
            name='project_status',
            field=models.CharField(choices=[('P', 'Pending'), ('C', 'Completed')], default='pending', max_length=1),
        ),
    ]
