# Generated by Django 4.0.5 on 2022-09-09 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('freelance_app', '0006_alter_freelancer_proposals_job_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freelancer_proposals',
            name='job_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='freelance_app.client_jobs'),
        ),
    ]
