# Generated by Django 4.0.5 on 2022-09-30 04:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelance_app', '0006_alter_client_contract_details_project_deadline_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client_contract_details',
            name='contract_amount',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='client_contract_details',
            name='project_deadline',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 30, 4, 12, 31, 737876)),
        ),
    ]
