# Generated by Django 4.0.5 on 2022-09-09 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('freelance_app', '0007_alter_freelancer_proposals_job_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freelancer_payment_details',
            name='contract_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='freelance_app.client_contract_details'),
        ),
    ]
