# Generated by Django 4.0.5 on 2022-09-12 05:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('freelance_app', '0008_alter_freelancer_payment_details_contract_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='client_job_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decription', models.TextField()),
                ('job_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='freelance_app.client_jobs')),
            ],
        ),
        migrations.AlterField(
            model_name='freelancer_proposals',
            name='job_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='freelance_app.client_job_details'),
        ),
    ]
