# Generated by Django 4.0.5 on 2022-09-30 07:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelance_app', '0009_client_contract_details_contract_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client_contract_details',
            name='project_deadline',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 30, 7, 7, 57, 948131)),
        ),
        migrations.AlterField(
            model_name='client_fee_record',
            name='handling_fee',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='client_fee_record',
            name='tax',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='client_fee_record',
            name='total_payment',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='freelancer_payment_details',
            name='Tax',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='freelancer_payment_details',
            name='earned',
            field=models.FloatField(),
        ),
    ]
