# Generated by Django 4.0.5 on 2022-09-12 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('freelance_app', '0009_client_job_details_alter_freelancer_proposals_job_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client_fee_record',
            name='contract_id',
        ),
        migrations.RemoveField(
            model_name='client_feedback_form',
            name='contract_id',
        ),
        migrations.RemoveField(
            model_name='client_job_details',
            name='job_id',
        ),
        migrations.RemoveField(
            model_name='client_jobs',
            name='client_id',
        ),
        migrations.RemoveField(
            model_name='freelancer_feedback_form',
            name='contract_id',
        ),
        migrations.RemoveField(
            model_name='freelancer_payment_details',
            name='contract_id',
        ),
        migrations.RemoveField(
            model_name='freelancer_payment_details',
            name='freelancer_id',
        ),
        migrations.RemoveField(
            model_name='freelancer_proposals',
            name='freelancer_id',
        ),
        migrations.RemoveField(
            model_name='freelancer_proposals',
            name='job_id',
        ),
        migrations.DeleteModel(
            name='client_contract_details',
        ),
        migrations.DeleteModel(
            name='client_details',
        ),
        migrations.DeleteModel(
            name='client_fee_record',
        ),
        migrations.DeleteModel(
            name='client_feedback_form',
        ),
        migrations.DeleteModel(
            name='client_job_details',
        ),
        migrations.DeleteModel(
            name='client_jobs',
        ),
        migrations.DeleteModel(
            name='freelancer_details',
        ),
        migrations.DeleteModel(
            name='freelancer_feedback_form',
        ),
        migrations.DeleteModel(
            name='freelancer_payment_details',
        ),
        migrations.DeleteModel(
            name='freelancer_proposals',
        ),
    ]
