# Generated by Django 4.0.5 on 2022-10-04 05:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelance_app', '0010_alter_client_contract_details_project_deadline_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='freelancer_proposals',
            name='proprosal_status',
            field=models.CharField(default='rejected', max_length=20),
        ),
        migrations.AlterField(
            model_name='client_contract_details',
            name='project_deadline',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 4, 5, 37, 30, 412546)),
        ),
    ]
