# Generated by Django 4.0.5 on 2022-09-12 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelance_app', '0011_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client_job_details',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
