# Generated by Django 4.0.5 on 2022-09-12 06:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('freelance_app', '0012_alter_client_job_details_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freelancer_proposals',
            name='job_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='freelance_app.client_job_details'),
        ),
    ]
