# Generated by Django 4.0.5 on 2022-10-11 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelance_app', '0012_usertoken_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client_contract_details',
            name='project_deadline',
            field=models.DateField(auto_now_add=True),
        ),
    ]
