# Generated by Django 4.0.5 on 2022-10-11 05:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelance_app', '0013_alter_client_contract_details_project_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client_contract_details',
            name='project_deadline',
            field=models.DateField(default=datetime.date(2022, 10, 11)),
        ),
    ]
