# Generated by Django 4.0.5 on 2022-09-12 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('freelance_app', '0014_alter_client_contract_details_emp_proposal_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='freelancer_details',
            old_name='id',
            new_name='freelancer_id',
        ),
    ]
