# Generated by Django 4.0.5 on 2022-09-13 06:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelance_app', '0016_rename_freelancer_id_freelancer_details_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client_details',
            name='client_country',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='client_details',
            name='email_id',
            field=models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator]),
        ),
        migrations.AlterField(
            model_name='freelancer_details',
            name='country',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='freelancer_details',
            name='email_id',
            field=models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator]),
        ),
    ]
