# Generated by Django 4.0.5 on 2022-10-13 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelance_app', '0016_alter_client_feedback_form_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client_feedback_form',
            name='feedback',
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='freelancer_feedback_form',
            name='feedback',
            field=models.TextField(max_length=100, null=True),
        ),
    ]
