# Generated by Django 4.0.5 on 2022-10-14 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelance_app', '0017_alter_client_feedback_form_feedback_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freelancer_proposals',
            name='proprosal_status',
            field=models.CharField(default='pending for approval', max_length=20),
        ),
    ]
