# Generated by Django 4.0.5 on 2022-09-13 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelance_app', '0017_alter_client_details_client_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client_jobs',
            name='description',
            field=models.TextField(default='description', max_length=3000),
        ),
    ]
