# Generated by Django 4.0.5 on 2022-09-13 07:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelance_app', '0018_client_jobs_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client_details',
            name='email_id',
            field=models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator('not a vaild email ')]),
        ),
        migrations.AlterField(
            model_name='freelancer_details',
            name='email_id',
            field=models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator('not a vaild email ')]),
        ),
    ]
