# Generated by Django 4.0.5 on 2022-10-26 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelance_app', '0019_alter_client_jobs_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='client_jobs',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
