# Generated by Django 4.0.5 on 2022-09-13 07:37

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('freelance_app', '0019_alter_client_details_email_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freelancer_details',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None),
        ),
    ]
