# Generated by Django 4.0.5 on 2022-09-26 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelance_app', '0021_remove_client_jobs_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client_jobs',
            name='description',
            field=models.TextField(default='', max_length=100),
        ),
    ]
