# Generated by Django 4.0.5 on 2022-09-26 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('freelance_app', '0022_client_jobs_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client_jobs',
            name='description',
        ),
    ]
