spring.application.name=restaurant
server.port=8089
spring.thymeleaf.cache=false
#spring.security.user.name=owner
#spring.security.user.password=owner@123
spring.datasource.url=jdbc:mysql://localhost:3306/example
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver