# Generated by Django 4.1.1 on 2022-09-27 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('couponcode', models.CharField(max_length=24)),
                ('discount', models.DecimalField(decimal_places=2, max_digits=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('valid_till', models.DateTimeField()),
            ],
            options={
                'db_table': 'coupons',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_name', models.CharField(max_length=24)),
                ('image', models.TextField()),
                ('description', models.TextField()),
            ],
            options={
                'db_table': 'places',
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_type', models.CharField(max_length=24)),
                ('model', models.CharField(max_length=24)),
                ('vehicle_number', models.CharField(max_length=24, unique=True)),
                ('isAC', models.BooleanField(default=False)),
                ('total_seats', models.IntegerField()),
            ],
            options={
                'db_table': 'vehicles',
            },
        ),
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tour_name', models.CharField(max_length=50)),
                ('tour_from', models.CharField(max_length=50)),
                ('tour_to', models.CharField(max_length=50)),
                ('tour_type', models.CharField(max_length=50)),
                ('nights', models.IntegerField()),
                ('days', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('image', models.TextField()),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('coupons', models.ManyToManyField(to='toursapp.coupon')),
                ('places', models.ManyToManyField(to='toursapp.place')),
                ('vehicleid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='toursapp.vehicle')),
            ],
            options={
                'db_table': 'tours',
            },
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_name', models.CharField(max_length=30)),
                ('package_type', models.CharField(max_length=30)),
                ('image', models.TextField()),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tours', models.ManyToManyField(to='toursapp.tour')),
            ],
            options={
                'db_table': 'packages',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55)),
                ('mobile', models.BigIntegerField()),
                ('address', models.TextField()),
                ('salary', models.DecimalField(decimal_places=2, max_digits=15)),
                ('vehicleid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='toursapp.vehicle')),
            ],
            options={
                'db_table': 'employees',
            },
        ),
    ]
