# Generated by Django 4.1.1 on 2022-09-28 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toursapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
