# Generated by Django 4.1.1 on 2022-09-28 03:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('toursapp', '0002_coupon_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='vehicleid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='toursapp.vehicle'),
        ),
    ]
