# Generated by Django 4.1.1 on 2022-09-29 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toursapp', '0003_alter_employee_vehicleid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('mobile', models.BigIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('status', models.BooleanField(default=True)),
                ('subject', models.TextField()),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'enquiry',
                'ordering': ['created_at'],
            },
        ),
    ]
