# Generated by Django 4.1.1 on 2022-09-29 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toursapp', '0004_enquiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='discount',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
