# Generated by Django 4.1.1 on 2022-10-04 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toursapp', '0005_alter_coupon_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='coupons',
            field=models.ManyToManyField(null=True, to='toursapp.coupon'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='places',
            field=models.ManyToManyField(null=True, to='toursapp.place'),
        ),
    ]
