# Generated by Django 4.1.1 on 2022-10-04 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toursapp', '0006_alter_tour_coupons_alter_tour_places'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='coupons',
            field=models.ManyToManyField(blank=True, null=True, to='toursapp.coupon'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='places',
            field=models.ManyToManyField(blank=True, null=True, to='toursapp.place'),
        ),
    ]
