# Generated by Django 4.1.1 on 2022-10-05 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toursapp', '0008_alter_tour_coupons_alter_tour_places'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='start_date',
            field=models.DateTimeField(null=True),
        ),
    ]
