# Generated by Django 4.1.1 on 2022-10-07 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('toursapp', '0009_tour_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='vehicleid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='toursapp.vehicle'),
        ),
    ]
