# Generated by Django 4.1.1 on 2022-10-09 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toursapp', '0010_alter_employee_vehicleid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='package_type',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
