# Generated by Django 4.1.1 on 2022-10-09 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toursapp', '0011_alter_package_package_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='package_type',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
