# Generated by Django 4.1.1 on 2022-10-09 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toursapp', '0012_alter_package_package_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='vehicleid',
        ),
        migrations.AddField(
            model_name='employee',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='tour',
            name='guides',
            field=models.ManyToManyField(null=True, to='toursapp.employee'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='coupons',
            field=models.ManyToManyField(to='toursapp.coupon'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='places',
            field=models.ManyToManyField(to='toursapp.place'),
        ),
    ]
