# Generated by Django 4.1.1 on 2022-10-09 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toursapp', '0013_remove_employee_vehicleid_employee_email_tour_guides_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='guides',
            field=models.ManyToManyField(to='toursapp.employee'),
        ),
    ]
