# Generated by Django 4.1.1 on 2022-10-09 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toursapp', '0014_alter_tour_guides'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='image',
            field=models.TextField(null=True),
        ),
    ]
