# Generated by Django 4.1.1 on 2022-10-09 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toursapp', '0015_employee_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='image',
            field=models.TextField(default='https://res.cloudinary.com/dklq1vuce/image/upload/v1665298218/employee_profile_pic_cl6agt.jpg'),
        ),
    ]
