# Generated by Django 4.1.1 on 2022-09-26 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employestable',
            name='employee_id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
