# Generated by Django 4.1.1 on 2022-09-27 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0002_alter_employestable_employee_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='loandetails',
            name='monthly_EMI',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loandetails',
            name='tenure',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
