# Generated by Django 4.1.1 on 2022-09-29 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0003_loandetails_monthly_emi_loandetails_tenure'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerToken',
            fields=[
                ('token', models.BigAutoField(primary_key=True, serialize=False)),
                ('customer_id', models.IntegerField()),
                ('token_key', models.CharField(max_length=200)),
                ('expiry_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeToken',
            fields=[
                ('token', models.BigAutoField(primary_key=True, serialize=False)),
                ('emp_id', models.IntegerField()),
                ('token_key', models.CharField(max_length=200)),
                ('expiry_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
