# Generated by Django 4.1.1 on 2022-09-30 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0004_customertoken_employeetoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customertable',
            name='customer_id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
