# Generated by Django 4.1.1 on 2022-09-30 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0005_alter_customertable_customer_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounttable',
            name='account_number',
            field=models.BigIntegerField(),
        ),
    ]
