# Generated by Django 4.1.1 on 2022-10-06 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0006_alter_accounttable_account_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logs',
            name='date_of_transaction',
        ),
        migrations.AlterField(
            model_name='logs',
            name='transaction_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
