# Generated by Django 4.1.1 on 2022-10-06 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0007_remove_logs_date_of_transaction_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='logs',
            old_name='transaction_id',
            new_name='transaction',
        ),
    ]
