# Generated by Django 4.1.1 on 2022-10-06 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0009_alter_transactiontable_transaction_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactiontable',
            name='receiver_status',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='transactiontable',
            name='sender_status',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
