# Generated by Django 4.1.1 on 2022-10-06 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0011_remove_logs_transaction_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactiontable',
            name='transaction_time',
            field=models.DateTimeField(null=True),
        )
    ]
