# Generated by Django 4.1.1 on 2022-10-06 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0012_alter_transactiontable_transaction_time_delete_logs'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Logs',
        ),
    ]
