# Generated by Django 4.1.1 on 2022-10-06 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0013_delete_logs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactiontable',
            name='transaction_time',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
