# Generated by Django 4.1.1 on 2022-10-06 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0014_alter_transactiontable_transaction_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactiontable',
            name='transaction_time',
            field=models.DateTimeField(null=True),
        ),
    ]
