# Generated by Django 4.1.1 on 2022-10-10 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0016_alter_transactiontable_transaction_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debitcard',
            name='expire_date',
            field=models.CharField(max_length=100),
        ),
    ]
