# Generated by Django 4.1.1 on 2022-10-10 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0017_alter_debitcard_expire_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debitcard',
            name='card_number',
            field=models.BigIntegerField(),
        ),
    ]
