# Generated by Django 4.1.1 on 2022-10-10 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0018_alter_debitcard_card_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debitcard',
            name='card_number',
            field=models.CharField(max_length=100),
        ),
    ]
