# Generated by Django 4.1.1 on 2022-10-11 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0019_alter_debitcard_card_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerImageTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_image', models.CharField(max_length=500)),
                ('cover_image', models.CharField(max_length=500)),
                ('user_id', models.IntegerField()),
            ],
        ),
    ]
