# Generated by Django 4.1.1 on 2022-10-12 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0021_alter_creditcard_card_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creditcard',
            name='card_numb',
        ),
        migrations.AddField(
            model_name='creditcard',
            name='card_number',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
