# Generated by Django 4.1.1 on 2022-10-13 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0023_customerrequests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerrequests',
            name='request_status',
            field=models.BooleanField(),
        ),
    ]
