# Generated by Django 4.1.1 on 2022-10-14 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0026_alter_debitcard_cvv'),
    ]

    operations = [
        migrations.AddField(
            model_name='debitcard',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
