# Generated by Django 4.1.1 on 2022-10-18 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0027_remove_debitcard_debit_id_debitcard_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='TotalRequestsTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=200)),
                ('customer_email', models.CharField(max_length=200)),
                ('request_type', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='debitcard',
            name='debit_id',
        ),
    ]
