# Generated by Django 4.1.1 on 2022-10-18 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0028_totalrequeststable_remove_debitcard_debit_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loandetails',
            name='date_of_approval',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='loandetails',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
