# Generated by Django 4.1.1 on 2022-10-18 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0029_alter_loandetails_date_of_approval_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='totalrequeststable',
            table='TotalRequestsTable',
        ),
    ]
