# Generated by Django 4.1.1 on 2022-10-18 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0030_alter_totalrequeststable_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='customertable',
            name='avg_monthly_salary',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='customertable',
            name='employee_type',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
