# Generated by Django 4.1.1 on 2022-10-18 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0031_customertable_avg_monthly_salary_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='totalrequeststable',
            table=None,
        )

    ]
