# Generated by Django 4.1.1 on 2022-10-18 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0032_alter_totalrequeststable_table_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerLoanStatusTable',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('loan_amount', models.BigIntegerField()),
                ('rate_of_interest_in_percent', models.IntegerField()),
                ('tenure_in_months', models.IntegerField()),
                ('monthly_EMI', models.BigIntegerField()),
                ('loan_status', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newapp.customertable')),
            ],
        ),
    ]
