# Generated by Django 4.1.1 on 2022-10-18 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0033_customerloanstatustable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loandetails',
            name='date_of_approval',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
