# Generated by Django 4.1.1 on 2022-10-03 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('appointment_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('slot', models.CharField(choices=[('10 AM', '10 AM'), ('1 PM', '1 PM'), ('4 PM', '4 PM')], max_length=100)),
                ('status', models.CharField(choices=[('booked', 'booked'), ('completed', 'completed'), ('approved', 'approved'), ('rejected', 'rejected'), ('pending', 'pending')], default='pending', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consultation_fee', models.IntegerField(blank=True, null=True)),
                ('test_fee', models.IntegerField(blank=True, null=True)),
                ('tax', models.IntegerField(blank=True, null=True)),
                ('total', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('branch_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('branch_name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Lab',
            fields=[
                ('lab_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('lab_number', models.IntegerField()),
                ('lab_type', models.CharField(max_length=100)),
                ('lab_name', models.CharField(max_length=100)),
                ('lab_status', models.CharField(choices=[('occupied', 'occupied'), ('available', 'available')], default='available', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, max_length=200, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('report_type', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.DecimalField(decimal_places=1, max_digits=1)),
                ('comment', models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('test_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('test_type', models.CharField(max_length=100)),
                ('test_name', models.CharField(max_length=100)),
                ('test_description', models.TextField(max_length=5000)),
                ('lab', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='appointment.lab')),
            ],
        ),
    ]
