# Generated by Django 4.1.1 on 2022-10-03 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='tests',
            field=models.ManyToManyField(blank=True, null=True, related_name='tests', to='appointment.test'),
        ),
    ]
