# Generated by Django 4.1.1 on 2022-10-04 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0004_remove_lab_lab_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='report_type',
        ),
        migrations.RemoveField(
            model_name='test',
            name='test_type',
        ),
        migrations.AlterField(
            model_name='test',
            name='test_description',
            field=models.TextField(max_length=5000, null=True),
        ),
    ]
