# Generated by Django 4.1.1 on 2022-10-04 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0005_remove_report_report_type_remove_test_test_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lab',
            name='lab_status',
        ),
        migrations.RemoveField(
            model_name='lab',
            name='lab_type',
        ),
    ]
