# Generated by Django 4.1.1 on 2022-10-04 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0006_remove_lab_lab_status_remove_lab_lab_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='test_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
