# Generated by Django 4.1.1 on 2022-10-04 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0008_alter_branch_branch_id_alter_lab_lab_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='branch_id',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='lab',
            name='lab_id',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='test',
            name='test_id',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
