# Generated by Django 4.0.5 on 2022-09-09 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='emp_pic',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
