# Generated by Django 4.0.5 on 2022-09-09 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_employee_devices_device_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='dept_password',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
