# Generated by Django 4.0.5 on 2022-09-09 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_employee_dept_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='dept_password',
            new_name='emp_password',
        ),
    ]
