# Generated by Django 4.1 on 2022-09-05 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('restaurant_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('restaurant_name', models.CharField(max_length=30)),
                ('restaurant_location', models.CharField(max_length=100)),
                ('restaurant_rating', models.DecimalField(decimal_places=1, max_digits=2)),
                ('restaurant_username', models.CharField(max_length=30)),
                ('restaurant_password', models.CharField(max_length=30)),
                ('restaurant_phn', models.CharField(max_length=20)),
            ],
        ),
    ]
