# Generated by Django 4.1 on 2022-09-05 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('OrderFood', '0002_customer_employee_food'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderFood',
            fields=[
                ('order_food_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('customer_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='OrderFood.customer')),
                ('emp_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='OrderFood.employee')),
                ('food_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='OrderFood.food')),
                ('restaurant_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='OrderFood.restaurant')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('transaction_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('payment_type', models.CharField(max_length=50)),
                ('payment_status', models.CharField(max_length=50)),
                ('amount', models.IntegerField()),
                ('order_food_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='OrderFood.orderfood')),
            ],
        ),
        migrations.CreateModel(
            name='OrderDetails',
            fields=[
                ('order_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('order_status', models.CharField(max_length=50)),
                ('order_time', models.DateTimeField(auto_now_add=True)),
                ('delivery_time', models.DateTimeField()),
                ('order_food_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='OrderFood.orderfood')),
                ('transaction_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='OrderFood.payment')),
            ],
        ),
        migrations.CreateModel(
            name='FoodAvailable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_available', models.BooleanField()),
                ('food_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='OrderFood.food')),
                ('restaurant_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='OrderFood.restaurant')),
            ],
        ),
    ]
