# Generated by Django 4.1 on 2022-09-07 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OrderFood', '0003_orderfood_payment_orderdetails_foodavailable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodavailable',
            name='food_id',
        ),
        migrations.RemoveField(
            model_name='foodavailable',
            name='restaurant_id',
        ),
        migrations.RemoveField(
            model_name='orderdetails',
            name='order_food_id',
        ),
        migrations.RemoveField(
            model_name='orderdetails',
            name='transaction_id',
        ),
        migrations.RemoveField(
            model_name='orderfood',
            name='customer_id',
        ),
        migrations.RemoveField(
            model_name='orderfood',
            name='emp_id',
        ),
        migrations.RemoveField(
            model_name='orderfood',
            name='food_id',
        ),
        migrations.RemoveField(
            model_name='orderfood',
            name='restaurant_id',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='order_food_id',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
        migrations.DeleteModel(
            name='Food',
        ),
        migrations.DeleteModel(
            name='FoodAvailable',
        ),
        migrations.DeleteModel(
            name='OrderDetails',
        ),
        migrations.DeleteModel(
            name='OrderFood',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
        migrations.DeleteModel(
            name='Restaurant',
        ),
    ]
