# Generated by Django 4.1.6 on 2023-02-13 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('booking_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('number_of_seats', models.IntegerField()),
                ('status', models.BooleanField()),
            ],
        ),
    ]
