# Generated by Django 4.1.6 on 2023-03-17 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_movie_rating'),
        ('booking', '0004_remove_booking_number_of_seats_remove_booking_show_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrderItem',
            new_name='BookingItem',
        ),
    ]
