# Generated by Django 4.1.6 on 2023-03-27 06:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_bookingaddress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingitem',
            name='order_detail',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookingItem', to='booking.booking'),
        ),
    ]
