movies = [
    {
        '_id':'1',
        'name': 'Don2',
        'image': '/Images/Don2.jpg',
        'description': 'Don turns himself in and escapes with Vardhaan from prison, following which he recruits a team to steal currency printing plates from a bank in Berlin.',
        'producer_company':'Excel Entertainment and Red Chillies Entertainment',
        'genre': 'Action',
        'price': 250,
        'Number_of_seats': 100,
        'Number_of_screens' : 50,
        'rating': 8.1,
        'numReviews':23,
    },
    {
        '_id':'2',
        'name': 'Brothers',
        'image': '/Images/Brothers.jpg',
        'description': 'Description2',
        'producer_company':'company2',
        'genre': 'Action',
        'price': 250,
        'Number_of_seats': 100,
        'Number_of_screens' : 70,
        'rating': 8.5,
        'numReviews':23,
    },
    {
        '_id':'3',
        'name': 'Joker',
        'image': '/Images/Joker.jpg',
        'description': 'Description3',
        'producer_company':'company3',
        'genre': 'Action',
        'price': 250,
        'Number_of_seats': 100,
        'Number_of_screens' : 0,
        'rating': 6.0,
        'numReviews':23,
    },
]