# Generated by Django 4.1 on 2022-10-14 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0002_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
