use surya_medplus;


CREATE TABLE books ( BookId INT PRIMARY KEY AUTO_INCREMENT, Title VARCHAR(255) NOT NULL, Author VARCHAR(255) NOT NULL, Category VARCHAR(100) NOT NULL, Status CHAR(1) NOT NULL CHECK (Status IN ('A', 'I')), Availability CHAR(1) NOT NULL CHECK (Availability IN ('A', 'I')) );
CREATE TABLE books_log ( LogId INT PRIMARY KEY AUTO_INCREMENT, BookId INT NOT NULL, Action VARCHAR(50) NOT NULL, ActionDate DATETIME NOT NULL, FOREIGN KEY (BookId) REFERENCES books(BookId) );
CREATE TABLE members ( MemberId INT PRIMARY KEY AUTO_INCREMENT, Name VARCHAR(255) NOT NULL, Email VARCHAR(255) NOT NULL UNIQUE, Mobile BIGINT NOT NULL UNIQUE, Gender CHAR(1) NOT NULL CHECK (Gender IN ('M', 'F')), Address VARCHAR(255) NOT NULL );
CREATE TABLE members_log ( LogId INT PRIMARY KEY AUTO_INCREMENT, MemberId INT NOT NULL, Action VARCHAR(50) NOT NULL, ActionDate DATETIME NOT NULL, FOREIGN KEY (MemberId) REFERENCES members(MemberId) );
CREATE TABLE issue ( IssueId INT PRIMARY KEY AUTO_INCREMENT, BookId INT NOT NULL, MemberId INT NOT NULL, Status CHAR(1) NOT NULL CHECK (Status IN ('I', 'R')), IssueDate DATE NOT NULL, ReturnDate DATE, FOREIGN KEY (BookId) REFERENCES books(BookId), FOREIGN KEY (MemberId) REFERENCES members(MemberId) ); 
CREATE TABLE issue_log ( LogId INT PRIMARY KEY AUTO_INCREMENT, IssueId INT NOT NULL, Action VARCHAR(50) NOT NULL, ActionDate DATETIME NOT NULL, FOREIGN KEY (IssueId) REFERENCES issue(IssueId) );