# Generated by Django 4.1 on 2022-10-11 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employeedetail', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='candidate_info',
            fields=[
                ('cid', models.IntegerField(default='-', primary_key=True, serialize=False)),
                ('name', models.CharField(default='-', max_length=50)),
                ('contact', models.IntegerField(default=0, unique=True)),
                ('age', models.CharField(default='-', max_length=50)),
                ('mail', models.EmailField(max_length=50, unique=True)),
                ('gender', models.CharField(default='-', max_length=50)),
                ('sheet_no', models.CharField(default='-', max_length=10)),
                ('status', models.CharField(default='-', max_length=10)),
                ('addharcard_no', models.IntegerField(default=0, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='vaacancy',
            fields=[
                ('vid', models.IntegerField(db_column='test', primary_key=True, serialize=False)),
                ('salary', models.CharField(default='-', max_length=50)),
                ('skill', models.CharField(default='-', max_length=50)),
                ('experience', models.CharField(default='-', max_length=50)),
                ('no_of_vacancy', models.CharField(default='-', max_length=50)),
                ('designeation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employeedetail.designation')),
            ],
        ),
        migrations.CreateModel(
            name='assesment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='-', max_length=20)),
                ('apptitute', models.IntegerField(default='-')),
                ('codeing', models.IntegerField(default='-')),
                ('interview1', models.IntegerField(default='-')),
                ('interview2', models.IntegerField(default='-')),
                ('result', models.CharField(default='-', max_length=50)),
                ('cid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruitment.candidate_info')),
            ],
        ),
        migrations.CreateModel(
            name='applying',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruitment.candidate_info')),
                ('vid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruitment.vaacancy')),
            ],
        ),
    ]
