# Generated by Django 4.1 on 2022-10-11 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate_info',
            name='sheet_no',
        ),
        migrations.AddField(
            model_name='candidate_info',
            name='update',
            field=models.CharField(default='no', max_length=10),
        ),
    ]
