# Generated by Django 4.1 on 2022-10-11 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0002_remove_candidate_info_sheet_no_candidate_info_update'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate_info',
            name='status',
        ),
        migrations.RemoveField(
            model_name='candidate_info',
            name='update',
        ),
        migrations.AddField(
            model_name='assesment',
            name='update',
            field=models.CharField(default='-', max_length=50),
        ),
    ]
