# Generated by Django 4.1 on 2022-10-13 05:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0004_alter_assesment_result_alter_assesment_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='assesment',
            name='vid',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='recruitment.vaacancy'),
            preserve_default=False,
        ),
    ]
