# Generated by Django 4.1 on 2022-10-13 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0005_assesment_vid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assesment',
            name='apptitute',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='assesment',
            name='codeing',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='assesment',
            name='interview1',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='assesment',
            name='interview2',
            field=models.IntegerField(default=0),
        ),
    ]
