# Generated by Django 4.1 on 2022-10-14 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0006_alter_assesment_apptitute_alter_assesment_codeing_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assesment',
            name='apptitute',
            field=models.CharField(default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='assesment',
            name='codeing',
            field=models.CharField(default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='assesment',
            name='interview1',
            field=models.CharField(default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='assesment',
            name='interview2',
            field=models.CharField(default='pending', max_length=10),
        ),
    ]
