# Generated by Django 4.1 on 2022-10-14 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0008_alter_assesment_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assesment',
            name='update',
            field=models.CharField(default='APPLICATION UNDER REVIEW', max_length=50),
        ),
    ]
