#pylint:disable=C0103
"""removed status field"""
# Generated by Django 4.1.1 on 2022-10-04 10:45

from django.db import migrations


class Migration(migrations.Migration):
    """migration changes"""

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='status',
        ),
    ]
