# Generated by Django 5.2.4 on 2025-07-18 11:51

import datetime
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('dept_id', models.BigAutoField(primary_key=True, serialize=False, validators=[django.core.validators.MinValueValidator(1)])),
                ('dept_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Designations',
            fields=[
                ('designation', models.CharField(max_length=20, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('emp_id', models.PositiveIntegerField(primary_key=True, serialize=False, validators=[django.core.validators.MinValueValidator(1000), django.core.validators.MaxValueValidator(9999)])),
                ('emp_name', models.CharField(max_length=20)),
                ('dob', models.DateField(null=True)),
                ('date_joined', models.DateField(default=datetime.datetime.today)),
                ('dept_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Employee.departments')),
                ('designation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Employee.designations')),
            ],
        ),
        migrations.CreateModel(
            name='DepartmentHeads',
            fields=[
                ('dept_head_id', models.PositiveIntegerField(primary_key=True, serialize=False, validators=[django.core.validators.MinValueValidator(1)])),
                ('dept_head_since', models.DateField()),
                ('dept_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Employee.departments', unique=True)),
                ('emp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Employee.employees')),
            ],
        ),
        migrations.CreateModel(
            name='PayScale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('dept_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Employee.departments')),
                ('designation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Employee.designations')),
            ],
            options={
                'unique_together': {('dept_id', 'designation')},
            },
        ),
    ]
