# Generated by Django 5.2.4 on 2025-07-28 06:18

import datetime
import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept_name', models.CharField(choices=[('R&D', 'Research and Development'), ('FSD', 'Full Stack Developer'), ('BD', 'Backend Development'), ('PD', 'Production'), ('TS', 'Transactions'), ('ND', 'Not Determined')], default='ND', max_length=3, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Designations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(choices=[('ASE', 'Associate Software Engineer'), ('JSE', 'Junior Software Engineer'), ('SSE', 'Senior Software Engineer'), ('NOD', 'Not Assigned')], default='NOD', max_length=3, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('emp_id', models.CharField(max_length=7, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(message='Employee ID must be in format OTGXXXX', regex='^OTG\\d{4}$')])),
                ('emp_name', models.CharField(max_length=20)),
                ('dob', models.DateField(null=True)),
                ('date_joined', models.DateField(default=datetime.datetime.today)),
                ('is_active', models.BooleanField(default=False)),
                ('dept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='Employee.departments')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeOfficeAddressDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=20)),
                ('emp', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='address_details', to='Employee.employees')),
            ],
        ),
        migrations.CreateModel(
            name='PayScale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10)),
                ('emp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pay_scales', to='Employee.employees')),
            ],
        ),
        migrations.CreateModel(
            name='ReportingManagers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manager_since', models.DateField()),
                ('emp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reporting_managers', to='Employee.employees')),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('employee', 'Employee'), ('hr', 'HR'), ('manager', 'Manager'), ('ceo', 'CEO')], default='employee', max_length=20)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='employees',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='EmployeeJobDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effective_from', models.DateField(null=True)),
                ('effective_till', models.DateField(null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('team_id', models.PositiveIntegerField(null=True)),
                ('designation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='designated_employees', to='Employee.designations')),
                ('emp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_details', to='Employee.employees')),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('emp',), name='unique_job_at_a_time'), models.CheckConstraint(condition=models.Q(('effective_from__lt', models.F('effective_till'))), name='check_valid_effective_dates')],
            },
        ),
    ]
