# Generated by Django 5.2.4 on 2025-07-14 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payscale',
            name='id',
        ),
        migrations.AddField(
            model_name='payscale',
            name='pk',
            field=models.CompositePrimaryKey('dept_id', 'designation', blank=True, editable=False, primary_key=True, serialize=False),
        ),
    ]
