# Generated by Django 5.2.4 on 2025-07-16 10:08

import datetime
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Designations',
            fields=[
                ('designation', models.CharField(max_length=20, primary_key=True, serialize=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='employees',
            name='manager_id',
        ),
        migrations.RemoveField(
            model_name='departments',
            name='manager_id',
        ),
        migrations.RemoveField(
            model_name='employees',
            name='age',
        ),
        migrations.AddField(
            model_name='employees',
            name='dob',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='employees',
            name='date_joined',
            field=models.DateField(default=datetime.datetime.today),
        ),
        migrations.AlterField(
            model_name='payscale',
            name='salary',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.CreateModel(
            name='DepartmentHeads',
            fields=[
                ('dept_head_id', models.PositiveIntegerField(primary_key=True, serialize=False, validators=[django.core.validators.MinValueValidator(1)])),
                ('dept_head_since', models.DateField()),
                ('dept_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Employee.departments', unique=True)),
                ('emp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Employee.employees')),
            ],
        ),
        migrations.AlterField(
            model_name='payscale',
            name='designation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Employee.designations'),
        ),
        migrations.AlterUniqueTogether(
            name='payscale',
            unique_together={('dept_id', 'designation')},
        ),
        migrations.DeleteModel(
            name='Managers',
        ),
    ]
