# Generated by Django 5.2.4 on 2025-07-24 10:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employees',
            old_name='dept_id',
            new_name='dept',
        ),
        migrations.AlterUniqueTogether(
            name='payscale',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='departmentheads',
            name='dept_id',
        ),
        migrations.RemoveField(
            model_name='departments',
            name='dept_id',
        ),
        migrations.AddField(
            model_name='departments',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='designations',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='payscale',
            name='emp',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='Employee.employees'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='designations',
            name='designation',
            field=models.CharField(choices=[('ASE', 'associate software engineer'), ('JSE', 'junior software engineer'), ('SSE', 'senior software engineer'), ('NOD', 'Not Determined')], default='NOD', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='payscale',
            name='salary',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddConstraint(
            model_name='employees',
            constraint=models.CheckConstraint(condition=models.Q(('emp_id__gte', 1000), ('emp_id__lte', 9999)), name='emp_id'),
        ),
        migrations.RemoveField(
            model_name='payscale',
            name='dept_id',
        ),
        migrations.RemoveField(
            model_name='payscale',
            name='designation',
        ),
    ]
