# Generated by Django 5.2.4 on 2025-07-24 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0002_rename_dept_id_employees_dept_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departments',
            name='dept_name',
            field=models.CharField(choices=[('R&D', 'Research and Development'), ('FSD', 'Full Stack Developer'), ('BD', 'Backend Development'), ('PD', 'Production'), ('TS', 'Transactions')], max_length=20),
        ),
    ]
