# Generated by Django 5.2.4 on 2025-07-24 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0003_alter_departments_dept_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='departmentheads',
            name='dept_head_id',
        ),
        migrations.AddField(
            model_name='departmentheads',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
