# Generated by Django 5.2.4 on 2025-07-24 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0004_remove_departmentheads_dept_head_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='departmentheads',
            old_name='emp_id',
            new_name='emp',
        ),
    ]
