# Generated by Django 5.2.4 on 2025-07-24 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0005_rename_emp_id_departmentheads_emp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departments',
            name='dept_name',
            field=models.CharField(choices=[('R&D', 'Research and Development'), ('FSD', 'Full Stack Developer'), ('BD', 'Backend Development'), ('PD', 'Production'), ('TS', 'Transactions'), ('ND', 'Not Determined')], default='ND', max_length=3, unique=True),
        ),
        migrations.AlterField(
            model_name='designations',
            name='designation',
            field=models.CharField(choices=[('ASE', 'associate software engineer'), ('JSE', 'junior software engineer'), ('SSE', 'senior software engineer'), ('NOD', 'Not Assigned')], default='NOD', max_length=3, unique=True),
        ),
    ]
