# Generated by Django 5.2.4 on 2025-07-25 02:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0006_alter_departments_dept_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payscale',
            name='emp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payscale', to='Employee.employees'),
        ),
    ]
