# Generated by Django 5.2.4 on 2025-07-25 02:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0007_alter_payscale_emp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departmentheads',
            name='emp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departmentheads', to='Employee.employees'),
        ),
        migrations.AlterField(
            model_name='employees',
            name='dept',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees_dept', to='Employee.departments'),
        ),
        migrations.AlterField(
            model_name='employees',
            name='designation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees_des', to='Employee.designations'),
        ),
    ]
