# Generated by Django 4.2.23 on 2025-08-04 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookStore', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='authors',
            name='role',
            field=models.CharField(default='author', max_length=20),
        ),
        migrations.AddField(
            model_name='books',
            name='content',
            field=models.CharField(max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='customers',
            name='role',
            field=models.CharField(default='customer', max_length=20),
        ),
    ]
