# Generated by Django 4.2.23 on 2025-07-31 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookStore', '0002_authors_role_books_content_customers_role_person'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Person',
        ),
    ]
