# Generated by Django 4.2.23 on 2025-07-31 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookStore', '0003_delete_person'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='content',
        ),
    ]
