# Generated by Django 4.2.23 on 2025-07-31 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookStore', '0004_remove_books_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='content',
            field=models.CharField(max_length=5000, null=True),
        ),
    ]
