(function(g){var m=window.AmazonUIPageJS||window.P,n=m._namespace||m.attributeErrors,u=n?n("CustomerReviewsCommonAssets",""):m;u.guardFatal?u.guardFatal(g)(u,window):u.execute(function(){g(u,window)})})(function(g,m,n){function u(){}g.when("A","cr-log-utils","cr-streaming-utils").register("cr-ajax-model",function(b,d,c){function a(a){k[a]&&(k[a].abort(),delete k[a])}function e(l,f,q,r,v,t,g,n){f=f||{};f.params=f.params||{};t=t?t:p++;v=v?v:f.error||function(){};r=r?r:0;q=q?q:2;n=n?n:"FATAL";var u=
"FATAL"===n?0:1,w=f.finallyCallback||function(){};g||(g="reviewsAjax"+h++,m.uet&&m.uet("tc",g));f.params.scope=g;f.contentType=f.contentType||"application/x-www-form-urlencoded;charset\x3dUTF-8";var x=f.success||function(){};f.success=function(a){delete k[t];"function"===typeof x&&x(a);"function"===typeof w&&w(a)};f.error=function(h,b,c){h=h||{};var k=(h.http||{}).status||"[]";if(401===k){var p;p=h;var x=v,y=p.http.getResponseHeader("x-amz-re-authentication-url");y?("function"===typeof x&&x(p),"function"===
typeof w&&w(p),d.logCount("AjaxRedirectToReAuthenticationUrl",1),m.location=y,p=!0):p=!1;if(p)return;r=q}a(t);r++;r<q?(b="AJAX Post to "+l+" from "+m.location.href+" failed, status code passed through parameter was: "+b+", status code extracted from XHR HTTP object was: "+k+", attempt "+r+" of "+q+", error message was: \n "+c,d.logError(b,"WARN"),e(l,f,q,r,v,t,g,n)):(b="AJAX Post to "+l+" from "+m.location.href+" failed, status code passed through parameter was: "+b+", status code extracted from XHR HTTP object was: "+
k+", exhausted "+q+" attempt(s), error message was: \n "+c,d.logError(b,n),d.logCount("AjaxFailureFatal",u),"function"===typeof v&&v(h),"function"===typeof w&&w(h))};"function"!==typeof f.chunk&&(f.chunk=function(a){"appendFadeIn"===a[0]?c.appendFadeIn(a):"replace"===a[0]&&c.replace(a)});k[t]=b.post(l,f);return t}var h=0,p=1,k={};return{abort:a,post:e,postWithoutFatals:function(a,h,b,c,d,k,p){return e(a,h,b,c,d,k,p,"WARN")}}});"use strict";g.when("A","cr-jQuery","cr-log-utils","cr-number-utils").register("cr-A",
function(b,d,c,a){b.getListFromState=function(a){var c=b.map(d("#cr-state-object, .cr-state-object"),function(a){return d(a).data("state")});return b.reduce(c,function(b,c){c!==n&&c[a]!==n&&b.push(c[a]);return b},[])};b.getValueFromState=function(a){var e=b.getListFromState(a);1<e.length&&c.logError("More than one  value defined for key: "+a,"ERROR");return e[0]};var e={top:-100,left:-100};b.inView=function(a){a=a||d();if("function"===typeof a.offset){var b=(a.offset()||e).top-d(m).scrollTop();a=
0<=b;b=b<d(m).height();return a&&b}return!1};b.onScreenAndVisible=function(b,c){b=b||d();c=a.isFiniteNumber(c)?c:0;if(b instanceof d||b.jquery){if(!b.is(":visible"))return!1;b=b[0].getBoundingClientRect();return b.top>=0-c&&b.left>=0-c&&b.bottom<=d(m).height()+c&&b.right<=d(m).width()+c}return!1};b.compositeEventWrapper=function(a,e,d){var l=a;d&&(l=b.throttle(l,d,{trailing:!1}));return c.jsGuard(function(a){a&&(l(a),e&&a.$event&&a.$event.preventDefault())})};b.freeze=function(a){return"undefined"!==
typeof Object&&"function"===typeof Object.freeze?Object.freeze(a):a};b.isFrozen=function(a){return"undefined"!==typeof Object&&"function"===typeof Object.isFrozen?Object.isFrozen(a):!1};return b});"use strict";g.when("jQuery").register("cr-jQuery",function(b){return b});"use strict";g.declare("reviews-constants",{PUSH_STATE:!0,REPLACE_STATE:!1,RATING_SERVICE_CONTEXT_ID:"ReviewsConsumption",data:{REFTAG:"data-reftag",CSM_COUNTER:"data-csm-counter",getReviews:{STANDARD:"data-reviews-state-param",CHECKED:"data-reviews-param-checked",
UNCHECKED:"data-reviews-param-unchecked"}},events:{CONTENT_CHANGED:"reviews:content-changed",RELOAD:"reviews:content-reload",RELOAD_COMPLETE:"reviews:content-reload-complete",AUTOSCROLL_COMPLETE:"reviews:autoscroll-complete",FILTER_FIRE_AGGREGATE:"reviews:filter-action:aggregate:trigger",FILTER_FIRE_UPDATE:"reviews:filter-action:trigger",FILTER_AGGREGATE:"reviews:filter-action:aggregate",FILTER_PUSH:"reviews:filter-action:push-state",FILTER_REPLACE:"reviews:filter-action:replace-state",PAGINATION:"reviews:page-action",
SEARCH_TEXTBOX:"reviews:search-textbox",SEARCH_BUTTON:"reviews:search-button",VOTE:"reviews:vote-action",TOGGLE_CLASS_CLICK:"reviews:toggle-class:click",AJAX_POST:"reviews:ajax-post",SCROLL_TO_ELEMENT_CLICK:"reviews:scroll-to-element:click",OPEN_MASH_MODAL:"reviews:open-mash-modal",FILTER_APPLY:"reviews:filter-action:apply",FILTER_CHANGE:"reviews:filter-action:change",FILTER_TAB_CLICKED:"reviews:filter-action:tab-clicked",FILTER_APPLY_BEGIN:"reviews:filter-action:apply-begin",FILTER_APPLY_SUCCESS:"reviews:filter-action:apply-success",
FILTER_APPLY_ERROR:"reviews:filter-action:apply-error",FILTER_APPLY_DONE:"reviews:filter-action:apply-done",INPUT_COMMENT:"reviews:input-comment",SUBMIT_COMMENT:"reviews:submit-comment",OPEN_SUBMISSION_COMMENT:"reviews:open-comment-submission",SORT_COMMENTS:"reviews:sort-comments",MORE_COMMENTS:"reviews:more-comments",EDIT_COMMENT:"reviews:edit-comment",CANCEL_EDIT_COMMENT:"reviews:cancel-edit-comment",DELETE_COMMENT:"reviews:delete-comment",SUBMIT_EDIT_COMMENT:"reviews:submit-edit-comment",MODIFY_EDIT_COMMENT:"reviews:modify-edit-comment",
INPUT_PRODUCT_LINK:"reviews:input-product-link",SELECT_PRODUCT_LINK:"reviews:select-product-link",STAR_RATING_CLICK:"ryp:star-rating-click",STAR_RATING_CLEAR:"ryp:star-rating-clear-click",TRIGGER_WEBLAB:"reviews:trigger-weblab",REFTAG_TRIGGER:"reviews:trigger-reftag"},filterOptions:{SORT_KEY:"sortBy",HELPFUL:"helpful",RECENT:"recent",LEGACY_HELPFUL:"byRankDescending",LEGACY_RECENT:"bySubmissionDateDescending",MOBILE_HELPFUL:"sh",MOBILE_RECENT:"sd",STAR_KEY:"filterByStar",ALL_STARS:"all_stars",ONE_STAR:"one_star",
TWO_STAR:"two_star",THREE_STAR:"three_star",FOUR_STAR:"four_star",FIVE_STAR:"five_star",POSTIVE:"positive",CRITICAL:"critical",FORMAT_KEY:"formatType",ALL_FORMATS:"all_formats",CURRENT_FORMAT:"current_format",AVP_KEY:"reviewerType",ALL_REVIEWS:"all_reviews",AVP_ONLY:"avp_only_reviews",MEDIA_KEY:"mediaType",ALL_CONTENTS:"all_contents",MEDIA_ONLY:"media_reviews_only",LANGUAGE_KEY:"filterByLanguage",HEIGHT_KEY:"filterByHeight",WEIGHT_KEY:"filterByWeight"},keycodes:{ENTER:13,BACK_SPACE:8,SPACE:32},aui:{HIDDEN:"aok-hidden",
NOWRAP:"aok-nowrap"}});"use strict";g.when("A","cr-string-utils","cr-log-utils").register("cr-popup",function(b,d,c){function a(a){var h={};a&&a.data&&(h=a.data);var p=d.defaultIfBlank(h.url,a.$target.find("a").andSelf().filter("a").attr("href")),k=d.defaultIfBlank(h.title,"CustomerReviews"),k=""+k,l="";b.each({width:"500",height:"500",resizable:"1",scrollbars:"1",toolbar:"0",status:"1"},function(a,b){a=d.defaultIfBlank(h[b],a);l+=b+"\x3d"+a+","});var l=l.slice(0,-1),f=null;try{(f=m.open(p,k,l))?
f.focus():c.logError("Unable to move focus to popup window with data: "+d.stringify(h),"ERROR"),a.$event.preventDefault()}catch(q){c.logError("Unable to open window with parameters: "+d.stringify(h),"FATAL",q)}return f}b.declarative("cr-popup",["click"],c.jsGuard(a));return{popup:a}});"use strict";g.when("A","cr-jQuery","reviews-constants","cr-ajax-model","cr-string-utils","cr-global-view").register("cr-generic-declarative-actions",function(b,d,c,a,e,h){function p(a){f(a)&&a.data.selector&&a.data.cssClass&&
(d(a.data.selector).toggleClass(a.data.cssClass),a.$event.preventDefault(),b.trigger("a:pageUpdate"))}function k(a){f(a)&&a.data.scrollToSelector&&(h.scrollTo(a.data.scrollToSelector,0),a.$event.preventDefault())}function l(c){if(f(c)&&c.data.url&&c.data.params){c.$event.preventDefault();b.declarative.remove(c.$currentTarget,r.AJAX_POST);c=c.data;var e=c.params,h=d(c.indicatorSelector)[0],k=q(d.fn.hide,c.hideOnSuccessSelector),l=q(d.fn.show,c.showOnFailureSelector);d(c.removeOnLoadSelector).remove();
a.post(c.url,{params:e,indicator:h,success:k,error:l})}}function f(a){return a&&a.data&&a.$event&&"function"===typeof a.$event.preventDefault}function q(a,b){if(b&&"function"===typeof a)return function(){var c=d(b);0<c.length&&a.call(c)}}var r=c.events;b.declarative(r.TOGGLE_CLASS_CLICK,"click",p);b.declarative(r.SCROLL_TO_ELEMENT_CLICK,"click",k);b.declarative(r.AJAX_POST,"click",l);return{toggleCssClass:p,scrollToElement:k,ajaxPost:l}});"use strict";g.register("cr-global-model",function(){return{generateUrl:function(b,
d){b&&"/"!==b.charAt(b.length-1)&&(b+="/");b&&d&&(b=b+"ref\x3d"+d);return b}}});"use strict";g.when("A","a-expander","cr-jQuery","reviews-constants","cr-string-utils").register("cr-global-view",function(b,d,c,a,e){function h(a){var b="";if(a&&a.closest!==n){var c=a.closest("*["+f.REFTAG+"]");c&&(b=c.attr(f.REFTAG))}e.isBlank(b)&&a&&a.closest!==n&&(a=a.closest("*[rel]"))&&(b=a.attr("rel"));return e.defaultIfBlank(b,"cm_cr_unknown")}function p(a){return a&&"function"===typeof a.is?a.is("*["+f.getReviews.CHECKED+
"]")&&a.is("*["+f.getReviews.UNCHECKED+"]"):!1}function k(a){return a&&a.has!==n&&a.is!==n?0<a.find(":checked").length||a.is(":checked"):!1}function l(a,b){return a&&a.attr!==n&&b?e.parseJSON(a.attr(b))||{}:{}}var f=a.data;b.on("a:pageUpdate",function(){d!==n&&d.initializeExpanders()});b.on(a.events.RELOAD_COMPLETE,function(){b.trigger("a:image:lazyLoad")});return{getReviewsStateParamsFromElement:function(a){var c=b.reduce(f.getReviews,function(a,b){return a+"*["+b+"],"},"").slice(0,-1),e;c&&a&&a.closest!==
n&&(e=a.closest(c));return p(e)?k(e)?l(e,f.getReviews.CHECKED):l(e,f.getReviews.UNCHECKED):l(e,f.getReviews.STANDARD)},getReftag:function(a){var b;a&&a.$target&&(b=a.$target);a&&a.id&&(b=c("#"+a.id));a&&a.expander&&a.expander.$expander&&(b=a.expander.$expander);b=h(b);"cm_cr_unknown"===b&&a&&a.data&&a.data.reftag&&(b=a.data.reftag);return b},getReftagByDom:h,scrollTo:function(a,b){a=c(a).offset();b=b||0;var e=c("#cr-state-object").data("state"),e=e!==n&&e.disableScroll;a&&a.top!==n&&!e&&(c("html,body").stop(),
c("html,body").animate({scrollTop:a.top-b},{queue:!1,duration:500}))}}});"use strict";g.when("cr-A","cr-jQuery","cr-lazy-widget-model","cr-lazy-widget-view","cr-log-utils","cr-number-utils","cr-string-utils","cr-uri-utils","ready").register("cr-lazy-widget-controller",function(b,d,c,a,e,h,p,k){function l(d){var f=b.getValueFromState("lazyWidgetDomainWhitelist"),h=k.getCurrentHostname();if(f)b:{for(var l=0;l<f.length;l++)if(p.endsWith(h,f[l])){e.logCount("LazyWidgetInvalidDomain",0);break b}e.logError("AJAX triggered from invalid domain: "+
h,"WARN");e.logCount("LazyWidgetInvalidDomain",1)}else e.logCount("LazyWidgetInvalidDomain",1),e.logError("AJAX triggered with null whitelist from domain: "+h,"WARN");c.loadLazyWidgets(a.getLazyWidgetStubs())&&(e.logCount("LazyWidgetTrigger",1),e.logCount("LazyWidgetTrigger:"+d,1))}var f={};f.bufferPixels=h.convertToInteger(b.getValueFromState("lazyWidgetLoaderBufferPixels"),1E3);f.delayBeforeTriggering=h.convertToInteger(b.getValueFromState("lazyWidgetLoaderDelayBeforeTriggering"),5E3);f.triggerLazyLoadIfWidgetWithinBuffer=
function(e){c.lazyLoadHasTriggered()||a.getLazyWidgetStubs().each(function(a,c){if(b.onScreen(d(c),f.bufferPixels))return l("scroll"),b.off("scroll",f.triggerLazyLoadIfWidgetWithinBuffer),!1})};var q={};f.logVisibleStubMetrics=function(c){a.getLazyWidgetStubs().each(function(a,c){a=d(c);c=a.data("widget-name");!q[c]&&b.onScreen(a)&&(e.logCount("VisibleLazyWidgetStub",1),e.logCount("VisibleLazyWidgetStub:"+c,1),q[c]=!0)})};b.on("scroll",f.logVisibleStubMetrics);b.on("scroll",f.triggerLazyLoadIfWidgetWithinBuffer);
d(a.getHoverTargets()).mouseenter(function(){l("hover")});e.logCount("LazyWidgetTrigger",0);return b.freeze(f)});"use strict";g.when("cr-A","cr-ajax-model","cr-uri-utils","ready").register("cr-lazy-widget-model",function(b,d,c){var a={},e=b.getValueFromState("lazyWidgetLoaderUrl"),h=!1;a.loadLazyWidgets=function(a){if(!h&&0<a.length){h=!0;var k=b.getValueFromState("asin"),l=b.getValueFromState("lazyWidgetCsrfToken"),f=b.getValueFromState("languageOfPreference");a=b.reduce(a,function(a,c){return a+
"\x26lazyWidget\x3d"+b.$(c).data("widget-name")},e+"?asin\x3d"+k+"\x26csrf\x3d"+l+"\x26language\x3d"+f);d.postWithoutFatals(a,{success:u,cache:!1,headers:{"cache-control":"no-cache"},params:c.getUrlParametersMap()||{}});return!0}return!1};a.lazyLoadHasTriggered=function(){return h};return b.freeze(a)});"use strict";g.when("cr-A","cr-jQuery","ready").register("cr-lazy-widget-view",function(b,d){var c={},a=b.getValueFromState("lazyWidgetLoaderHoverTargetsSelector")||"";c.getLazyWidgetStubs=function(){return d(".cr-lazy-widget")};
c.getHoverTargets=function(){d(a)};return b.freeze(c)});"use strict";g.when("A").register("cr-log-utils",function(b){function d(a,b,c){m.ueLogError&&("string"!==typeof b&&(b="FATAL"),c?m.ueLogError(c,{message:a,logLevel:b.toUpperCase(),attribution:"CustomerReviewsJS"}):m.ueLogError({message:a},{logLevel:b.toUpperCase(),attribution:"CustomerReviewsJS"}))}function c(a,b){return"string"===typeof b?b+a:"CustomerReviews:"+a}return{logError:d,jsGuard:function(a){if("function"===typeof a)return function(){try{return a.apply(this,
arguments)}catch(b){d("Uncaught Error in function","FATAL",b)}};d("Unable to wrap non-function","ERROR");return a},incrementCount:function(a,b){m.ue&&(a=c(a,b),b=m.ue.count(a)||0,m.ue.count(a,b+1))},logCount:function(a,b,d){m.ue&&(a=c(a,d),m.ue.count(a,b))}}});"use strict";g.when("A","reviews-constants").register("cr-mash-utils",function(b,d){function c(a){g.when("mash").execute(function(b){b.navstack.begin().modalOpen(a).end()})}var a=!1;g.when("mash").execute(function(){a=!0});b.declarative(d.events.OPEN_MASH_MODAL,
"click",function(a){c(a.data.url);a.$event.preventDefault()});return{isMash:function(){return a},openModal:c}});"use strict";g.when("A","cr-log-utils").register("cr-number-utils",function(b,d){return{convertToInteger:function(b,a){if(b===parseInt(b,10))return b;if(null!==b&&b!==n&&""!==b)return parseInt(b.replace(/[^0-9]/g,""),10);if(a!==n)return a;d.logError("convertToInteger","Cannot convert "+b+" to Integer");return 0},isFiniteNumber:function(b){return"number"===typeof b&&!isNaN(b)&&isFinite(b)}}});
"use strict";g.when("cr-A","reviews-constants","cr-ajax-model","cr-global-model").register("cr-reftag-utils",function(b,d,c,a){function e(a){c.postWithoutFatals(a)}b.declarative(d.events.REFTAG_TRIGGER,"click",function(a){a.data.refMarker&&a.data.reftagTriggerUrl&&e(a.data.reftagTriggerUrl+"/ref\x3d"+a.data.refMarker)});return{triggerRefTagWithUrl:e,triggerRefTag:function(c){var d=b.getValueFromState("reftagTriggerUrl");d&&c&&e(a.generateUrl(d,c))}}});"use strict";g.when("A","cr-jQuery").register("cr-streaming-utils",
function(b,d){return{appendFadeIn:function(c){if(null!==c&&2<c.length&&null!==c[1]&&null!==c[2]){var a=c[1];c=d(c[2]).hide();d(a).append(c);b.fadeIn(c,500,"ease-in-out",function(){})}},replace:function(b){if(null!==b&&2<b.length&&null!==b[1]&&null!==b[2]){var a=b[2];d(b[1]).replaceWith(d(a))}}}});"use strict";g.when("A","cr-log-utils").register("cr-string-utils",function(b,d){function c(a){return null===a||a===n?!0:0===b.trim(a).length}return{defaultIfBlank:function(a,b){return c(a)?b:a},isBlank:c,
parseJSON:function(a){try{return b.parseJSON(a)}catch(c){d.logError("Unable to parse JSON object","ERROR",c)}return null},startsWith:function(a,b){return a===b?!0:null===a||null===b?!1:0===a.indexOf(b)},endsWith:function(a,b){if(a===b)return!0;if(null===a||null===b)return!1;var c=a.lastIndexOf(b);return-1!==c&&c===a.length-b.length},stringify:function(a){return m.JSON&&m.JSON.stringify?m.JSON.stringify(a):a}}});"use strict";g.when("A").register("cr-uri-utils",function(b){function d(){return m.location.hostname}
function c(a){a=a||m.location.href;var c={},d=a.indexOf("?"),g=a.indexOf("#");a=a.slice(d+1,g>d?g:n)||"";d=[];-1<a.indexOf("\x26")?d=a.split("\x26"):-1<a.indexOf("\x3d")&&(d=[a]);b.each(d,function(a,b){0<a.indexOf("\x3d")&&(a=a.split("\x3d"),c[a[0]]=a[1])});return c}return{getUrlParametersMap:c,addKeyValuePair:function(a,b,d){d=d||0;if(c(a)[b]===d||!a||!b)return a;b="?"+b+"\x3d"+d;return-1<a.indexOf("?")?a.replace("?",b+"\x26"):a+b},getCurrentHostname:d,getDomainRealmBaseUrl:function(a){a=a||d();
if(-1!==a.indexOf(".corp.amazon.com"))return"https://development.amazon.com/";if(-1!==a.indexOf(".proxy.amazon.com")){a=a.split(".")[1];var b={dub:"https://pre-prod.amazon.co.uk/",pdx:"https://pre-prod.amazon.co.jp/",pek:"https://pre-prod.amazon.cn/"};return b[a]!==n?b[a]:"https://pre-prod.amazon.com/"}return"/"}}});"use strict";g.when("A","reviews-constants").register("cr-weblab-utils",function(b,d){function c(a){m.ue&&m.ue.trigger&&m.ue.trigger(a.weblabID,a.treatment)}b.declarative(d.events.TRIGGER_WEBLAB,
"click",function(a){a.data.weblab&&a.data.treatment&&c({weblabID:a.data.weblab,treatment:a.data.treatment})});return{triggerWeblab:c}});"use strict";g.when("cr-A","cr-jQuery","cr-string-utils","cr-weblab-utils","afterReady").register("cr-weblab-on-view-utils",function(b,d,c,a){function e(a,c,e){k[c]||(a=h(d(a),c,e)(),l[c]=(l[c]||[]).concat(a),b.on.scroll(a))}function h(a,c,d){return function t(){b.inView(a)&&(g(c,d),b.each(l[c]||[],function(a){b.off("scroll",a)}));return t}}function g(b,c){k[b]||
(k[b]=!0,a.triggerWeblab({weblabID:b,treatment:c}))}var k={},l={};b.each(d("*[data-cr-weblab-trigger-on-scroll]"),function(a,b){a=d(a);var k=a.attr("data-cr-weblab-trigger-on-scroll"),k=c.parseJSON(k);null!==k&&(b="cr-weblab-trigger-on-scroll-"+b,a.addClass(b),e("."+b,k.weblabId,k.treatment))});return{triggerOnScrollIntoView:e,triggerWeblab:g}});"use strict";g.when("A","cr-uri-utils","cr-string-utils","3p-urijs","cr-jQuery").register("cr-extended-uri-utils",function(b,d,c,a,e){function h(){return a(m.location.href)}
function g(){return h().query()}return e.extend(d,{getCurrentUri:h,getCurrentQueryString:g,getCurrentQueryParameters:function(){return a.parseQuery(g())},isAmazonDomain:function(b){if("string"===typeof b||b instanceof String)b=a(b);var d=c.startsWith(b.domain(),"amazon");!1===d&&(b=b.hostname(),b=b.substring(b.indexOf(".")+1),d=c.startsWith(b,"amazon"));return d},setQueryParameters:function(d,e){if("string"===typeof d||d instanceof String)d=a(d);b.each(e,function(a,b){c.isBlank(a)?d.removeSearch(b):
d=d.setSearch(b,a)});return d},setReftag:function(b,d){if("string"===typeof b||b instanceof String)b=a(b);for(var e=b.segment(),g=!1,h=e.length-1;0<=h;h--)if(c.startsWith(e[h],"ref\x3d")){g=!0;e[h]="ref\x3d"+d;break}g||e.push("ref\x3d"+d);b.segment(e);return b}})});"use strict";g.when("A","cr-jQuery").register("histogram-trigger",function(b,d){function c(){b.onScreen(d("#histogramTable"))&&b.trigger("scroll")}b.on.afterLoad(c);return{triggerHistogram:c}})});
/* ******** */
(function(a){var b=window.AmazonUIPageJS||window.P,d=b._namespace||b.attributeErrors,c=d?d("CustomerReviewsMedleyAssets",""):b;c.guardFatal?c.guardFatal(a)(c,window):c.execute(function(){a(c,window)})})(function(a,b,d){a.when("A","reviews-constants","medley-twister-view","medley-twister-model","ready").register("medley-twister-controller",function(c,k,e,a){function b(b){b=a.getASIN();var f=e.getDisplayedASIN();f&&b!==f&&(e.fadeReviews(!0),a.getReviews(f,function(){a.setASIN(f)},function(){},function(){e.fadeReviews(!1);
c.trigger(k.events.RELOAD_COMPLETE)}))}var d=e.getLoadedASIN();a.setASIN(d);c.on("a:pageUpdate",b);return{onTwist:b}});"use strict";a.when("A","cr-jQuery").register("medley-twister-view",function(a,b){return{getDisplayedASIN:function(){return String(b("#ASIN").val()||"")},getLoadedASIN:function(){return(b("#cr-state-object").data("state")||{}).asin||""},fadeReviews:function(a){!1===a?b("#cm-cr-review-list .review,#most-recent-reviews-content .review").css("opacity",1):b("#cm-cr-review-list .review,#most-recent-reviews-content .review").css("opacity",
.5)}}});"use strict";a.when("A","cr-global-model","cr-ajax-model","cr-uri-utils","cr-jQuery").register("medley-twister-model",function(b,a,e,d,l){function c(b){var a=d.getUrlParametersMap()||{};a.asin=b;return a}var h;return{setASIN:function(a){h=a||""},getASIN:function(){return h},getReviews:function(a,b,d,g){var f=l("#cr-state-object").data("state");"string"===typeof a&&10===a.length?e.post(f.medleyReviewsAjaxUrl,{params:c(a),attribution:"getMedleyReviews",success:b,error:d,finallyCallback:g}):
"function"===typeof g&&g()}}})});
/* ******** */
(function(f){var h=window.AmazonUIPageJS||window.P,k=h._namespace||h.attributeErrors,c=k?k("CustomerReviewsVotingAssets",""):h;c.guardFatal?c.guardFatal(f)(c,window):c.execute(function(){f(c,window)})})(function(f,h,k){f.when("A","vote-model","vote-view","a-modal","cr-log-utils").register("vote-controller",function(c,b,a,l,f){function h(e,d){m(e,d);a.showElementByCssSelector(e,d.inFlight)}function m(e,d){a.hideElementByCssSelector(e,d.hideVoteComponents);d.hideAbuseComponents&&a.hideElementByCssSelector(e,
d.hideAbuseComponents)}function k(e,d){d.isReportAbuse&&(e=c.$("#mobile-abuse-"+d.reviewId),l.get(e).hide());h(e,d.cssSelectors);b.submitVote(d,function(g){if(!0===g){g=e;var b=d.cssSelectors;m(g,b);a.showElementByCssSelector(g,b.onSuccess)}else g=e,b=d.cssSelectors,m(g,b),a.showElementByCssSelector(g,b.onError)},function(b){if(401===b.http.status){if(b.http.getResponseHeader("x-amz-re-authentication-url")){f.logCount("Ajax401WithReAuthUrl:SubmitVote",1);return}f.logCount("Ajax401WithoutReAuthUrl:SubmitVote",
1)}b=e;var c=d.cssSelectors;m(b,c);a.showElementByCssSelector(b,c.onError)})}c.declarative("reviews:vote-action","click",function(a){k(a.$target,a.data);a.$event.preventDefault()});return{submitVote:k}});"use strict";f.when("A","cr-ajax-model").register("vote-model",function(c,b){return{submitVote:function(a,c,f){var l={"anti-csrftoken-a2z":a.csrfT};a.physicalId&&a.imageExtension&&(l["x-amz-extra-params"]=[a.physicalId,a.imageExtension]);b.post(a.ajaxUrl,{params:{reviewId:a.reviewId},attribution:"submitVote",
success:c,error:f,headers:l})}}});"use strict";f.when("A").register("vote-view",function(c){function b(a,b){return a.closest(".cr-vote").find(b)}return{hideThankYouAlert:function(a){b(a,".cr-vote-success").addClass("aok-hidden")},showThankYouAlert:function(a){b(a,".cr-vote-success").removeClass("aok-hidden")},showErrorAlert:function(a){b(a,".cr-vote-error").removeClass("aok-hidden")},showFeedback:function(a){b(a,".cr-vote-feedback").removeClass("aok-hidden")},hideFeedback:function(a){b(a,".cr-vote-feedback").addClass("aok-hidden")},
hideButtons:function(a){b(a,".cr-vote-buttons").addClass("aok-hidden")},hideElementByCssSelector:function(a,c){b(a,c).addClass("aok-hidden")},showElementByCssSelector:function(a,c){b(a,c).removeClass("aok-hidden")}}})});
/* ******** */
(function(g){var v=window.AmazonUIPageJS||window.P,u=v._namespace||v.attributeErrors,c=u?u("CustomerReviewsGalleryAssets",""):v;c.guardFatal?c.guardFatal(g)(c,window):c.execute(function(){g(c,window)})})(function(g,v,u){g.when("A","cr-jQuery","cr-log-utils","reviews-constants","review-image-assets-loaded").register("review-image-binder",function(c,a,e,b){function l(d,b,f,m,r){if(!(d&&b&&f instanceof a&&m instanceof a&&r instanceof a))return e.logError("Invalid parameters for imageBinder.initializeEventHandlers with ASIN: "+
d+", galleryName: "+b+", $popoverTrigger: "+f+", $thumbnails: "+m+", $galleryLink: "+r,"FATAL"),!1;var c="reviewsLightbox-ready-"+b;m.click(function(){h(d,b);var e=m.index(this);f.click();g.when(c).execute(function(){a("#"+b).trigger("jumpToImageAtIndex",e)})});r.click(function(){h(d,b);f.click();g.when(c).execute(function(){a("#"+b).trigger("hideImmersiveView")})});return!0}function h(a,b){if(!a||!b)return e.logError("Invalid parameters for imageBinder.initializeImageGallery with ASIN: "+a+", galleryName: "+
b,"FATAL"),!1;if(q)return!0;(new ReviewsLightbox(b,"DESKTOP")).initializeForAsin(a);return q=!0}var q=!1,k={};g.when("reviewsLightbox-js").execute(function(){var d=a("#reviews-image-gallery-container"),b=d.attr("data-asin");0<d.length&&b&&l(b,"reviews-image-gallery",d.find(".a-popover-trigger"),d.find(".review-image-tile"),d.find(".reviews-image-gallery-link"))});c.on(b.events.RELOAD_COMPLETE,function(){k={}});return{bindReview:function(d,b,f){var e=new ReviewGallery(f,"DESKTOP"),c=a("#"+b);c.find(".review-image-tile").each(function(b){a(this).click(function(){k[d]||
(e.initializeForReview(d),k[d]=!0);c.find(".a-popover-trigger").click();g.when("reviewsLightbox-ready-"+f).execute(function(){e.render();e.showImageAtIndex(b)})})})},initializeImageGallery:h,initializeEventHandlers:l}});"use strict";g.when("A","cr-jQuery","cr-image-popover-data-fetcher","cr-see-all-images-controller").register("cr-image-popover-controller",function(c,a,e,b){function l(){for(var b=0;b<w.length;b++)b!=t&&(a(w[b]).unbind("click"),a(w[b]).removeClass("cr-lightbox-selected")),a(w[b]).click(h(b))}
function h(a){return function(){d(a)}}function q(){a(u).unbind("click");a(z).unbind("click");a(u).click(function(){var a=parseInt(t,10)+1;d(a);k()});a(z).click(function(){var a=parseInt(t,10)-1;d(a);k()});a(F).mouseenter(function(){k()}).mouseleave(function(){G.animate({opacity:0},100);v.animate({opacity:0},100)})}function k(){var b=.25,d=.25;a(u).css("cursor","pointer");a(z).css("cursor","pointer");var f=e.getReviewIds();if(!x&&t===y.length-1||x&&t===y.length-1&&f.indexOf(A)==f.length-1)b=0,a(u).css("cursor",
"auto");f=e.getReviewIds();if(!x&&0===t||x&&0===t&&0==f.indexOf(A))d=0,a(z).css("cursor","auto");G.animate({opacity:b},100);v.animate({opacity:d},100)}function d(b){if(0<=b&&b<y.length)B.attr("src",y[b]),a(w[t]).removeClass("cr-lightbox-selected"),a(w[b]).addClass("cr-lightbox-selected"),t=b;else if(x){var d=e.getReviewList(),f=e.getReviewIds(),c=f.indexOf(A),h={popover:{$trigger:{context:{}}}};b>t?(c++,c<f.length&&(h.popover.$trigger.context.id=f[c]+"-0",m(h))):(c--,-1<c&&(h.popover.$trigger.context.id=
f[c]+"-"+(d[f[c]].images.length-1),m(h)))}}function p(b){a(C).empty();b.forEach(function(b,d){d===t?a(C).append('\x3cimg src\x3d"'+b+'" class\x3d"cr-lightbox-image-thumbnail cr-lightbox-selected" /\x3e'):a(C).append('\x3cimg src\x3d"'+b+'" class\x3d"cr-lightbox-image-thumbnail"/\x3e')});w=n.find(".cr-lightbox-image-thumbnail");l()}function f(b,f,e,c){n=(x=c||!1)?a("#cr_customers_image_gallery"):a("#"+b+"_image_popover");G=n.find(".cr-lightbox-navigator-button__next");v=n.find(".cr-lightbox-navigator-button__back");
u=n.find(".cr-lightbox-navigator-container__next");z=n.find(".cr-lightbox-navigator-container__back");w=n.find(".cr-lightbox-image-thumbnail");F=n.find(".cr-lightbox-image-viewer");B=F.find(".cr-lightbox-main-image");K=n.find(".cr-lightbox-review-title");L=n.find(".cr-lightbox-review-body");M=n.find(".cr-lightbox-review-origin");D=n.find(".cr-lightbox-review-rating");C=n.find(".cr-lightbox-image-thumbnails");x&&(E=n.find(".cr-lightbox-customer-profile"),N=n.find(".cr-lightbox-customer-profile .a-profile-name"),
O=n.find(".cr-lightbox-customer-profile .a-profile-avatar \x3e img"),H=D.find(".a-icon-alt"));y=f;"string"===typeof f&&(y=f.substring(1,f.length-1).split(","));l();d(r(e).thumbnailId||0);q()}function m(b){var a=e.getReviewList();e.getReviewIds();for(var d=r(b).reviewId,c=[],h=[],m=0;m<a[d].images.length;m++)c.push(a[d].images[m].source),h.push(a[d].images[m].lowResSource);A=d;f(d,c,b,!0);b=A;K.text(a[b].title);D.removeClass();D.addClass("a-icon a-icon-star a-star-"+a[b].starRating+" cr-lightbox-review-rating");
H.text(H.text().replace(/\d([.,]\d)?/,a[b].starRating+".0"));p(h);L.text(a[b].reviewText);M.text(a[b].originDescription);x&&(a=a[b],null===a.customerProfileLink||0===a.customerProfileLink.length?E.css("cursor","initial"):E.css("cursor",""),E.attr("href",a.customerProfileLink),N.text(a.customerName),O.attr("src",a.customerProfileImage));g(!1)}function r(a){return a&&a.popover&&a.popover.$trigger&&a.popover.$trigger.context&&(a=a.popover.$trigger.context.id)&&(a=a.split("-"),1<a.length)?{reviewId:a[0],
thumbnailId:parseInt(a[1],10),seeAllImages:!1}:{seeAllImages:!0}}function J(a){r(a).seeAllImages?g(!0):m(a)}function g(d){n=a("#cr_customers_image_gallery");d?(n.hide(),I.show(),b.updateSeeAllImages(I,m),B&&B.attr("src","")):(n.show(),I.hide(),S.hide(),T.show(),P.removeClass("cr-lightbox-review-row-no-display"),P.addClass("cr-lightbox-review-row"))}var y,t=0,G,v,u,z,w,F,B,A,x=!1,Q=!1,K,L,M,D,C,E,N,O,H,I=a("#seeAllImagesContainer"),n=a("#cr_customers_image_gallery"),S=a(".cr-large-loadingIcon"),P=
a("#crReviewRow"),T=a("#crViewAllImagesLink");return{initImagePopover:f,loadDataAndInitImageGalleryPopover:function(a,b,d,f){e.isDataLoaded()?J(a):e.fetchData(d,b,f,function(b,f){if(b=!Q)a:{b=e.getReviewIds();for(f=0;f<d.length;f++)if(0>b.indexOf(d[f])){b=!1;break a}b=!0}b&&(J(a),Q=!0)})},toggleSeeAllView:g}});"use strict";g.when("A","cr-jQuery","cr-log-utils").register("cr-image-popover-data-fetcher",function(c,a,e){function b(a,b,d){a="/hz/reviews-render/get-reviews-with-media?mediaType\x3dimage\x26asin\x3d"+
a+"\x26csrfToken\x3d"+b;d!==u&&(a+="\x26nextToken\x3d"+d);return a}function l(a,d,m,r,g,R){m=b(d,m,R);c.ajax(m,{method:"get",success:function(b){for(var f in b.reviewsWithMediaList)k[f]=b.reviewsWithMediaList[f];f=Object.keys(k);q=a.slice();for(var c=0;c<f.length;c++)0>a.indexOf(f[c])&&q.push(f[c]);"function"===typeof r&&r(k,q);b.nextToken?l(a,d,b.csrfToken,r,g,b.nextToken):h=!0},error:function(a){e.logCount("ReviewWithImages-DataFetcher-Error");"function"===typeof g&&g()}})}var h=!1,q=[],k={},d=
null;return{fetchData:l,getReviewList:function(){return k},getReviewIds:function(){return q},isDataLoaded:function(){return h},getCustomerImageAltText:function(){d||(d=a(".review-with-images-section .cr-customer-image-thumbnail")[0].getAttribute("alt"));return d}}});"use strict";g.when("A","cr-jQuery","cr-image-popover-data-fetcher").register("cr-see-all-images-controller",function(c,a,e){function b(b,c,f,h){b=a("\x3cdiv\x3e",{class:"cr-thumbnail-preview-tile",css:{background:"url("+b+") 50% 50% no-repeat"},
role:"img",alt:e.getCustomerImageAltText()});b.click(function(){h({popover:{$trigger:{context:{id:c+"-"+f}}}})});return b}function l(a,c,f){for(var d=e.getReviewList(),r=e.getReviewIds(),l=h;h<l+f;){var g=r[k];if(g&&d[g]){k++;for(var p=0;p<d[g].images.length;p++){var t="undefined"===typeof q[g+p]?!0:!1;t&&(a.append(b(d[g].images[p].lowResSource,g,p,c)),h++,0==h%7&&a.append("\x3cbr /\x3e"),q[g+p]=g+p)}}else break}}var h=0,q={},k=0;return{updateSeeAllImages:function(a,b){l(a,b,50);var d=0;a.scroll(function(){var f=
a.scrollTop();200<f-d&&(d=f,l(a,b,50))})}}});"use strict";g.when("cr-A","cr-jQuery","cr-streaming-utils","cr-media-gallery-view","cr-media-gallery-model").register("cr-media-gallery-controller",function(c,a,e,b,g){function h(){return 480<a(v).width()?3:2}function l(){var a=b.getCurrentMasonryItems(),d=h();0<a.length&&(a=b.getPreciseMaxMasonryListHeightItems(a,d),b.setMasonryListHeight(a.heightInPixelOfColumn,"px",a.nItemInColumn*p))}function k(a){if(!c.objectIsEmpty(a)&&!c.objectIsEmpty(a.data)){b.toggleMediaListLoadingState(!0);
var d=g.updateMediaType(a.data.mediaType);b.updateFilterBar(d);g.getMedia(a.data,function(){},function(){},function(){b.toggleMediaListLoadingState(!1)},function(a){"appendFadeIn"===a[0]&&(b.removeMasonryItemLoadingElements(),e.appendFadeIn(a))})}}function d(){a(".a-manually-loaded.cr-mg-image-element").not("[src]").each(function(){var b=a(this);b.is(":visible")&&c.onScreen(b,m)&&c.loadImageManually(b)})}c.on("resize",function(){b.isMediaGalleryPageVisible()?l():f=!0});c.on("scroll",d);var p=8,f=
!1,m=500;return{initialize:l,getNoOfColumns:h,initializeAfterPopoverHide:function(){f&&l();f=!1},initializeMediaFilters:function(a,b){g.setInitialParams(a,b);c.declarative("cr:media-filter","click",c.compositeEventWrapper(k,!0,100))},manualLazyLoadImages:d}});"use strict";g.when("A","cr-jQuery").register("cr-media-gallery-view",function(c,a){return{getCurrentMasonryItems:function(){return a(".cr-mg-masonry-list").find(".cr-mg-masonry-item")},setMasonryListHeight:function(c,b,g){var e=a(".cr-mg-masonry-list-height-control").get(0);
e&&(e.style.setProperty("--height-to-column-width",c+b),e.style.setProperty("--height-in-pixel",g+"px"))},getPreciseMaxMasonryListHeightItems:function(c,b){for(var e=Array(b),h=Array(b),g=0;g<b;g++)e[g]=0,h[g]=0;var k=0;c.each(function(){var d=a(this).children(".cr-mg-ratio-control");e[k%b]+=d.get(0).getBoundingClientRect().height;h[k%b]+=1;k++});c=e.indexOf(Math.max.apply(Math,e));return{heightInPixelOfColumn:e[c],nItemInColumn:h[c]}},isMediaGalleryPageVisible:function(){var c=a(".cr-mg-masonry-list-height-control");
return c?c.is(":visible"):!1},updateFilterBar:function(c){var b="image"===c;c="video"===c;a(".cr-mg-filter-btn-vid").toggleClass("cr-mg-filter-btn-selected",c);a(".cr-mg-filter-btn-img").toggleClass("cr-mg-filter-btn-selected",b)},toggleMediaListLoadingState:function(c){a(".cr-mg-masonry-list-loading").toggleClass("aok-hidden",!c)},removeMasonryItemLoadingElements:function(){a(".cr-mg-masonry-item-loading").remove()}}});"use strict";g.when("cr-A","cr-log-utils","cr-ajax-model").register("cr-media-gallery-model",
function(c,a,e){var b={},g;return{setInitialParams:function(a,c){b.asin=a;b.mediaType=c},updateMediaType:function(a){if("image"===a||"video"===a||"all"===a)b.mediaType=b.mediaType===a?"all":a;return b.mediaType},getMedia:function(h,l,k,d,p){g&&e.abort(g);var f=c.now();a.logCount("GetMedia:Count",1);g=e.post("/hz/reviews-render/ajax/media/get/?ie\x3dUTF8",{params:b,attribution:"getMedia",headers:{"anti-csrftoken-a2z":h.csrfToken},success:function(){var b=c.now()-f;a.logCount("GetMedia:Status",1);a.logCount("GetMedia:RequestTime",
b);l()},error:function(){a.logCount("GetMedia:Status",0);k()},finallyCallback:function(){d();g=0},timeout:3E4,chunk:p,cache:!0},1)}}});"use strict";g.when("A","cr-jQuery").register("cr-review-inline-images-controller",function(c,a){function e(b){return a("#%s-cr-inline-images-preview".replace("%s",b)).find(".cr-review-inline-images-main-image")}c.declarative("cr-review-inline-images-thumbnail-click","click",function(a){var b=a.data.imageSrc;e(a.data.reviewId).attr("src",b)});return{getMainImage:e,
getAllThumbnails:function(b){return a("#%s-cr-inline-images-preview".replace("%s",b)).find(".cr-review-inline-images-thumbnails .cr-review-inline-images-thumbnail")}}});"use strict";g.when("cr-inline-videos-controller","ready").register("cr-inline-videos-module",function(c){c.initialize(!0)});"use strict";g.when("A","reviews-constants","cr-log-utils","cr-inline-videos-view","cr-vse-brila-player-gateway").register("cr-inline-videos-controller",function(c,a,e,b,g){function h(a){b.getPlayerPlaceholders().each(function(f,
e){f=c.$(e);if(!b.isPlayerRequestPending(f)&&(!a||a&&b.isPlayerPlaceholderInViewport(f))){b.markPlayerRequestAsPending(f);e=b.extractVideoAsset(f);var h=c.$("#cr-state-object").data("state");e={videoUrl:e.videoUrl,thumbnailUrl:e.thumbnailUrl,reviewId:e.reviewId,closedCaptions:e.closedCaptions,vseContentId:e.vseContentId,marketplaceId:h.marketplaceId,locale:h.locale,page:h.page||"cr_page",placement:h.page?h.page+"_cr_inline_review":"cr_inline_review"};g.getVideoPlayer("vse_reviews_desktop_"+e.reviewId+
"_"+c.now(),e,l(e),k(f),d(f))}})}function l(a){return!c.objectIsEmpty(a)&&!c.objectIsEmpty(a.vseContentId)&&""!=a.vseContentId}function k(a){return function(d){b.markPlayerRequestAsDone(a);b.renderPlayer(a,d)}}function d(a){return function(d){b.markPlayerRequestAsDone(a);b.showErrorMessage(a);e.logError("Failed loading inline video player: "+JSON.stringify(d),"ERROR")}}function p(b){if(b)c.on(c.constants.BROWSER_EVENTS.SCROLL,function(){h(!0)});c.on(a.events.RELOAD_COMPLETE,function(){h(b)})}return{initialize:function(a){h(a);
p(a)},fetchVideoPlayers:h}});"use strict";g.when("A").register("cr-inline-videos-view",function(c){return{getPlayerPlaceholders:function(){return c.$(".cr-video-desktop-placeholder")},extractVideoAsset:function(a){a=a.data();return{reviewId:a.reviewId,videoUrl:a.videoUrl,thumbnailUrl:a.thumbnailUrl,closedCaptions:a.closedCaptions,vseContentId:a.vseContentId}},markPlayerRequestAsPending:function(a){a.data("playerRequestPending",!0)},markPlayerRequestAsDone:function(a){a.removeData("playerRequestPending");
a.removeClass("cr-video-desktop-placeholder")},isPlayerRequestPending:function(a){a=a.data("playerRequestPending");return"undefined"!==a&&a},isPlayerPlaceholderInViewport:function(a){return c.onScreen(a,800)},renderPlayer:function(a,c){a.html(c)},showErrorMessage:function(a){a.addClass("cr-media-show-error-msg")}}});"use strict";g.when("A","cr-uri-utils","cr-log-utils","cr-ajax-model").register("cr-vse-brila-player-gateway",function(c,a,e,b){function l(a,b,l){var d={requester:"vse_reviews_desktop",
clientPrefix:a,marketplaceID:b.marketplaceId,locale:b.locale,page:b.page,placement:b.placement};l&&b.vseContentId?d.video={contentID:b.vseContentId,contentIDType:"VIDEO_ID"}:(b.videoUrl&&b.thumbnailUrl&&b.reviewId||e.logCount(h("vse_player:${placement}:incomplete_video_payload",b),1),d.video={videoURL:b.videoUrl,imageURL:b.thumbnailUrl,contentID:b.reviewId,contentIDType:"EXTERNAL_VIDEO_ID"},c.objectIsEmpty(b.closedCaptions)||""==b.closedCaptions||(d.video.closedCaptions=b.closedCaptions));g.now("Brila").execute("vse-assets-check",
function(a){a!==u&&(d.excludeAssets=["Brila","VSEPlayer"])});return d}function h(a,b){return a.replace("${placement}",b.placement)}var q=a.getDomainRealmBaseUrl()+"vap/ew/subcomponent/vseplayer";return{getVideoPlayer:function(a,d,g,f,m){var k=c.now();a={params:l(a,d,g),paramsFormat:"json",crossDomain:!0,method:"post",contentType:"application/json",withCredentials:!0,timeout:4E3,success:function(a){var b=c.now()-k;e.logCount(h("vse_player:${placement}:load:status",d),1);e.logCount(h("vse_player:${placement}:load:request_time",
d),b);"function"===typeof f&&f(a)},error:function(a){e.logCount(h("vse_player:${placement}:load:status",d),0);"function"===typeof m&&m(a)}};e.logCount(h("vse_player:${placement}:load:count",d),1);b.post(q,a,2)}}})});
/* ******** */
(function(g){var m=window.AmazonUIPageJS||window.P,p=m._namespace||m.attributeErrors,e=p?p("CustomerReviewsFilteringAssets",""):m;e.guardFatal?e.guardFatal(g)(e,window):e.execute(function(){g(e,window)})})(function(g,m,p){g.when("cr-A","cr-jQuery","cr-filtering-view","cr-filtering-model","cr-global-view","reviews-constants","cr-streaming-utils").register("cr-filtering-controller",function(e,f,b,d,l,c,k){function h(n){var a=!1,c=!1;n.toggleFilters&&(c=!0);d.setASIN(b.getLoadedFilterParam("asin"));
a=d.setReviewerType(n.reviewerType,c)||a;a=d.setFormatType(n.formatType,c)||a;a=d.setFilterByKeyword(n.filterByKeyword,c)||a;a=d.setFilterByLanguage(n.filterByLanguage,c)||a;a=d.setSortOrder(n.sortOrder,c)||a;a=d.setStarFilter(n.filterByStar,c)||a;a=d.setPageNumber(n.pageNumber,c)||a;a=d.setHeightFilter(n.filterByHeight,c)||a;return a=d.setWeightFilter(n.filterByWeight,c)||a}function q(a){if(h(a.data)||a.data.forceReload)a.data.sortOrder&&b.setSortDropdown(a.data.sortOrder),b.hideReviewLoadError(),
b.hideReviews(),b.showLoadingSpinner(),e.trigger(c.events.FILTER_APPLY_BEGIN,a),d.getReviews(function(){b.showReviews();"filterByHeight"===d.getActiveTab()&&b.scrollToFilterIndex("filterByHeight");"filterByWeight"===d.getActiveTab()&&b.scrollToFilterIndex("filterByWeight");e.trigger(c.events.FILTER_APPLY_SUCCESS,a)},function(){b.showReviewLoadError();e.trigger(c.events.FILTER_APPLY_ERROR,a)},function(){b.hideLoadingSpinner();e.trigger(c.events.FILTER_APPLY_DONE,a);e.trigger(c.events.RELOAD_COMPLETE)},
function(a){"appendFadeIn"===a[0]?k.appendFadeIn(a):"replace"===a[0]&&k.replace(a)},l.getReftag(a)),a.data.scrollToSelector&&l.scrollTo(a.data.scrollToSelector,0)}function g(a){a&&a.data&&q(a)}function a(a){a&&a.data&&a.$target&&a.data.filterType&&(a.data[a.data.filterType]=a.$target.val(),q(a))}function r(a){a&&a.data&&a.data.filterType&&(b.deactivateFilterTabHeaders(),b.activateFilterTabHeader(a.data.filterType),b.changeFilterOptionsTo(a.data.filterType),d.setActiveTab(a.data.filterType),"filterByHeight"!==
a.data.filterType&&"filterByWeight"!==a.data.filterType||b.scrollToFilterIndex(a.data.filterType))}d.setReviewsAjaxUrl(b.getReviewsAjaxUrl());b.enableDesktopDPFilterDropdown();e.declarative(c.events.FILTER_APPLY,"click",e.compositeEventWrapper(g,!0,100));e.declarative(c.events.FILTER_CHANGE,"change",e.compositeEventWrapper(a,!0,100));e.declarative(c.events.FILTER_TAB_CLICKED,"click",r);d.setReviewerType(b.getLoadedFilterParam("reviewerType"),!1);d.setFormatType(b.getLoadedFilterParam("formatType"),
!1);d.setFilterByKeyword(b.getLoadedFilterParam("filterByKeyword"),!1);d.setFilterByLanguage(b.getLoadedFilterParam("filterByLanguage"),!1);d.setStarFilter(b.getLoadedFilterParam("filterByStar"),!1);d.setSortOrder(b.getLoadedFilterParam("sortOrder"),!1);d.setPageNumber(b.getLoadedFilterParam("pageNumber"),!1);d.setHeightFilter(b.getLoadedFilterParam("filterByHeight"),!1);d.setWeightFilter(b.getLoadedFilterParam("filterByWeight"),!1);d.setLanguage(b.getLoadedFilterParam("languageOfPreference"));b.getLoadedFilterParam("showLanguageFilter")?
d.setActiveTab("filterByLanguage"):b.getLoadedFilterParam("showHeightFilter")&&(d.setActiveTab("filterByHeight"),b.scrollToFilterIndex("filterByHeight"));return{setFilterParams:h,onFilterApply:g,onFilterChange:a,onFilterTabClicked:r}});"use strict";g.when("A","cr-ajax-model","ready").register("cr-filtering-model",function(e,f){function b(){return h.asin||""}function d(){return g||""}function l(a,c){c?h[a]=c:delete h[a]}function c(a,c,b){var d=!1;a&&c!==p&&(d=k(a)!==c,!d&&b&&(c="CLEAR_VALUE",d=!0),
l(a,c));return d}function k(a){return h[a]||""}var h={},g="",m;return{getReviews:function(a,c,b,d,l){var e=g;m&&f.abort(m);l&&(e+="ref\x3d"+l);m=f.post(e,{params:h,attribution:"getFilteredReviews",success:a,error:c,finallyCallback:function(){b();m=0},chunk:d})},setASIN:function(a){var c=b()!==a;l("asin",a);return c},getASIN:b,setReviewsAjaxUrl:function(a){var c=d()!==a;g=a||"";return c},getReviewsAjaxUrl:d,setReviewerType:function(a,b){return c("reviewerType",a,b)},getReviewerType:function(){return k("reviewerType")},
setFormatType:function(a,b){return c("formatType",a,b)},getFormatType:function(){return k("formatType")},setFilterByKeyword:function(a,b){return c("filterByKeyword",a,b)},getFilterByKeyword:function(){return k("filterByKeyword")},setFilterByLanguage:function(a,b){return c("filterByLanguage",a,b)},getFilterByLanguage:function(){return k("filterByLanguage")},setSortOrder:function(a,b){return c("sortBy",a,b)},getSortOrder:function(){return k("sortBy")},setStarFilter:function(a,b){return c("filterByStar",
a,b)},getStarFilter:function(){return k("filterByStar")},setPageNumber:function(a,b){return c("pageNumber",a,b)},getPageNumber:function(){return k("pageNumber")},setHeightFilter:function(a,b){return c("filterByHeight",a,b)},getHeightFilter:function(){return k("filterByHeight")},setWeightFilter:function(a,b){return c("filterByWeight",a,b)},getWeightFilter:function(){return k("filterByWeight")},getFilterParams:function(){return h||{}},updateFilterParam:l,setActiveTab:function(a){return l("activeTab",
a)},getActiveTab:function(){return k("activeTab")},setLanguage:function(a){return l("language",a)}}});"use strict";g.when("cr-A","cr-jQuery","a-dropdown","ready").register("cr-filtering-view",function(e,f,b){function d(b){return(f("#cr-state-object").data("state")||{})[b]||""}return{getReviewsAjaxUrl:function(){return(f("#cr-state-object").data("state")||{}).reviewsAjaxUrl||""},showLoadingSpinner:function(){var b=e.getValueFromState("onLoadShowHideElements");f(b).removeClass("aok-hidden")},hideLoadingSpinner:function(){var b=
e.getValueFromState("onLoadShowHideElements");f(b).addClass("aok-hidden")},hideReviews:function(){f(".filterable-reviews-content").addClass("aok-hidden")},showReviews:function(){f(".filterable-reviews-content").removeClass("aok-hidden")},showReviewLoadError:function(){f(".review-load-error").removeClass("aok-hidden")},hideReviewLoadError:function(){f(".review-load-error").addClass("aok-hidden")},deactivateFilterTabHeaders:function(){f(".cr-tab-header-text").removeClass("cr-tab-active")},activateFilterTabHeader:function(b){f(".cr-tab-header-text-"+
b).addClass("cr-tab-active")},changeFilterOptionsTo:function(b){f(".cr-tab-content").addClass("aok-hidden");f(".cr-tab-content-"+b).removeClass("aok-hidden")},getLoadedFilterParam:d,setSortDropdown:function(d){b.getSelect("cm-cr-sort-dropdown").setValue(d)},scrollToFilterIndex:function(b){var c;c=0;var e;e=d("isCardTreatmentEnabled")?f(".cr-horizontal-scroll-list-cardify-padding ul \x3e *:first-child"):f(".cr-horizontal-scroll-list-padding ul \x3e *:first-child");var h=f(m).width();b=f("ul#"+b+"-button-list")[0];
if(e===p||h===p||b===p)c=-1;else{var g=parseInt(b.dataset.index);e=parseInt(e.css("padding-left").replace("px",""));if(-1!==g){c=e-h/2;for(h=0;h<g;h++)c+=f("#"+b.children[h].firstElementChild.id).outerWidth(!0);c+=f("#"+b.children[g].firstElementChild.id).outerWidth(!0)/2}}0>c||f(".cr-filter-scroll-container").animate({scrollLeft:c},50)},enableDesktopDPFilterDropdown:function(){f("#cm-cr-dp-review-sort-type").removeClass("aok-hidden")}}});"use strict";g.when("cr-A","cr-lighthut-terms-view","reviews-constants",
"cr-log-utils").register("cr-lighthut-terms-controller",function(e,f,b,d){function g(b){b&&b.filterByKeyword!==p&&(f.setSelected(b.filterByKeyword),d.incrementCount("LighthutTermClicked"))}e.on(b.events.FILTER_APPLY_BEGIN,e.compositeEventWrapper(function(b){b&&b.data&&g(b.data)}));return{onFilterApplied:g}});"use strict";g.when("A","cr-jQuery","ready").register("cr-lighthut-terms-view",function(e,f){return{setSelected:function(b){b=b.replace(/ /g,"_");var d=(b=f("#cr-lighthouse-term-"+b))&&b.hasClass("cr-lighthut-term-selected");
f(".cr-lighthut-term-selected").removeClass("cr-lighthut-term-selected");d||b.addClass("cr-lighthut-term-selected")}}})});
/* ******** */
