# Generated by Django 4.1.1 on 2022-09-09 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookingData',
            fields=[
                ('booking_id', models.AutoField(primary_key=True, serialize=False)),
                ('date_time', models.DateTimeField()),
                ('reviews', models.TextField(blank=True, null=True)),
                ('ratings', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('equip_id', models.AutoField(primary_key=True, serialize=False)),
                ('equip_name', models.CharField(max_length=255)),
                ('rent_per_slot', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('facility_id', models.AutoField(primary_key=True, serialize=False)),
                ('facility_name', models.CharField(max_length=255)),
                ('facility_location', models.CharField(max_length=255)),
                ('facility_phone', models.CharField(max_length=255, unique=True)),
                ('facility_email', models.CharField(max_length=255)),
                ('facility_password', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='FacilitySports',
            fields=[
                ('facility_sport_id', models.AutoField(primary_key=True, serialize=False)),
                ('cost_per_slot', models.IntegerField()),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='models.facility')),
            ],
        ),
        migrations.CreateModel(
            name='Slots',
            fields=[
                ('slot_id', models.AutoField(primary_key=True, serialize=False)),
                ('slot_time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Sports',
            fields=[
                ('sport_id', models.AutoField(primary_key=True, serialize=False)),
                ('sport_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=255)),
                ('user_phone', models.CharField(max_length=255, unique=True)),
                ('user_email', models.CharField(max_length=255)),
                ('user_password', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SlotsBookedForBookingId',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='models.bookingdata')),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='models.slots')),
            ],
        ),
        migrations.CreateModel(
            name='SlotsAvailableForFacilitySports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facility_sport', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='models.facilitysports')),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='models.slots')),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('invoice_id', models.AutoField(primary_key=True, serialize=False)),
                ('total_cost', models.IntegerField()),
                ('invoice_pdf', models.TextField()),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='models.bookingdata')),
            ],
        ),
        migrations.AddField(
            model_name='facilitysports',
            name='sport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='models.sports'),
        ),
        migrations.CreateModel(
            name='EquipmentsRentedForBookingId',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='models.bookingdata')),
                ('equip', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='models.equipment')),
            ],
        ),
        migrations.AddField(
            model_name='equipment',
            name='sport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='models.sports'),
        ),
        migrations.AddField(
            model_name='bookingdata',
            name='facility_sport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='models.facilitysports'),
        ),
        migrations.AddField(
            model_name='bookingdata',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='models.user'),
        ),
    ]
