# Generated by Django 4.1.1 on 2022-09-09 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0002_alter_all_users_designation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='all_users',
            name='Designation',
        ),
        migrations.AddField(
            model_name='all_users',
            name='Last_Name',
            field=models.CharField(default='', max_length=20),
        ),
    ]
