# Generated by Django 4.1.1 on 2022-09-09 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0004_all_users_designation_all_users_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='all_users',
            name='Designation',
        ),
        migrations.RemoveField(
            model_name='all_users',
            name='First_Name',
        ),
        migrations.RemoveField(
            model_name='all_users',
            name='Last_Name',
        ),
        migrations.RemoveField(
            model_name='all_users',
            name='username',
        ),
    ]
