# Generated by Django 4.1.1 on 2022-09-09 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0005_remove_all_users_designation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='all_users',
            name='Designation',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AddField(
            model_name='all_users',
            name='First_Name',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='all_users',
            name='Last_Name',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='all_users',
            name='username',
            field=models.CharField(default='', max_length=30),
        ),
    ]
