# Generated by Django 4.1.1 on 2022-09-09 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Admin', '0007_delete_all_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='All_Users',
            fields=[
                ('username', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('First_Name', models.CharField(max_length=20)),
                ('Last_Name', models.CharField(max_length=20)),
                ('Designation', models.CharField(max_length=25)),
            ],
        ),
    ]
