# Generated by Django 4.1.1 on 2022-09-12 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0008_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject_Details',
            fields=[
                ('subject_code', models.CharField(max_length=35)),
                ('subject_name', models.CharField(max_length=6)),
                ('sub_subject_name', models.CharField(max_length=35, primary_key=True, serialize=False)),
            ],
        ),
    ]
