# Generated by Django 4.1.1 on 2022-09-12 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0009_subject_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject_details',
            name='subject_code',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='subject_details',
            name='subject_name',
            field=models.CharField(max_length=35),
        ),
    ]
