# Generated by Django 4.1.1 on 2022-09-12 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0010_alter_subject_details_subject_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='classes_details',
            fields=[
                ('class_code', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('class_name', models.CharField(max_length=35)),
            ],
        ),
    ]
