# Generated by Django 4.1.1 on 2022-09-12 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0012_alter_classes_details_class_code_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='classes_details',
        ),
    ]
