# Generated by Django 4.1.1 on 2022-09-12 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0014_classes_details'),
    ]

    operations = [
        migrations.DeleteModel(
            name='classes_details',
        ),
    ]
