# Generated by Django 4.1.1 on 2022-09-12 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0012_delete_classes_details'),
        ('Admin', '0016_classes_details'),
    ]

    operations = [
    ]
