# Generated by Django 4.1.1 on 2022-09-12 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0017_merge_20220912_0738'),
    ]

    operations = [
        migrations.CreateModel(
            name='class_details',
            fields=[
                ('class_code', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('class_name', models.CharField(max_length=35)),
            ],
        ),
    ]
