# Generated by Django 4.1.1 on 2022-09-12 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Faculty', '0001_initial'),
        ('Admin', '0019_alter_subject_details_sub_subject_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='batch_details',
            fields=[
                ('batch_id', models.IntegerField(primary_key=True, serialize=False)),
                ('faculty_name', models.CharField(max_length=40)),
                ('time', models.TimeField()),
                ('class_code', models.ForeignKey(max_length=6, on_delete=django.db.models.deletion.CASCADE, to='Admin.class_details')),
                ('facul_username', models.ForeignKey(max_length=35, on_delete=django.db.models.deletion.CASCADE, to='Faculty.faculty_details')),
                ('subject_code', models.ForeignKey(max_length=6, on_delete=django.db.models.deletion.CASCADE, to='Admin.subject_details')),
            ],
        ),
    ]
