# Generated by Django 4.1.1 on 2022-09-12 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0020_batch_details'),
    ]

    operations = [
        migrations.DeleteModel(
            name='All_Users',
        ),
    ]
