# Generated by Django 4.1.1 on 2022-09-30 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0021_delete_all_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='faculty_details',
            fields=[
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('facul_username', models.CharField(max_length=35, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=12)),
                ('gender', models.CharField(max_length=6)),
                ('date_of_birth', models.DateField()),
                ('main_subject', models.CharField(max_length=35)),
                ('department', models.CharField(max_length=35)),
                ('joining_date', models.DateField()),
                ('qualification', models.CharField(max_length=35)),
                ('experience', models.IntegerField()),
                ('user_type', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='student_details',
            fields=[
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('stud_username', models.CharField(max_length=35, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=15)),
                ('gender', models.CharField(max_length=6)),
                ('date_of_birth', models.DateField(default=None)),
                ('father_name', models.CharField(max_length=35)),
                ('roll_no', models.IntegerField()),
                ('user_type', models.CharField(default='', max_length=15)),
                ('status', models.BooleanField(default=False)),
                ('class_name', models.ForeignKey(max_length=35, on_delete=django.db.models.deletion.CASCADE, to='Admin.class_details')),
            ],
        ),
        migrations.CreateModel(
            name='feedback_by_student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=12)),
                ('year', models.IntegerField()),
                ('Q1', models.IntegerField()),
                ('Q2', models.IntegerField()),
                ('Q3', models.IntegerField()),
                ('Q4', models.IntegerField()),
                ('Q5', models.IntegerField()),
                ('Q6', models.IntegerField()),
                ('Q7', models.IntegerField()),
                ('Q8', models.IntegerField()),
                ('remarks', models.TextField(max_length=200)),
                ('GPA', models.DecimalField(decimal_places=2, max_digits=3)),
                ('stud_username', models.ForeignKey(max_length=35, on_delete=django.db.models.deletion.CASCADE, to='Admin.student_details')),
                ('to_faculty', models.ForeignKey(max_length=35, on_delete=django.db.models.deletion.CASCADE, to='Admin.faculty_details')),
            ],
        ),
        migrations.CreateModel(
            name='feedback_by_faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=12)),
                ('year', models.IntegerField()),
                ('Q1', models.IntegerField()),
                ('Q2', models.IntegerField()),
                ('Q3', models.IntegerField()),
                ('Q4', models.IntegerField()),
                ('Q5', models.IntegerField()),
                ('remarks', models.TextField(max_length=200)),
                ('GPA', models.DecimalField(decimal_places=2, max_digits=3)),
                ('facul_username', models.ForeignKey(max_length=35, on_delete=django.db.models.deletion.CASCADE, to='Admin.faculty_details')),
                ('to_student', models.ForeignKey(max_length=35, on_delete=django.db.models.deletion.CASCADE, to='Admin.student_details')),
            ],
        ),
        migrations.AlterField(
            model_name='batch_details',
            name='facul_username',
            field=models.ForeignKey(max_length=35, on_delete=django.db.models.deletion.CASCADE, to='Admin.faculty_details'),
        ),
    ]
