# Generated by Django 4.1.1 on 2022-10-04 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0022_faculty_details_student_details_feedback_by_student_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student_details',
            old_name='class_name',
            new_name='class_name_id',
        ),
    ]
