# Generated by Django 4.1.1 on 2022-10-04 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0023_rename_class_name_student_details_class_name_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student_details',
            old_name='class_name_id',
            new_name='class_name',
        ),
    ]
