# Generated by Django 4.1.1 on 2022-10-06 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0025_testmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='testmodel',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
