# Generated by Django 4.1.1 on 2022-10-06 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0026_testmodel_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testmodel',
            name='id',
        ),
        migrations.AlterField(
            model_name='testmodel',
            name='username',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
