# Generated by Django 4.1.1 on 2022-10-06 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0027_remove_testmodel_id_alter_testmodel_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student_details',
            name='class_name',
        ),
        migrations.RemoveField(
            model_name='student_details',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='student_details',
            name='father_name',
        ),
        migrations.RemoveField(
            model_name='student_details',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='student_details',
            name='roll_no',
        ),
        migrations.RemoveField(
            model_name='student_details',
            name='status',
        ),
        migrations.RemoveField(
            model_name='student_details',
            name='user_type',
        ),
    ]
