# Generated by Django 4.1.1 on 2022-10-06 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0028_remove_student_details_class_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_details',
            name='gender',
            field=models.CharField(default='Male', max_length=6),
        ),
    ]
