# Generated by Django 4.1.1 on 2022-10-06 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0029_student_details_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_details',
            name='gender',
            field=models.CharField(max_length=6),
        ),
    ]
