# Generated by Django 4.1.1 on 2022-10-06 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0030_alter_student_details_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_details',
            name='date_of_birth',
            field=models.DateField(default=None),
        ),
    ]
