# Generated by Django 4.1.1 on 2022-10-06 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0031_student_details_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_details',
            name='father_name',
            field=models.CharField(default=None, max_length=35),
        ),
    ]
