# Generated by Django 4.1.1 on 2022-10-06 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0032_student_details_father_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_details',
            name='roll_no',
            field=models.IntegerField(default=None),
        ),
    ]
