# Generated by Django 4.1.1 on 2022-10-06 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0033_student_details_roll_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_details',
            name='user_type',
            field=models.CharField(default='', max_length=15),
        ),
    ]
