# Generated by Django 4.1.1 on 2022-10-06 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0035_student_details_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_details',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
