# Generated by Django 4.1.1 on 2022-10-06 07:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0036_remove_student_details_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_details',
            name='class_name',
            field=models.ForeignKey(default='9th', max_length=35, on_delete=django.db.models.deletion.CASCADE, to='Admin.class_details'),
        ),
    ]
