# Generated by Django 4.1.1 on 2022-10-06 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0037_student_details_class_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student_details',
            name='status',
        ),
    ]
