# Generated by Django 4.1.1 on 2022-10-06 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0038_remove_student_details_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student_details',
            name='class_name',
        ),
    ]
