# Generated by Django 4.1.1 on 2022-10-06 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0040_student_details_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student_details',
            name='status',
        ),
    ]
