# Generated by Django 4.1.1 on 2022-10-06 08:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0042_student_details_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_details',
            name='class_code',
            field=models.ForeignKey(default='MM1004', max_length=6, on_delete=django.db.models.deletion.CASCADE, to='Admin.class_details'),
        ),
    ]
