# Generated by Django 4.1.1 on 2022-10-07 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0043_student_details_class_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_details',
            name='date_of_birth',
            field=models.CharField(max_length=20),
        ),
    ]
