# Generated by Django 4.1.1 on 2022-10-12 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0044_alter_student_details_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty_details',
            name='date_of_birth',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='faculty_details',
            name='joining_date',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='faculty_details',
            name='main_subject',
            field=models.CharField(max_length=6),
        ),
    ]
