# Generated by Django 4.1.1 on 2022-10-12 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0045_alter_faculty_details_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty_details',
            name='main_subject',
            field=models.CharField(max_length=35),
        ),
    ]
