# Generated by Django 4.1.1 on 2022-10-12 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0046_alter_faculty_details_main_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty_details',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
