# Generated by Django 4.1.1 on 2022-10-12 05:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0047_faculty_details_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty_details',
            name='main_subject',
            field=models.ForeignKey(max_length=35, on_delete=django.db.models.deletion.CASCADE, to='Admin.subject_details'),
        ),
    ]
