# Generated by Django 4.1.1 on 2022-10-12 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0048_alter_faculty_details_main_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='department_details',
            fields=[
                ('department_code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('department_name', models.CharField(max_length=35)),
            ],
        ),
    ]
