# Generated by Django 4.1.1 on 2022-10-12 05:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0049_department_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty_details',
            name='department',
            field=models.ForeignKey(max_length=10, on_delete=django.db.models.deletion.CASCADE, to='Admin.department_details'),
        ),
        migrations.AlterField(
            model_name='faculty_details',
            name='main_subject',
            field=models.ForeignKey(max_length=6, on_delete=django.db.models.deletion.CASCADE, to='Admin.subject_details'),
        ),
    ]
