# Generated by Django 4.1.1 on 2022-10-12 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0050_alter_faculty_details_department_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subject_details',
            old_name='sub_subject_name',
            new_name='category',
        ),
    ]
