# Generated by Django 4.1.1 on 2022-10-14 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0051_rename_sub_subject_name_subject_details_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty_details',
            name='date_of_birth',
            field=models.CharField(max_length=60),
        ),
    ]
