# Generated by Django 4.1.1 on 2022-10-14 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0052_alter_faculty_details_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_details',
            name='date_of_birth',
            field=models.CharField(max_length=60),
        ),
    ]
