# Generated by Django 4.1.1 on 2022-10-17 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0053_alter_student_details_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class_details',
            name='class_code',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='subject_details',
            name='subject_code',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
