# Generated by Django 4.1.1 on 2022-10-18 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0054_alter_class_details_class_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_details',
            name='class_code',
            field=models.ForeignKey(max_length=6, on_delete=django.db.models.deletion.CASCADE, to='Admin.class_details'),
        ),
    ]
