# Generated by Django 4.1.1 on 2022-10-19 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0055_alter_student_details_class_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty_details',
            name='joining_date',
            field=models.CharField(max_length=60),
        ),
    ]
