# Generated by Django 5.2.4 on 2025-07-14 06:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Directors',
            fields=[
                ('director_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True, unique=True)),
            ],
            options={
                'db_table': 'Directors',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('movie_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('genre', models.CharField(blank=True, max_length=50, null=True)),
                ('duration_minutes', models.IntegerField(blank=True, null=True)),
                ('current_views', models.IntegerField(blank=True, null=True)),
                ('max_views', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Movies',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Users',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Moviedirectors',
            fields=[
                ('pk', models.CompositePrimaryKey('director_id', 'movie_id', blank=True, editable=False, primary_key=True, serialize=False)),
                ('director', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='MovieSql.directors')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='MovieSql.movies')),
            ],
            options={
                'db_table': 'MovieDirectors',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Watchhistory',
            fields=[
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('watch_date', models.DateField(blank=True, null=True)),
                ('movie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='MovieSql.movies')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='MovieSql.users')),
            ],
            options={
                'db_table': 'WatchHistory',
                'managed': True,
            },
        ),
    ]
