# Generated by Django 5.2.4 on 2025-07-14 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MovieSql', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchhistory',
            name='watch_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
