# Generated by Django 5.2.4 on 2025-07-14 10:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MovieSql', '0002_alter_watchhistory_watch_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moviedirectors',
            name='pk',
        ),
        migrations.AddField(
            model_name='moviedirectors',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='moviedirectors',
            name='director',
            field=models.ForeignKey(db_column='director_id', on_delete=django.db.models.deletion.DO_NOTHING, to='MovieSql.directors'),
        ),
        migrations.AlterField(
            model_name='moviedirectors',
            name='movie',
            field=models.ForeignKey(db_column='movie_id', on_delete=django.db.models.deletion.DO_NOTHING, to='MovieSql.movies'),
        ),
    ]
