# Generated by Django 5.2.4 on 2025-07-14 10:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MovieSql', '0003_remove_moviedirectors_pk_moviedirectors_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviedirectors',
            name='director',
            field=models.ForeignKey(db_column='director_id', on_delete=django.db.models.deletion.CASCADE, to='MovieSql.directors'),
        ),
        migrations.AlterField(
            model_name='moviedirectors',
            name='movie',
            field=models.ForeignKey(db_column='movie_id', on_delete=django.db.models.deletion.CASCADE, to='MovieSql.movies'),
        ),
    ]
