# Generated by Django 5.2.4 on 2025-07-14 12:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MovieSql', '0004_alter_moviedirectors_director_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchhistory',
            name='movie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MovieSql.movies'),
        ),
        migrations.AlterField(
            model_name='watchhistory',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MovieSql.users'),
        ),
    ]
