# Generated by Django 5.2.4 on 2025-07-15 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MovieSql', '0005_alter_watchhistory_movie_alter_watchhistory_user'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='moviedirectors',
            unique_together={('director', 'movie')},
        ),
    ]
