# Generated by Django 5.2.4 on 2025-07-15 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MovieSql', '0006_alter_moviedirectors_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
