# Generated by Django 5.2.4 on 2025-07-15 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MovieSql', '0007_alter_users_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='users',
            options={'managed': False},
        ),
    ]
