import { maxDaysAllowedForExclusionParameterResult, rangeTypeMap } from "../constants/MarketingConstant";

const FormHelper = () => {


    const getParametersFormForpathlabConf = (parameters,helpers) => {

        let parametersOptions = [];
        Object.entries(parameters).map(([key, value]) => {
            parametersOptions.push(helpers.createOption(key, value, value));
        });
        let paramRangeOptions = Object.keys(rangeTypeMap).map(label => {
            const value = rangeTypeMap[label];
            return helpers.createOption(label, label, value);
        });
        let paramCombinationValue = [];
        ['and','or'].map((each)=> {
            paramCombinationValue.push(helpers.createOption(each, each, each));
            })
        let timeDurationOptions = [];
        [3,6,9,12,15,18,21,24].map((each)=> {
            timeDurationOptions.push(helpers.createOption(each, each, each));
        })
        
        const getParametersFormForpathlabConf = {
            "htmlElementType": "FORM",
            "id": "getParametersFormForpathlabConf",
            "label": null,
            "name": null,
            "value": null,
            "className": "mb-3",
            "readOnly": false,
            "disabled": false,
            "autofocus": false,
            "required": false,
            "style": null,
            "attributes": null,
            "message": null,
            "htmlActions": null,
            "elementSize": null,
            "defaultValue": null,
            "helperText": null,
            "labelClassName": "small",
            "htmlGroups": [
                {
                    "htmlElementType": "ELEMENTGROUP",
                    "id": "group1",
                    "label": null,
                    "name": null,
                    "value": null,
                    "className": "row g-3",
                    "readOnly": false,
                    "disabled": false,
                    "autofocus": false,
                    "required": false,
                    "style": null,
                    "attributes": null,
                    "message": null,
                    "htmlActions": null,
                    "elementSize": null,
                    "defaultValue": null,
                    "helperText": null,
                    "labelClassName": null,
                    "groups": [{
                        "htmlElementType": "ELEMENTGROUP",
                        "id": "group2",
                        "label": null,
                        "name": null,
                        "value": null,
                        "className": "w-auto",
                        "readOnly": false,
                        "disabled": false,
                        "autofocus": false,
                        "required": false,
                        "style": null,
                        "attributes": null,
                        "message": null,
                        "htmlActions": null,
                        "elementSize": null,
                        "defaultValue": null,
                        "helperText": null,
                        "labelClassName": null,
                        "groups": null,
                        "groupElements": [
                            {
                                "htmlElementType": "BUTTON",
                                "id": "addParameter",
                                "label": "Add",
                                "name": null,
                                "value": null,
                                "className": "btn btn-success  px-4 py-2",
                                "readOnly": false,
                                "disabled": true,
                                "autofocus": false,
                                "required": false,
                                "style": {"height": "50px"},
                                "attributes": null,
                                "message": null,
                                "htmlActions": null,
                                "elementSize": null,
                                "defaultValue": null,
                                "helperText": null,
                                "labelClassName": null,
                                "src": null,
                                "href": null,
                                "reset": false,
                                "submit": false,
                                "variant": null,
                                "hidden": false
                            },
                        ],
                    },
                    {
                        "htmlElementType": "ELEMENTGROUP",
                        "id": "group3",
                        "label": null,
                        "name": null,
                        "value": null,
                        "className": "w-auto",
                        "readOnly": false,
                        "disabled": false,
                        "autofocus": false,
                        "required": false,
                        "style": null,
                        "attributes": null,
                        "message": null,
                        "htmlActions": null,
                        "elementSize": null,
                        "defaultValue": null,
                        "helperText": null,
                        "labelClassName": null,
                        "groups": null,
                        "groupElements": [
                            {
                                "htmlElementType": "BUTTON",
                                "id": "clear",
                                "label": "Clear",
                                "name": null,
                                "value": null,
                                "className": "  brand-secondary btn px-4 py-2",
                                "variant":"",
                                "style": {"height": "50px"},
                                "labelClassName": null,
                                "reset": true,
                            }
                        ],
                    }],
                    "groupElements": [
                        {
                            "htmlElementType": "DATALIST",
                            "id": "parameterName",
                            "label": "Select Parameter",
                            "name": null,
                            "value": null,
                            "className": null,
                            "readOnly": false,
                            "disabled": false,
                            "autofocus": false,
                            "required": false,
                            "style": null,
                            "attributes": null,
                            "message": null,
                            "htmlActions": null,
                            "elementSize": null,
                            "defaultValue": null,
                            "helperText": null,
                            "labelClassName": "w-100",
                            "values": parametersOptions,
                            "multiple": false,
                            "considerInputText": false,
                            "dataListClassName": " col-12 col-lg-4 col-md-4 col-xl-3 col-xxl-2",
                            "hidden": false
                        },
                        {
                            "htmlElementType": "DATALIST",
                            "id": "rangeType",
                            "label": "Select Range Type",
                            "name": null,
                            "value": null,
                            "className": null,
                            "readOnly": false,
                            "disabled": true,
                            "autofocus": false,
                            "required": false,
                            "style": null,
                            "attributes": null,
                            "message": null,
                            "htmlActions": null,
                            "elementSize": null,
                            "defaultValue": null,
                            "helperText": null,
                            "labelClassName": "w-100",
                            "values": paramRangeOptions,
                            "multiple": false,
                            "considerInputText": false,
                            "dataListClassName": " col-12 col-lg-4 col-md-4 col-xl-3 col-xxl-2",
                            "hidden": false
                        },
                        {
                            "htmlElementType": "INPUT",
                            "id": "minValue",
                            "label": "Enter Min Value",
                            "name": null,
                            "value": null,
                            "className": null,
                            "readOnly": false,
                            "disabled": true,
                            "autofocus": false,
                            "required": false,
                            "style": null,
                            "attributes": null,
                            "message": null,
                            "htmlActions": null,
                            "elementSize": null,
                            "defaultValue": null,
                            "helperText": null,
                            "labelClassName": " col-12 col-lg-4 col-md-4 col-xl-3 col-xxl-2",
                            "type": "number",
                            "regex": "^-?[0-9]+(.[0-9]{1,2})?$",
                            "minLength": null,
                            "maxLength": null,
                            "min": 1,
                            "max": null,
                            "placeholder": null,
                            "clearIcon": false,
                            "hidden": false
                        },
                        {
                            "htmlElementType": "INPUT",
                            "id": "maxValue",
                            "label": "Enter Max Value",
                            "name": null,
                            "value": null,
                            "className": null,
                            "readOnly": false,
                            "disabled": true,
                            "autofocus": false,
                            "required": false,
                            "style": null,
                            "attributes": null,
                            "message": null,
                            "htmlActions": null,
                            "elementSize": null,
                            "defaultValue": null,
                            "helperText": null,
                            "labelClassName": " col-12 col-lg-4 col-md-4 col-xl-3 col-xxl-2",
                            "type": "number",
                            "regex": "^-?[0-9]+(.[0-9]{1,2})?$",
                            "minLength": null,
                            "maxLength": null,
                            "min": 1,
                            "max": null,
                            "placeholder": null,
                            "clearIcon": false,
                            "hidden": false
                        },
                        {
                            "htmlElementType": "INPUT",
                            "id": "absoluteValue",
                            "label": "Enter absolute value",
                            "name": null,
                            "value": null,
                            "className": null,
                            "readOnly": false,
                            "disabled": true,
                            "autofocus": false,
                            "required": false,
                            "style": null,
                            "attributes": null,
                            "message": null,
                            "htmlActions": null,
                            "elementSize": null,
                            "defaultValue": null,
                            "helperText": null,
                            "labelClassName": " col-12 col-lg-4 col-md-4 col-xl-3 col-xxl-2",
                            "type": "number",
                            "regex": "^[a-zA-Z]+$|^-?[0-9]+(.[0-9]{1,2})?$",
                            "minLength": null,
                            "maxLength": null,
                            "min": 1,
                            "max": null,
                            "placeholder": null,
                            "clearIcon": false,
                            "hidden": false
                        },
                        {
                            "htmlElementType": "DATALIST",
                            "id": "time",
                            "label": "Select Time Duration (months)",
                            "name": null,
                            "value": null,
                            "className": null,
                            "readOnly": false,
                            "disabled": true,
                            "autofocus": false,
                            "required": false,
                            "style": null,
                            "attributes": null,
                            "message": null,
                            "htmlActions": null,
                            "elementSize": null,
                            "defaultValue": null,
                            "helperText": null,
                            "labelClassName": "w-100",
                            "values": timeDurationOptions,
                            "multiple": false,
                            "considerInputText": false,
                            "dataListClassName": " col-12 col-lg-4 col-md-4 col-xl-3 col-xxl-2",
                            "hidden": false
                        },
                    ]
                },
            ],
            "notes": null,
            "atleastOneFieldRequired": false,
            "submitDisabled": false,
            "hidden": false
        };
        return getParametersFormForpathlabConf;
    }

    const geExcludetParametersFormForpathlabConf = (parameters,helpers) => {

        let parametersOptions = [];
        parameters && Object.entries(parameters).map(([key, value]) => {
            parametersOptions.push(helpers.createOption(key, value, value));
        });
        let paramCombinationValue = [];
        ['and','or'].map((each)=> {
            paramCombinationValue.push(helpers.createOption(each, each, each));
            })
        const geExcludetParametersFormForpathlabConf = {
            "htmlElementType": "FORM",
            "id": "geExcludetParametersFormForpathlabConf",
            "label": null,
            "name": null,
            "value": null,
            "className": "mb-3",
            "readOnly": false,
            "disabled": false,
            "autofocus": false,
            "required": false,
            "style": null,
            "attributes": null,
            "message": null,
            "htmlActions": null,
            "elementSize": null,
            "defaultValue": null,
            "helperText": null,
            "labelClassName": "small",
            "htmlGroups": [
                {
                    "htmlElementType": "ELEMENTGROUP",
                    "id": "group1",
                    "label": null,
                    "name": null,
                    "value": null,
                    "className": "row g-3",
                    "readOnly": false,
                    "disabled": false,
                    "autofocus": false,
                    "required": false,
                    "style": null,
                    "attributes": null,
                    "message": null,
                    "htmlActions": null,
                    "elementSize": null,
                    "defaultValue": null,
                    "helperText": null,
                    "labelClassName": null,
                    "groups": [{
                        "htmlElementType": "ELEMENTGROUP",
                        "id": "group2",
                        "label": null,
                        "name": null,
                        "value": null,
                        "className": "w-auto",
                        "readOnly": false,
                        "disabled": false,
                        "autofocus": false,
                        "required": false,
                        "style": null,
                        "attributes": null,
                        "message": null,
                        "htmlActions": null,
                        "elementSize": null,
                        "defaultValue": null,
                        "helperText": null,
                        "labelClassName": null,
                        "groups": null,
                        "groupElements": [
                            {
                                "htmlElementType": "BUTTON",
                                "id": "exclusionAddParameter",
                                "label": "Add",
                                "name": null,
                                "value": null,
                                "className": "btn btn-success px-4 py-2",
                                "readOnly": false,
                                "disabled": true,
                                "autofocus": false,
                                "required": false,
                                "style": {"height": "50px"},
                                "attributes": null,
                                "message": null,
                                "htmlActions": null,
                                "elementSize": null,
                                "defaultValue": null,
                                "helperText": null,
                                "labelClassName": null,
                                "src": null,
                                "href": null,
                                "reset": false,
                                "submit": false,
                                "variant": null,
                                "hidden": true
                            },
                        ],
                    },
                    {
                        "htmlElementType": "ELEMENTGROUP",
                        "id": "group3",
                        "label": null,
                        "name": null,
                        "value": null,
                        "className": "w-auto",
                        "readOnly": false,
                        "disabled": false,
                        "autofocus": false,
                        "required": false,
                        "style": null,
                        "attributes": null,
                        "message": null,
                        "htmlActions": null,
                        "elementSize": null,
                        "defaultValue": null,
                        "helperText": null,
                        "labelClassName": null,
                        "groups": null,
                        "groupElements": [
                            {
                                "htmlElementType": "BUTTON",
                                "id": "exclusionClear",
                                "label": "Clear",
                                "name": null,
                                "value": null,
                                "className": " px-4 brand-secondary btn py-2",
                                "variant":"",
                                "style": {"height": "50px"},
                                "labelClassName": null,
                                "reset": true,
                                "hidden":true
                            }
                        ],
                    }],
                    "groupElements": [
                        {
                            "htmlElementType": "RADIO",
                            "id": "triggerParameterTestType",
                            "label": "",
                            "name": "Parameter Test Type",
                            "value": null,
                            "className": null,
                            "readOnly": false,
                            "disabled": false,
                            "autofocus": false,
                            "required": false,
                            "style": null,
                            "attributes": null,
                            "message": null,
                            "htmlActions": null,
                            "elementSize": null,
                            "defaultValue": null,
                            "helperText": null,
                            "labelClassName": null,
                            "values": [
                                {
                                    "htmlElementType": "OPTION",
                                    "id": "pathology",
                                    "label": "All",
                                    "name": "pathology",
                                    "value": "P",
                                    "className": null,
                                    "readOnly": false,
                                    "disabled": false,
                                    "autofocus": false,
                                    "required": false,
                                    "style": null,
                                    "attributes": null,
                                    "message": null,
                                    "htmlActions": null,
                                    "elementSize": null,
                                    "defaultValue": null,
                                    "helperText": null,
                                    "labelClassName": null,
                                    "displayValue": "Pathology",
                                    "hidden": false
                                },
                                {
                                    "htmlElementType": "OPTION",
                                    "id": "radiology",
                                    "label": "Radiology",
                                    "name": "radiology",
                                    "value": "T",
                                    "className": null,
                                    "readOnly": false,
                                    "disabled": false,
                                    "autofocus": false,
                                    "required": false,
                                    "style": null,
                                    "attributes": null,
                                    "message": null,
                                    "htmlActions": null,
                                    "elementSize": null,
                                    "defaultValue": null,
                                    "helperText": null,
                                    "labelClassName": null,
                                    "displayValue": "Radiology",
                                    "hidden": false
                                }
                            ],
                            "hidden": false
                        },
                        {
                            "htmlElementType": "DATALIST",
                            "id": "parameterName",
                            "label": "Select Exclusion Trigger",
                            "name": null,
                            "value": null,
                            "className": null,
                            "readOnly": false,
                            "disabled": false,
                            "autofocus": false,
                            "required": false,
                            "style": null,
                            "attributes": null,
                            "message": null,
                            "htmlActions": null,
                            "elementSize": null,
                            "defaultValue": null,
                            "helperText": null,
                            "labelClassName": "w-100",
                            "values": parametersOptions,
                            "multiple": false,
                            "considerInputText": false,
                            "dataListClassName": " col-12 col-lg-4 col-md-4 col-xl-3 col-xxl-2",
                            "hidden": true
                        },
                        {
                            "htmlElementType": "INPUT",
                            "id": "time",
                            "label": "Enter no of days",
                            "name": "numberOfDays",
                            "value": null,
                            "className": null,
                            "readOnly": false,
                            "disabled": true,
                            "autofocus": false,
                            "required": false,
                            "style": null,
                            "attributes": null,
                            "message": null,
                            "htmlActions": null,
                            "elementSize": null,
                            "defaultValue": null,
                            "helperText": null,
                            "labelClassName": "col-12 col-lg-4 col-md-4 col-xl-3 col-xxl-2",
                            "regex": "^(?:[1-9]|[1-9]\d|[1-6]\d{2}|7[0-2]\d|730)$",
                            "minLength": null,
                            "maxLength": 3,
                            "type": "text",
                            "min": 1,
                            "max": maxDaysAllowedForExclusionParameterResult,
                            "placeholder": 'Enter no of days',
                            "clearIcon": false,
                            "hidden": true
                        },
                    ]
                },
            ],
            "notes": null,
            "atleastOneFieldRequired": false,
            "submitDisabled": false,
            "hidden": false
        };
        return geExcludetParametersFormForpathlabConf;
    }


    

    return Object.freeze({
        getParametersFormForpathlabConf,
        geExcludetParametersFormForpathlabConf
    })
}

export default FormHelper