# Generated by Django 4.1 on 2022-08-19 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BookName', models.CharField(max_length=122)),
                ('AuthorName', models.CharField(max_length=122)),
                ('price', models.CharField(max_length=12)),
                ('genre', models.CharField(max_length=12)),
                ('status', models.CharField(max_length=12)),
            ],
        ),
    ]
