# Generated by Django 4.1 on 2022-08-22 10:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BnR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=122)),
                ('BookName', models.CharField(max_length=122)),
                ('AuthorName', models.CharField(max_length=122)),
                ('BorrowDate', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BookName', models.CharField(max_length=122)),
                ('AuthorName', models.CharField(max_length=122)),
                ('price', models.CharField(max_length=12)),
                ('genre', models.CharField(max_length=12)),
                ('status', models.CharField(max_length=12)),
            ],
        ),
    ]
