# Generated by Django 4.1 on 2022-08-23 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_extendeduser'),
    ]

    operations = [
        migrations.AddField(
            model_name='bnr',
            name='mode',
            field=models.CharField(default='borrow', max_length=20),
        ),
    ]
