# Generated by Django 4.1 on 2022-08-24 10:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_bnr_mode'),
    ]

    operations = [
        migrations.DeleteModel(
            name='books',
        ),
        migrations.AddField(
            model_name='bnr',
            name='ReturnDate',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='bnr',
            name='fine',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.AlterField(
            model_name='bnr',
            name='mode',
            field=models.CharField(default='Borrow', max_length=20),
        ),
    ]
