# Generated by Django 4.1 on 2022-08-24 11:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_delete_books_bnr_returndate_bnr_fine_alter_bnr_mode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bnr',
            name='BorrowDate',
        ),
        migrations.RemoveField(
            model_name='bnr',
            name='DueDate',
        ),
        migrations.RemoveField(
            model_name='bnr',
            name='ReturnDate',
        ),
        migrations.RemoveField(
            model_name='bnr',
            name='Username',
        ),
        migrations.RemoveField(
            model_name='bnr',
            name='fine',
        ),
        migrations.RemoveField(
            model_name='bnr',
            name='mode',
        ),
        migrations.AddField(
            model_name='book',
            name='BorrowDate',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='book',
            name='DueDate',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='book',
            name='ReturnDate',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='book',
            name='Username',
            field=models.CharField(default='no issue', max_length=122),
        ),
        migrations.AddField(
            model_name='book',
            name='fine',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.AddField(
            model_name='book',
            name='mode',
            field=models.CharField(default='Borrow', max_length=20),
        ),
    ]
