# Generated by Django 4.1 on 2022-09-16 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept_name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=25)),
                ('password', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='salary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Team_lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lead_name', models.CharField(max_length=25)),
                ('leave_request', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(max_length=25)),
                ('det_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.department')),
                ('salary_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='apps.salary')),
            ],
        ),
        migrations.CreateModel(
            name='personal_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30, null=True)),
                ('full_name', models.CharField(max_length=25)),
                ('dob', models.DateField()),
                ('contact_no', models.IntegerField()),
                ('dep_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.department')),
                ('lead_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.team_lead')),
                ('login_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='apps.log')),
            ],
        ),
        migrations.CreateModel(
            name='leave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_type', models.CharField(max_length=25)),
                ('profil_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.personal_details')),
            ],
        ),
        migrations.CreateModel(
            name='insurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insurance_name', models.CharField(max_length=25)),
                ('persona_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.personal_details')),
            ],
        ),
        migrations.CreateModel(
            name='Attendence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_time', models.TimeField()),
                ('out_time', models.TimeField()),
                ('DATE', models.DateField()),
                ('profil_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.personal_details')),
            ],
        ),
    ]
