# Generated by Django 4.1 on 2022-09-16 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='salary_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.salary'),
        ),
    ]
