# Generated by Django 4.1 on 2022-09-16 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_alter_role_salary_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendence',
            name='profil_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pro', to='apps.personal_details'),
        ),
        migrations.AlterField(
            model_name='insurance',
            name='persona_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prof', to='apps.personal_details'),
        ),
        migrations.AlterField(
            model_name='leave',
            name='profil_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='apps.personal_details'),
        ),
        migrations.AlterField(
            model_name='personal_details',
            name='dep_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department', to='apps.department'),
        ),
        migrations.AlterField(
            model_name='personal_details',
            name='lead_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teamlead', to='apps.team_lead'),
        ),
        migrations.AlterField(
            model_name='role',
            name='salary_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='apps.salary'),
        ),
    ]
