# Generated by Django 4.1.3 on 2022-11-17 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone', models.IntegerField()),
                ('address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=61)),
            ],
        ),
        migrations.CreateModel(
            name='Marks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks_obtained', models.IntegerField()),
                ('std_id', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.studentdetails', verbose_name='Student Id')),
                ('sub_id', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.subjects', verbose_name='Subject Id')),
            ],
        ),
    ]
