# Generated by Django 4.1.3 on 2022-11-23 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentdetails',
            name='gender',
            field=models.CharField(default='Male', max_length=10),
        ),
    ]
