# Generated by Django 4.1.3 on 2022-12-02 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_branch_studentdetails_branch_id_subjects_branch_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sem_name', models.IntegerField(choices=[(1, 'Sem-I'), (2, 'Sem-II'), (3, 'Sem-III'), (4, 'Sem-IV'), (5, 'Sem-V'), (6, 'Sem-VI'), (7, 'Sem-VII'), (8, 'Sem-VIII')])),
            ],
        ),
        migrations.AddField(
            model_name='marks',
            name='sem_id',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.semester', verbose_name='Semester'),
        ),
        migrations.AddField(
            model_name='studentdetails',
            name='sem_id',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.semester', verbose_name='Semester'),
        ),
        migrations.AddField(
            model_name='subjects',
            name='sem_id',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.semester', verbose_name='Semester'),
        ),
    ]
