# Generated by Django 4.1.3 on 2022-12-02 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_semester_marks_sem_id_studentdetails_sem_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semester',
            name='sem_name',
            field=models.IntegerField(choices=[('Sem-I', 1), ('Sem-II', 2), ('Sem-III', 3), ('Sem-IV', 4), ('Sem-V', 5), ('Sem-VI', 6), ('Sem-VII', 7), ('Sem-VIII', 8)]),
        ),
    ]
