# Generated by Django 4.1.3 on 2022-12-02 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_semester_sem_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semester',
            name='sem_name',
            field=models.CharField(max_length=10),
        ),
    ]
