# Generated by Django 4.1.3 on 2022-12-06 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_semester_sem_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdetails',
            name='phone',
            field=models.CharField(max_length=20),
        ),
    ]
