# Generated by Django 4.1 on 2022-09-13 05:14

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('dept_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dept_name', models.CharField(max_length=30)),
                ('dept_description', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Developers',
            fields=[
                ('developer_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('developer_name', models.CharField(max_length=30)),
                ('developer_mobile_no', models.IntegerField()),
                ('developer_email', models.CharField(max_length=50)),
                ('developer_password', models.CharField(max_length=30)),
                ('developer_username', models.CharField(max_length=30)),
                ('developer_address', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('issue_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('issue_name', models.CharField(max_length=50)),
                ('issue_description', models.CharField(max_length=300)),
                ('issue_created_date', models.DateField()),
                ('issue_status', models.CharField(default='open', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=30)),
                ('user_email', models.CharField(max_length=50)),
                ('user_phone_no', models.IntegerField()),
                ('user_address', models.CharField(max_length=70)),
                ('user_password', models.CharField(max_length=30)),
                ('user_dept_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index_app.department')),
            ],
        ),
        migrations.CreateModel(
            name='Tracking',
            fields=[
                ('tracking_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('issue_status', models.CharField(default='open', max_length=30)),
                ('issue_status_description', models.CharField(max_length=300)),
                ('issue_deadline', models.DateField()),
                ('issue_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index_app.issue')),
                ('issue_solver_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index_app.developers')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product_description', models.CharField(max_length=300)),
                ('product_name', models.CharField(max_length=30)),
                ('product_dept_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index_app.department')),
                ('product_developer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index_app.developers')),
            ],
        ),
        migrations.AddField(
            model_name='issue',
            name='issue_creator_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index_app.user'),
        ),
        migrations.AddField(
            model_name='issue',
            name='issue_dept_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index_app.department'),
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('comment_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('comment_date', models.DateField()),
                ('comment_description', models.CharField(max_length=300)),
                ('dept_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index_app.department')),
                ('issue_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index_app.issue')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index_app.user')),
            ],
        ),
        migrations.CreateModel(
            name='Bug',
            fields=[
                ('bug_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bug_name', models.CharField(max_length=30)),
                ('bug_description', models.CharField(max_length=300)),
                ('bug_creator_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index_app.developers')),
                ('bug_dept_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index_app.department')),
            ],
        ),
    ]
