# Generated by Django 5.2.4 on 2025-07-22 06:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=100)),
                ('employee_email', models.EmailField(max_length=254, unique=True)),
                ('birth_date', models.DateField()),
                ('mobile_number', models.PositiveBigIntegerField(validators=[django.core.validators.MinValueValidator(6000000000), django.core.validators.MaxValueValidator(9999999999)])),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('reference_files_url', models.URLField(blank=True)),
                ('country', models.CharField(choices=[('IND', 'India'), ('CHN', 'China'), ('MX', 'Mexico'), ('SL', 'Sri Lanka'), ('NZ', 'New Zealand'), ('USA', 'America')], default='IND', max_length=3)),
            ],
        ),
    ]
