# Generated by Django 5.2.4 on 2025-07-22 07:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='departmentmodel',
            name='dept_name',
            field=models.CharField(blank=True, default='NOT DETERMINED', max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='employeemodel',
            name='dept_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Portfolio.departmentmodel'),
            preserve_default=False,
        ),
    ]
