# Generated by Django 5.2.4 on 2025-07-22 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio', '0002_departmentmodel_dept_name_employeemodel_dept_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeemodel',
            name='country',
        ),
        migrations.RemoveField(
            model_name='employeemodel',
            name='reference_files_url',
        ),
        migrations.CreateModel(
            name='EmployeeFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_to_files', models.URLField()),
                ('emp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Portfolio.employeemodel')),
            ],
        ),
    ]
