# Generated by Django 4.1 on 2022-09-12 05:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('Appointment_id', models.IntegerField(primary_key=True, serialize=False)),
                ('Time_of_appointment', models.TimeField()),
                ('appointment_date', models.DateField()),
                ('Appointment_Status', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Appointment_service_Info',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('Appointment_id', models.IntegerField()),
                ('service_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('branch_id', models.IntegerField(primary_key=True, serialize=False)),
                ('branch_name', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('Client_id', models.IntegerField(primary_key=True, serialize=False)),
                ('Client_first_name', models.CharField(max_length=50)),
                ('Client_last_name', models.CharField(max_length=50)),
                ('Client_Email_id', models.EmailField(max_length=254)),
                ('Client_contact_number', models.CharField(max_length=10)),
                ('Password', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='services_provided',
            fields=[
                ('service_id', models.IntegerField(primary_key=True, serialize=False)),
                ('service_name', models.CharField(max_length=50)),
                ('Amount_to_be_paid', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('trans_id', models.IntegerField(primary_key=True, serialize=False)),
                ('trans_date', models.DateTimeField(auto_now_add=True)),
                ('trans_type', models.CharField(max_length=20)),
                ('Total_amount', models.IntegerField()),
                ('trans_status', models.CharField(max_length=20)),
                ('Appointment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salon.appointment')),
            ],
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('review_id', models.IntegerField(primary_key=True, serialize=False)),
                ('comments_and_reviews', models.CharField(max_length=500)),
                ('rating', models.IntegerField()),
                ('Appointment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salon.appointment')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('emp_id', models.IntegerField(primary_key=True, serialize=False)),
                ('emp_name', models.CharField(max_length=50)),
                ('role', models.CharField(max_length=20)),
                ('emp_email_id', models.EmailField(max_length=10)),
                ('emp_contact_number', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=20)),
                ('branch_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salon.branch')),
            ],
        ),
        migrations.AddField(
            model_name='appointment',
            name='Client_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salon.client'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='emp_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salon.employee'),
        ),
    ]
