# Generated by Django 4.1 on 2022-09-26 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Appointment_service_Info',
        ),
        migrations.AddField(
            model_name='appointment',
            name='services',
            field=models.ManyToManyField(to='salon.services_provided'),
        ),
    ]
