# Generated by Django 4.1 on 2022-09-26 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0002_delete_appointment_service_info_appointment_services'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='client',
            table='Client',
        ),
    ]
