# Generated by Django 4.1 on 2022-09-26 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0003_alter_client_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='appointment',
            table='Appointment',
        ),
        migrations.AlterModelTable(
            name='branch',
            table='Branch',
        ),
        migrations.AlterModelTable(
            name='employee',
            table='Employee',
        ),
        migrations.AlterModelTable(
            name='reviews',
            table='Reviews',
        ),
        migrations.AlterModelTable(
            name='services_provided',
            table='services_provided',
        ),
        migrations.AlterModelTable(
            name='transaction',
            table='Transaction',
        ),
    ]
