# Generated by Django 5.2.4 on 2025-07-11 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
                ('student_class', models.CharField(max_length=10)),
                ('date_of_admission', models.DateField(auto_now=True)),
            ],
            options={
                'db_table': 'student',
            },
        ),
    ]
