# Generated by Django 4.0.3 on 2022-09-12 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('customer_name', models.CharField(max_length=30)),
                ('customer_address', models.CharField(max_length=100)),
                ('customer_username', models.CharField(max_length=30)),
                ('customer_password', models.CharField(max_length=30)),
                ('customer_phn', models.CharField(max_length=20)),
                ('customer_email', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('emp_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('emp_name', models.CharField(max_length=30)),
                ('emp_username', models.CharField(max_length=30)),
                ('emp_password', models.CharField(max_length=30)),
                ('emp_phn', models.CharField(max_length=20)),
                ('emp_email', models.CharField(max_length=40)),
                ('is_available', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('food_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('food_name', models.CharField(max_length=30)),
                ('food_price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('food_desc', models.CharField(max_length=100)),
                ('food_photo', models.CharField(max_length=50)),
                ('is_available', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('menu_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('menu_type', models.CharField(max_length=30)),
                ('is_available', models.BooleanField(default=False)),
                ('food_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.food')),
            ],
        ),
        migrations.CreateModel(
            name='OrderFood',
            fields=[
                ('order_food_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('customer_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.customer')),
                ('emp_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.employee')),
                ('food_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.food')),
                ('menu_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.menu')),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('restaurant_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('restaurant_name', models.CharField(max_length=30)),
                ('restaurant_location', models.CharField(max_length=100)),
                ('restaurant_avg_rating', models.DecimalField(decimal_places=1, max_digits=2)),
                ('restaurant_username', models.CharField(max_length=30)),
                ('restaurant_password', models.CharField(max_length=30)),
                ('restaurant_phn', models.CharField(max_length=20)),
                ('restaurant_avaibility', models.CharField(max_length=20)),
                ('open_timing', models.TimeField()),
                ('close_timing', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('review_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('review', models.CharField(max_length=100)),
                ('rating', models.DecimalField(decimal_places=1, max_digits=2)),
                ('restaurant_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.restaurant')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('transaction_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('payment_type', models.CharField(max_length=50)),
                ('payment_status', models.CharField(max_length=50)),
                ('amount', models.IntegerField()),
                ('order_food_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.orderfood')),
            ],
        ),
        migrations.AddField(
            model_name='orderfood',
            name='restaurant_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.restaurant'),
        ),
        migrations.CreateModel(
            name='OrderDetails',
            fields=[
                ('order_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('order_status', models.CharField(max_length=50)),
                ('order_time', models.DateTimeField(auto_now_add=True)),
                ('delivery_time', models.DateTimeField()),
                ('order_food_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.orderfood')),
                ('transaction_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.payment')),
            ],
        ),
        migrations.AddField(
            model_name='menu',
            name='restaurant_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.restaurant'),
        ),
    ]
