# Generated by Django 4.1.1 on 2022-10-04 08:04

from django.db import migrations, models
import django.db.models.deletion
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='customer_address',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='food_id',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='restaurant_location',
        ),
        migrations.AddField(
            model_name='customer',
            name='customer_address1',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='customer',
            name='customer_address2',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='customer_city',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='customer',
            name='customer_code',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='customer',
            name='customer_state',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='food',
            name='restaurant_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.restaurant'),
        ),
        migrations.AddField(
            model_name='orderdetails',
            name='customer_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.customer'),
        ),
        migrations.AddField(
            model_name='orderdetails',
            name='emp_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.employee'),
        ),
        migrations.AddField(
            model_name='orderdetails',
            name='restaurant_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.restaurant'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='restaurant_address1',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='restaurant_address2',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='restaurant_city',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='restaurant_code',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='restaurant_email',
            field=models.CharField(default=None, max_length=40, unique=True, validators=[home.models.validate_mail]),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='restaurant_photo',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='restaurant_state',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_email',
            field=models.CharField(max_length=40, unique=True, validators=[home.models.validate_mail]),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_phn',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_username',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='emp_email',
            field=models.CharField(max_length=40, unique=True, validators=[home.models.validate_mail]),
        ),
        migrations.AlterField(
            model_name='employee',
            name='emp_phn',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='emp_username',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='is_available',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='food_photo',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='food_price',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='close_timing',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='open_timing',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='restaurant_avaibility',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='restaurant_avg_rating',
            field=models.DecimalField(decimal_places=1, max_digits=2, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='restaurant_phn',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.CreateModel(
            name='MenuList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.food')),
                ('menu_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.menu')),
            ],
        ),
    ]
