# Generated by Django 4.1.1 on 2022-10-14 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_customer_customer_address_remove_menu_food_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderfood',
            name='emp_id',
        ),
    ]
