# Generated by Django 4.1.1 on 2022-09-26 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_customer_customer_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_address2',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='is_available',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='restaurant_address2',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='restaurant_avg_rating',
            field=models.DecimalField(decimal_places=1, max_digits=2, null=True),
        ),
    ]
