# Generated by Django 4.1.1 on 2022-10-19 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_user_remove_customer_customer_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='role',
            field=models.CharField(default='customer', max_length=10),
        ),
        migrations.AddField(
            model_name='employee',
            name='role',
            field=models.CharField(default='employee', max_length=10),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='role',
            field=models.CharField(default='restaurant', max_length=10),
        ),
    ]
