# Generated by Django 4.1.1 on 2022-10-19 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_customer_role_employee_role_restaurant_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='food',
            old_name='restaurant_id',
            new_name='restaurant',
        ),
    ]
