# Generated by Django 4.1.1 on 2022-09-26 05:46

from django.db import migrations, models
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_customer_customer_address2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='restaurant_email',
            field=models.CharField(default=None, max_length=40, unique=True, validators=[home.models.validate_mail]),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_email',
            field=models.CharField(max_length=40, unique=True, validators=[home.models.validate_mail]),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_phn',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_username',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='emp_email',
            field=models.CharField(max_length=40, unique=True, validators=[home.models.validate_mail]),
        ),
        migrations.AlterField(
            model_name='employee',
            name='emp_phn',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='emp_username',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='restaurant_avg_rating',
            field=models.DecimalField(decimal_places=1, max_digits=2, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='restaurant_phn',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
