# Generated by Django 4.1.1 on 2022-10-14 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_orderfood_emp_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderfood',
            name='price',
            field=models.IntegerField(null=True),
        ),
    ]
