# Generated by Django 4.1.1 on 2022-10-26 07:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0004_rename_restaurant_id_food_restaurant"),
    ]

    operations = [
        migrations.RenameField(
            model_name="orderfood", old_name="customer_id", new_name="customer",
        ),
        migrations.RenameField(
            model_name="orderfood", old_name="food_id", new_name="food",
        ),
        migrations.RenameField(
            model_name="orderfood", old_name="menu_id", new_name="menu",
        ),
        migrations.RenameField(
            model_name="orderfood", old_name="restaurant_id", new_name="restaurant",
        ),
        migrations.AlterField(
            model_name="food",
            name="restaurant",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="food",
                to="home.restaurant",
            ),
        ),
    ]
