# Generated by Django 4.1.1 on 2022-09-26 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_food_food_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='food_photo',
            field=models.TextField(max_length=500, null=True),
        ),
    ]
