# Generated by Django 4.1.1 on 2022-09-26 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_food_food_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='restaurant_avaibility',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
