# Generated by Django 4.1.1 on 2022-10-14 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_food_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='quantity',
        ),
    ]
