# Generated by Django 4.1.1 on 2022-09-26 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_restaurant_restaurant_avaibility'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='close_timing',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='open_timing',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
