# Generated by Django 4.1.1 on 2022-09-27 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_restaurant_close_timing_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='restaurant_photo',
            field=models.TextField(max_length=500, null=True),
        ),
    ]
