# Generated by Django 4.1.1 on 2022-09-28 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_restaurant_restaurant_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='food_price',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='is_available',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
