# Generated by Django 4.1.1 on 2022-09-28 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_food_food_price_alter_food_is_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='is_available',
            field=models.BooleanField(default=False),
        ),
    ]
