# Generated by Django 4.1.1 on 2022-09-28 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_alter_food_food_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='food_price',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
