# Generated by Django 4.1.1 on 2022-09-28 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_alter_food_food_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='restaurant_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.restaurant'),
        ),
    ]
