# Generated by Django 4.1.1 on 2022-09-29 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_orderdetails_customer_id_orderdetails_emp_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menulist',
            name='food_id',
        ),
        migrations.AddField(
            model_name='menulist',
            name='food_id',
            field=models.ManyToManyField(blank=True, null=True, to='home.food'),
        ),
    ]
