# Generated by Django 4.1.1 on 2022-09-29 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_remove_menulist_food_id_menulist_food_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menulist',
            name='food_id',
        ),
        migrations.AddField(
            model_name='menulist',
            name='food_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.food'),
        ),
    ]
