# Generated by Django 4.0.8 on 2022-10-28 07:07

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AllUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=70)),
                ('name', models.CharField(max_length=70)),
                ('password', models.CharField(max_length=70)),
                ('verified', models.CharField(choices=[('V', 'VERIFIED'), ('N', 'NOT VERIFIED')], default='N', max_length=1)),
                ('type_of_user', models.CharField(choices=[('D', 'DOCTOR'), ('P', 'PATIENT'), ('S', 'STAFF'), ('A', 'Admin')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(default='hydrabad', max_length=220)),
                ('name', models.CharField(max_length=70)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('email', models.CharField(max_length=70)),
                ('experience', models.IntegerField()),
                ('qualification', models.CharField(max_length=70)),
                ('phone_no', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='Patients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('insurance_id', models.CharField(max_length=20, unique=True)),
                ('email', models.CharField(max_length=70)),
                ('phone_no', models.CharField(max_length=70)),
                ('address', models.CharField(max_length=220)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('experience', models.IntegerField()),
                ('designation', models.CharField(max_length=70)),
                ('email', models.CharField(max_length=70)),
                ('phone_number', models.CharField(max_length=70, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DatewiseSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date(2022, 10, 28))),
                ('startTime', models.TimeField(default='17:30:00')),
                ('endTime', models.TimeField(default='20:30:00')),
                ('status', models.CharField(choices=[('A', 'Available'), ('B', 'Booked')], default='A', max_length=1)),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.doctor')),
            ],
            options={
                'unique_together': {('date', 'doctor', 'startTime', 'endTime')},
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='users.patients')),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.datewiseslot')),
            ],
        ),
    ]
