# Generated by Django 4.0.8 on 2022-10-28 19:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alluser',
            name='email',
            field=models.CharField(max_length=70, unique=True),
        ),
        migrations.AlterField(
            model_name='datewiseslot',
            name='date',
            field=models.DateField(default=datetime.date(2022, 10, 29)),
        ),
    ]
