# Generated by Django 4.1 on 2022-10-10 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('role_id', models.IntegerField(primary_key=True, serialize=False)),
                ('role_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_id', models.IntegerField(primary_key=True, serialize=False)),
                ('employee_name', models.CharField(max_length=50)),
                ('doj', models.DateField()),
                ('phone', models.CharField(max_length=13)),
                ('email', models.EmailField(max_length=60)),
                ('address', models.CharField(max_length=250)),
                ('salary', models.FloatField()),
                ('role_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.role')),
            ],
            options={
                'managed': True,
            },
        ),
    ]
