# Generated by Django 4.1 on 2022-10-10 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='employee',
            table='gmemployee',
        ),
    ]
