# Generated by Django 4.1 on 2022-09-12 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_remove_theatre_theatre_screens'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hall',
            name='Hall_no',
        ),
    ]
