# Generated by Django 4.1 on 2022-09-29 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_hall_baseprice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='Selected_seats_id',
        ),
        migrations.DeleteModel(
            name='Selected_seats',
        ),
    ]
