# Generated by Django 4.1.1 on 2022-09-12 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='faculty_details',
            fields=[
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('facul_username', models.CharField(max_length=35, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=12)),
                ('gender', models.CharField(max_length=6)),
                ('date_of_birth', models.DateField()),
                ('main_subject', models.CharField(max_length=35)),
                ('department', models.CharField(max_length=35)),
                ('joining_date', models.DateField()),
                ('qualification', models.CharField(max_length=35)),
                ('experience', models.IntegerField()),
                ('user_type', models.CharField(max_length=15)),
            ],
        ),
    ]
