# Generated by Django 4.1.1 on 2022-09-30 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0007_remove_feedback_by_student_stud_username_and_more'),
        ('Admin', '0022_faculty_details_student_details_feedback_by_student_and_more'),
        ('Faculty', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='faculty_details',
        ),
    ]
