# Generated by Django 4.1.4 on 2022-12-21 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40, unique=True)),
            ],
            options={
                'verbose_name_plural': '3. Category',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('language', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name_plural': '5. Course',
            },
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=25)),
                ('last_name', models.CharField(max_length=25)),
                ('email', models.CharField(max_length=40, unique=True)),
                ('password', models.CharField(max_length=25, unique=True)),
                ('qualification', models.CharField(max_length=25)),
                ('designation', models.CharField(max_length=25)),
                ('mobile_no', models.CharField(max_length=25, unique=True)),
                ('address', models.TextField()),
            ],
            options={
                'verbose_name_plural': '1. Instructor',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=25)),
                ('last_name', models.CharField(max_length=25)),
                ('email', models.CharField(max_length=40, unique=True)),
                ('password', models.CharField(max_length=25, unique=True)),
                ('qualification', models.CharField(max_length=25)),
                ('interested_category', models.TextField(max_length=25)),
                ('mobile_no', models.CharField(max_length=25, unique=True)),
                ('address', models.TextField()),
            ],
            options={
                'verbose_name_plural': '2. Student',
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=30)),
                ('url', models.TextField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.course')),
            ],
            options={
                'verbose_name_plural': '6. Topic',
            },
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.category')),
            ],
            options={
                'verbose_name_plural': '4. SubCategory',
            },
        ),
        migrations.AddField(
            model_name='course',
            name='subcategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.subcategory'),
        ),
        migrations.AddField(
            model_name='course',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.instructor'),
        ),
    ]
