# Generated by Django 4.1.4 on 2023-01-04 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instructor',
            old_name='address',
            new_name='skills',
        ),
    ]
