# Generated by Django 4.1.4 on 2023-01-18 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_rename_address_instructor_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='image',
            field=models.ImageField(null=True, upload_to='course_images/'),
        ),
    ]
