# Generated by Django 4.1.4 on 2023-02-03 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_alter_topic_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='title',
            field=models.CharField(max_length=120),
        ),
    ]
