# Generated by Django 4.1.4 on 2023-02-09 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_studentfavoritecourse'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentfavoritecourse',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
