# Generated by Django 4.1.1 on 2022-09-27 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('toursapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_of_people', models.IntegerField()),
                ('passenger_details', models.TextField()),
                ('isCancelled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'booking_details',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.TextField()),
                ('mobile', models.BigIntegerField()),
                ('isAdmin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_logged_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='UserToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('token', models.CharField(max_length=255)),
                ('expired_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(max_length=50)),
                ('transaction_id', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('coupon_applied', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='toursapp.coupon')),
            ],
            options={
                'db_table': 'payment_details',
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('rating', models.DecimalField(decimal_places=1, max_digits=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bookingid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bookingsapp.bookingdetails')),
            ],
            options={
                'db_table': 'feedback',
            },
        ),
        migrations.CreateModel(
            name='CancellationDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refund_status', models.TextField()),
                ('cancellation_charges', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reason_for_cancellation', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bookingid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bookingsapp.bookingdetails')),
            ],
            options={
                'db_table': 'cancellation_details',
            },
        ),
        migrations.AddField(
            model_name='bookingdetails',
            name='paymentid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookingsapp.paymentdetails'),
        ),
        migrations.AddField(
            model_name='bookingdetails',
            name='tourid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='toursapp.tour'),
        ),
        migrations.AddField(
            model_name='bookingdetails',
            name='userid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookingsapp.user'),
        ),
        migrations.AddField(
            model_name='bookingdetails',
            name='vehicleid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='toursapp.vehicle'),
        ),
    ]
