# Generated by Django 4.1.1 on 2022-09-29 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingsapp', '0002_remove_feedback_bookingid_feedback_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='rating',
            field=models.DecimalField(decimal_places=2, max_digits=2),
        ),
    ]
