# Generated by Django 4.1.1 on 2022-09-29 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingsapp', '0004_alter_feedback_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.TextField(default='https://res.cloudinary.com/dklq1vuce/image/upload/v1664469247/smiley-dp_nu8kdg.jpg'),
        ),
    ]
