# Generated by Django 4.1.1 on 2022-10-04 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingsapp', '0005_user_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingdetails',
            name='vehicleid',
        ),
        migrations.AddField(
            model_name='paymentdetails',
            name='total_price',
            field=models.FloatField(null=True),
        ),
    ]
