# Generated by Django 4.1.1 on 2022-10-05 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingsapp', '0006_remove_bookingdetails_vehicleid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentdetails',
            name='transaction_id',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
