# Generated by Django 4.1.1 on 2022-10-07 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingsapp', '0007_alter_paymentdetails_transaction_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='rating',
            field=models.FloatField(),
        ),
    ]
