# Generated by Django 4.1.1 on 2022-10-07 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingsapp', '0008_alter_feedback_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cancellationdetails',
            name='cancellation_charges',
            field=models.FloatField(),
        ),
    ]
