# Generated by Django 4.1.1 on 2022-10-08 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingsapp', '0009_alter_cancellationdetails_cancellation_charges'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cancellationdetails',
            name='reason_for_cancellation',
            field=models.TextField(blank=True, null=True),
        ),
    ]
