# Generated by Django 4.1.1 on 2022-10-12 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingsapp', '0010_alter_cancellationdetails_reason_for_cancellation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='comment',
            field=models.TextField(null=True),
        ),
    ]
