# Generated by Django 4.1.1 on 2022-10-28 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bookingsapp", "0011_alter_feedback_comment"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bookingdetails",
            options={"ordering": ["created_at"]},
        ),
    ]
