spring.application.name=Backend
spring.datasource.url=jdbc:mysql://localhost:3306/springlibrary
spring.datasource.username=root
spring.datasource.password=Tarun@1728
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
