# Generated by Django 4.1 on 2022-09-09 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hall',
            fields=[
                ('Hall_id', models.IntegerField(primary_key=True, serialize=False)),
                ('Hall_no', models.IntegerField()),
                ('T_No_Of_Seats', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('Movie_id', models.IntegerField(primary_key=True, serialize=False)),
                ('Movie_name', models.CharField(max_length=45)),
                ('Movie_lang', models.CharField(max_length=45)),
                ('Movie_details', models.CharField(max_length=45)),
                ('Movie_Release_date', models.DateField()),
                ('Movie_category', models.CharField(max_length=450)),
                ('Movie_cast', models.CharField(max_length=450)),
                ('Movie_reviews', models.CharField(max_length=450)),
            ],
        ),
        migrations.CreateModel(
            name='PROMOCODE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PROMOCODE', models.CharField(max_length=45)),
                ('Discount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Snacks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Snacks_id', models.IntegerField()),
                ('Snacks_name', models.CharField(max_length=45)),
                ('Snacks_price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Theatre',
            fields=[
                ('Theatre_id', models.IntegerField(primary_key=True, serialize=False)),
                ('Theatre_name', models.CharField(max_length=45)),
                ('Theatre_location', models.CharField(max_length=45)),
                ('Theatre_screens', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('User_id', models.IntegerField(primary_key=True, serialize=False)),
                ('User_name', models.CharField(max_length=45)),
                ('User_phone', models.CharField(max_length=45)),
                ('User_email', models.CharField(max_length=45)),
                ('User_DOB', models.DateField()),
                ('User_Address', models.CharField(max_length=450)),
            ],
        ),
        migrations.CreateModel(
            name='Selected_seats',
            fields=[
                ('Selected_seats_id', models.IntegerField(primary_key=True, serialize=False)),
                ('Seating_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.theatre')),
                ('User_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.user')),
            ],
        ),
        migrations.CreateModel(
            name='Seating',
            fields=[
                ('Seating_id', models.IntegerField(primary_key=True, serialize=False)),
                ('Type_of_seat', models.IntegerField()),
                ('No_Of_Seats', models.IntegerField()),
                ('Hall_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.hall')),
                ('Theatre_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.theatre')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Payment_id', models.IntegerField()),
                ('Booking_id', models.IntegerField()),
                ('T_price', models.IntegerField()),
                ('PROMOCODE', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.promocode')),
            ],
        ),
        migrations.AddField(
            model_name='hall',
            name='Movie_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.movie'),
        ),
        migrations.AddField(
            model_name='hall',
            name='Theatre_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.theatre'),
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cart_id', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('total_snacks_price', models.IntegerField()),
                ('Snacks_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.snacks')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('Booking_id', models.IntegerField(primary_key=True, serialize=False)),
                ('Date', models.DateField()),
                ('Hall_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.hall')),
                ('Movie_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.movie')),
                ('Selected_seats_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.selected_seats')),
                ('Theatre_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.theatre')),
                ('User_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.user')),
            ],
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Bill_id', models.IntegerField()),
                ('total_price', models.IntegerField()),
                ('Payment_Status', models.CharField(max_length=45)),
                ('Payment_mode', models.CharField(max_length=45)),
                ('Cart_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.cart')),
                ('Payment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.payment')),
            ],
        ),
    ]
