# Generated by Django 4.1 on 2022-09-12 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_booking_date_alter_movie_movie_release_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='theatre',
            name='Theatre_screens',
        ),
    ]
