# Generated by Django 4.1 on 2022-09-12 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_remove_hall_hall_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='hall',
            name='Hall_no',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='hall',
            name='T_No_Of_Seats',
            field=models.IntegerField(default=1),
        ),
    ]
