# Generated by Django 4.1 on 2022-09-12 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_hall_hall_no_alter_hall_t_no_of_seats'),
    ]

    operations = [
        migrations.AddField(
            model_name='theatre',
            name='Theatre_screens',
            field=models.IntegerField(default=1),
        ),
    ]
