# Generated by Django 4.1 on 2022-09-12 12:34

from django.db import migrations, models
import home.views


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_theatre_theatre_screens'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='User_phone',
            field=models.CharField(max_length=45, validators=[home.views.validate_Phone]),
        ),
    ]
