# Generated by Django 4.1 on 2022-09-12 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_user_user_phone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='snacks',
            options={'managed': True},
        ),
        migrations.RemoveField(
            model_name='cart',
            name='Snacks_id',
        ),
        migrations.AddField(
            model_name='cart',
            name='Snacks',
            field=models.ManyToManyField(to='home.snacks'),
        ),
    ]
