# Generated by Django 4.1 on 2022-09-12 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_alter_selected_seats_seating_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='Booking_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.booking'),
        ),
    ]
