# Generated by Django 4.1 on 2022-09-22 07:40

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_alter_hall_theatre_id_alter_user_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='Snacks',
        ),
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default='mphs', max_length=45),
        ),
        migrations.AlterField(
            model_name='booking',
            name='Date',
            field=models.DateField(default=datetime.date(2022, 9, 22)),
        ),
        migrations.AlterField(
            model_name='hall',
            name='Theatre_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.theatre'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='Movie_Release_date',
            field=models.DateField(default=datetime.date(2022, 9, 22)),
        ),
        migrations.AlterField(
            model_name='user',
            name='User_DOB',
            field=models.DateField(default=datetime.date(2022, 9, 22)),
        ),
        migrations.AlterField(
            model_name='user',
            name='User_phone',
            field=models.CharField(max_length=45),
        ),
    ]
