# Generated by Django 4.1 on 2022-09-26 09:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_alter_booking_date_alter_movie_movie_release_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='Date',
            field=models.DateField(default=datetime.date(2022, 9, 26)),
        ),
        migrations.AlterField(
            model_name='movie',
            name='Movie_Release_date',
            field=models.DateField(default=datetime.date(2022, 9, 26)),
        ),
        migrations.AlterField(
            model_name='user',
            name='User_DOB',
            field=models.DateField(default=datetime.date(2022, 9, 26)),
        ),
        migrations.AlterField(
            model_name='user',
            name='User_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
    ]
