# Generated by Django 4.1 on 2022-09-26 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_hall_date_hall_starttime'),
    ]

    operations = [
        migrations.AddField(
            model_name='hall',
            name='endTime',
            field=models.TimeField(auto_now=True),
        ),
    ]
