# Generated by Django 4.1 on 2022-09-26 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_hall_endtime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='User_email',
            field=models.CharField(default='', max_length=45, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='User_phone',
            field=models.CharField(default='', max_length=45, unique=True),
        ),
    ]
