# Generated by Django 4.1 on 2022-09-27 08:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_alter_user_user_email_alter_user_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='Date',
            field=models.DateField(default=datetime.date(2022, 9, 27)),
        ),
        migrations.AlterField(
            model_name='hall',
            name='Date',
            field=models.DateField(default=datetime.date(2022, 9, 27)),
        ),
        migrations.AlterField(
            model_name='hall',
            name='endTime',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='hall',
            name='startTime',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='movie',
            name='Movie_Release_date',
            field=models.DateField(default=datetime.date(2022, 9, 27)),
        ),
        migrations.AlterField(
            model_name='user',
            name='User_DOB',
            field=models.DateField(default=datetime.date(2022, 9, 27)),
        ),
    ]
