# Generated by Django 4.1 on 2022-09-29 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_alter_booking_date_alter_hall_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hall',
            name='baseprice',
            field=models.IntegerField(default=100),
        ),
    ]
