# Generated by Django 4.1 on 2022-09-30 08:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_remove_booking_selected_seats_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='Selected_seats',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='booking',
            name='Booking_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='booking',
            name='Date',
            field=models.DateField(default=datetime.date(2022, 9, 30)),
        ),
        migrations.AlterField(
            model_name='hall',
            name='Date',
            field=models.DateField(default=datetime.date(2022, 9, 30)),
        ),
        migrations.AlterField(
            model_name='movie',
            name='Movie_Release_date',
            field=models.DateField(default=datetime.date(2022, 9, 30)),
        ),
        migrations.AlterField(
            model_name='user',
            name='User_DOB',
            field=models.DateField(default=datetime.date(2022, 9, 30)),
        ),
    ]
