# Generated by Django 4.1 on 2022-10-04 07:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0031_alter_users_options_alter_users_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='Payment_Status',
            field=models.CharField(default='Paid', max_length=45),
        ),
        migrations.AddField(
            model_name='payment',
            name='Payment_mode',
            field=models.CharField(default='MasterCard', max_length=45),
        ),
        migrations.AlterField(
            model_name='booking',
            name='Date',
            field=models.DateField(default=datetime.date(2022, 10, 4)),
        ),
        migrations.AlterField(
            model_name='hall',
            name='Date',
            field=models.DateField(default=datetime.date(2022, 10, 4)),
        ),
        migrations.AlterField(
            model_name='movie',
            name='Movie_Release_date',
            field=models.DateField(default=datetime.date(2022, 10, 4)),
        ),
        migrations.AlterField(
            model_name='users',
            name='User_DOB',
            field=models.DateField(default=datetime.date(2022, 10, 4)),
        ),
    ]
