# Generated by Django 4.1 on 2022-10-10 05:17

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0035_alter_payment_payment_id_alter_payment_payment_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='Date',
            field=models.DateField(default=datetime.date(2022, 10, 10)),
        ),
        migrations.AlterField(
            model_name='hall',
            name='Date',
            field=models.DateField(default=datetime.date(2022, 10, 10)),
        ),
        migrations.AlterField(
            model_name='movie',
            name='Movie_Release_date',
            field=models.DateField(default=datetime.date(2022, 10, 10)),
        ),
        migrations.AlterField(
            model_name='users',
            name='Role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('User', 'User'), ('TheatreOwner', 'TheatreOwner')], default='User', max_length=20),
        ),
        migrations.AlterField(
            model_name='users',
            name='User_DOB',
            field=models.DateField(default=datetime.date(2022, 10, 10)),
        ),
        migrations.AlterField(
            model_name='users',
            name='is_active',
            field=models.CharField(default=False, max_length=25),
        ),
        migrations.CreateModel(
            name='Date',
            fields=[
                ('Date', models.DateField(primary_key=True, serialize=False)),
                ('T_No_Of_Seats', models.IntegerField(default=100)),
                ('Hall_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.hall')),
            ],
        ),
    ]
