# Generated by Django 4.1 on 2022-10-10 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0038_datewisehall_movie_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datewisehall',
            name='Movie_id',
        ),
    ]
