# Generated by Django 4.1 on 2022-10-14 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0041_alter_booking_date_alter_datewisehall_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='theatre',
            name='Theatre_owner',
            field=models.CharField(default='Owner', max_length=45),
        ),
    ]
