# Generated by Django 4.1 on 2022-10-17 05:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0042_theatre_theatre_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='Payment_id',
        ),
        migrations.AlterField(
            model_name='booking',
            name='Date',
            field=models.DateField(default=datetime.date(2022, 10, 17)),
        ),
        migrations.AlterField(
            model_name='datewisehall',
            name='Date',
            field=models.DateField(default=datetime.date(2022, 10, 17)),
        ),
        migrations.AlterField(
            model_name='hall',
            name='Date',
            field=models.DateField(default=datetime.date(2022, 10, 17)),
        ),
        migrations.AlterField(
            model_name='movie',
            name='Movie_Release_date',
            field=models.DateField(default=datetime.date(2022, 10, 17)),
        ),
        migrations.AlterField(
            model_name='users',
            name='User_DOB',
            field=models.DateField(default=datetime.date(2022, 10, 17)),
        ),
    ]
