# Generated by Django 4.1 on 2022-10-25 07:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0044_booking_booking_status_alter_booking_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='Payment_Status',
            field=models.CharField(choices=[('Paid', 'Paid'), ('Not Paid', 'Not Paid')], default='Paid', max_length=45),
        ),
        migrations.AddField(
            model_name='booking',
            name='Payment_mode',
            field=models.CharField(default='Online', max_length=45),
        ),
        migrations.AddField(
            model_name='booking',
            name='T_price',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='booking',
            name='Date',
            field=models.DateField(default=datetime.date(2022, 10, 25)),
        ),
        migrations.AlterField(
            model_name='datewisehall',
            name='Date',
            field=models.DateField(default=datetime.date(2022, 10, 25)),
        ),
        migrations.AlterField(
            model_name='hall',
            name='Date',
            field=models.DateField(default=datetime.date(2022, 10, 25)),
        ),
        migrations.AlterField(
            model_name='movie',
            name='Movie_Release_date',
            field=models.DateField(default=datetime.date(2022, 10, 25)),
        ),
        migrations.AlterField(
            model_name='users',
            name='User_DOB',
            field=models.DateField(default=datetime.date(2022, 10, 25)),
        ),
    ]
