# Generated by Django 4.1 on 2022-10-25 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0046_remove_hall_t_no_of_seats'),
    ]

    operations = [
        migrations.AddField(
            model_name='datewisehall',
            name='Movie_id',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='home.movie'),
        ),
        migrations.AddField(
            model_name='datewisehall',
            name='endTime',
            field=models.TimeField(default='20:30:00'),
        ),
        migrations.AddField(
            model_name='datewisehall',
            name='startTime',
            field=models.TimeField(default='17:30:00'),
        ),
    ]
